### ISSUE TITLE
Adding informative HELP pages (inside app)

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#117]
I propose to add a few pages or one long page (?) of HELP information on the most important items and features. In particular: 

 - [x] on all "Menu" items
 - [ ] on all the *DataBase* (DB) tables + items
 - [ ] on all the *Settings* items

The help-page should be categorized something like:

 * Status Icons
 * Menu / Shortcut (items)
 * Database (tables and items)
 * Open Cell ID API KEY addition
 * AT Command Injector

The text should not be longer than 1-4 lines, and very easy to understand. If needed we can link to more detailed descriptions in a fully documented, and several pages long help section, at a later stage.

**Comment by SecUpwN** [comment]
@E3V3A, we now have the requested **[ i ]** buttons in our Navigation Drawer.
Can this Issue be closed or is there anything else that we have to add as well?

**Comment by E3V3A** [comment]
Yeah, I think that pretty much covers it, if there's something else, we can re-open later.
