### ISSUE TITLE
Maps Viewer

### ISSUE THREAD

**Issue by xLaMbChOpSx** [SecUpwN/Android-IMSI-Catcher-Detector#13]
The View Map feature originally from RawPhone was used to display a map with signal strength overlays showing tracked data about signal strength information captured through the app. 

I have rewritten a portion of this but wanted to ask if this is what we want to display on the map or show something else as signal strength is not really a main objective of the project. 

Any thoughts or suggestions would be great so I don't waste time on writing something we don't really want. :)

**Comment by SecUpwN** [comment]
@E3V3A, what is the current state of this Issue? Is the Map Viewer perfect now?

**Comment by darkerego** [comment]
I am confused as to how to interpret the antenna map viewer data. So the green circles are known, real cells, the blue ones are... i don't know? And the green arrow that appears and sometimes moves? What does that indicate?

**Comment by He3556** [comment]
Hello darkerego  
On the map we use clusterization now - than means that Cell Towers will be grouped. The red dots are clustered and the green dots are single cell towers. The arrow is your own position. I hope this info will help you.

**Comment by darkerego** [comment]
Thanks for the reply. I just updated from an older version to the newest and whenever I at home I get the yellow icon warning. What do the blue ring circles that appear on the map represent?

**Comment by SecUpwN** [comment]
@He3556, I am strongly voting for adding a legend to the map. New Issue for this?

**Comment by darkerego** [comment]
@SecUpwN  I second that! That would be a great feature. I've gotten some of my friends to use AIMSICD and they are intrigued, and a map legend would be very helpful for new users to interpret the data they are seeing. One other question, is there documentation somewhere explaining what exactly the AT Command Processor can be used for? Forgive me if I overlooked it, but the wiki pages I could find provided limited information. Btw, I love this project and would like to thank all of the developers for their efforts.

**Comment by E3V3A** [comment]
Closed in favor of #228 and #250.

**Comment by bmcycles** [comment]
Why do I get multiple cells in one location and they move and they have different cid they are not anywhere near a real cell site and their lat and lon coordinates are all just a few numbers off and what are the red lines on map than span out away from each major city into nowhere

**Comment by bmcycles** [comment]
Please help asap on my question I think we are being watched for a long time there are lots of different signs and issues that come up often thanks

**Comment by bmcycles** [comment]
Please help asap on my question I think we are being watched for a long time there are lots of different signs and issues that come up often thanks

**Comment by SecUpwN** [comment]
>Why do I get multiple cells in one location and they move and they have different cid they are not anywhere near a real cell site and their lat and lon coordinates are all just a few numbers off and what are the red lines on map than span out away from each major city into nowhere

@bmcycles, sorry to hear you're having Issues. Please file a fresh Issue with [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md#debugging) and add screenshots.
