### ISSUE TITLE
Network Information empty

### ISSUE THREAD

**Issue by andr3jx** [SecUpwN/Android-IMSI-Catcher-Detector#137]
Hello, on my Nexus 7 (see [TD](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Testing-Devices)) is Network Information empty. Using apps like NetMonster I can see Network Information. Unfortunately there is nothing in the logcat.

We need better logging in the app to find the bug.
```
09-30 23:40:12.573    6681-6681/com.SecUpwN.AIMSICD E/MultiRil﹕ Samsung Multiclient RIL not available: gsm.version.ril-impl = android xgold-ril 1.18
09-30 23:40:12.743    6681-6681/com.SecUpwN.AIMSICD D/dalvikvm﹕ GC_FOR_ALLOC freed 202K, 4% free 7969K/8216K, paused 21ms, total 21ms
09-30 23:40:13.303    6681-6681/com.SecUpwN.AIMSICD I/AIMSICD_Service﹕ Service launched successfully.
09-30 23:40:13.313    6681-6681/com.SecUpwN.AIMSICD I/Choreographer﹕ Skipped 61 frames!  The application may be doing too much work on its main thread.
09-30 23:40:13.403    6681-6681/com.SecUpwN.AIMSICD D/libEGL﹕ loaded /system/lib/egl/libEGL_tegra.so
09-30 23:40:13.413    6681-6681/com.SecUpwN.AIMSICD D/libEGL﹕ loaded /system/lib/egl/libGLESv1_CM_tegra.so
09-30 23:40:13.423    6681-6681/com.SecUpwN.AIMSICD D/libEGL﹕ loaded /system/lib/egl/libGLESv2_tegra.so
09-30 23:40:13.443    6681-6681/com.SecUpwN.AIMSICD D/OpenGLRenderer﹕ Enabling debug mode 0
09-30 23:40:13.813    6681-6681/com.SecUpwN.AIMSICD D/dalvikvm﹕ GC_FOR_ALLOC freed 400K, 6% free 8075K/8516K, paused 17ms, total 17ms
09-30 23:40:14.013    6681-6681/com.SecUpwN.AIMSICD I/Choreographer﹕ Skipped 41 frames!  The application may be doing too much work on its main thread.
```

**Comment by SecUpwN** [comment]
@Ueland, would you please have a look at this since it seems @andr3jx is "having a break"? :disappointed:

**Comment by andr3jx** [comment]
@SecUpwN This issue can wait because it only affects tablets, we have more important issues.

**Comment by SecUpwN** [comment]
>This issue can wait because it only affects tablets, we have more important issues.

Might be. But I am sifting through our Issues on a regular basis and I noticed that we have too many Issues that "can wait", because they are created but not maintained well afterwards. On which one are you currently working (if any)? If everyone would care more about their created tickets, we'd also be faster. So without pushing you to do anything, please don't forget about solving this one. Thank you!

**Comment by E3V3A** [comment]
@andr3jx  Can you get back on this, so we can resolve it? Did you have a suggestion for how to fix it? 

I was just looking around and found this. Perhaps we need to check for [PHONE_TYPE_SIP](http://developer.android.com/reference/android/telephony/TelephonyManager.html#PHONE_TYPE_SIP) instead?

**Comment by andr3jx** [comment]
I will do some tests next month, checking for PHONE_TYPE_SIP will not help because the tablet returns PHONE_TYPE_NONE.

**Comment by Davidmylove** [comment]
Thank you

**Comment by E3V3A** [comment]
I came across [THIS](http://stackoverflow.com/questions/16541172/getallcellinfo-returns-null-in-android-4-2-1) post. Perhaps this problem is related? 

> This is preferred over using getCellLocation although for older devices this may return null in which case getCellLocation should be called.
> 
> Some sources report that this method is only implemented on CDMA/LTE devices, and other types of devices (including GSM/LTE ones) will return null. Where implemented, it will return only LTE cells.
> 
> TelephonyManager.getCellLocation() will return only GSM/UMTS or CDMA cells. It it limited to one cell, the one with which the device is currently registered. This is your safest bet if you are sure your code will only be running on GSM/UMTS or CDMA devices, and if you are only interested in the cell with which the device is currently registered.

So I searched our code for these: 
 * [getAllCellInfo](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/search?utf8=%E2%9C%93&q=getAllCellInfo&type=Code) in: DeviceApi17.java 
 * [getCellLocation](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/search?utf8=%E2%9C%93&q=getCellLocation+) in: CellTracker.java, Device.java

**Comment by andr3jx** [comment]
The post is unrelated for this issue.

**Comment by E3V3A** [comment]
Well if you have the solution, as it appears above, why don't you post a code snippet for us to try to fix it or make PR? It doesn't seem anyone know what to do here, other than you. I want to see this issue closed as much as you do, especially since you seem to know what the problem is.

**Comment by andr3jx** [comment]
I think the only way to do it properly is to replace the switch case phonetype with something like this:
http://stackoverflow.com/a/14485139

**Comment by SecUpwN** [comment]
Thank you for digging further into this, @andr3jx. The comment you've found has been written by @iagreen, who works for [Wink Inc.](http://www.winkincproductions.com/) - maybe he cares to help us? I have just written a short invitation via E-Mail to him. And sometimes I wonder if it is only me having such a strong Google-Fu... :panda_face:

**Comment by E3V3A** [comment]
@andr3jx  Any news? Where should that code go? Are you working on it or waiting for someone else to do it? Feedback please.

**Comment by andr3jx** [comment]
@E3V3A No news. The code should help to decide if we need to take the GSM or the CDMA case. I'm not working on it at the moment. I would prefer that someone does it but I could do some tests next week.
If you ask why tobykurien was unassigned by me, maybe because I misclicked somewhere while browsing the issues.

**Comment by E3V3A** [comment]
@andr3jx  Please go to test room and test b29 and see if it has resolved this issue.

**Comment by andr3jx** [comment]
Works on KitKat 4.4.4 and Lollipop. Issue solved!
