### ISSUE TITLE
 Build: Automatic version and app name update with Gradle

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#147]
Implement automatic build and version updates when using Travis-CI and Gradle, to build our App. 
The `build.gradle` script to do this, is described [HERE](http://bryankrosenbaum.com/2013/11/27/getting-to-know-gradle-auto-increment-version-and-signing-releases/), and lastest version can be found [HERE](https://github.com/bryanro/later-android/blob/master/Later/build.gradle). This would obviously require a few modifications in the *RegEx* as our build string is different, including changing the correct min/max of the supported API. (min=API-**17**, max=?) 

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.SecUpwN.AIMSICD"
        android:versionCode="24"
        android:versionName="0.1.24-alpha-build-12">
```

The link above also provide a way to implement automatic APK signing, using a [signing.properties](https://github.com/bryanro/later-android/blob/master/signing.properties) file. 

And [HERE](http://toastdroid.com/2014/03/28/customizing-your-build-with-gradle/) is a way to automatically name the built APK.

**Comment by SecUpwN** [comment]
@E3V3A and @He3556 do we really still need this? Having rethought all of this, I think it is much more convenient to change that by hand when it is due, and this also eases up my work with updating the `CHANGELOG`. Thus, I'd vote for removing that unnecessary code. We now have autiamtic builds made from our `development` branch as stated in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/148#issuecomment-82622401 - I guess that should be good enough, right?

**Comment by SecUpwN** [comment]
@E3V3A and @DimaKoz, I would like to update you on the situation over here at my place: I have noticed that for the means of maintaining this project and updating the app version, I am much more in control of the process when **doing it by hand** (increasing the version in `AndroidManifest.xml`). @DimaKoz is also perfectly following the [version instructions] now and doing it by hand as well.

**To the point:** I would vote for removig the unnecessary code from [build.gradle](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/build.gradle) so that we don't have stuff that we don't need, what do you say, @E3V3A? As for testing code, we will keep using [Buildozer](https://buildozer.io/accounts/926/members).

**Comment by E3V3A** [comment]
@SecUpwN Hmm, I understand the manual fixing is working great, and that it is simpler. However, I'm not convinced this is very convenient for debugging. It mean we always have to manually change the name after each download/update, when saving, especially when I like to keep all previous versions for reference when trying to hunt down bugs. I often install and remove several versions on device for comparing. **What exactly is the problem with the previous build.script?** It's been working fine for me. In addition I'd like to keep the app name as short as possible, as I described [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/147#issuecomment-61174231).

I think the only reason the script is not automatically renaming the output, is because you previously insisted that all **builds** are published in a monotonically increasing sequence. (I.e. 1,2,3...) This is AFAIK not standard for development, and I don't see why we would want it to be like that. In any case before developer make a PR he should check/set the proper versioning anyway.

**Comment by SecUpwN** [comment]
Thanks for your clarification, @E3V3A. I am not really seeing through anymore and I would love you and @DimaKoz to construct the update mechanism as proposed to convince me. Unassigned myself.

**Comment by DJaeger** [comment]
Why close this?
I thought one of the purposes of this issue is to automaticly name the builded APKs of Buildozer?
But this is not working until now.

**Comment by SecUpwN** [comment]
>Why closing this?

See https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/453#issue-85968943 and my comment thereafter. Thank you.

**Comment by E3V3A** [comment]
> I thought one of the purposes of this issue is to automaticly name the builded APKs of Buildozer?

That was also my point once upon a time, but @SecUpwN insists of naming each build manually, so unless you can convince him otherwise...

**Comment by DJaeger** [comment]
We have much different things on versioning discussed in this issue.

I don't want to change anything on the versioning or naming or realease flow.

I only think a naming of the APKs as @E3V3A said in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/147#issuecomment-98541653 would be great, at least for Buildozer Builds.

As all created APKs by them are called app.apk I can not determine which version it is, also not from the Mails of Buildozer, as the only say there own Buildnumber.
Now I have app.apk, app(2).apk, app(3).apk in my download directory.

I don't have the time to research the versionname out of the AndroidManifest.xml of the time I received the mail to rename the file myself, as I want to use the less time I have to contribute to the issues and code and don't want to waste it with something like that.
Especially for an Issue like https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/505 we have to test behaviors of different previous versions/builds.

@SecUpwN Please consider at least to automatically name the builds by Buildozer.

**Comment by SecUpwN** [comment]
>@SecUpwN Please consider at least to automatically name the builds by Buildozer.

After re-reading the whole thread, I do see that need for that and have just contacted the Buildozer support team to tell me how to finally accomplish this task. I am re-opening this Issue once more.

**Comment by smarek** [comment]
Well I provided PR to address this issue, about naming the APK, there is a way to provide the APK name from Gradle, do we want to implement that too? I'd be for using the same ID (git id append) as append to APK name (ie. `app-0747dc5.apk`), however we could possibly end up with large number of APKs that don't get automatically deleted

**Comment by SecUpwN** [comment]
>I'd be for using the same ID (git id append) as append to APK name (ie. `app-0747dc5.apk`), however we could possibly end up with large number of APKs that don't get automatically deleted

I'm not sure what you mean exactly. We're building our internal testing APKs via [Buildozer](https://buildozer.io/). And the APKs that we add to our [Releases](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases) are being manually created, signed and added by myself. So anyone who is going to craft the builds themselves, will end up getting an APK with the commit ID appended, right? If so, why not delete old compiled APKs by hand so that the folder does not clutter? ;-)

**Comment by smarek** [comment]
Yes, I've seen the request to Buildozer to provide APKs suffixed with versionCode, that's neat idea.
About the Releases, I can easily provide Gradle configuration to sign the release APK automatically depending on environment variables contents (if missing, release will remain unsigned, if provided, gradle will try to sign using specified keystore key and passwords can be env hardcoded or provided on-demand in password prompt), see example here: https://github.com/cgeo/cgeo/blob/80fedda8589d9791f42af4b82338ebd17ff9ad96/main/build.gradle#L282

About deleting old versions, we'd have to provide way to remove all old APKs or automatically delete APKs older than `XX TimeUnit` (ie. X days or hours)

**Comment by smarek** [comment]
Or second nice example of Gradle signing integration depending on env variables https://github.com/WhisperSystems/Signal-Android/blob/master/build.gradle#L246

**Comment by SecUpwN** [comment]
Beautiful! @He3556, since you'ter crafting our Releases, what do you think about merging this? And to both of you: Will this change anything in the release cycle and publishing Releases?

**Comment by smarek** [comment]
IMHO it will make the process only easier to do automatically (so you can even hook cron locally to check if master was pushed and new APK has to be generated or something like that :+1: )
