### ISSUE TITLE
Build: Automatic upload of Travis-CI build to GitHub

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#148]
We would like to have the latest App as built by Travis-CI, to be (semi- ?) automatically uploaded to our GitHub downloads section. Comments on how this can be accomplished are most welcome. Trvais-CI *S3 Deployment* is discussed [HERE](http://docs.travis-ci.com/user/deployment/s3/) and *Build Artifacts* [HERE](http://chairnerd.seatgeek.com/keeping-track-of-build-artifacts/).

[HERE](http://stackoverflow.com/questions/21628642/call-github-api-with-travis-to-build-tag) is one solution, and [HERE](http://stackoverflow.com/questions/18297340/how-to-package-compress-and-deploy-binaries-as-zip-tar-gz-from-a-github-repo-wi) is another.

**Comment by SecUpwN** [comment]
@E3V3A and @He3556 I just discovered [Buildozer](https://buildozer.io/) and it sounds too good to be true! :smiley: I just signed up and I will test their service. If it works as expected, I might integrate it for automated distribution (means, we could accomplish automated official releases with our release key)!

**Comment by SecUpwN** [comment]
@He3556, I am closing this Issue as finally **FIXED**. After many sleepless nights and about 100 E-Mails with the Buildozer support I have now figured out how we can automatically always fetch the latest APK when changes have been made in branch development: Just log in to the [our Buildozer](https://buildozer.io/projects/43768/), access the latest build and download the automatically created APK. As for the automatic upload of the builds: I'd like to avoid that. We want to keep our Releases clean, thus will only add real and tested releases.

Anyone who wants to grab the latest APK can just contact me to get added to the developers team. All current members of AIMSICD should have received an invitation to Buildozer just now. **ENJOY**! :+1:
