### ISSUE TITLE
Debug: Need on screen logcat entries

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#164]
In order to better debug the detection parameters, we'd like to have some of the **log.i** and **log.e** entries displayed on screen. We're particularly interested in ones coming from these files:
```
AIMSICDDbAdapter.java
Cell.java
CellTracker.java 
Device.java
DeviceFragment.java
DeviceApi17.java 
RilExecutor.java
SamsungMulticlientRilExecutor.java
SmsReceiver.java
```
Perhaps it is possible to add it in such a way that it is only shown when built with Gradle's "*assembleDebug*"? Also, when they're shown, it would be extra nice if it was shown just like the on-screen-dispaly (OSD) in the Android built-in CPU and process info...

@tobykurien  What do you think? Is this possible?

Q: Why all this? 
A: We need a way to debug individual items in the detection matrix.

**Comment by SecUpwN** [comment]
@E3V3A and @Ueland, can we close this as solved now?

**Comment by Ueland** [comment]
I would say so, yes.
