### ISSUE TITLE
OpenCellID Measurements

### ISSUE THREAD

**Issue by kolg** [SecUpwN/Android-IMSI-Catcher-Detector#188]
Hello,

I'm trying to contribute to OCID via your app. I can see some blue markers on the map in the app, the first measurements are also in aimsicd-ocid-data.csv. The other blue markers are not listed in the file.
I have some questions:
1. The blue markers only appear when i switch 3G on or off on my phone. Leaving 3G on (or off), no new markers are created, even when i'm cycling around lots of different cells. Why is that?
2. My Measurements are not shown on OpenCellID.org, though I copied my API key into the app.
3. Why are the later measurements shown by blue markers not included in the aimsicd-ocid-data.csv?

Hardware: Fairphone FP1, OS Cherry 1.6 (Android 4.2.2)
AIMSICD version 0.1.24-alpha

**Comment by E3V3A** [comment]
@kolg We really like that you have a Fairphone. We'd like to test more on this device.

* The best way to contribute OCID data, is by using their own App for this. It is called: [inViu OpenCellID](https://www.enaikoon.com/en/apps/plugins/opencellid/). 

* If you have any other issues, please send me an email or join our internal chat and I can send you the latest build to test with.
 
Thanks again.
