### ISSUE TITLE
How to use /dev/socket/rild rild-debug and /dev/diag?

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#200]
This issue is an offshoot of #195 in order to better understand the usage of the radio related debug interfaces. It is required to keep comments clear and on-topic. All other discussions and tests should be posted [on our XDA thread](http://forum.xda-developers.com/showthread.php?t=1422969). 

**Q:** So what do we want to do? 
**A:** We want to be able to communicate with the radio debug interface in order to be able to get radio parameters not already part of the AOS API. We need these to provide a better detection mechanism. There are usually a number of common devices present in the Android device tree. The most relevant ones are:
```
/dev/socket/rild
/dev/socket/rild-debug
/dev/diag
```
Then there are loads of baseband specific ones, especially for Qualcomm devices. We don't go into the details of these here, at least not yet.

**Q:** Are these sockets hardware/device dependent?
**A:** *unknown and to be determined*

**Q:** Do we have any practical examples?
**A:** Here is one:

*[socat](http://forum.xda-developers.com/showpost.php?p=51837955&postcount=28)* is an extremely useful tool for connecting to sockets, ports and all sorts of devices. For example, we can use it (here on a *Samsung Galaxy S4-mini*, GT-I9195) to connect to the **rild-debug** socket like this:

Open a root shell and run this: 
```bash
# socat UNIX:/dev/socket/rild-debug - | hexdump -C

00000000  00 00 00 20 01 00 00 00  04 04 00 00 11 00 00 00  |... ............|
00000010  51 55 41 4c 43 4f 4d 4d  ef 03 08 00 01 00 00 00  |QUALCOMM........|
00000020  03 00 00 00 00 00 00 08  01 00 00 00 ea 03 00 00  |................|
00000030  00 00 00 3c 01 00 00 00  f1 03 00 00 13 04 00 00  |...<............|
00000040  00 00 00 00 ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00000050  ff ff ff ff ff ff ff ff  63 00 00 00 ff ff ff 7f  |........c.......|
00000060  ff ff ff 7f ff ff ff 7f  ff ff ff 7f ff ff ff 7f  |................|
```

> NOTE: Connecting with socat to /dev/socket/rild-debug blocks radio on phone.
> As soon as socket has been released, normal network access is restored.

Then what? That's what this issue is about. Running *[strace](http://forum.xda-developers.com/showpost.php?p=51699440&postcount=23)* on the *rild* daemon can be very useful (as shown in #27 ).

**Comment by benutzer74** [comment]
Does the current version (0.1.30-alpha-b00) make use of accessing /dev/diag? On my system /dev/diag has permissions 660 and is owned by radio:qcom_diag. Is it dangerous to make /dev/diag world readable and writable? Other tools need rw access to /dev/diag and Android does not have a usermod command to add user apps to the group qcom_diag, thus only making /dev/diag world rw is possible...

**Comment by SecUpwN** [comment]
@He3556, same thing here: Should we re-open this and try to continue investigation with @scintill?
