### ISSUE TITLE
Feature request: Let the map start at my location

### ISSUE THREAD

**Issue by Ueland** [SecUpwN/Android-IMSI-Catcher-Detector#205]
When opening the map page, i am greeted with 24 small maps of the whole world. It would be more useful if it started on my location.

**Comment by SecUpwN** [comment]
@tobyurien, is the above mentioned by E:V:A easy to implement for you?

**Comment by tobykurien** [comment]
Actually it already works mostly like that - see https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/app/src/main/java/com/SecUpwN/AIMSICD/activities/MapViewerOsmDroid.java#L496-L509

**Comment by E3V3A** [comment]
Yep, I think we can close this for now. The map centers alright, but the BTS points closest to "me" are not shown. Which is something that has changed in the last month... I'm not sure what it causing this, but it could be a an OCID problem. Perhaps they've scrapped BTS that has been previously uploaded in my area. Only a proper working map function can fix and check this.

**Comment by tobykurien** [comment]
I also notice that my currently connected BTS is no longer showing on the map. If this is true for everyone, we should add that as a new issue.

**Comment by tobykurien** [comment]
I see no blue pins, even after a while. Infact it should immediately plot that since I'm connected to a BTS. I'll look into it.
