### ISSUE TITLE
Bug Report: 0.1.25-alpha-b3

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#206]
Here are a couple of things to be distributed into separate issues.
**Test Device**: *Samsung Galaxy S4-mini* `(GT-I9195), stock JB4.2.2, Enforcing`

---

- [x] 1. After successfully requesting an OCID API key, the question box re-appears, and you have to push "Cancel".
- [x] 2. It's impossible to download the OCID data, if the last location is not determined. Determination should be from:

  - [ ] **a)** The currently connected MCC, and if this fails, a fall-back to:
  - [ ] **b)** Manually selecting, by clicking on a country (from the Deafult MCC locations).

- [ ] 4. Before downloading OCID data, all (except default) DB tables are empty. At least the cell table has to have something, as long as SIM is unlocked, and phone connected to something.
- [x] 5. The "About AIMSICD" window is too high (~1 text line) for my screen, forcing me to scroll down to be able to see all of the "LICENSE/CREDITS" text buttons. Probably due to incorrect padding.
- [ ] 6. The "About AIMSICD" buttons are all linking to the website. Instead they should:

  - [ ] **a)** The list of "status Icons" should link to a text box with desciptive text.
  - [ ] **b)** The 3 "wide" buttons should take you to our GH site.
  - [ ] **c)** The last 6 "buttons" should also get you a pop-up scrollable text box (or window).

- [x] 7.  `Map Viewer:` Doesn't retain the last shown map-view after exiting and re-entering map. Map does *weird* stuff when no location has been found. (Like re-sizing itself and going to random locations and zoom's.)
- [x] 8. `Debugging / Debug Logs:` None of the buttons seem to work. Nearly impossible to exit and take a very long time to react.  
- [x] 9. ~~Attempting to re-download OCID data, when already downloaded, temporarily locks-up phone. Instead should display message that data has already been downloaded.~~
- [ ] 10. After returning from some operations to the side-menu, the previously selected item is highlighted. 
- [ ] 11. `Map Viewer:` 

  - [ ] **a)** Upon first entry, it only shows one BTS. In order to see others, you have to exit and re-enter MapView to show the others. 
  - [x] **b)** Selecting "Satellite" map-type doesn't allow you to zoom in.  **We should remove the other map types, as they don't work.** 
  - [x ] **c)** Hitting "Settings" icon (upper left) after selecting new map-type get you back to main side-menu, when it should take you back to map. This is probably just the wrong icon and should be a the AIMSICD icon. (?) Since normal *back* button works as expected here.
  - [x] **d)** `LAC` is not shown in the BTS details of the cell towers.
  - [/] **e)** `Samples` are *empty* for BLUE BTSs. Should be re-labelled as ~~either "now" or~~ "0"
  - [x] **f)** Some BTS `Samples` are "**-1**". (That comes from OCID data.)

- [x] 12. AIMSICD crashes after waking up from *sleep* when in MapView.
- [x] 13. In `OCID DB` table, many BTS entries are shown with: 

  - [x] **a)** `Samples: -1`, and with 
  - [ ] **b)** `AvgSignal: 0`. Not sure what this means, yet... (Anyone?)

- [x] 14. AIMSICD service doesn't shut down after exit application, even though it is un-checked in settings. 

---
These are in addition to, or as a compliment to previously stated issues as mentioned in: #23, #65, #137, #166, #168, #203 and #205.

**Comment by SecUpwN** [comment]
As for number 5, I suggest removing `Anonymous Donations`. Do you agree, @E3V3A and @He3556?

**Comment by E3V3A** [comment]
Yes, I agree.

**Comment by E3V3A** [comment]
Apart from the items in [this comment](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/206#issuecomment-67722728) already documented, we can close this issue...

**Comment by SecUpwN** [comment]
@E3V3A, why are you closing this if not fully solved? Noone will have a look at it any longer!
