### ISSUE TITLE
MTK measurements using native AT commands

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#219]
**Note**: This is an MTK device specific issue. 

If you're unsure about your device, check if you device look similar to any of the MT*nnnn* labelled devices on our [developer device list](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Testing-Devices), that show a `gsm.version.ril-impl` property as "**mtk gemini ril 1.0**". 

Of all the Androids out there, it seem that those devices based on the *Mediatek* (**MTK**) chipset, are all using the *AT Command Processor* (ATCoP) to talk to the baseband (BP) processor. Although this is the main method of communication, many of the unsolicited results can be found in both the radio *logcat* ring buffer and possibly in the RIL debug interfaces. This issue is to present the exact AT commands needed to obtain the required measurements used for detection. To implement this, it is crucial to resolve issue #23.

The "stuff' we will eventually need are the following:

| GH ref | Measurement | AT command sequence |
|:------ |:----------- |:--------------------|
| #100  | Neighboring cells info |
| #93  | TMSI |
| #97  | RSSI, |
|   | TX power |
| #73  | T3212 |
|   | TA |
|   | A5/x |
|   | ARFCN |
|   | Various BCCH parameters |
|   | "Location Update Request" / reject response |
| #82  | Manual RAT selection |

@andr3jx  You're the only one I know who have looked at this in detail. Perhaps you can help fill in the blanks?

**Comment by dummys** [comment]
Hi, I'm trying to parse the result of AT command on a MTK device. Did you have figured it out which one it is ? I tried the ttyGS0 but without luck using the atinout tool. Here is the thread on XDA: http://forum.xda-developers.com/general/networking/send-raw-command-to-mtk-baseband-t3163425
In logcat I can't find any related stuff about AT, the only result I have it's enabling the mtklogger in the engineering app then tailing the radio_log in sdcard.

**Comment by andr3jx** [comment]
@dummys I see your question is not relevant for the project but I'll help anyway.
If you want to see radio log you need to use `logcat -b radio`. [Read this post](http://forum.xda-developers.com/showpost.php?p=53679792&postcount=286) to learn how to send AT commands from commandline.

**Comment by dummys** [comment]
Wow, i'm so dumb... I already read that, but you know what ? It's better working when a sim card is inserted :dancer:
Thanks a lot for your help.
Cheers,
Jon

**Comment by SecUpwN** [comment]
@He3556 shall we re-open this Issue to find the needed AT commands? Or is this "non-relevant" now?

**Comment by agilob** [comment]
@andr3jx probably not... but always worth asking, do you have copy of `Engineer Menu source code` you linked above? The repository was destroyed `Repository unavailable due to DMCA takedown.`

@trizet could you share the repo code on my email if you still have it?

**Comment by andr3jx** [comment]
@agilob 
How about you check [my fork](https://github.com/andr3jx/MTK6577)? Of course I have backup of everything, I'm aware that everything can disappear any moment.

**Comment by agilob** [comment]
Thanks @andr3jx  :)

**Comment by NCLnclNCL** [comment]
.
