### ISSUE TITLE
How to upload exact BTS locations (CounterMeasure)

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#220]
**The problem:**
Some of the more advanced AIMSICD detection depend on knowing the exact location of a BTS. However, this information is rarely available, and when it is, it is usually for a specific network operator (MNO). That data is obtained by downloading or querying public or private databases. However, in only very special cases are the exact BTS location provided, and this situation is deteriorating with the rapiddly increasing popularity of *micro-* and *pico-cells*  All other times when a GPS position is available from an external source, that info is based on some kind of average of the locations at which most of the measurements was made. These are made by the phones. This makes pinpointing specific BTS antennas difficult, and if you don't know where the *real* antenna should be, it make it much harder to find a fake or IMSI-Catcher type device in the area, especially as these can be very small and easily hidden from view. 

But humans are great at spotting unusual devices on houses, towers, cars, and so on. So we can expect that some interested and technical persons would recognize such an antenna.

**Q:**  *How can I upload the exact location of an antenna that I have spotted and observed in the wild?*

**A:** There is a great app called [RF Signal Tracker](https://sites.google.com/site/androiddevelopmentproject/home/rf-signal-tracker) that allow you to detect BTS and then move them to their correct locations on the map, and upload them to OCID. Here's what they say:

> One of the great deficiencies of the app is that, unless you are an engineer for a cellular carrier, you probably do not have access to a complete and accurate site location database. Therefore, I have added a feature which will allow a user to insert a site on the map, and in turn the site database, by simply pressing a spot on the map. Not perfect, but it does minimize the short comings of the open source location services on the web. Instructions are below. Long pressing (2 seconds or more) an empty spot on the map will launch a dialog which will give the user the option of inserting the current serving cell into that spot on the map. This will allow users to define site locations even if they do not have access to specific site location data. Long pressing a site icon on the map will launch a dialog giving the user these options: `Move XXXXX to selected site` - This will attach the current serving cell to the site represented by the selected icon. Often, Google will show two sites as separated by a few dozen meters when, in fact, they are sectors on the same site. This option lets you bundle these cells together on the one site. `Move selected site to cell XXXXX` - This will move all the sectors on the selected site to the same site as the serving cell. Like the first option but in reverse. Remove selected site and all attached cells - This removes (temporarily) all the sectors on the selected site from the database. If you are using the Google or OpenCellID location services then the cell will appear in its original position (If you handover to that cell, the app will first search its database for the cell and then go online to find it. If it is successful it will store that cell location back in its database). If using Local location then the site is deleted from the database, but can be reloaded from the original data file. `Remove XXXXX from selected site` - This option removes the specific cell from the selected site. All other cells remain unchanged. This is used if you attach a cell to the wrong site.

**Comment by E3V3A** [comment]
Did you get any response? 

In general this is a great idea, but it's not for the public. It is nearly impossible for a non mobile-communications expert to correctly determine where a particular -- and currently connected to -- cell tower is located. So if we ever decide to include this, it should probably be a developer option in settings.

**Comment by SecUpwN** [comment]
>Did you get any response?

Depends from whom you wanted one..

**Comment by demantz** [comment]
Hi, sorry for my (very) late reply! Other things came up and I forgot to reply on this one..

I'm very short on time right now, because I'm in the final stage of handing in my bachelor thesis..
And in addition I don't have a rooted Android smartphone at hand. I use a rooted Nexus 7 for development, which doesn't really help with this project..

I would really like to contribute to this project and maybe in the near future I can. But at the moment I have to concentrate on my thesis. Thanks for asking anyway ;) I felt honored!

Cheers,
Dennis

**Comment by E3V3A** [comment]
@demantz No problem, thanks for getting back to us.

@SecUpwN This is not a Counter Measure, so I'm closing this.

**Comment by SecUpwN** [comment]
I don't get why you file great ideas, yet close them when nobody appears to immediately work on them, @E3V3A. It means that we're getting either all hot for it and start researching (while leaving other Issues behind) or that great Ideas just vanish because you suddenly think we don't need them. Why not re-open this?
