### ISSUE TITLE
Qualcomm modem Jamming Detection

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#221]
According to some past documents, many Qualcomm baseband processors (BP) and SoC's has a built in "Jamming Detection" feature. This is clearly not documented in any other place and I've never seen any device or software using it. It would be great to find out if this is something that we could use.

**Comment by E3V3A** [comment]
So I'm closing this as it's not a relevant issue, but worth remembering.

**Comment by freddymartinez9** [comment]
It would be useful to have to detect downgrade attacks. I've mentioned this previously ...

**Comment by E3V3A** [comment]
I know, but we have no idea how to activate and use this in the Qualcomm BPs...especially from Androids. Maybe we should start a [signature collection campaign](https://www.change.org/?lang=en-US) to have them release this info?
