### ISSUE TITLE
AT Command Interface

### ISSUE THREAD

**Issue by Kml55** [SecUpwN/Android-IMSI-Catcher-Detector#23]
I am browsing the source code. I do not have a rooted phone but I am wondering the AT Command injection output. Can you provide application screenshots ?

**Comment by E3V3A** [comment]
Just as a reminder, [here](http://stackoverflow.com/questions/16173387/android-child-process-logcat-keeps-running-after-parent-process-app-died?rq=1) is one way to kill shell processes from within Java...

**Comment by E3V3A** [comment]
Fixed in commit: 8a6fbd98cf0bdcbdc321931827f5d9aadc91d03a
