### ISSUE TITLE
Feasibility of spoofing TA

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#231]
Although this is currently completely off topic, I'd still like to throw this idea out there. It may not even be possible, but as I understand it, there should be nothing preventing it either. 

My idea is to provide a phone location counter measure, by spoofing the `Timing Advance` (**TA**) parameter in the baseband. *TA* is used both by GMS and LTE, whereas LTE have a `Propagation Delay` (**PD**) value, in addition. Either way, the effect of this kind of clandestine spoof is that the BTS would think you're located at one annular distance, rather than where you actually are. Obviously it is only possible to spoof being further away, by delaying the signals received to (or sent from) your phone. 

The only drawback, is that it requires a baseband hack. By putting a delay loop somewhere early in the RFFE data reception loop. Or the opposite, by delaying the outgoing signals. However, this would probably require some serious baseband SW RE. That would make this hack a CIA class hack. 

But since we're such geniuses, we can just make a poor-mans version of this. As every radio-amateur knows, we can add a well constructed RF signal propagation delay circuit (or even cable loop) to our antenna to take care of this delay. And this is a really great idea! It would be the first serious `anti-mobile-tracking` design, ever!

I wanna see a picture of the first one.

**Comment by E3V3A** [comment]
I guess we should try to close any properly tagged issues... But let's start with closing only our own ones.

**Comment by SecUpwN** [comment]
Why did you close this? This is a fantastic idea and you were fire and flame for it..

**Comment by E3V3A** [comment]
It's not directly related to this app and very hard to implement even for a baseband ARM expert.
