### ISSUE TITLE
False "CHANGING LAC!!" alarm on bad cell coverage

### ISSUE THREAD

**Issue by Ueland** [SecUpwN/Android-IMSI-Catcher-Detector#239]
It appears that the "CHANGING LAC!!" warning is triggered very easy **while the phone has bad cell coverage**, should figure out a smart way to avoid that, perhaps set a minimum cell coverage level before trigging or something. Logcat: https://defuse.ca/b/cOjp8FlSUhEPHSAkrtlLwZ (password: fish)

**Comment by ihackshit** [comment]
I have noticed this message quite often when moving fast in a vehicle. Could this be cause of the signal strenght presented varies too much, and in that case could this warning be suppressed?

**Comment by E3V3A** [comment]
No, but it could be a timing issue. Many times the LAC and CID doesn't change at the same time or are both delayed with respect to what baseband is actually using. In addition this detection is not suitable for moving devices. So you'll get false alarms when moving from one coverage area to another. AIMSICD should be a thought of as a sensitive measurment instrument, which you turn on when you've already arrived at some place and put your phone down, or at most moving around slowly by foot.

**Comment by SecUpwN** [comment]
>So you'll get false alarms when moving from one coverage area to another.

Hm.. how do you like the idea of adding a countdown timer within the `Preferences` which counts down how long all notifications shall be suppressed? Would be useful when traveling for certain times..

**Comment by E3V3A** [comment]
Could be an option, but let's understand and solve the problem in OP first.

**Comment by ihackshit** [comment]
E3V3A: Okay, this makes sense however could it not be supressed when gps-cordinate change? I move around a lot and whenever i pick up the phone i see a warning. Additionally, and this is not related to the LAC changes, but it would be helpful to be able to jump to the specific warning details when notified about a warning, allowing you to fast see what LAC is causing the issue, if nothing else but to be able to correlate problems to certain places (bad signal/LAC).

**Comment by Ueland** [comment]
We could take a look at the accelerometer just as we do with the signal measurements, and not register anything until the phone lays still for N seconds?

**Comment by E3V3A** [comment]
@ Ueland:  Sound good to me. 
@ ihackshit: Yes, you're talking about an event logger. We'd like to see this as well and we've filed #201 and #238 to deal with this.

**Comment by He3556** [comment]
the false changing LAC alert has nothing to do with the movement itself. We just check if a LAC of a certain CellID changes. So when the phone is moving and it connects to another Cell - than of cause the LAC can also change. 
@ihackshit and @Ueland (or everybody else with this issue) maybe you could try a special version of our App. I added Thread.sleep(1000); before we read the LAC. Now the app is reacting slowly all the time - but it is only for testing. Than it would be great if you could export your db and send it to us + the Debug Log when a false detection pops up again. 
I will add a download link here tomorrow. ok?

**Comment by Ueland** [comment]
Throw the code bit into its own thread and the lag should go away. ;)

**Comment by ihackshit** [comment]
Cool, would love to give it a go! Thanks for a great app and great response.

**Comment by E3V3A** [comment]
> Throw the code bit into its own thread and the lag should go away.
@He3556 Do you know how to do that? If yes, Please implement, else ask Tor for more details.

**Comment by He3556** [comment]
Here is a debug version for everybody who gets the wrong alerts (@Ueland, @ihackshit )
I added "Thread.sleep(200);" before "return this.lac;" - for a possible timing problem.
If there is a false alert again, please send your logcat.
https://www.dropbox.com/s/yz15jox2qfj4nue/AIMSICD-v0.1.25-alpha-b9-DEBUG.apk?dl=0

**Comment by Ueland** [comment]
I will give it a try soon.

**Comment by Ueland** [comment]
Installed your version now, @He3556 
What should we do with this case, just let it stay open a while longer?

**Comment by SecUpwN** [comment]
>What should we do with this case, just let it stay open a while longer?

@Ueland, yes, please let this stay open until confirmed that false alarms do not occur anymore. Would you please continue monitoring this Issue and close it when you are finally sure everything works great?

**Comment by Ueland** [comment]
Will do.

**Comment by Ueland** [comment]
New alarm today, it took several hours thebefore the app  went back to normal state.

https://defuse.ca/b/lkpdL0v5imaYTWMq9UpNHC (fish)

**Comment by E3V3A** [comment]
Hi! When you do logcat dumps, please include the **timestamp** with `-v time` flag. Changing LAC can be a false positive if phone detects a new LAC before CID is updated... Did you track down location?

**Comment by Ueland** [comment]
If timestamps is needed then the debug view should dsplay them, when i dump a log i only use the debug view, i dont have time to find a machine to dump logs with as this error occurs when i am traveling. And no, i do not know exactly where it happend, all i know is that it happens around 10-20% of the time when i travel to or from work.

**Comment by E3V3A** [comment]
That is a lot! 

Ok, I blindly changed this [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/d23a54f3b65953c47a550980219b21e2364514f7) without testing. I hope it doesn't break anything.

**Comment by He3556** [comment]
Tor has another debug version, where i added some time to wait, before the getLAC() is fired. So if there is still a wrong allert even with this version (and after the note i left in the chat for you) we need to try something else. Or maybe there realy is a catcher on your way?  would be great to know the cellID. Thanks for testing!

**Comment by E3V3A** [comment]
Well he's in the middle of the current catcher crisis area...but then the OP states in area of poor coverage. No telling. We need to also dump both "signal strength" (**DBi_meas**:*rx_signal*) and all CID,LAC,PSC and RAT changes to the new `EventLog` table, so that we can see, what is going on.

**Comment by Ueland** [comment]
Issue has not been detected for over a week with the latest build, appears fixed. yay! :)
