### ISSUE TITLE
Need to export API key

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#245]
We need a way to export the OCID (or MLS) API key for recycling and testing on multiple mobiles. Problem is that OCID only seem to allow the registration of a new Key once per day. The export should be via display, SMS, email, clipboard or textfile.

**Comment by SecUpwN** [comment]
@E3V3A, when you actually add the label `REMEMBER_THIS`, shall that still be implemented?

**Comment by E3V3A** [comment]
Maybe. Could be useful for exporting the API key table in the future when using other DB sources.
