### ISSUE TITLE
Suppress multiple GPS Notifications

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#251]
Hey folks! A few of my friends recently reported that our App displays notifications too often, especially the one with disabled `Location Services`. This makes the impression our App wants to "call home":

[![Location Services Disabled](https://spideroak.com/share/IFEU2U2JINCA/GitHub/home/SecUpwN/SpiderOak/SCREENSHOTS/LocationServices_Disabled.png)](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/251)

The best thing would be if our App would only notify the user **once**. Feel free to propose any other solution for this, but I noticed myself that it is pretty annoying having to click `CANCEL` every single time..

**Comment by E3V3A** [comment]
Yes, this is indeed very annoying, but is related to the GPS use and issue #246. It is Google location services pushing that message, then following with another message from Google. But second message you should select "Cancel"... @SecUpwN Can you get screenshot also of second message?

**Comment by SecUpwN** [comment]
@E3V3A, which second message? I don't get one. Just the above from OP.

**Comment by E3V3A** [comment]
After you select `OK` to the message above, you'll get this screen: 

![locatioservices1](https://cloud.githubusercontent.com/assets/194392/5592555/ec737102-91dc-11e4-98d8-be6440df0dd0.png)

Then this window pop-up:

![locationconsent1](https://cloud.githubusercontent.com/assets/194392/5592561/0c445fbe-91dd-11e4-8cc1-c1e02ab94ddb.png)

And you should select `Disagree`.

**Comment by SecUpwN** [comment]
Thanks for the clarification, I actually get this and it is also working as it should. But I am one of those guys who likes to avoid using GPS at all times. Thus, we should enable suppression as in the OP.

**Comment by E3V3A** [comment]
I think (?) this is related to the Google permission:
```
android.permission.WRITE_GSERVICES	   : Allows an application to modify the Google service map. 
```
Unfortunately it is not clear what the `Google Service Map` really is and is doing...

So then we have to find out how we can use that to automatically "Disagree".

**Comment by DJaeger** [comment]
How about checking GPS before using it and not simply forcing it to use and if it is not active showing a dialog like the following?

<table>
  <tr>
    <td colspan="3"><b>GPS disabled</b></td>
  </tr>
  <tr>
    <td colspan="3">
      AIMSICD can not check and/or track<br/>cells if GPS is disabled.
      <br/>
      Do you want AIMSICD to wait for GPS,<br/>stop cell checking/tracking<br/>or reactivate GPS?
      <br/>
       [&nbsp;&nbsp;] Remember this
    </td>
  </tr>
  <tr>
    <td>Wait</td>
    <td>Stop</td>
    <td>Enable GPS</td>
  </tr>
</table>

**Comment by E3V3A** [comment]
Whats the difference between wait and reactivate?

**Comment by DJaeger** [comment]
"Wait will wait until it is activated next time, for example if you activate GPS yourself if you leave your house.
"Enable GPS" (reactivate) will active it imadiately or redirect the user to do it himself.
The text should be optimized to be more clear, this is only a first proposal.

**Comment by SecUpwN** [comment]
>How about checking GPS before using it and not simply forcing it to use and if it is not active showing a dialog like the following?

**THANKS, this sounds like a *much* better solution to me, @DJaeger! Enhanced text proposal (removed the wording around checking, because as far as I know our app currently continuously checks cells if they match the imported OCID database - please correct me if I'm wrong here):

<table>
  <tr>
    <td colspan="3"><b>GPS disabled</b></td>
  </tr>
  <tr>
    <td colspan="3">
      AIMSICD can not track cells if<br/>GPS is disabled.
      Do you want<br/>AIMSICD to wait for GPS,<br/>stop cell tracking or reactivate GPS?
      <br/>
[&nbsp;&nbsp;] Remember this choice
  <tr>
    <td>Wait</td>
    <td>Stop</td>
    <td>Enable GPS</td>
  </tr>
</table>

**Comment by E3V3A** [comment]
From that window it is still not clear to the user what is the difference between Waiting and Enabling...and neither do I.

**Comment by DJaeger** [comment]
How about:

<table>
  <tr>
    <td colspan="3"><b>GPS disabled</b></td>
  </tr>
  <tr>
    <td colspan="3">
      AIMSICD can not track cells if<br/>GPS is disabled.
      <br/>
      What do you want AIMSICD to do?
      <br/>
      <b>Wait</b> until GPS is activated</br>next time and then continue<br/>tracking
      <br/>
      <b>Stop</b> cell tracking
      <br/>
      <b>Activate GPS</b> now and continue<br/>tracking
      <br/>
       [&nbsp;&nbsp;] Remember this
    </td>
  </tr>
  <tr>
    <td>Wait</td>
    <td>Stop</td>
    <td>Activate GPS</td>
  </tr>
</table>

Any ideas to shorten this?

**Comment by DJaeger** [comment]
@SecUpwN: Please rename this issue, for example to "Suppress multiple GPS Notifications", that it's more clear what it is about and we can find it.
Thanks.

**Comment by E3V3A** [comment]
done

**Comment by SecUpwN** [comment]
>Any ideas to shorten this?

Here is my suggestion:

<table>
  <tr>
    <td colspan="3"><b>Attention: GPS is disabled!</b></td>
  </tr>
  <tr>
    <td colspan="3">
      AIMSICD can not track cells if<br/>GPS is disabled. Please decide:
      <br/>
      <b>Wait</b> until GPS is activated</br>next time to continue tracking
      <br/>
      <b>Stop</b> cell tracking continuously
      <br/>
      <b>Activate GPS</b> now and continue</br>tracking for antenna map viewer
      <br/>
       [&nbsp;&nbsp;] Remember this choice
    </td>
  </tr>
  <tr>
    <td>Wait</td>
    <td>Stop</td>
    <td>Activate GPS</td>
  </tr>
</table>

**Comment by E3V3A** [comment]
Do we need both wait and stop? Right now, if you choose cancel on the google pop-up, GPS activation it is stopped automatically. Let's try not to accommodate for too many options.. So I don't think we need the wait option.

**Comment by TPS** [comment]
I understand @SecUpwN's dialog box  better if "continuously" is replaced by "completely" or "permanently," & that change makes the difference between "Wait" & "Stop abundantly clear.

**Comment by DJaeger** [comment]
Permanently sounds like you can never reactivate it.
Change continuously to completely could be a solution.

@E:V:A: You are right, but with that it will stay deactivated until it is manually reactivated. The "Wait" option is a "do not care anymore" option to automaticly activate and deactivate tracking with activating and deactivating GPS

**Comment by E3V3A** [comment]
How about?

<table>
  <tr>
    <td colspan="3"><b>Attention: GPS is disabled!</b></td>
  </tr>
  <tr>
    <td colspan="3">
      AIMSICD can not track cells if<br/>GPS is disabled. Please decide:<br/>
      <b>Stop</b> cell tracking or <br/> 
<b>Activate GPS</b> now and continue</br>tracking for antenna map viewer
      <br/><br/>
       [&nbsp;&nbsp;] Remember this choice
    </td>
  </tr>
  <tr>
    <td>Stop</td>
    <td>Activate GPS</td>
  </tr>
</table>

**Comment by DJaeger** [comment]
@E3V3A: That is what we currently have with the extention of the choose to remember!?

**Comment by E3V3A** [comment]
I though that was what AOS gave us? Now you're saying its produced by our App? 
Hell, if I'd known, I'd removed it long ago...

**Comment by DJaeger** [comment]
Where did I say, that it is produced by the app?
It is only triggert by the app, but produced by AOS.

**Comment by swordsteel** [comment]
I think it should be a toggle anyway. Consider a dude sitting at home or office and not moving for half a day. The cell masts aren't going to move around him. So the point of gps in an already known location doesn't make sense but also gives much better battery life.

**Comment by agilob** [comment]
>he cell masts aren't going to move around him

;_; this is all what this project is about

**Comment by swordsteel** [comment]
Very true, but so is scaling to the threat level. If your device already knows the area from previous cell monitoring, and you are mostly stationary in that area, the gps becomes redundant as long as you are not moving because the location is known, the existing cell masts have already been fingerprinted, so gps could in effect be turned off if you know where you are.

Example of this is if I am at home and I have (let's use the word "fingerprinted" for now) fingerprinted my area with gps enabled on Android-IMSI-Catcher-Detector, As long as I don't move I should be able to turn off the gps in AICD and the device will still monitor for rogue IMSI catchers because the location is already known. The primary benefit of a toggle like this is to give better battery life to the phone and to have a tighter grip over the gps unit.

GPS always on is worrisome, it would mean I need to vet every app on my phone, as to whether or not it has access to the gps device. I think that would be tedious for the average user. The neat solution is to toggle the gps on demand based on the user making the decision on his current location and the user threat level.

**Comment by agilob** [comment]
Yes, I agree, that's why AIMSICD should use not **only** GPS location but also WiFi and network.

**Comment by SecUpwN** [comment]
@He3556, would you please update me on why you closed this Issue? Thanks. :)

**Comment by He3556** [comment]
Sorry, looks like  i was to quick here.

**Comment by SecUpwN** [comment]
@NezSpencer, thanks for offering your helpo to work on this! Are you able to change the current notification seen in the OP to the one described in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/251#issuecomment-128287748? I guess that will be most convenient to our users.

**Comment by NezSpencer** [comment]
I like @E3V3A 's proposed dialog but with little modifications as shown below

|  __Attention: GPS is disabled!__   |
|---|
|  AIMSICD can not track cells if GPS<br> is disabled. <br> Please __Enable GPS__ for cell tracking. <br><br> [  ] Remember this choice  |
|Not Now |: Enable GPS:| 

In addition, there should be an __enable GPS__ preference on the settings screen

**Comment by NezSpencer** [comment]
edit : there should be an __Enable GPS__ to the right of the __Not now__ button. I dont knw why it did not show

**Comment by NezSpencer** [comment]
something like this

| __Attention: GPS is disabled!__ |
| --- |--- |
| AIMSICD can not track cells if GPS<br>is disabled.<br>Please Enable GPS for cell tracking.<br><br> [ ] Remember this choice <br>
Not Now &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Enable GPS |

**Comment by SecUpwN** [comment]
@NezSpencer, looks great! Feel free to craft a pull request to finally fix this Issue with it.
