### ISSUE TITLE
Samsung Galaxy S2: Strange glitch in Cell Information

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#255]
I have a friend running our App on his Samsung Galaxy S2 Plus and experiences this glitch.
Below screenshot shows the wording `Ciphering Indicator` - is that how it's supposed to look?

[![Cell_Information](https://cloud.githubusercontent.com/assets/6000299/5604393/a6fe128c-93ba-11e4-90f4-7708a0ab75ec.png)](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/255)

**Comment by E3V3A** [comment]
Yes, but the *S2 Plus* is not a GT-I9100, so this doesn't work, or you'd have seen something more there. What's the exact model number of that phone?
