### ISSUE TITLE
Move text fragments from About icons to strings.xml

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#256]
The text next to the detection icons in the `About` settings drawer in the `../res/layout/about_fragment.xml` should be moved to the `../values/strings.xml` file for easy edit and access.

**Comment by E3V3A** [comment]
Perhaps this doesn't make sense after all...

**Comment by SecUpwN** [comment]
@E3V3A, I see that differently: It **does** make sense. But I guess this Issue can be handled as a duplicate of #190 since this one will likely restructure it anyway. Please continue discussion there.
