### ISSUE TITLE
Cell signal strength data cannot be seen in database viewer

### ISSUE THREAD

**Issue by Ueland** [SecUpwN/Android-IMSI-Catcher-Detector#257]
I suspect that i have forgotten to implement that feature, creating this ticket as a reminder to myself.

**Comment by evilsocket** [comment]
Hi @Ueland I'd like to work on this issue since it seems to be a good starter for me, could you please tell me which kind of data are you referring to? ( unique bts data, bts measurements, ... )

**Comment by Ueland** [comment]
This is the data stored in the cellSignal-table ( https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java )

**Comment by evilsocket** [comment]
yeah but it's actually shown in the BuildTable method here https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/app/src/main/java/com/SecUpwN/AIMSICD/fragments/DbViewerFragment.java#L167 ... I see AvgSignal and RSS fields, so I was wondering where do we miss that.

**Comment by Ueland** [comment]
That is from the OpenCellID-data, this issue is about the data the device itself picks up and stores.

**Comment by evilsocket** [comment]
got it, thanks

**Comment by Ueland** [comment]
no problem! :)

**Comment by Ueland** [comment]
I will need to get this implemented by thursday due to a field trip to a "spy area", can you get it up before that or should i dig into it? Sorry about the nagging.

**Comment by evilsocket** [comment]
I can't

**Comment by Ueland** [comment]
Aight, no worries, i will look into it :+1:

**Comment by E3V3A** [comment]
Sure enough, now it works! :)

**Comment by SecUpwN** [comment]
>Sure enough, now it works! :)

I can confirm that it works, too. @Ueland, would you please clarify the question of E:V:A and see if the time period for saving the data can be enhanced somehow? If not, close this Issue when it is solved.

**Comment by Ueland** [comment]
@E3V3A Yes, this is part of #97. Based on @He3556 s original sketch, data will only be saved in bulks every B seconds. It is quite possible to save it to DB ASAP if we want to do that instead, but i suspect that it is a good thing to not lock the database once every thirty seconds as it keeps any other code from writing to the DB i the meantime.

**Comment by E3V3A** [comment]
@Ueland I'm not sure it works that way. The new SQLite3 is using some other methods while often in RAM disk like device, so I don't think we need to worry about any timing issues here. After all AOS is using dozens of DBs concurrently... Just my though.

**Comment by E3V3A** [comment]
More interesting is if the Signal values shown is indeed **dBm** or **ASU** units or soemthign else? dBm are usually negative...

**Comment by Ueland** [comment]
It is dBm, but I removed the negative bit while saving the data (not quite sure why).  I will do a new PR that fixes all these issues.

**Comment by E3V3A** [comment]
Also i get huge numbers on some!  Please check.

**Comment by Ueland** [comment]
Got some example numbers?

**Comment by E3V3A** [comment]
I'll send in email...

**Comment by Ueland** [comment]
This will be fixed with the current pull request #275
