### ISSUE TITLE
Busted IMSI-Catchers in Oslo, Norway + Source Data

### ISSUE THREAD

**Issue by Ueland** [SecUpwN/Android-IMSI-Catcher-Detector#259]
Somebody want to look into this? (Wow)

All source data as zip: http://mm.aftenposten.no/2015/01/05-mobov/files/source.zip

processed as excel spreadsheet: http://mm.aftenposten.no/2015/01/05-mobov/files/csv.zip
processed as SQL: http://mm.aftenposten.no/2015/01/05-mobov/files/tables.sql.zip

Specs: http://mm.aftenposten.no/2015/01/05-mobov/files/teknisk_beskrivelse.pdf (Norwegian, but nice maps)

**Comment by E3V3A** [comment]
Awesome! Too bad we didn't get some support for completing this 1 year ago, and we'd be rich by now. :laughing: What is very interesting is that they have essentially used less parameters than what we propose to do. And if you look at the logcat output, you'll see this is exactly the output you'd have expected to see from our [SamsungMulticlientRilExecutor](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/app/src/main/java/com/SecUpwN/AIMSICD/rilexecutor/SamsungMulticlientRilExecutor.java) method, showing ciphering info ans the FUBAR timer (T3212 with the wrong name "T1312".)

**Comment by E3V3A** [comment]
Please leave the "Detection" label only for specific detection methods.

**Comment by SecUpwN** [comment]
>Yep, and some special measuring equipment, that could as well have been ours...in the future.

One more reason to find a better anonymous funding method! @Ueland have you been sifting through the data if there are other valuable things we can learn and implement into our App? @E3V3A, this is not really an Issue - how about me creating a new page for Developer Resources to add it there?

**Comment by Ueland** [comment]
I have not gone through the data yet, need some spare time on my hands first.

**Comment by E3V3A** [comment]
@SecUpwN Sound great.

**Comment by SecUpwN** [comment]
@Ueland, you data has been added to our new [Resources](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Resources). @E3V3A, feel free to polish. // Solved.
