### ISSUE TITLE
How IMSI-Catchers were detected in Norway

### ISSUE THREAD

**Issue by Ueland** [SecUpwN/Android-IMSI-Catcher-Detector#260]
Just summarizing this article from Norwegian, are all this points considered by this app?
http://www.aftenposten.no/nyheter/iriks/Derfor-konkluderer-ekspertene-med-at-dette-er-mobilspionasje-7846966.html

1: Duplicated cell IDs, the IMSI catchers "stole" the Cell ID of a neighbouring cell.
2: Some catches operated in two bands(3G + 4G?)
3: They had (very) high signals (this one we are working on)
4: "reselection values" changed a lot while they were active

**Comment by SecUpwN** [comment]
Awesome finding, @Ueland! Please add the missing points to our [Detection List](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/230)!

**Comment by E3V3A** [comment]
There's nothing missing! 
1. is the "LAC/CID Consistency" (2)
2. is the "MNO RAT Consistency" (11)
3. is the "RX Signal Strength" (9)
4. is 3 and possibly 7 and 8, as this is an ambiguous term.

**Comment by SecUpwN** [comment]
>There's nothing missing!

Means we're already taking care of these things. Issue solved. :smiley_cat:

**Comment by arshadsaudi** [comment]
SecUpwN  its awesome what you contemplated to do and hats off for that. Can you tell me the status for the progress achieved for these ?

**Comment by arshadsaudi** [comment]
I have commented even though the thread is closed
