### ISSUE TITLE
Incorrect artwork sizes in drawable folders

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#263]
Sorry folks, another Issue. If @tobykurien or @Ueland can calrify some things to me, I will assign this to myself and solve this quickly, especially since I am currently working with GIMP anyhow. Here it is:

After checking https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/463fec0c9f1dadd86ab04209ec146ab28a75e17b, I noticed that we are using different sizes in the `drawable` folders. But as far as I know Icons sizes really depend on what type of Icon it is and where it is placed within the App. With this Issue I would like to check and fix all of our Icons, map pins and anything else in the `drawable` folders.

---

**Resources:**

* [Android: Screen Densities, Sizes, Configurations, and Icon Sizes](http://stefan222devel.blogspot.com/2012/10/android-screen-densities-sizes.html)
* [Supporting different screens: Create different Bitmaps](https://developer.android.com/training/basics/supporting-devices/screens.html#create-bitmaps)

---

Question for @tobykurien: After you've had a close look into our `drawables`, is it only the map pins that are incorrect, or also the menu Icons or anything else as well? Please post a list what needs to be fixed!

**Comment by tobykurien** [comment]
Only the map pins that were recently modified. You should use this tool to correctly resize the drawables: https://romannurik.github.io/AndroidAssetStudio/

**Comment by SecUpwN** [comment]
@E3V3A, thanks for the instructions, I about to craft these at the very moment. Would these work?

* BLUE pin at largest scale: 144x144 canvas size and centered
* The pins GREEN ORANGE and RED are **not** changing size but placed on proper canvas

Please give me a hint if I misunderstood your instructions.

**Comment by E3V3A** [comment]
I haven't recompiled, but just from looking at them, I bet they are still too big, since the not-blue icons are all bigger than the blue one, when they should be < 33% of the colored ones size... (Which is how I tested before I made them all the same size.)

**Comment by SecUpwN** [comment]
@E3V3A, I do not get what to change. @tobykurien, would you please take a minute to correct it?

**Comment by E3V3A** [comment]
@SecUpwN If you don't get what to change, why did you change it? Now the icons are HUGE perhaps you should revert that icon PR...

**Comment by He3556** [comment]
The (absolute) sizes are correct of the icons. And the icons itself is a little smaller (about 30%) than the blue ones. The difference you can see from the distance between the circle and the border - the red line.
Let's try and compile it
![cl](https://cloud.githubusercontent.com/assets/2507905/5652627/6b038942-96b2-11e4-8bc2-8452a8a2c2f4.jpg)
![cl2](https://cloud.githubusercontent.com/assets/2507905/5652628/6d470fe4-96b2-11e4-9213-53944403dfcf.jpg)

**Comment by He3556** [comment]
Mhh, ok they are getting bigger when i zoom out. So i think we need to use the clustering feature of openStreetMap. No matter how small the icon is, it will always be to big as long as we show them all on the map and don't use the clustering.

**Comment by E3V3A** [comment]
I did, that's why I answered. Now at the largest zoom-in factor, the green dots are the size of a house, and the blue bigger. What you have to account for are not the border of the canvas, but the relative diameters in pixels. Thus the green diameter should be < 30% of the blue one, possibly more. Of course this is not fixed, but that is kind of what I found look better on my device. So if you have a larger screen it will probably look better as the dots become relatively smaller.

**Comment by E3V3A** [comment]
With the way these pins are drawn at the moment, using a fixed overlay (?) that doesn't scale along with the map (shadow layer), the icons we always look huge. Which is probably why Michael of Antennas decided to use circles drawn instead of icons. I don't know if you can scale the icons with the map, only OSM expert can answer. Perhaps @ziem? 

Please see his response in my email.

> >> - We're trying to get filled circles drawn in different colors and
>> sizes, precisely centered on the position.
>
> > Omsdroid doesn't support marker coloring like google maps. But this can be achieved using tinting or ColorFilter:
> > http://stackoverflow.com/questions/25482489/what-is-new-in-drawable-tinting-in-android-l-developer-preview-compared-to-previ (available only in Android L)
> > http://blog.danlew.net/2014/08/18/fast-android-asset-theming-with-colorfilter/
>


> >> - We'd like to have connecting lines to a few of these points.
>
> > This can be done with PathOverlay class. Which is deprecated ;(. Osmdroid authors recommended using https://code.google.com/p/osmbonuspack/ which is under GNU Lesser GPL license. Is it OK?
>
> Sound good to me, but it depend on the license, size and whether there
are any hidden and privacy invading bloat in that package. We have to
discuss with our developers.

**Comment by He3556** [comment]
To change it to vector/drawn icons would be a lot of work (for nothing than colored dots). 
Instead i rather try to get some dots done with one of the tools, Toby linked to. Give me some time...

**Comment by SecUpwN** [comment]
>If you don't get what to change, why did you change it?

@E3V3A, because I had a problem with the old Icons not respecting the `drawable` properties at all, no matter if the new pins would work as expected or not. We all have to be more patient with each other.

>So i think we need to use the clustering feature of openStreetMap.

@He3556, I am **very** thankful you're digging into this, and a special **THANKS** flies out to @ziem, I've heard he will be coding the clustering of the Icons. Awesome thing, will wait for the pull request!

>Instead i rather try to get some dots done with one of the tools, Toby linked to. Give me some time...

@He3556, do you want me to revert https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/c71112c94cf41c94d192d3a59fc6b4133910ce75 or should I keep it like this for now?
