### ISSUE TITLE
Raw data from IMSI catchers

### ISSUE THREAD

**Issue by MatejKovacic** [SecUpwN/Android-IMSI-Catcher-Detector#266]
Norwegian newspaper Aftenposten publishes raw data (logs, gps-traces etc) from cell phone surveillance finds in Oslo: https://www.reddit.com/r/netsec/comments/2rm9r5/norwegian_newspaper_aftenposten_publishes_raw/

They say they have used CryptoPhone (a German phone with security and privacy features) and Falcon II (counter intelligence equipment.).

Found on ReddIt (https://www.reddit.com/r/netsec/comments/2rm9r5/norwegian_newspaper_aftenposten_publishes_raw/).

**Comment by He3556** [comment]
Thank you @MatejKovacic for this information. 
We have a discussion about it here: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/259
Maybe you want to move the infos to this issue?

**Comment by SecUpwN** [comment]
Thank you for these findings, @MatejKovacic! Please post these in the Issue @He3556 mentioned.
