### ISSUE TITLE
Better error handling for Requesting OCID API key

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#267]
Requesting a second OCID API key within 24 hours of the first (from the same IP) results in a `Java Language Exception` because of `503 Service Unavailable`. We need a sensible error message here.

**Comment by Ueland** [comment]
Users still need to get a sane error message, a 503 does not explain the problem to them :)

**Comment by E3V3A** [comment]
This should be an easy one to do!  I guess a try/catch should do with a toast message. Where in the code do I have to look? @He3556 ?

**Comment by E3V3A** [comment]
@Ueland Could you provide a sane message for this, so we can close this?

**Comment by E3V3A** [comment]
From the [HTTP status codes](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes) wiki: 

`503 Service Unavailable`:
>    The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.

This can probably be handled in [CellTracker.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/b7c0a600c6759591d4687f69c8766327322f9a92/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java##L263-299), or maybe in [OpenCellIdActivity.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/app/src/main/java/com/SecUpwN/AIMSICD/activities/OpenCellIdActivity.java). I don't know what's better.

**Comment by E3V3A** [comment]
Could someone please test this? So that I can close it. @SecUpwN ?

**Comment by SecUpwN** [comment]
>Could someone please test this? So that I can close it.

@E3V3A, since you've already merged, it is closed. Works perfectly for me! Done?

**Comment by E3V3A** [comment]
Uhmm I have to merge to build for you to test. Why would you wanna close before confirmed fixed?

**Comment by SecUpwN** [comment]
>Uhmm Why would you wanna close before confirmed fixed?

I didn't close it. GitHub automatically closes Issues if you mention `fix #<Issues>` which *you* did with `added comments and tried to fix #267 and #287` as well as `Test fix of #267 and code re-formatting`. But my test with build 20 confirms that you've successfully added the sensitive error message `Only one new API key request per 24 hours. Please try again later.` now. Closing this since it is really solved.

**Comment by E3V3A** [comment]
Wow!  So GitHub does all this automatically...so what am I doing here!? GitHub should just fix all our bugs as well!
