### ISSUE TITLE
Add copyright in map

### ISSUE THREAD

**Issue by Gitschubser** [SecUpwN/Android-IMSI-Catcher-Detector#270]
The app use a map from OpenStreetMap.
Where could you find the copyright?
http://www.openstreetmap.org/copyright/en

**Comment by He3556** [comment]
Thanks for your hint, Gitschubser - we are currently working on the Map and we will add the copyright asap - maybe later tonight.

**Comment by SecUpwN** [comment]
Danke für Deine freundliche Benachrichtigung, @Gitschubser! Hast ein gutes Adlerauge. :smiley_cat: @He3556, please tackle this one. But where to add the copyright? I'll be updating `CREDITS` as well.

**Comment by Gitschubser** [comment]
Die Community von OSM kann bei fehlendem Copyright sehr pingelig sein ;-)

**Comment by SecUpwN** [comment]
>Die Community von OSM kann bei fehlendem Copyright sehr pingelig sein ;-)

Danke. Blickige Leute wie Du sind bei mir hoch angesehen. Mach' weiter so!

**Comment by He3556** [comment]
thats why i changed it immediately. 
And i can totally understand them - thanks a lot Gitschubser.
