### ISSUE TITLE
Map crashes, when BTS GPS coordinates are far from each other

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#272]
I just noticed, that if you have made measurements in one place,  and the next place differs a lot in location, the map crashes...

**Comment by SecUpwN** [comment]
@E3V3A, if #466 has been resolved, please see if this is fixed as well since @wvengen mentioned it,

**Comment by E3V3A** [comment]
Seem fixed.
