### ISSUE TITLE
CreditsRoll: Merging SOURCES into CREDITS

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#273]
[![CreditsRoll](https://github.com/frakbot/CreditsRoll/raw/master/img/scroll.gif "Once upon a time...")](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/273)

Looks **AWESOME**, right? Yes! With this Issue I would like to tackle what we've been talking about at the very beginning of this project: Having our `CREDITS` get displayed directly in our App, which is also part of the solution for #174. **NOTICE:** This is to be solved until we are in `BETA` stage, so no hurry on this one.

Maybe the funky @rock3r can chime in on this one so that I know how to implement this?

**Things to solve:**

* [CreditsRoll](https://github.com/frakbot/CreditsRoll) uses [Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0) - can we use it with our [our GPLv3+](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/LICENSE)?
* Our `SOURCES` shall be merged into `CREDITS` - but in a format that works with CreditsRoll
* The `CREDITS` file shall be easily updatable and be pulled into our App on each compilation
* When pressing the `CREDITS` button in our App, the funky CreditsRoll shall appear

**Comment by rock3r** [comment]
Well guys it's fairly simple to use `CreditsRoll` in your app... it works basically like a normal `TextView`, you `setText()` on it and (start the crawl animation](https://github.com/frakbot/CreditsRoll/blob/master/demo/src/main/java/net/frakbot/creditsrolldemo/MainActivity.java#L81). Easy peasy :)

**Comment by SecUpwN** [comment]
Thanks for the hints, @rock3r! I'd like to merge our `SOURCES` into the `CREDITS` file, which format do the `CREDITS` have to be in? Would you like to craft a pull request for transformiung our `CREDITS` button? :smiley_cat:

**Comment by rock3r** [comment]
You can literally show any text you want on there -- there is no specific format for the text. I'd recommend you to test it properly on devices, though, because you seem to have long lines in your credits and sources, which might not play that well with the crawl format. Just play with it until something you like comes out!

**Comment by SecUpwN** [comment]
>You can literally show any text you want on there -- there is no specific format for the text.

Hence my plan to merge `SOURCES` into `CREDITS` and restructure `CREDITS` like your [demotext](https://github.com/frakbot/CreditsRoll/blob/087214b2483c107c9ba4bd78935ffe4216ff817f/demo/src/main/res/values/strings.xml) to look good on all devices. To get this straight: I'll just replace the [Credits Link](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/c5ac81061ea0f378207cf23dbb50932cb9eb47de/app/src/main/java/com/SecUpwN/AIMSICD/fragments/AboutFragment.java#L84) with [MainActivity](https://github.com/frakbot/CreditsRoll/blob/master/demo/src/main/java/net/frakbot/creditsrolldemo/MainActivity.java) of `CreditsRoll`? Please excuse my lack of knowledge on how to add it, I'm having a hard time learning.

**Comment by rock3r** [comment]
Your `setLink()` will open another activity that will basically be really similar to the demo's `MainActivity`, instead of opening a URL. That should be all you need to do -- of course, do modify the `MainActivity` to suit your needs (e.g., you probably won't need the seek bar, and you might want to start scrolling the text automatically in `onResume`).

**Comment by rock3r** [comment]
As per the `CREDITS` file, you can keep them in a file, but they will need to be in the `assets` folder of your app, or they won't be included in the apk. Reading the file content from assets is then [quite straightforward](http://stackoverflow.com/a/16110044/488563).

**Comment by E3V3A** [comment]
As awesome this credit roll look,  I'm concerned about the performance impact on older devices such as single and dual core phones like,  GT-I9100

**Comment by E3V3A** [comment]
And test done in these?

**Comment by rock3r** [comment]
There shouldn't be any big performance issue - there is no OpenGL ES involved, it's just standard text drawing with some (native in Android) pseudo-3D transform. I don't have said device(s) to test on, but if you do, please let me know how it works.

**Comment by SecUpwN** [comment]
@rock3r, could you craft a pull request for this so that we just have to adjust our [CREDITS](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/CREDITS), please?

**Comment by rock3r** [comment]
I'd love to but I'm quite busy right now :( Sorry guys. On the bright side, it's easy, so I'm sure you can do it. I have basically explained what you have to do already, so it's just a matter of doing it (for which again, I'm sorry, I just don't have the time right now).

**Comment by E3V3A** [comment]
This is very cool, but perhaps a little bit too nerdy for the app? Also, it is not too easy to read for people with reading problems, or problems with their eyesight, or with very small screens.

**Comment by SecUpwN** [comment]
>This is very cool, but perhaps a little bit too nerdy for the app?

No, I disagree on that. If we don't add it into the App, people will likely not read the `CREDITS` at all. And then again, who really cares? We are coding a real "sci-fy" app here, so why not add some funk? ;-)

**Comment by kairenken** [comment]
@rock3r mCreditsRollView = (CreditsRollView) mActivity.findViewById(R.id.creditsroll); is returning null all the time. Do you have any idea what went wrong? You can find my commt here: https://github.com/kairenken/Android-IMSI-Catcher-Detector/commit/bb6e95388139ce93289a081e205337cc906c3173

**Comment by SecUpwN** [comment]
@kairenken, I have been discussing this with @banjaxbanjo and he sent you a fix via E-mail! ;-)

**Comment by SecUpwN** [comment]
@kairenken, this is to update you on the current situation: I have tried to merge the changes from your fork, but it broke our Travis CI cycle with the error message `A problem occurred configuring project ':app'. Cannot evaluate module CreditsRoll : Configuration with name 'default' not found.`. Seems as if `CreditRoll` uses deprecated libraries. Maybe you can update those to work neatly with our App, @rock3r? Summing it up, we had to revert the changes and have to re-think this. We will only merge it when it is working properly.
