### ISSUE TITLE
Many Missing BTS in Map Viewer

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#280]
Checking the BTS pins in the `Map Viewer`, reveals that most BTS near the currently connected cell are missing from the map. This has been confirmed as a problem with our app and not the imported OCID data. 

Here's how OCID shows the area (around the kings palace in Oslo):
![oslo_open_cellid](https://cloud.githubusercontent.com/assets/194392/5729240/a2b3f9be-9b79-11e4-9fbc-b44b623c737a.png)

Whereas in `Map Viewer`, the same area is shown like this. (The lonely pin on the left with with "2" is where the measurement were taken.)

![screenshot_2015-01-11-22-14-08 1](https://cloud.githubusercontent.com/assets/194392/5729267/e32b9aba-9b79-11e4-8f46-f18e8b833f98.png)

Perhaps @ziem has an idea of whats wrong?

**Comment by SecUpwN** [comment]
@E3V3A, how does a user know which dot color means what?

**Comment by ziem** [comment]
@E3V3A - I'll check it tomorrow but I'm adding all BTS:
[MapViewerOsmDroid.java#L581](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/app/src/main/java/com/SecUpwN/AIMSICD/activities/MapViewerOsmDroid.java#L581)
[MapViewerOsmDroid.java#L575](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/master/app/src/main/java/com/SecUpwN/AIMSICD/activities/MapViewerOsmDroid.java#L575)

**Comment by Ueland** [comment]
I know that Oslo has bad opencellid cover bit hopefully not that bad. :)

**Comment by E3V3A** [comment]
That's water point. The first map show that there should be excellent coverage!

**Comment by ziem** [comment]
Bug was also present in commit 11cdefb: ![screenshot](https://dl.dropboxusercontent.com/u/16134555/osmdroid/device-2015-01-14-191149.png).

**Comment by E3V3A** [comment]
Yes, I know... and I don't know how to find out when this started, without going back to test all alpha versions.

**Comment by ziem** [comment]
Everything seems OK - I think that it's not app bug. 

I changed my location to 59.91370666666667°, 10.750721666666667° and downloaded OpenCellId data. Then I saved CSV (from generated URL) and displayed data using [umap.openstreetmap.fr](umap.openstreetmap.fr):
![OpenCellId data](https://dl.dropboxusercontent.com/u/16134555/osmdroid/Zrzut%20ekranu%202015-01-15%20o%2021.59.40.png)

As you can see OpenCellId API doesn't return many of the BTS situated in Oslo (I don't know why).

Logs:
> Last known location (59.91370666666667°, 10.750721666666667°) = (1.04569144840741 rad, 0.18763549004882565 rad)
http://www.opencellid.org/cell/getInArea?key=SECRET_KEY&BBOX=59.01438647233198,8.956539505349062,60.81302686100135,12.544903827984273&lac=0&format=csv

BBOX is correct:
![BBOX](https://dl.dropboxusercontent.com/u/16134555/osmdroid/Zrzut%20ekranu%202015-01-15%20o%2022.15.05.png)

**Comment by He3556** [comment]
For me the BTS are on the right place in the map. Before i had 50% in the middle of the forest.

**Comment by Ueland** [comment]
@ziem wtf, i checked the map on opencellid.org and they display them correct. Bug in their downloads perhaps?

**Comment by ziem** [comment]
Yes, but I may be wrong. Can someone confirm this?

**Comment by SecUpwN** [comment]
>Yes, but I may be wrong. Can someone confirm this?

@ziem, I'd like to! Some detailed instructions to get the confirmation you need?

**Comment by E3V3A** [comment]
Yes, there are a may missing, and the missing ones seem to be the ones nearby. A few potential problems I can think of:
 1. I remember we talked about making a some kind of bounding circle where outside BTS would be marked as insecure (since they shouldn't be picked up in an urban environment). But I don't know if this was implemented or even started. Perhaps @He3556 knows? (Yes, the BTS shown are correct, but there are loads of them missing.) 
 2. Or it could be a faulty initial implementation of the BTS color/selection rules in #250.
 3. It could be a OCID download API problem. Perhaps they started to apply filtering on downloaded data?
 4. Or it could be a faulty way that we select what OCID data to download. (It worked before.)

**To test**, we have to first confirm that we're actually downloading the missing OCID data. Use different app and find a few BTS towers near you, then use AIMSICD and see if they are present in the `Database Viewer` table. Then open the `Map Viewer` and see if you can find them.

@SecUpwN  To test this: Download any other App using OCID data and compare. You can even use AIMSICD versions <= v.0.1.24.

**Comment by Gitschubser** [comment]
Limit, only maximum 1000 cells.

http://wiki.opencellid.org/wiki/API
<limit> 	integer 	A number defining maximum size of the returned list. Default and maximum value is 1000. 	yes

**Comment by Gitschubser** [comment]
http://www.opencellid.org/cell/getInArea?key=SECRET_KEY&BBOX=59.01438647233198,8.956539505349062,60.81302686100135,12.544903827984273&lac=0&format=csv

shows only 1000 cells (1001 - first line with description)

![cells](https://cloud.githubusercontent.com/assets/7853509/5779762/aa724a38-9da5-11e4-867d-298f5ed093c5.jpg)

**Comment by E3V3A** [comment]
Very interesting. This means that we have to get a GPS lock first, and use that result for the OCID downloa, instead of the current default. (What is the default now?)

**Comment by SecUpwN** [comment]
Thank you for your valuable input, @Gitschubser. So to sum it up, our implementation is right and OpenCellID just cannot display more than 1000 cells? Would this in turn mean that this Issue is solved?

**Comment by E3V3A** [comment]
@Gitschubser  How are those first 1000 selected? (What criteria? GPS, LAC, CID?)

**Comment by Gitschubser** [comment]
@E3V3A Good question, i think only @msemm can answer it.
I have not found any system how the result is sorted.

Here are the answer of the first ten lines from http://www.opencellid.org/cell/getInArea?key=SECRET_KEY&BBOX=59.01438647233198,8.956539505349062,60.81302686100135,12.544903827984273&lac=0&format=csv:
59.96187479411764,11.002951294117645,242,2,794,2101,0,-1,34,1,GSM,,,,,,,,
59.976147519230786,11.052338365384617,242,2,794,2109,0,-1,52,1,GSM,,,,,,,,
59.937758375,10.98884475,242,2,794,62021,0,-1,8,1,GSM,,,,,,,,
59.93059159999999,10.9837818,242,2,794,34322,0,-1,5,1,GSM,,,,,,,,
59.93445735135135,10.964788162162161,242,1,12001,2145,0,-1,37,1,GSM,,,,,,,,
59.9630875625,11.015284812500001,242,2,794,34321,0,-1,16,1,GSM,,,,,,,,
59.93133909090909,10.961942454545454,242,5,2010,6583,0,-1,11,1,GSM,,,,,,,,
59.9272915,10.967234499999998,242,5,2010,6562,0,-1,6,1,GSM,,,,,,,,
59.938756974999976,10.9868943375,242,1,12001,2603,-90,2338,80,1,GSM,,,,,,,,
59.93665197826089,10.968867108695653,242,1,12001,22069,-51,1971,46,1,GSM,,,,,,,,
59.93272476973682,10.962016730263153,242,1,12001,22039,0,1398,152,1,GSM,,,,,,,,


The api returns only 1000 cells but opencellid.org shows all cells in her own map.
Only a restriction from the project OCID. 

The bbox in is  Android-IMSI-Catcher-Detector/app/src/main/java/com/SecUpwN/AIMSICD/utils/Helpers.java defined as 100 mile = 161 km?
I think in a area with more than 1000 cells you get only always the first 1000 lines from OCID back.

* Requests Cell data from OpenCellID.org, calculating a 100 mile bounding radius
* and requesting all Cell ID information in that area.

**Comment by Gitschubser** [comment]
The bbox http://opencellid.org/cell/getInAreaSize?key&BBOX=59.01438647233198,8.956539505349062,60.81302686100135,12.544903827984273 includes 20250 cells! ;-)

**Comment by E3V3A** [comment]
Ah! Thanks @Gitschubser, that must indeed be the problem!

I'll change it and add some comments there and see what happens. I think we should not have a radius larger than ~10 Km in an urban environment. Timing Advance reaches to 35 Km. But that is way too large in urban areas. We should start with this, otherwise we have to tune it depending on some other parameters or in settings, or by first fetching the [number of cells in a particular location](http://wiki.opencellid.org/wiki/API#Getting_the_number_of_cells_in_a_specified_area). So let's try to fix this by hard coding the value for testing.

**Comment by E3V3A** [comment]
Fixed! **Dev's**: Please test with my latest build and [commit](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/9278d0bafbd46521773f6f5ddfd5aee8891cb482). 
All thanks to @Gitschubser !
