### ISSUE TITLE
Bug Report E-Mail address not added (in K-9 Mail)

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#287]
[![K-9 Mail](https://github.com/k9mail/k-9/raw/master/images/feature_graphic.png)](https://github.com/k9mail/k-9/)

Ok, here we go: I am filing this Issue because the bug report E-Mail address that is implemented in our App and which should be automatically added to the bug report E-Mail in `Debugging`, is missing.

Hence, since I thought I does not show anyhow and we might not need it, I tried to remove it. This was a fatal failure since several other Issues popped afterwards. ~~Luckily, @E3V3A fixed my breakage with https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/75984a13ad5fc03233387abc730535b53a9e982f.~~ 

Question: Is this an Issue that only appears when using my beloved [K-9 Mail](https://github.com/k9mail/k-9), or is this a general Issue that everybody has? How come the E-Mail address does not get added into the `To:` field?

**Comment by E3V3A** [comment]
Also make sure K9 can handle attachments from API.  Contact k9 Dev.

**Comment by cketti** [comment]
From http://developer.android.com/reference/android/content/Intent.html#EXTRA_EMAIL

    A String[] holding e-mail addresses that should be delivered to.

Make sure `EXTRA_EMAIL` contains a string array, not a single string.

**Comment by E3V3A** [comment]
@SecUpwN, I didn't fix this! I fixed the other DB Viewer one...

**Comment by SecUpwN** [comment]
>I didn't fix this! I fixed the other DB Viewer one...

@E3V3A, in the OP I meant that you reverted my changes, which fixed the DB failures to occur.

>Make sure `EXTRA_EMAIL` contains a string array, not a single string.

Thanks for listening to my E-Mail and chiming in, @cketti! Would changing [Line 150](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/75984a13ad5fc03233387abc730535b53a9e982f/app/src/main/java/com/SecUpwN/AIMSICD/activities/DebugLogs.java#L150) from `intent.putExtra(Intent.EXTRA_EMAIL);` to `android.intent.extra.EMAIL(Intent.EXTRA_EMAIL, "a3841c3c@opayq.com");` be the right solution?

**Comment by cketti** [comment]
```java
intent.putExtra(Intent.EXTRA_EMAIL, new String[] { "a3841c3c@opayq.com" });
```

**Comment by E3V3A** [comment]
Thanks a bundle @cketti! 

@SecUpwN  Please let me know in internal chat before merging code! This time I was working on this when you made the change causing merge conflict and wasting my time. Thanks.
