### ISSUE TITLE
Highlighting updates on "Phone/SIM Details" page

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#288]
The current  Main page `Phone/SIM Details` doesn't show network updates very clearly. The way it currently looks is this:

![Hmm](https://spideroak.com/share/IFEU2U2JINCA/GitHub/home/SecUpwN/SpiderOak/SCREENSHOTS/Device_Details.png)

What I would like to see is that items that have just changed are highlighted in (for example) yellow and then slowly fading away into the normal blue text with time. Perhaps around ~20 seconds or so. 

This would probably require that the code is using a [ACTION_PHONE_STATE_CHANGED](http://developer.android.com/reference/android/telephony/TelephonyManager.html#ACTION_PHONE_STATE_CHANGED) listener, and not a polling mechanism, if not already implemented. It has to use a *listener* and not a polling mechanism or otherwise we risk missing quick changes. In addition, any changes will have to be immediately added to the `EventLog` of the DB. See #215.

**Comment by tobykurien** [comment]
We aren't polling, we are infact using a phone state listener, see: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L251

**Comment by E3V3A** [comment]
@tobykurien I know, I wrote the comments there, but then:
 1. Why isn't the info above immediately updated in the measurement DB?
 2. Why aren't we using it that way?  Since [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/1afeb541e1dc23425506225d194184f0c9278f82/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L251-L257) we're doing some kind of polling with a default [REFRESH_RATE](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/1afeb541e1dc23425506225d194184f0c9278f82/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L1132-L1137) delay of 25s. 

Would be great if someone could clearly explain this.

**Comment by SecUpwN** [comment]
I see that this Issue may be part of #288. Linking to keep track of it.

**Comment by E3V3A** [comment]
This is a real issue, but the comments above are outdated. There are some solutions for dynamically highlighting text found on Stackexchange.

**Comment by SecUpwN** [comment]
Just stumbled across [Android Transition](https://github.com/kaichunlin/android-transition). Maybe @kaichunlin can help us with our Issue here?

**Comment by kaichunlin** [comment]
Hi there, if my understanding is correct, you just need to animate the changed item(s). In this case it can be accomplished using the technique [here](http://stackoverflow.com/questions/18216285/android-animate-color-change-from-color-to-color).

**Comment by E3V3A** [comment]
Thanks, but how would this be implemented in these particular items?
