### ISSUE TITLE
Missing OCID columns in DBe_import table 

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#292]
Apparently not all the OCID columns available from the downloaded CSV file is used to populate the `DBe_import` table. Out of 19 possible items, we're only using 8. 

```bash
# sqlite3 -header aimsicd.db 'select * from opencellid;' |head -2
_id|Lat|Lng|Mcc|Mnc|Lac|CellID|AvgSigStr|Samples|Timestamp
1|54.63376|25.160243|246|3|20|1294|0|-1|2015-01-19 20:52:10
2|54.6430095|25.2016433|246|3|20|41119|0|-1|2015-01-19 20:52:10

# cat opencellid.csv
lat,lon,mcc,mnc,lac,cellid,averageSignalStrength,range,samples,changeable,radio,rnc,cid,psc,tac,pci,sid,nid,bid
54.7260,25.2562,246,1,101,4746,0,-1,14,1,GSM,,,,,,,,
54.6799,25.2886,246,3,601,2732424,9,-1,8,1,UMTS,41,45448,,,,,,
```

Unfortunately because of the confusing state of the **old** [DB table structure](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/215), I have not been able to track down this issue. However, I think it's done here in [AIMSICDDbAdapter.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/09c37741fcd55fbc0d3b741e4555a94eee0cf174/app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java#L509-649) somewhere. 

Although it would be a luxury to get all, the minimum set for our current DB structure would be:
```
lat, lon, mcc, mnc, lac, cellid, averageSignalStrength, --, samples, changeable, radio, rnc, cid, psc, --, --, --, --, --
```
They should be described [here](http://wiki.opencellid.org/wiki/API#Getting_the_list_of_cells_in_a_specified_area) , but unfortunately the CSV file we have doesn't correspond very well to this, and some items are unknown or ambiguous. Like "cellid" and "cid"...

Perhaps @msemm or @Gitschubser has an answer?

**UPDATED**: 2015-08-02

**Comment by E3V3A** [comment]
I've now implemented:  **range, changeable** and **radio**. I don't know if we need the others, and I still didn't get any clarification of the difference between "cellid" and "cid" from @msemm...  

@He3556  Can you check if we need any other from here, and why? (If nothing, we can close this.)

**Comment by Gitschubser** [comment]
id,mcc,mnc,lac,cellid,lat,lon,created_at,measured_at,signal,rating,speed,direction,radio,ta,rnc,cid,psc,tac,pci,sid,nid,bid
54ac0e710cf296cabe3a80b3,262,1,21115,2666627,48.796281,9.202933,1420562010000,1420544835000,-89,,1.0,234.0,UMTS,,40,45187,,,,,,

cellid=2666627 (28 Bit)
cid=45187 (16 Bit)

Mod(cellid/65536) = cid

**Comment by SecUpwN** [comment]
@Gitschubser, thanks, but your comment above is currently like throwing a rock at us. What is it?

**Comment by E3V3A** [comment]
@Gitschubser  Thanks a lot, that explains it perfectly! I wish that info had been found in the API pages and not hidden away with different labels on the [FAQ](http://wiki.opencellid.org/wiki/FAQ) page. ;)

**Long CellID vs. short Cell ID** (CellID vs CID):

> The formula for the long cell ID is as follows:
> Long CID = 65536 * RNC + CID
> 
> RNC: the Radio Network Controller
> CID: a short cell ID (an integer in the range of 0 to 65535)
>
> If you have the Long CID, you can get RNC and CID in the following way:
> RNC = Long CID / 65536 (integer division)
> CID = Long CID mod 65536 (modulo operation)
>
> Example for long cell ID 66808694:
> RNC = 66808694 / 65536 = 1019
> CID = 66808694 mod 65536 = 27510

**Comment by Gitschubser** [comment]
Sorry, i thought that are simple basics here.
The cellid (UMTS) 2666627 (28 bit) includes the rnc 40 and the cid 45187 (16 bit).

rnc = cellid/65536
cid (16 bit) = modulo(cellid/65536)

2666627/65536=40,689 -> rnc = 40

Modulo: http://en.wikipedia.org/wiki/Modulo_operation
rnc: Radio Network Controller http://en.wikipedia.org/wiki/Radio_Network_Controller
Bit: http://de.wikipedia.org/wiki/Bit or http://en.wikipedia.org/wiki/Bit
http://www.duven.de/d2sender/d2dxb.htm

I hope i could explain it better.

**Comment by SecUpwN** [comment]
@Gitschubser, thanks that was perfect. SCubs on! :smile:

**Comment by E3V3A** [comment]
This has mostly been resolved in the new DB overhaul.
