### ISSUE TITLE
Better error handling for blocked downloading

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#293]
**Problem:** Attempting to download OCID data when not having a permissive firewall, results in an uncaught exception. This is especially important to fix when we will have different `DBe_import` data options.

**Solution:** We need to:
 1. find a way to check if *AFWall+* (or other firewall) is blocking our network connection and
 2. make an exception `catch{}` in the download code, to display a sensible error message.

You can reproduce error by installing *AFWall+* and disallow any network connection. Then try to download OCID data.

**Comment by SecUpwN** [comment]
Maybe @ukanth would be so friendly to chime in on on this one?

**Comment by E3V3A** [comment]
I guess we need to add something like this, somewhere.

```java
 try {
        result = new httprRequest().execute().get();
        // A work around to fix the problem
        if(internet avialable) {
            blahblah();
        } else { 
            blahblah2();
        }
    } catch (InterruptedException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } catch (ExecutionException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
```
PS. I have no idea what the correct exceptions should be there...

I'm trying to track down where the download is done, and have reached an enigma.
There are two places where I think this can happen, either in:
  1. [Helpers.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/3a5039efb6f4c7e13627e422d972657179d0de2e/app/src/main/java/com/SecUpwN/AIMSICD/utils/Helpers.java#L117-136) or
  2.  in [RequestTask.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/b06b791d049e74ac7163b18dce14028886ea3c63/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java#L63-174). 

But in (2), and at first sight, it seem that it is used for uploading data to OCID, but then it is immediately followed by a download from their servers.... ??? If that is what is actually happening, then that is another bug, as we should not attempt to download data we just uploaded. Also, OCID take at least  a few minutes before adding new data to their servers, and by even attempting to do this, we're corrupting our own data with potential fake BTS data. Any upload should be done by careful user control, if at all... 

I would appreciate some enlightenment and a few code comments.

**Comment by E3V3A** [comment]
I tried to reproduce this bug and now it doesn't appear. Can someone else please check?

**Comment by SecUpwN** [comment]
>I tried to reproduce this bug and now it doesn't appear. Can someone else please check?

Should be **fixed** since AIMSICD spits out the correct error message: `Error retrieving OpenCellID data. Check your network!` We can expand that error message with adding something like `Check your network and firewall settings!`. Please **close this** if you consider the current message good enough.
