### ISSUE TITLE
AIMSICD freezes Lollipop device

### ISSUE THREAD

**Issue by benutzer74** [SecUpwN/Android-IMSI-Catcher-Detector#294]
AIMSICD version 0.1.25-alpha-b15 freezes my device, running Android Lollipop 5.0.2 with Cyanogenmod CM12.

With Cyanogenmod CM11 (KitKat), AIMSICD runs well.

The device freezes right after starting AIMSICD. Only a device reset with power button key works. The device is completely stuck after starting AIMSICD.

I have no clue, if this might be a Cyanogenmod specific or Android 5 issue.

Can other Lollipop users run AIMSICD on their Lollipop device?

**Comment by Ueland** [comment]
What device is this? I have no problem with latest Android on my Nexus 5.

**Comment by benutzer74** [comment]
It´s a SONY Xperia Z1. Generally the Lollipop CM12 works pretty stable for such early nightly.

I think I could use logcat to see what happens when running AIMSICD?

**Comment by E3V3A** [comment]
Yes, please provide a logcat according to our instrux [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues).

**Comment by benutzer74** [comment]
Magic has happened...
Instead of resetting the device with the power button I waited and the device did a reboot on its own. And now AIMSICD runs...

I was able to download the OpenCell data and put the OpenCell ID key into preferences. I looked at the information tabs and they work...

All I did was to wait for the device for automatic reboot, it works now...

Do I have to click on "Close and comment"? Can the admin close this topic? I am totally new to Github. I guess when I close this, you can´t reply here, right? I´ll see. Thanks.

**Comment by E3V3A** [comment]
@benutzer74  Thank you for reporting! Please feel free to report any further issues in the future. You're one of the few here on an L device (AFAIK) so you're testing is valuable.

**Comment by SecUpwN** [comment]
@benutzer74, herzlich Willkommen zu unserem Projekt gegen IMSI-Catcher! Wenn Du Fragen haben solltest und Englisch sich als zu kompliziert erweisen sollte: Viele von [uns](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Contact) sprechen auch Deutsch.

**Comment by SecUpwN** [comment]
@benutzer74, herzlich Willkommen zu unserem Projekt gegen IMSI-Catcher! Wenn Du Fragen haben solltest und Englisch sich als zu kompliziert erweisen sollte: Viele von [uns](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Contact) sprechen auch Deutsch.

**Comment by SecUpwN** [comment]
@benutzer74, herzlich Willkommen zu unserem Projekt gegen IMSI-Catcher! Wenn Du Fragen haben solltest und Englisch sich als zu kompliziert erweisen sollte: Viele von [uns](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Contact) sprechen auch Deutsch.
