### ISSUE TITLE
Progress Bar: Not showing Progress

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#297]
Yes, we actually have a progress bar in our App! Wait, you've never seen it? It is likely because something is preventing it from working properly. I have marked in **RED** where it is located: 
![progress_bar](https://cloud.githubusercontent.com/assets/6000299/5860640/9b34e170-a25a-11e4-8361-18d4ddbc75e7.png)

Our progress bar is actually quite awesome and works somewhat like the one used in the @Trello App. Fixing this Issue should include that the progress bar fires off whenever **anything** takes any time - thus for example fetching OCID data, backing up and restoring Databases and similar things.

**Comment by E3V3A** [comment]
I'll look into it. The problem is that you need some kind of feedback from the process, and when it comes to the HTTP fetching, there is no feedback until either failed or done, AFAICT, but I could (hopefully) be wrong. Perhaps this can be done with timer or something...

**Comment by SecUpwN** [comment]
>Perhaps this can be done with timer or something...

From a programing perspective, how tifficult is it to implement the launch of the progress bar when hitting `Download Local OCID Data` and finishing it when result is either `failed/no internet` or `success`?

**Comment by E3V3A** [comment]
Actually this brings up a new issue..  #303.

**Comment by E3V3A** [comment]
I looked at this, and I can't see why it's not showing. Perhaps it's doing the download/update too fast to be seen/shown or the max progress value is getting initiated wrong? I think @tobykurien understand this much better than I. Can you please have another look?

**Comment by E3V3A** [comment]
Looking at the part that is supposed to do the downloading, [this line](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/2fd528115526d666fe8e3337345942e2f1359539/app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java#L828) yields 0, which is probably why there is no ProgressBar shown from subsequent lines. (I commented out those lines.)

**Comment by E3V3A** [comment]
Like I said before, progress bar cannot be shown when downloading block-mode streams. In addition if the (restore) files are small, which they are most of the time. There will be no time to update the bar before its already done. You will simply not see anything. I guess you could try to update the bar between each file, and set it to 50% just to see something.
