### ISSUE TITLE
Crash at trying to view "Measured Signal Strengths" in Database Viewer

### ISSUE THREAD

**Issue by kolg** [SecUpwN/Android-IMSI-Catcher-Detector#300]
Description of the Crash mentioned in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/299:

What I did: 

- start aLogcatROOT, pause, clear. (optional, just for the log)
- open AIMSICD, go to Database Viewer, choose "Measured Signal Strengths", press "Load Data"
- App crashes, note pops up that AIMSICD was closed.
- go back to aLogcatROOT, pause, save log.
log: https://defuse.ca/b/DcM4uBqK

Hardware: Fairphone FP1, OS Cherry 1.6 (Android 4.2.2)
AIMSICD version v0.1.25-alpha-build-15

**Comment by E3V3A** [comment]
This seem to be the problem.
```
E/AndroidRuntime( 8283): Caused by: android.database.sqlite.SQLiteException: no such table: cellSignal (code 1): , while compiling: SELECT cellID, signal, timestamp FROM cellSignal ORDER BY timestamp DESC
```
However, we've been doing many changes since **b15**, so please try [this b23](https://www.sendspace.com/file/hz5d7a) one, and report back.

**Comment by kolg** [comment]
alright, thanks. no problems with b23 yet, but since my database is empty, I'll go and get some new tracking data. 
I'll report if something similar happens.
So I think this issue can be closed?

**Comment by E3V3A** [comment]
@kolg  Please close it if you think its working.
