### ISSUE TITLE
Add more info to email when sending debug report

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#301]
Using the built-in `Debug Logger` function to see logcat entries, you can also send the result via email. 
The problem? The email is missing crucial information about the device. We also need to:
 - [x]  add the output of `getprop | sort` to that email and
 - [x] ask the user to add a short message about the problem.

**Comment by SecUpwN** [comment]
>* ask the user to add a short message about the problem.

I would like to add to that: Messages should not be able to be send without having entered an additional error description. Not sure if we can prevent opening the sharing intent before this is done?

**Comment by E3V3A** [comment]
@SecUpwN 
I added the message and also tried to add the "getprop" output in the same email, but for some reason the result is empty. Perhaps @tobykurien can have a look, as this seem trivial. Please note that this code is now in the newly created `DevTest` branch.

**Comment by tobykurien** [comment]
@E3V3A pipes don't work when executing shell processes this way. Also, copy & pasting code is the worst mistake you can make when coding, so please don't do that in future.

**Comment by E3V3A** [comment]
@tobykurien  Thanks a lot for that PR and for cleaning up my code. I had no idea pipes doesn't work. (Why not?) Also, C&P is the only way for me to make any progress on my own, when I don't have any input for advice, even if I know it is bad coding practice, but I've gotta learn somehow... 

So one question remain. Can we also sort the `getprop` list? Something like: 
```
blahblah.sort(getpropResults);
```

**Comment by tobykurien** [comment]
Is it really important to sort the getprop? If so, I can look into it (yes it's possible).

**Comment by E3V3A** [comment]
Of course not, but I thought it would be simple as a pipe. :)

**Comment by E3V3A** [comment]
@tobykurien  Can you please have a look at why the entire log is cleared on every update instead of showing last 1000 lines?
