### ISSUE TITLE
Missing bonuspack_bubble Error in logcat

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#307]
I'm getting the following error in logcat:
```
E/BONUSPACK(31923): Marker: layout/bonuspack_bubble not found in com.SecUpwN.AIMSICD
```
What is that? It seem related to OSM... [Here](http://osmbonuspack.googlecode.com/svn/trunk/OSMBonusPack/src/org/osmdroid/bonuspack/overlays/Marker.java) is the relevant code causing this message. And [here](https://code.google.com/p/osmbonuspack/wiki/Tutorial_0) is some other related info.

@ziem Do you have any ideas about this?

**Comment by SecUpwN** [comment]
I digged around and found [this Issue](https://code.google.com/p/osmbonuspack/issues/detail?id=58). When does the error occur exactly?

**Comment by ziem** [comment]
https://code.google.com/p/osmbonuspack/wiki/HowToInclude
> If you are going to use standard OSMBonusPack "bubbles", browse the source, go to trunk/OSMNavigator and download in your project resources the following files:
> For a white bubble:
> 
>   drawable-mpi/bonuspack_bubble.9.png
>   layout/bonuspack_bubble.xml 

> For a dark-grey bubble:

>   drawable-mpi/bonuspack_bubble_black.9.png
>   layout/bonuspack_bubble_black.xml 

> For the "more info" button:

>   drawable/btn_moreinfo.xml
>   drawable-mpi/moreinfo_arrow.png
>   drawable-mpi/moreinfo_arrow_pressed.png

I didn't include this files because map viewer doesn't display any kind of "bubbles" (InfoWindows).

**Comment by E3V3A** [comment]
That's what I thought,  which make me wonder why we get that error. After looking at the link, perhaps there is a setting we've missed somewhere, that tell osm not to look for this bubble...

**Comment by ziem** [comment]
I will fix it ASAP.

**Comment by ziem** [comment]
In order to remove this error I have to add to project all files listed above. Is it ok?

**Comment by E3V3A** [comment]
Hi @ziem, thanks so much for looking into this. The code that checks this is:
```java
...
protected static MarkerInfoWindow mDefaultInfoWindow = null;
...
public Marker(MapView mapView, final ResourceProxy resourceProxy) {
		super(resourceProxy);
		mBearing = 0.0f;
		mAlpha = 1.0f; //opaque
		mPosition = new GeoPoint(0.0, 0.0);
		mAnchorU = ANCHOR_CENTER;
		mAnchorV = ANCHOR_CENTER;
		mIWAnchorU = ANCHOR_CENTER;
		mIWAnchorV = ANCHOR_TOP;
		mDraggable = false;
		mIsDragged = false;
		mPositionPixels = new Point();
		mPanToView = true;
		mFlat = false; //billboard
		mOnMarkerClickListener = null;
		mOnMarkerDragListener = null;
		if (mDefaultIcon == null)
			mDefaultIcon = resourceProxy.getDrawable(bitmap.marker_default);
		mIcon = mDefaultIcon;
		if (mDefaultInfoWindow == null || mDefaultInfoWindow.mMapView != mapView){
			//build default bubble, that will be shared between all markers using the default one:
			Context context = mapView.getContext();
			String packageName = context.getPackageName();
			int defaultLayoutResId = context.getResources().getIdentifier("bonuspack_bubble", "layout", packageName);
			if (defaultLayoutResId == 0)
				Log.e(BonusPackHelper.LOG_TAG, "Marker: layout/bonuspack_bubble not found in "+packageName);
			else 
				mDefaultInfoWindow = new MarkerInfoWindow(defaultLayoutResId, mapView);
		}
		setInfoWindow(mDefaultInfoWindow);
	}
...
```
So I guess from what you say is that there is no way change the `mDefaultInfoWindow` somehow to avoid this? If it's not possible, then go ahead and add the code. Only those files right? If so, then please re-sync and make the PR to `development` branch.

**Comment by ziem** [comment]
Done.

**Comment by SecUpwN** [comment]
Huge thanks for your awesome contributions, @ziem! Will merge this in a second.
