### ISSUE TITLE
Debug logger repeatedly clears logcat window

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#310]
For some reason after some modification by @tobykurien the entire log is cleared on every screen update instead of showing last 1000 lines. But the log should only be cleared from user button.

**Comment by SecUpwN** [comment]
Doesn't happen to me on the latest version. Feel free to re-open should this persist.

**Comment by E3V3A** [comment]
Well it's still there.

**Comment by E3V3A** [comment]
It's kind of working, but it is cleared when first started, which is bad since you'll miss any previous errors. The Java code used for this activity is just way too obscure for me to deal with...

**Comment by SecUpwN** [comment]
>It's kind of working, but it is cleared when first started, which is bad since you'll miss any previous errors.

I am running the current version `0.1.25-alpha-b40` and everything appears to be working fine. Should you experience this Issue again, please specify the exact steps to reproduce the Issue. Thank you.
