### ISSUE TITLE
Error when installing the apk file

### ISSUE THREAD

**Issue by Hallamann** [SecUpwN/Android-IMSI-Catcher-Detector#313]
After downloading the latest version on my device, I tried to install it. Android (version 4.0.3) asks me whether I want to install the package or verify and install the package. Both actions fail with an error message saying "error when parsing the package". So I cannot install the software.

**Comment by SecUpwN** [comment]
Thanks for testing our App, @Hallamann! Here a re a few questions I#d like you to answer:

1. From where did you download the package?
2. Have you made sure that the MD5 sum matches?
3. Which device are you using? Please follow [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues).

**Comment by E3V3A** [comment]
@Hallamann  Our App is only supported from Jelly Bean (API **17**) and up. I think you're using old Ice-cream Sandwich...  Please update your AOS and try again.
