### ISSUE TITLE
Adding data to gsmmap.org

### ISSUE THREAD

**Issue by penguinpowernz** [SecUpwN/Android-IMSI-Catcher-Detector#317]
Hey guys I was wondering if you, or if you plan to, support adding data to the [gsmmap.org](http://gsmmap.org) site.

Or maybe a site that shows live data of where IMSI Catchers are detected by this app (and hopefully others) so that people can look at the map and know to stay away from those areas.  I am not sure if such a site exists, but it would be cool to help make one.

Cheers

**Comment by SecUpwN** [comment]
Good morning and thanks for showing your honest interest, @penguinpowernz! Your idea is great, but unfortunately not every project seems to be so open -minded like we are. Please see [Similar Projects](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Similar-Projects) to get a feeling why that is. But don't count on me here, rather wait for @E3V3A to add his own thoughts as well. Thanks!

**Comment by E3V3A** [comment]
Hi @penguinpowernz ! Sure, supporting gsmmap, would be really nice. But you'd have to provide the details about their API and how we can upload our data there. As we're a very small team, we simply don't have time to add new features without your help. Same thing goes for the live map. It sound easy to implement in theory, but time consuming for the non-expert.

**Comment by penguinpowernz** [comment]
Yea I'm sure I would be able to track down API details and all the required information etc. But I have no experience with programming on Android I'm afraid - much prefer the web side of things.  I have read your roadmap and everything and can see how you guys are time limited, definitely have the work cut out for you and it is much appreciated.

I reckon the live site idea would be awesome, especially if the similar projects developers join in as well so we can get the most data points.  There is currently no such site at the moment AFAIK, but I would like to make one when I get the time.  I'm sure the FBI/DHS would fight/DDOS to take it down though.

Whether the privacy conscious users of these apps would want to part with their lon/lat digits is another question however...

**Comment by E3V3A** [comment]
@penguinpowernz  Any news?

**Comment by penguinpowernz** [comment]
Hey still looking for the GSM Map stuff... there is no API as such, but there is an upload form.  Just trying to find some details on format of the file (for CSV) by looking through the source code, as there are no details on their Wiki.  I'll email them if I don't have much more luck.

**Comment by SecUpwN** [comment]
A quick search turned up that the seems to be a [russian variant of GSMMAP](http://gsmmap.ru/). [Here](https://translate.google.com/translate?hl=en&sl=ru&tl=en&u=http%3A%2F%2Fgsmmap.ru%2F) is the translated site, they even have a [forum](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fgsm-msk.m-pro.ru%2Fviewforum.php%3Ff%3D6&edit-text=&act=url) to digg into. Thanks for trying to find the API for GSMMAP, @penguinpowernz. Maybe you should ask on [their mailing list](https://lists.srlabs.de/cgi-bin/mailman/listinfo/gsmmap)?

**Comment by E3V3A** [comment]
The code for uploading should be found in either the SnoopSnitch sources or their other GSMMap app... They have open repos, AFAIK.

**Comment by SecUpwN** [comment]
@penguinpowernz, please have a closer look at their [repository](https://opensource.srlabs.de/projects/snoopsnitch/repository) to find the relevant parts.

**Comment by penguinpowernz** [comment]
Sorry I was on holiday.

Yea I think I found the correct files here, but unfortunately can't understand them (I ditched java long ago): https://opensource.srlabs.de/projects/snoopsnitch/repository/revisions/master/show/SnoopSnitch/src/de/srlabs/snoopsnitch/upload

I also emailed them to ask if they could point us to a spec of some sort.

**Comment by SecUpwN** [comment]
>I also emailed them to ask if they could point us to a spec of some sort.

Thank you for keeping up you engagement in our project. Let us know here when they answered.

**Comment by penguinpowernz** [comment]
Got the following reply:

> Hi Robert,
>
>Thanks for offering support. GSMmap uses (and SnoopSnitch produces) raw
radio data while other apps like AIMSICD collect high-level data from
the Android OS. As we need the low-level radio data to calculate our
metrics data from AIMSICSD is inherently unsuitable for our purpose.
>
>Cheers,
>Alex

So it seems that visualizing the AIMSICD data in GIS would be better suited as a "reported stingray" locations map.  I hope to start a project like this in the future, but I have a few others on at the moment so will come back to you guys when I get a chance for that.

Cheers

**Comment by TPS** [comment]
FWIW, #898 contains docs with some Stingray details.
