### ISSUE TITLE
FC when hitting "Home" button during BTS map info

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#323]
We get a FC when hitting the Android "Home" (middle) button, while the detailed BTS view in `Antenna Map Viewer` is shown.

**Comment by SecUpwN** [comment]
Still valid within the latest internal build and all the fixes?

**Comment by E3V3A** [comment]
There is really no good reason to ask this... If it's fixed, the issue will be closed. If you keep asking for every open issue, people are gonna get very annoyed following our GitHub. In addition, instead of asking you can test it for yourself!

**Comment by SecUpwN** [comment]
>There is really no good reason to ask this...

Calm down, please. My phone lacks the middle button, otherwise I wouldn't have asked.

**Comment by SecUpwN** [comment]
Is this still the case on our current internal version `0.1.26-alpha-b02`? Shouldn't be!

**Comment by E3V3A** [comment]
Well, "should" doesn't test it.

**Comment by SecUpwN** [comment]
>Well, "should" doesn't test it.

One of the main reasons why we keep "collecting" Issues rather than making progress, is because the people who actually open them do not keep checking if the Issue has been fixed in between, although at times not properly linked with a commit. It would be awesome if you could check your Issues regularly.

**Comment by E3V3A** [comment]
>It would be awesome if you could check your Issues regularly.

Which I do. If there's no PR addressing the issue, it is 99.99% unlikely to have been fixed, unless there is some magic working behind the scenes that I don't know about.

**Comment by SecUpwN** [comment]
>Which I do.

Perfect. No need t get angry here, I'm barely trying to maintain this project properly.

**Comment by E3V3A** [comment]
And you do a great job of that. But there surely will be no progress if you keep on closing outstanding issues, just because nobody has been able to address them.

**Comment by E3V3A** [comment]
I don't see this anymore. 
So please re-test this issue now. (Using Buildozer build >= 211)
