### ISSUE TITLE
Using Hangouts as SMS app trips "Type Zero SMS.." alert and crash.

### ISSUE THREAD

**Issue by git-ew** [SecUpwN/Android-IMSI-Catcher-Detector#330]
When using Hangouts app as SMS client, incoming SMS triggers the "Alert!! Type Zero SMS Intercepted!" message.

When going to the database viewer to check "Silent SMS", clicking "Load Data" button drops the UI and I get "Unfortunately, Android IMSI-Catcher Detector has stopped." message.

Running Cyanogenmod 12-20150205-NIGHTLY-shamu (Android 5.0.2) on Nexus 6, Sprint.

**Comment by E3V3A** [comment]
@git-ew please try the latest debug build from XDA thread.
@SecUpwN can you update the release so we don't have to deal with these old issues?

**Comment by SecUpwN** [comment]
@E3V3A, as you've suggested in our internal chat, I would like to wait with a new release until some more of the current core Issues have been fixed. Please feel free to send a message to our forkers.

**Comment by SecUpwN** [comment]
@git-ew, since this Issue is older than a month now, I'd like you to either test the [latest Release](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases) or just send me a short E-Mail (click my name here) so that I can send you the very latest compiled APK of our `development` branch. Thank you!

**Comment by git-ew** [comment]
Thanks.
Installed and running 0.1.25-alpha-b35 and tested SMS with Hangouts app.
All looks good now. No alert trip.

**Comment by git-ew** [comment]
Thanks.
Installed and running 0.1.25-alpha-b35 and tested SMS with Hangouts app.
All looks good now. No alert trip.
