### ISSUE TITLE
cellid not present in opencellid database?

### ISSUE THREAD

**Issue by jamsec12ty** [SecUpwN/Android-IMSI-Catcher-Detector#336]
Hi im relatively new to this and was wondering why I'm getting this error when I start aimsicd tracking. The status symbol goes yellow and the error comes up.  

I apologize if this was covered before. I looked and couldn't find the issue in a previous post. Any help would be appreciated. Also if there is a site that can get me up to speed please provide a link.  :) cheers

**Comment by SecUpwN** [comment]
Good evening @jamsec12ty! Please make sure to follow [these instructions](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues) and also tell us which version of AIMSICD you are using. The error you are describing has likely been fixed in the `development` branch..

**Comment by jamsec12ty** [comment]
Hello

I'm using version 0.1.25-alpha.




---- Security: Pwned. wrote ----

Good evening @jamsec12ty! Please make sure to follow [these instructions](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues) and also tell us which version of AIMSICD you are using. The error you are describing has likely been fixed in the `development` branch..

---

**Comment by E3V3A** [comment]
This was fixed in development branch with the closure of #290.
