### ISSUE TITLE
Reconsideration of lowest supported API

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#34]
In the last week I have made a 180 degree change of mind, regarding the lowest AOS API level supported by AIMSICD. Before I was convinced that supporting AOS from GB 2.3.4 (API 10) and up was the right thing to do. But as weeks went by and my insight have increased I am more convinced than ever that our lowest supported API should be around JB 4.1 (API 16). Why is this? Because I realize that the unaligned inconveniences for using GB far outweigh the benefits for backward compatibility, simply because we just don't have any userbase that need this level of support. Especially when application developer benefits for using API 16 and after is so much greater. In addition I think that lower-level perhaps cross platform compatibility is better for API 16 and on...

I'd like to hear developer comments on this. 

@He3556 @SecUpwN @xLaMbChOpSx  : Sorry, don't kill me! I know you spent time removing API 16 stuff to make backward compatibility. 

Also have a look at grand master Chainfires blog post:
"[Gingerdeath II: Choconomics](https://plus.google.com/+Chainfire/posts/LDW4jMjj23Z)"

**Comment by SecUpwN** [comment]
@E3V3A, I am making an exception for user `Chad` here, who [posted](http://aimsicd.store.aptoide.com/app/market/com.SecUpwN.AIMSICD/28/9517721/Android+IMSI-Catcher+Detector#cmt331632) the following on Aptoide:

>Posting a comment via the website/GitHub is a joke based on all the details you have to give while being careful not to duplicate previous bug reports, so I'm posting here on good old Aptoide. I understand this app is being actively developed so it won't be compatible with all models. It currently is not compatible with my make. The minimum sdk required is 16 I believe and I have 15. My phone model is a Samsung GS2 t-989 if that's any help. This app looks awesome, I hope it can get optimized for older phone models. In the meantime good luck developers and thank you for helping combat unconstitutional spy tactics.

Please let me know if it makes sense going lower or what else you would suggest. Thank you.

**Comment by E3V3A** [comment]
No sense at all.

**Comment by TPS** [comment]
FWIW, #898 contains docs with some Stingray details.

**Comment by webcoderz** [comment]
Post this as its own issue. And refer to the documents directly not linking
to a separate issue. Its becoming spam mail.

**Comment by TPS** [comment]
Sorry, @akrolla.  I did so, but no 1 seems to have noticed/commented/reacted, so I'm hoping this will expose it a little more.

**Comment by webcoderz** [comment]
I downloaded them all! I think they're great I understand man. No worries
hopefully we can use the knowledge gained to reverse engineer one to
properly understand its use and protocols and also to understand to what
extent of access they have.
