### ISSUE TITLE
MuckRock published analysis of USMS StingRay acquisition docs

### ISSUE THREAD

**Issue by rjh427** [SecUpwN/Android-IMSI-Catcher-Detector#341]
Dunno if this will provide any useful info or not, I haven't taken time to look through it. Thought you guys might like to know...

"MuckRock just published our analysis of USMS StingRay acquisition docs released last week:  https://www.muckrock.com/news/archives/2015/mar/03/us-marshals-service-conceal-key-details-millions-s/

Top finding: USMS redacted info that's available on two other federal budget websites, including contract/invoice numbers."

**Comment by SecUpwN** [comment]
Thank you so much for your contribution, @rjh427! We will have to review that in the upcoming days since we're preparing for a fresh **RELEASE** within the next few hours. Heavy development, stay tuned.

**Comment by SecUpwN** [comment]
Had another look at this and I must say that this is "nothing new" to us since apparently such companies keep spying wherever possible and of course spending the money of innocent people to buy these devices. I would like @He3556 to have another look if we shall this handle differently or close it.

**Comment by He3556** [comment]
thanks for the link. Not realy new technical infos but the density of stingrays must be realy huge, if every "headhunter" has its own equipment. scary numbers, 400 arrests each day ^^

**Comment by SecUpwN** [comment]
@rjh427 since both of us as well as likely other team members have reviewed this, I would like to close this as solved. Please feel warmly invited to tweet about the MuckRock publishing and add us to that tweet using our hashtag `#AIMSICD` - the more people know about our tool, the more help we'll get!

**Comment by TPS** [comment]
FWIW, #898 contains docs with some Stingray details.
