### ISSUE TITLE
Funny logcat error from DeviceAPI17

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#348]
Checking logcat I found this mysterious error: 
```
E/dalvikvm( 4600): Could not find class 'android.telephony.CellInfoWcdma',
referenced from method com.SecUpwN.AIMSICD.utils.DeviceApi17.loadCellInfo
```
I was looking in this file but couldn't find anything particular. Perhaps @tobykurien can have a look, since he wrote the code.

**Comment by SecUpwN** [comment]
I have had a quick look and found the reference on [line 13](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/89bc61cde66f91783d17a635cda31e9fb67f1997/app/src/main/java/com/SecUpwN/AIMSICD/utils/DeviceApi17.java#L13) in `DeviceApi17.java`. Not sure what exactky is missing or wrong, maybe digging through the [CellInfoWcdma class overview](https://developer.android.com/reference/android/telephony/CellInfoWcdma.html) helps us any?

**Comment by whitequark** [comment]
Yeah it's kind of gross. You have to use reflection to stay compatible with API level 17. The PR you've linked has pretty much everything you need to successfully integrate it elsewhere.

**Comment by E3V3A** [comment]
Just to clarify. Is this really fixed? How was it fixed? Did you remove API 17 compatibility or implement reflection? Sorry, but it's not clear from the PR info.

**Comment by DimaKoz** [comment]
> How was it fixed? Did you remove API 17 compatibility or implement reflection?

@E3V3A The selected section has been switched off for less than 18 API
https://github.com/DimaKoz/Android-IMSI-Catcher-Detector/blob/ed2167ac9fdbcdf19d9c2e2a2cbaa4736952e111/app/src/main/java/com/SecUpwN/AIMSICD/utils/DeviceApi17.java#L85-L100

> Is this really fixed?

I'm sorry, but I don't have a phone to check elimination of this bug. Now it should work without falling down.
We can use reflection for that: http://stackoverflow.com/a/21098621
but it must be done developer who can verify this code. I don't got that chance, unfortunately.

**Comment by SecUpwN** [comment]
>The selected section has been switched off for less than API 18

Please have a look at the pull request I linked in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/348#issuecomment-97245124. there, they use reflection to also enable compatibility with API 17 - everything needed should be available in https://github.com/whitequark/LocalGSMLocationProvider/commit/9d8771e8dd171041987fc5a7d62932ddbeda7a79. Can you change the code of our app to do a proper reflection, please? I'm sure that @whitequark can help us checking if it works.

**Comment by whitequark** [comment]
Yeah, I can run your code at an API level 17 device at least

**Comment by E3V3A** [comment]
I'm closing this (as insignificant) until someone can verify it's still present.

**Comment by SecUpwN** [comment]
>I'm closing this (as insignificant) until someone can verify it's still present.

@E3V3A, does that mean that you do not experience it anymore?
