### ISSUE TITLE
Android-IMSI-Catcher-Detector

### ISSUE THREAD

**Issue by KloeverGz** [SecUpwN/Android-IMSI-Catcher-Detector#352]

**Comment by SecUpwN** [comment]
@KloeverGz, welcoem to our project. Please make sure to craft Issues with a valid title and valid content. This "Issue" is completely `INVALID` - see our [Bug Submission Guideline](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues). Thank you.
