### ISSUE TITLE
What is this thing?

### ISSUE THREAD

**Issue by rjh427** [SecUpwN/Android-IMSI-Catcher-Detector#357]
Possibly related, possibly not. Anyone have any idea what this thing is?

A cypherpunk on the cypherpunk list writes:
We had someone loitering near our front office door today. The
conversation went like this:

  Me: What are you doing?
  Him: Nothing
  Me: Where are you from?
  Him: A company
  Me: Do you work for Google (he was wearing a Google t-shirt)?
  Him: No
  Me: Who do you work for?
  Him: Leidos

He had a device hidden near the stairwell door:

  https://www.alfie.wtf/photos/wispy.jpg

Sorry for the low quality image. It was taken from a capture of a
video. I've got the video at work but would rather not release it as
yet because it has his face on it.

The diameter of the antenna base was around 2cm and the height
of the antenna was around 15cm.

Someone on Reddit said that it looked like a jammer. After going to
Google Images and searching for the following, it looks like he's on the
right track:

  - "GSM detector"
  - "GSM jammer"
  - "GPS detector"
  - "GPS jammer"

If anyone has info on what this device could be or where I could go to
get more info, that would be much appreciated.

**Comment by SecUpwN** [comment]
@rjh427, q quick search for the company [Leidos](https://www.leidos.com/) tells it all:

> Leidos: Solutions for National Security, Health and Engineering

If I were @alfiedotwtf, I'd get a new phone and a new SIM and maybe file a case against the spy.

**Comment by alfiedotwtf** [comment]
Hi everyone,

Installling the app now! Thinking about putting this on a spare phone and leaving it onsite to monitor the office.

@SecUpwN: I could call them out, but I'm pretty sure they wouldn't comment on it. It's not like they will come out on Twitter with "ohh yes, sorry about that. It was our ultra-hacking device. You're pwn3d".

Nothing else to report at the moment. You can follow along the thread at home:

  https://cpunks.org//pipermail/cypherpunks/2015-March/007009.html

Alfie

**Comment by E3V3A** [comment]
This is not really related to our app, so I'll close this and we can still talk about it elsewhere. 

If I had caught that guy, I wouldn't have let him go without grilling him thoroughly and get a lawyer on his ass to launch an industrial espionage case. Citizens arrest? I'd have ripped that HW out of his hand so fast he couldn't blink. Although the device doesn't *look* GSM related it is definitely some kind of surveillance device. The multiple antennas would be used to Jam 3-6 bands while the 4th block could work as the WiFi/IMSIC/SMS/GSM/LTE interceptor or data collector.

**Comment by airobot60** [comment]
> Possibly related, possibly not. Anyone have any idea what this thing is?
> 
> A cypherpunk on the cypherpunk list writes:
> We had someone loitering near our front office door today. The
> conversation went like this:
> 
>   Me: What are you doing?
>   Him: Nothing
>   Me: Where are you from?
>   Him: A company
>   Me: Do you work for Google (he was wearing a Google t-shirt)?
>   Him: No
>   Me: Who do you work for?
>   Him: Leidos
> 
> He had a device hidden near the stairwell door:
> 
>   https://www.alfie.wtf/photos/wispy.jpg
> 
> Sorry for the low quality image. It was taken from a capture of a
> video. I've got the video at work but would rather not release it as
> yet because it has his face on it.
> 
> The diameter of the antenna base was around 2cm and the height
> of the antenna was around 15cm.
> 
> Someone on Reddit said that it looked like a jammer. After going to
> Google Images and searching for the following, it looks like he's on the
> right track:
> - "GSM detector"
> - "GSM jammer"
> - "GPS detector"
> - "GPS jammer"
> 
> If anyone has info on what this device could be or where I could go to
> get more info, that would be much appreciated.
>

**Comment by flanneryb** [comment]
There are no pictures that are no video, can you telepathically send this
out to everybody on the list?
