### ISSUE TITLE
Force problem description in bugreport emails

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#364]
The current debug logs allow users to send emails. The text in the logs clearly state (in 2 places) that users should describe their problem before sending of their logs. This has request has been completely ignored and thus this log sending function should either be removed or force the user to fill in the description. A simple way to obfuscate the email address should also be implemented to make it more difficult for github spam robots to scrape files for email addresses.

**Comment by SecUpwN** [comment]
Good evening @E3V3A. I still do think that having the possibility of sending a logfile is a good idea, but I knew you'd be tired of receiving improper bug reports eventually. I will add the warning `NO HELP WITHOUT DESCRIPTIONS!` inside the `helpUs` string and also contact GitHub support for a email obfuscation.
