### ISSUE TITLE
Proper updates of versionCode and versionName

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#365]
Thanks to the great help of @krt16s in [this GitLab Issue](https://gitlab.com/fdroid/fdroiddata/issues/180), I have been able to find the cause for why our app is not updating on F-Droid since `0.1.25-alpha-b6`. It appears  that the `android:versionCode` has to count upwards to initiate a new build on F-Droid. Therefore, I am proposing the following changes:

* Example for **DEVELOPING** on `development` branch:

`android:versionName`: 0.1.25-alpha-b**37** -> 0.1.25-alpha-b**38** -> 0.1.25-alpha-b**39**  and so on..

* Example for **RELEASING** to our stores and GitHub Releases:

android:versionCode="**25**" -> android:versionCode="**26**" -> android:versionCode="**27**" and so on..
To simplify it, we are also ging to count upwards like this: 0.1.**25**-alpha -> 0.1.**26**-alpha and so on..

I hope you all agree with these changes. You can basically continue development like you always did since @He3556 and I are preparing the releases. Please just confirm and this Issue will be solved. Thx.

**Comment by krt16s** [comment]
Everything that increments the VC is fine with me.

**Comment by He3556** [comment]
yes let's close this issue :)
