### ISSUE TITLE
Type Zero Silent SMS upon receiving any SMS message

### ISSUE THREAD

**Issue by lucas-phillips** [SecUpwN/Android-IMSI-Catcher-Detector#366]
Regardless of the source of the SMS message, even if I send one to myself, AIMSICD goes off saying its a "Type Zero Silent SMS".
![notifications](https://cloud.githubusercontent.com/assets/9609541/7002338/1690ff48-dc17-11e4-97e2-eb63ff9a13f5.png)

**Comment by E3V3A** [comment]
No version info, no device info and no logcat logs, case closed. (We'll reopen if you can provide more details if relevant.)

**Comment by lucas-phillips** [comment]
AIMSICD: Version: 0.1.25-alpha-b6
Model Name: LG-VS985
CyanogenMod Version: 12-20150327-NIGHTLY-vs985
Android Version: 5.0.2
Logcat: https://bpaste.net/show/29cd84eb0731 (grepped for `IMSI`)

=== Device Information ===
Phone Type: CDMA
RIL Version: 00

=== SIM Information ===
Country: us
Operator Name: Verizon

=== Network Information ===
Provider Name: Verizon Wireless
Provider Code:
Type: LTE
LAC:
Roaming: false
Data Activity: Dormant
Data Status: Connected

**Comment by SecUpwN** [comment]
Good evening, @lucas-phillips! Thank you so much for reporting this Issue. I will (temporarily) re-open your Issue since you've updated it properly. E:V:A will have a look at your logcat, but please don't be disappointed if we come to the conclusion that we cannot fix that yet since #69 has not yet been fully integrated, thus this feature is not yet working as it should. We simply lack developers at this time. :(

**Comment by git-ew** [comment]
@lucas-phillips I was seeing the same behavior while using google hangouts for my sms app.
A link was provided for version 0.1.25-alpha-b35 and that seemed to fix the behavior.

Check out closed issue #330 for more details and link to see if that fixes your issue.

https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/330

**Comment by SecUpwN** [comment]
Thanks for helping him out, @git-ew. I have just sent him an APK for testing. Hoping it is fixed.

**Comment by lucas-phillips** [comment]
@SecUpwN the APK you sent did fix the issue. Thank you.
