### ISSUE TITLE
Idea: Use Mozilla Location Service cell network db to assist discovery of false cell networks

### ISSUE THREAD

**Issue by garvankeeley** [SecUpwN/Android-IMSI-Catcher-Detector#367]
Hi, I am just looking at your project for the first time, and was thinking that you might want to be aware of another cell tower database. MLS, https://location.services.mozilla.com, posts hourly updates of cell networks discovered. Perhaps that can be of use in detecting temporary cell networks.

FYI, the github repo for the service is https://github.com/mozilla/ichnaea,
and the client is https://github.com/mozilla/MozStumbler

**Comment by E3V3A** [comment]
Hi @garvankeeley  Thanks for trying to help. But we're working with those guys since some time, but we don't have developers to implement the alternative DB downloads.

**Comment by SecUpwN** [comment]
Good evening @garvankeeley, please follow #71. Thank you.
