### ISSUE TITLE
The app haven't been updated on f-droid since a long time

### ISSUE THREAD

**Issue by Dostoi** [SecUpwN/Android-IMSI-Catcher-Detector#369]
The version on [F-Droid](https://f-droid.org/repository/browse/?fdfilter=imsi&fdid=com.SecUpwN.AIMSICD) is 0.1.25-alpha-b6 and has last been updated the 2015-01-02. Your last version is v0.1.25-alpha-build-37 and was add 18 days ago. Why is there no update on F-Droid more often ?

**Comment by SecUpwN** [comment]
Good evening @Dostoi, thanks for chiming in! I am aware of the problem and have cleared it up a while ago already, see #365. I am still cleaning up our repository, our app will update on F-Droid soon. Cheers!

**Comment by Dostoi** [comment]
Hi, my bad, I didn't find this issue before. Thanks for the quick answer :)
Keep up the good work !
