### ISSUE TITLE
Build tools version 21.1.1 is obsolete

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#370]
Current version for 21 is 21.1.2. The project and dependencies use 21.1.1.

Could you update buildToolsVersions or add instructions how to install this specific version?

`android update sdk --no-ui --all --filter build-tools-21.1.1`

If you think this is not important issue close it, I just wanted to let you know ;)

**Comment by SecUpwN** [comment]
Good evening @agilob, thank you for making us aware of it, we like people like you! :+1:

I am cleaning out our repo, but would it work if I just edit the `buildToolsVersion` in `third_party/rootshell/build.gradle `, `app/build.gradle ` and `travis.yml` or would that break anything?

**Comment by agilob** [comment]
I don't have enough experience in android development to decide which was is better ;)
This should work for people without obsolete tools/sdks, which are not installed by android SDK manager by default after new version is released.
