### ISSUE TITLE
Reduce Git repository size

### ISSUE THREAD

**Issue by rtyley** [SecUpwN/Android-IMSI-Catcher-Detector#371]
I'm the author of [the BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/), a faster, simpler alternative to `git filter-branch`, and @SecUpwN asked me how I would go about reducing the size of Android-IMSI-Catcher-Detector's Git repo, working on the assumption that the large size of the repo is off-putting for potential new contributors (see also #362).

The repository currently has a packfile of 34M, which can't be considered _huge_, but there's potential for reducing it down to around half of it's current size. It's up to you to decide if that's a benefit worth pursing - remember that commit ids change will change!

Before rewriting history, I'd recommend removing all the unwanted cruft from the current filetree, eg screenshots and jars under https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/tree/development/app/libs - unless there is some reason why these jars can't become gradle dependencies?

Run the BFG over a mirror clone of your repository - a fresh copy of the clone each time is best. The BFG is extremely fast to run, so you can experiment with a few different thresholds for removal, and see what gets deleted (the BFG produces a `deleted.txt` report for every run, listing every removed file).

Prepare your contributors for history to be rewritten. Any outstanding pull requests will need to be rebased against the new history, and in general, your contributors will be best off just deleting their current working copy, and cloning a new one, to ensure they don't push dirty history back to your new repo.

After a few tests, I ran the BFG against your repo with `--strip-blobs-bigger-than 128K`, which was about as aggressive as I could get without removing the history of `AimsicdService.java`, which has been very big in the past. Almost all [the removed files](https://docs.google.com/spreadsheets/d/1VZGc7PwOPbkWi1IdoBH7jPB_KFcAd-y377yR4gwHB6M/edit?usp=sharing) were pngs & svgs. This yielded a new pack-size of 21M:

```
$ git clone --mirror git@github.com:bfg-repo-cleaner-demos/Android-IMSI-Catcher-Detector.git
$ cd Android-IMSI-Catcher-Detector.git/
$ ls -lh objects/pack/pack-*.pack
-r--r--r-- 1 roberto roberto  34M Apr 16 20:41 objects/pack/pack-c62cb2f13a93ac0d05d91a872ca4a5bd78ebec2e.pack
$ java -jar ~/bfg.jar --strip-blobs-bigger-than 128K
$ git reflog expire --expire=now --all && git gc --prune=now --aggressive
$ ls -lh objects/pack/pack-*.pack
-r--r--r-- 1 roberto roberto  21M Apr 16 20:45 objects/pack/pack-ea5c8acab0f465cf4234daf0cdb763fb85f3694c.pack
 $ git push
```

...the BFG protects every file in your current commit, so this run was held back a bit by all the big files currently sitting in your file tree - getting down to about 16M would be possible with a bit more clear-up.

The cleaned repository is available at https://github.com/bfg-repo-cleaner-demos/Android-IMSI-Catcher-Detector if you'd like to check it out. Good luck with your project, I wish you every success!

**Comment by SecUpwN** [comment]
Thank you so  responding so promptly! I have been getting awesome help by @dalibor as well and he listed the commands which would be needed to delete history of the folders I want to remove, namely:

* DOCUMENTATION
* MISC
* PROMOTION
* SCREENSHOTS

They have already been transferred and linked accordingly to [our SpiderOak](https://spideroak.com/browse/share/AIMSICD/GitHub/). So to clarify the plan I am having here, please check my procedure:

1. Merge our branch `development` into `master`.
2. Temporarily remove branch `development`.
3. Remove the folders mentioned above.
4. Creating a fresh fork of this project.
5. Cloning the fresh fork and apply these commands:

> $ git clone git@github.com:SecUpwN/Android-IMSI-Catcher-Detector.git
>
> 2. Check size
>
> $ du -sh .
>
> 49M.
>
> 3. Remove all files in the dirs you want
> $ git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch DOCUMENTATION/*'
>
> $ git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch MISC/*'
>
> $ git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch PROMOTION/*'
>
> $ git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch SCREENSHOTS/*'
>
> 4. Force all objects in your local repository to be dereferenced and garbage collected
>
> $ git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin
>
> $ git reflog expire --expire=now --all
>
> $ git gc --prune=now
>
> 5. Check size again
>
> $ du -sh .
>
> 38M.
>
> 6. Force push to override Github repository and branches
>
> git push origin --force --all
>
> 7. Force push to override Github tags
>
> git push origin --force --tags

After that procedure, I would apply your above commands, `git push origin --force --tags` and recreate our branch `development`. Please tell me if you can detect any errors in my logic here.

**Comment by rtyley** [comment]
Personally, I wouldn't bother with any of the steps quoted in step 5. If you really want to explicitly delete those folders, then the BFG can do those at the same time as striping blobs:

```
$ bfg --delete-folders '{DOCUMENTATION,MISC,PROMOTION,SCREENSHOTS}' --strip-blobs-bigger-than 128K
```

This will handle all transformations at the same time, much faster and more easily than `git filter-branch`, with the added benefit that commit ids in commit messages will be correctly mapped over the entire process.

**Comment by SecUpwN** [comment]
Oh man, I cannot thank you enough for your wonderful support! And how about the [Stackoverflow Script](http://stackoverflow.com/a/7945209/1673062) - do you see any use for it, or does BFG handle that as well?

**Comment by rtyley** [comment]
> And how about the Stackoverflow Script - do you see any use for it, or does BFG handle that as well?

The BFG will output fairly similar information in the `.bfgreport` directory (tho' it only gives the filename, not the full path of the file). If you do a test run of the BFG you get all that info, in less than 2 seconds.

Personally, I wouldn't bother with the stackoverflow script, because I've got a lot of confidence in how the BFG operates, but you can if you like.


> BFG really seems to be a kick-ass tool..

Thanks! Endorsements on your site, or shared on twitter, etc, are always appreciated.

**Comment by SecUpwN** [comment]
Hey @rtyley, I'm not sure if you're still awake (it's 02:21 AM over here in Germany), I'm dealing with:

>Before rewriting history, I'd recommend removing all the unwanted cruft from the current filetree, eg screenshots and jars under https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/tree/development/app/libs - unless there is some reason why these jars can't become gradle dependencies?

How can I make these gradle dependencies? Let me know, I am about to hit the button! ;-)

**Comment by rtyley** [comment]
> How can I create these gradle dependencies?

Your gradle deps are defined here:

https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/d7057d8bb184/app/build.gradle#L129-L136

Better to define dependencies by their artifact id, so that they can be downloaded, rather than incorporating the jars into your repo. You can use http://search.maven.org/ to find the artifact ids for the dependencies you currently have in `app/libs`.

https://developer.android.com/tools/building/configuring-gradle.html#buildFileBasics
http://stackoverflow.com/a/18821544/438886

**Comment by SecUpwN** [comment]
Thank you so much for your awesome BFG cleaner, @rtyley - our repository has now been successfully cleaned out and we're now at an unbelievably tiny size of **just ~5 MB**! Have a look at [our Twitter](https://www.twitter.com/AIMSICD). ;-)

**TO ALL CURRENT FORKERS:**

* Please **delete** your old fork and **re-fork** our project!
* Do not hesitate to craft pull requests like crazy now!
* Spread the word everywhere using our [Media Material](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Media-Material)!

I am linking your names here only once to ensure everyone is getting the message above and everyone is re-forking us: @0359xiaodong, @0x7678, @2005sz, @79144876, @9hao, @adelynx, @ahdidar, @ako2345, @Alexis374, @andr3jx, @AndroidBase, @AnwarMohamed, @aphix, @ariosx, @arturP, @atwong01, @austad, @banjaxbanjo, @bkerler, @boyliang, @jokerNi, @kaiwenjui, @GeneBlue, @BundyRukus, @burning131617, @bvernoux, @calberca10, @calyth, @canselcik, @CCrashBandicot, @CevinEichnau, @cflq3, @chackerian, @chadmiller, @chagge, @charlesnw1, @clam1110, @Cloud59, @CloudeXpert, @cmotc, @cocaman, @codesomniare, @ColdSauce

**Comment by SecUpwN** [comment]
Please see previous message above!

@IrmaDoe, @JamesAlias, @jamesbchen, @jbnixx, @Jeyaprakashchinaraj, @jimmyyang2014, @johnzweng, @joseniem, @KangProject

**Comment by SecUpwN** [comment]
We cleaned our repository, you must re-fork. Please see [this message](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/371#issuecomment-93998806)!

@nehz, @Niyikiza, @nosepick, @petetandon, @phoenixDevelopment, @proximer, @pmocek, @Reaper951, @Robbenklopper123, @rocksontrees, @RyanTech, @RyDroid, @sagarpshah, @Sandman671, @sears31907, @sikopet, @simudream, @sonnyochoa, @stinkydan, @tanujmathur, @TeddyBear06, @testkeyman, @Thata93, @therealtylerdurden, @therob3000, @ttxx9999, @vyp, @Wp1stop, @wttrtpy, @ytrjp, @zhuhui, @ziem, @zimndev
