### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by cyklodev** [SecUpwN/Android-IMSI-Catcher-Detector#373]
Hi guys,
I build your app on my phone (S3 not root) and i see that a permissions was missing in the ADB log.

`uses-permission android:name="android.permission.INTERACT_ACROSS_USERS_FULL" `

After adding this,  i havent no more the warning. Does it come from my phone or the fact that i have not a rooted phone ?

**Comment by SecUpwN** [comment]
>I build your app on my phone (S3 not root) and i see that a permissions was missing in the ADB log.

Good evening @cyklodev! It seems you haven't followed our guide on [how to submit Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues). Without any logcat we don't know which error message is shown. And why should we need to add this permission?

**Comment by E3V3A** [comment]
> `android.permission.INTERACT_ACROSS_USERS_FULL` is a signature level permission. Your app will not be able to use it until and unless it has the same signature as the system... 

So yes, this may be a root issue. It is also a hidden/undocumented google permission.
