### ISSUE TITLE
Hide or clarify examples in EventLog and DB Viewer

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#380]
I have been alerted via Twitter and email multiple times now that people had been likely "connected" to a fake base station and "received" silent SMS. Both of these events identified to be the examples we just added to show what it may look like. Below is a screenshot of a concerned user.

These are our options now (please vote):

1. Hide examples until a small button called "Show/Hide example" is getting pressed.
2. Add `EXAMPLE` in bold red letters to each of of these examples.

![EventLog](https://pbs.twimg.com/media/CDD9_IiUMAAMO1J.jpg)

**Comment by E3V3A** [comment]
Dead twitter link. And you already know what I would vote for, **neither**. Keep people off the app until they understand how to use it. Why should we waste time developing code for an alpha app, just to inform people, that it is "alpha" and demo? That just doesn't make any sense.

**Comment by SecUpwN** [comment]
>Keep people off the app until they understand how to use it.

I can't and do not want to prevent people running around and testing our app.

>Why should we waste time developing code for an alpha app, just to inform people, that it is "alpha" and demo?

They know that it is in ALPHA stage, it is displayed everywhere. But I guess adding a simple red word `EXAMPLE` into both of these example messages won't be a huge hurdle, right @DimaKoz?

>A better solution may be to include the info on first install splash screen.

From my experience, people install stuff, maybe read the splash screen quickly and then simply forget about it. I know you're always thinking from a developers perspective, but sometimes this perspective is a little limited. We just add that red word into those two messages and this will be solved.

**Comment by DimaKoz** [comment]
>They know that it is in ALPHA stage, it is displayed everywhere. But I guess adding a simple red word EXAMPLE into both of these example messages won't be a huge hurdle

I think you are right @SecUpwN
