### ISSUE TITLE
Silent SMS is set off for all SMS messages

### ISSUE THREAD

**Issue by tempIMSIacc1** [SecUpwN/Android-IMSI-Catcher-Detector#382]
Whenever I receive any SMS message, the Silent SMS alert goes off, turning the alert icon red (and sometimes crashing the IMSI catcher app). This happens for all SMS messages, both encrypted ones I receive from people using SMSsecure and unencrypted ones I simply send to myself. I exported the SMS log and only the legitimate text messages were there, though for all of my messages the Class was "UNKNOWN" and the ServiceCtr was an empty field.

Is this a bug? If so, how can I fix it? It makes texting difficult. If not, does this mean someone is actively tracking me?

**Comment by SecUpwN** [comment]
Good morning @tempIMSIacc1! Thank you for notifying us, but I expect this to be a duplicate of #330 and #366. Please either compile the `development` branch yourself, or send me an email to receive the current testing APK with a temporary signature. Public release `v0.1.26-alpha` will come out this Friday!

**Comment by tempIMSIacc1** [comment]
Yup, looks like it. I'll just wait for the new version to come out on Fdroid- until then I disabled SMS access in App Ops.
