### ISSUE TITLE
Mobile Justice for EU

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#398]
Would be great to have AIMSICD connected to some similar service like [Meerkat](https://play.google.com/store/apps/details?id=co.getair.meerkat), [Periscope](https://www.periscope.tv/) or [Mobile Justice](https://www.mobilejusticeca.org/how-it-works/). So our users could also record the use of these surveillance devices.

**Comment by SecUpwN** [comment]
@E3V3A which of these services do you prefer? we should agree on one that is available everywhere.

**Comment by agilob** [comment]
Is there a point of that? If AIMSICD detects danger changes settings to flight mode, then user loses internet connection

**Comment by E3V3A** [comment]
I think we can close this...

**Comment by SecUpwN** [comment]
>If AIMSICD detects danger changes settings to flight mode, then user loses internet connection.

@agilob, another approach could be to store detected danger zones and upload them later?
