### ISSUE TITLE
Update ServiceMode parser for better RIL/API support 

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#402]
We're currently using an old version of the *SamsungRilMulticlient* code used in [../utils/OemCommands.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/utils/OemCommands.java), this code need to be updated to what's found in the **CM12.1** [code](https://github.com/CyanogenMod/android_packages_apps_SamsungServiceMode/blob/cm-12.1/src/com/cyanogenmod/samsungservicemode/OemCommands.java) in order to support more devices (Such as Samsungs) running on Qualcomm and Intel baseband HW. There are some obvious additional code adjustments needed here. This code is called from [CellInfoFragment.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/afc3bfa01c8c94de28d7813c19c1fde9ec8a786e/app/src/main/java/com/SecUpwN/AIMSICD/fragments/CellInfoFragment.java) to obtain Neighboring Cells and Ciphering info, and eventually other things.

**Comment by E3V3A** [comment]
Easy to implement!

**Comment by E3V3A** [comment]
`$ colordiff -w OemCommands1.java OemCommands2.java`
```
1,8c1
< /* Android IMSI-Catcher Detector | (c) AIMSICD Privacy Project
<  * -----------------------------------------------------------
<  * LICENSE:  http://git.io/vki47 | TERMS:  http://git.io/vki4o
<  * -----------------------------------------------------------
<  */
< package com.SecUpwN.AIMSICD.utils;
<
< import android.util.Log;
---
> package com.cyanogenmod.samsungservicemode;
14,20c7,12
< /*
<  * These are the OEM commands used by the MulticlientRil ServiceMode menu scraper,
<  * and possibly elsewhere. OEM commands (as the name suggests) are device dependent
<  * and these particular ones are for Samsung Galaxy S2, AFAIK.
<  * -- E:V:A
<  */
< public class OemCommands {
---
> import android.content.Context;
> import android.util.Log;
>
> class OemCommands {
>
>     private static final String TAG = "OemCommands";
22d13
<     private static final String TAG = "AIMSICD_OemCommands";
31d21
<
37d26
<
54d42
<     // E:V:A  What is 16?
72d59
<
76c63,74
<     public static byte[] getEnterServiceModeData(int modeType, int subType, int query) {
---
>     private int mApiVersion;
>
>     private OemCommands(int apiVersion) {
>         mApiVersion = apiVersion;
>     }
>
>     public static OemCommands getInstance(Context context) {
>         int apiVersion = context.getResources().getInteger(R.integer.config_api_version);
>         return new OemCommands(apiVersion);
>     }
>
>     public byte[] getEnterServiceModeData(int modeType, int subType, int query) {
81a80
>             if (mApiVersion == 1) {
82a82,87
>             } else if (mApiVersion == 2) {
>                 dos.writeShort(8);
>                 dos.writeByte(4);
>             } else {
>                 throw new IllegalArgumentException("Invalid API version " + mApiVersion);
>             }
93c98
<     public static byte[] getEndServiceModeData(int modeType) {
---
>     public byte[] getEndServiceModeData(int modeType) {
98a104
>             if (mApiVersion == 1) {
99a106,111
>             } else if (mApiVersion == 2) {
>                 dos.writeShort(6);
>                 dos.writeByte(4);
>             } else {
>                 throw new IllegalArgumentException("Invalid API version " + mApiVersion);
>             }
108c120
<     public static byte[] getPressKeyData(int keycode, int query) {
---
>     public byte[] getPressKeyData(int keycode, int query) {
113a126
>             if (mApiVersion == 1) {
114a128,133
>             } else if (mApiVersion == 2) {
>                 dos.writeShort(7);
>                 dos.writeByte(4);
>             } else {
>                 throw new IllegalArgumentException("Invalid API version " + mApiVersion);
>             }

```

**Comment by SecUpwN** [comment]
>`$ colordiff -w OemCommands1.java OemCommands2.java`

Thanks for letting me know, I'm on it and will fix this in a few minutes. ;-)

**Comment by SecUpwN** [comment]
Awesome, builds seem to fail now. @banjaxbanjo can you see what I did wrong? :(

**Comment by E3V3A** [comment]
Sorry, that was misleading as it was meant as a reference to us new code and not as a patch.

**Comment by SecUpwN** [comment]
>Sorry, that was misleading as it was meant as a reference to us new code and not as a patch.

Ok, seems that I misunderstood it. Even though builds are currently failing due to the changes, I'd like to avoid having to revert that commit. What else needs to be done to complete the update correctly?

**Comment by wvengen** [comment]
#468 fixes this

**Comment by SecUpwN** [comment]
Awesome, @wvengen! Will this fully fix this Issue so that we can close it?
