### ISSUE TITLE
TRACKING toggle status should be shown on drawer

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#404]
In the menu drawer, under `TRACKING` we can toggle the AIMSICD monitoring and *2G-only* tracking. When disabled, there is a small red cross next to the antenna icon. However, when enabled, as by default, there is nothing, thus user cannot know in advance the current status. 

Suggestion: Add a small green circle when enabled.

**Comment by SecUpwN** [comment]
>Suggestion: Add a small green circle when enabled.

Should that small green circle also be displayed when `Toggle AIMSICD monitoring` is enabled?

**Comment by E3V3A** [comment]
1. See 2
 2. Yes
 3. Don't understand your question.

**Comment by SecUpwN** [comment]
@E3V3A, I have prepared the following change to be added. Please confirm you like it:
![Track Cell](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/drawable-hdpi/track_cell.png) --> ![Track Cell](https://cloud.githubusercontent.com/assets/6000299/7446891/1966329e-f1d7-11e4-8ece-2840e85e9cc9.png)


![Track Cell](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/drawable-hdpi/track_cell.png) -->

**Comment by E3V3A** [comment]
Look good to me.

**Comment by SecUpwN** [comment]
>Look good to me.

Will make myself another coffee, enlarge that green check mark and then add it ASAP.
