### ISSUE TITLE
Show Refresh Rate without opening menu

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#405]
In `Preferences` under the `SYSTEM SETTINGS`, we have `Refresh Rate`. The currently selected refresh rate is not shown. Solution: Display currently selected refresh rate without user having to click there.

**Comment by SecUpwN** [comment]
Wanna give this a shot. Waiting for an answer on my [question on StackExchange](https://android.stackexchange.com/questions/112753/update-menu-item-with-selection-from-same-menu).

**Comment by E3V3A** [comment]
@SecUpwN  Read their response. You need to post on [stackoverflow](http://stackoverflow.com/), instead and add code snippets...

**Comment by DJaeger** [comment]
Try this out in translatable_strings.xml.
Replace:
```
<string name="pref_refresh_summ">Control the frequency of device updates</string>
```
With:
```
<string name="pref_refresh_summ">Control the frequency of device updates\nCurrent selection: %s</string>
```
Have not found this in documentation, but in some apps sources.
Looks like it would work without any other changes.

**Comment by SecUpwN** [comment]
>You need to post on stackoverflow, instead and add code snippets...

@E3V3A, how shall I add code snippets if I don't even know where we can change this? Honestly, these forums call themselves "Android Enthusiasts", tell that "anyone can post a question" and then they close a well described question as being "off-topic"? Fuck them! Any other hints on this Issue?

**Comment by DJaeger** [comment]
Mhm, seems to need additional work.
Look here:
http://stackoverflow.com/questions/531427/how-do-i-display-the-current-value-of-an-android-preference-in-the-preference-su

**Comment by SecUpwN** [comment]
@DJaeger, could we possibly add the selected value to the `Refresh Rate` header itself?

**Comment by DJaeger** [comment]
Stackoverflow is mainly for coding and stackexchange for more generic.

**Comment by DJaeger** [comment]
Yes you can.
Instead of setSummary use setTitle

**Comment by SecUpwN** [comment]
Thanks, which one of the methods listed at your above link would be best?

**Comment by DJaeger** [comment]
The first is more simple and should be enought.
The second is more advanced and seems to handle more preference types.

But remember, that setTitle and setSummary replace the current value, so you should get the string from resource file set the value and replace with that.
With only replacing your title will be only the value and no other string.

**Comment by SecUpwN** [comment]
>The first is more simple and should be enought.

Which one do you mean? [This](https://stackoverflow.com/a/2888607)?

**Comment by DJaeger** [comment]
Yes.

But please try first only using this solution:
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/405#issuecomment-113050105

As getSummary seems to be used to get the string and the documentation says, that it replaces `%s` with the current value, it should be enought.
The other solution seems to be for preferences not got from recources.
http://developer.android.com/reference/android/preference/ListPreference.html#getSummary%28%29

**Comment by SecUpwN** [comment]
Works beautifully, thanks you very much @DJaeger! :+1:

**Comment by SecUpwN** [comment]
Reviewed this again and think it may be better adding it to the title. Would this work, @DJaeger?

```JAVA
    <string name="pref_refresh_title">Refresh Rate:  %s</string>
```

If so, I will craft another pull request to move the display to the title. @E3V3A, what do you think?

**Comment by E3V3A** [comment]
Screen shot?

**Comment by SecUpwN** [comment]
>Screen shot?

![Preferences](https://spideroak.com/share/IFEU2U2JINCA/GitHub/home/SecUpwN/SpiderOak/SCREENSHOTS/Preferences.png)

**Comment by E3V3A** [comment]
Yes, make the changes.

**Comment by DJaeger** [comment]
It doesn't seem to work from the doku.
The methods for title don't work with formatter.

**Comment by DJaeger** [comment]
You have to make your own preference change listener for this.
But I wouldn't make it so complacated for simply print this.
I think the current solution is enougth a the common solution.

**Comment by SecUpwN** [comment]
>You have to make your own preference change listener for this.
But I wouldn't make it so complacated for simply print this.
I think the current solution is enougth a the common solution.

Yes, I agree. It was just a thought I had. I will keep it as it is since we all have eyes and it works. ;-)
