### ISSUE TITLE
Debug Logs are spammed when using XPrivacy

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#406]
When viewing the live logcat entries using the `Debug Logs` function, each entry is accompanied with the internal logcat command line, i.e. `logcat -t 500 -v brief -b main ...`, if you have installed XPrivacy. 

Solution: Filter logcat from using all related `XPrivacy` and `Xposed` entries. 
(Or only get rid of `XPrivacy/XRuntime`.)

**Comment by SecUpwN** [comment]
>Solution: Filter logcat from using all related `XPrivacy` and `Xposed` entries.

So that means our app should automatically filter these out when pressing `Debugging`?

**Comment by E3V3A** [comment]
Yes, by adding something like: `... XPrivacy/XRuntime:S Xposed:S` to the logcat line.

**Comment by E3V3A** [comment]
Hopefully fixed by https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/3a363321371ab6e08404fae20bb4453751629f33#diff-5937f7a5dfa8e4d10ae1df7b4091f29d

**Comment by E3V3A** [comment]
May consider to also silence: `XPrivacy/XTelephonyManager:S`...

**Comment by SecUpwN** [comment]
Are the above mentioned now silenced, @E3V3A? If not, feel invited to do so.

**Comment by E3V3A** [comment]
Added!
