### ISSUE TITLE
No BTS Measurements shown in DB viewer

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#407]
Entering `Database Viewer` and attempting to view either `Unique BTS Data` or `BTS Measurements` yield and empty table.

@DimaKoz Can you please have a look at this, as it seem to have something to do with your PRs. Are there any particular reasons why you replaced all the `case` statements with `else if`s? I found the former code much easier to read and handle... Compare [old](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/3562e09cc7d52f0973021e2ec8d8519f25ae3625/app/src/main/java/com/SecUpwN/AIMSICD/fragments/DbViewerFragment.java) code with the [latest](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/fragments/DbViewerFragment.java).

**Comment by DimaKoz** [comment]
>>Are there any particular reasons why you replaced all the case statements with else ifs?

The old code did bug in languages other than English
The tables were not displayed.
I found this bug.
@SecUpwN  confirmed it.
I see all the tables in the Database Viewer
What exactly the problem with the new code now?

**Comment by DimaKoz** [comment]
What language setting on your phone?
Maybe I would be able to repeat the bug that you see.

How many records you have in your "Unique BTS Data" and "BTS Measurements" tables?

**Comment by E3V3A** [comment]
I see, yes, that make sense. My language is set to default on ENG.

Yeah, I got it now after first enabling GPS and then restarting app. It took a few seconds. I don't think that GPS should be required to get these populated. Not sure whats causing this delay.

On a separate note, I also noticed that the RSS (Relative Signal Strength) fields are wrong, showing the dec equivalent of 0xFFFFFFF., i.e. it's not receiving the correct data.

**Comment by DimaKoz** [comment]
our app still has many bugs as possible(Now I'm trying to fix a few memory leaks since it makes me sad when I see it)

Yesterday I noticed that BTS moves with me, if you look at the map at this moment.
Sometimes she remained in place (recorded in the database), adding an unknown BTS (so we send the wrong data on www.opencellid.org)
![screenshot_2015-05-02-21-20-00](https://cloud.githubusercontent.com/assets/3092276/7444857/54fc2b88-f1a0-11e4-9552-03343333cb26.jpeg)

**Comment by DimaKoz** [comment]
>(Just too bad it makes it harder to read.)

I agree with you fully
We need a little refactoring (for example, add an adapter for spinner)
Then you can easily return ```case``` statements

**Comment by SecUpwN** [comment]
@DimaKoz, I am very happy having you here and working so hard to improve our code wherever possible! One small advice: Please make sure that when uploading screenshots of your device, no personal data (like BTS, IMEI, IMSI and such) gets exposed publicly. We know for a fact that we're being monitored by IMSIC producers. As for the meomory leaks: I have added you to our [Coverity Scan](https://scan.coverity.com/projects/3346), from where you should be able to comfortably see what leaks and why. Any fixes there are highly appreciated.

**Comment by SecUpwN** [comment]
@E3V3A, I have just sent you another invite to our [Buildozer](https://buildozer.io/accounts/926) which enables you to test the bleeding edge code of our `development` branch. Please make sure to constantly check if this Issue is still valid.

**Comment by E3V3A** [comment]
ok thanks, I'll have a look at it.

**Comment by SecUpwN** [comment]
>ok thanks, I'll have a look at it.

Yes, please test the latest build. This bug seems fixed to me, feel free to re-open if it isn't.

**Comment by E3V3A** [comment]
@SecUpwN Is that the same build as b00? Or only available on Buildozer?

**Comment by SecUpwN** [comment]
>Or only available on Buildozer?

@E3V3A, do you think I invited you to Buildozer because I am having too much time? ;-) Buildozer builds a rresh APK for testing when commiting anything to our `developmen` branch. And this fixed.

**Comment by E3V3A** [comment]
Well, then you need to add me to the project, do that there's something to download...

**Comment by SecUpwN** [comment]
>Well, then you need to add me to the project, do that there's something to download...

Already done since a few hours, sorry for having forgotten that important point. ;-)

**Comment by E3V3A** [comment]
This issue, is still present exactly as described. Again, upon first start all info is shown about currently connected BTS, but DB is empty.

**Comment by agilob** [comment]
I can't reproduce this issue, after new install in 10minutes I had 4 new unique cells and 4 measures.

**Comment by E3V3A** [comment]
Thta's the point, "after 10 minutes". You should have at least one immediately.

**Comment by E3V3A** [comment]
This issue seem to have been fixed when I tested on **0.1.28-alpha-b03**.
