### ISSUE TITLE
Antenna Map Viewer: Overlay of small Map Legend

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#408]
Hey guys, sorry for piling up Issues again. I have received feedback from people that they do use the `Antenna Map Viewer` but do not know what each circle on the map stands for. **Solution:** In the top right corner of our `Antenna Map Viewer` users can already change the Map Type and download the OCID data. I propose adding a small legend to overlay the map to quickly show what each circle stands for. This feature has also been requested in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/13#issuecomment-86796058 and will certainly enhance the users experience.

**Comment by E3V3A** [comment]
Great idea, and I don't think we even need a button for that. A very small legend should suffice, and if the legend is clicked, a larger more details description is shown.

**Comment by ziem** [comment]
@E3V3A Legend can be easily displayed above map like [TextView](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/res/layout/map.xml#L14) with contributors. I can do it, just tell me what do you want it to look like?

**Comment by SecUpwN** [comment]
>I can do it, just tell me what do you want it to look like?

Any examples you can link us to?

**Comment by ziem** [comment]
I was thinking about something similar to: https://bellevuentss.files.wordpress.com/2012/04/tap-google-map-legend.jpg .

**Comment by SecUpwN** [comment]
@ziem, looks great! I'd prefer some sort of gray background though and this thing should be small. But since I know you're a real pro coding stuff for maps, feel invited to craft an initial pull request! ;-)

**Comment by E3V3A** [comment]
Perfect, if it will use same icons.

**Comment by SecUpwN** [comment]
>Please send a text description of the markers on the map (for the window, where they will show the markers and their description)

@DimaKoz, I have just updated the OP since we came to the conclusion that we [don't need a buttton](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/408#issuecomment-98537155) a small map legend that overlays the map in the top right corner, similar to what @ziem [suggested](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/408#issuecomment-98704005) should be perfect. Here is my proposal of the descriptions you've asked for (separate coloring Issue [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/250)):

*  BLUE = Currently connected BTS
* GREEN = Nearby previously seen BTS
* ORANGE = Known imported BTS of OCID
* RED = New or previously unknown BTS

Feel invited to correct me on the above suggestions if you disagree.

**Comment by E3V3A** [comment]
I suggest:

| PIN                                                                                                                                      | EVENT                         |
|------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|
| ![BLUE](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/drawable-hdpi/ic_map_pin_blue.png)     | Currently connected BTS |
| ![GREEN](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/drawable-hdpi/ic_map_pin_green.png)   | Well known & encrypted BTS |
| ![ORANGE](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/drawable-hdpi/ic_map_pin_orange.png) | New or recently added BTS  |
| ![RED](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/drawable-hdpi/ic_map_pin_red.png)       | Unknown or insecure BTS |

Of course the legend should be without the table "header" shown above, to conserve screen space.

**Comment by SecUpwN** [comment]
@E3V3A, thanks for updating the legend. I fully agree and would love to see it it added like this.
Who of you is going to do it, @ziem or @DimaKoz? Please tell us here to avoid double work.

**Comment by ziem** [comment]
I can do it, but after the weekend.

**Comment by SecUpwN** [comment]
>I can do it, but after the weekend.

@ziem, yes, please give it a shot. Thank you for committing yourself to this.

**Comment by ziem** [comment]
Sorry for delay. Legend is almost ready:

![Legend](http://i.imgur.com/feUvrSC.png)

Font size: `10sp`.
Background color: `#50ffffff`.

What do you think about it? Do you have any suggestions how can I improve it?

**Comment by E3V3A** [comment]
Thanks @ziem! That above look very good. I still need to test. Is the legend transparent?

**Comment by ziem** [comment]
Yes, legend is transparent:
![Transparent legend](http://i.imgur.com/ijcrHYe.png)

**Comment by SecUpwN** [comment]
>What do you think about it? Do you have any suggestions how can I improve it?

Looks awesome and doesn't take away too much space. Do you think we'd need to add any sort of expanded descriptions when touching the legend, @E3V3A? In my eyes this thing looks about perfect!

**Comment by E3V3A** [comment]
The only thing I could think of, is an expanded explanation of the icons, in a pop-up window, when the legend is clicked. (We already have this elsewhere AFAIK.)

**Comment by SecUpwN** [comment]
>(We already have this elsewhere AFAIK.)

Do you mean your descriptions from #250?

**Comment by E3V3A** [comment]
No I mean the ones in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Status-Icons and explanation that should be linked from the About drawer item.

**Comment by SecUpwN** [comment]
@E3V3A, I'm afraid I don't get what you want to accomplish. The explanations for the Status Icons have been implemented already, you can view them by clicking the Icons in the `About` menu. Please clarify.

**Comment by E3V3A** [comment]
I mean hitting the legend will take you there, unless there's a UX problem with doing that. (E.g. for small screens with large legend?)

**Comment by ziem** [comment]
Created pull request with map legend.

**Comment by SecUpwN** [comment]
>I mean hitting the legend will take you there, unless there's a UX problem with doing that.

>Done - created pull request with map legend.

@ziem, awesome work! Just waiting for another Issue to be solved, will merge this soon.

@E3V3A, the Status Icons page has nothing to do with the map legend and I would like to avoid adding too many links. If a user wants to now about the Status Icons, he can view the detailed descriptions through the `About` page. Furthermore, do we really need to explain anything more for the map legend? Should be pretty self-explanatory now. Let's give it a shot and see if we really need to add anything else.

**Comment by ziem** [comment]
@SecUpwN - thanks ;). If you would like me to help you with other things, let me know.

**Comment by SecUpwN** [comment]
>If you would like me to help you with other things, let me know.

Thanks for the kind offer, @ziem! It would be awesome if you could send me a private email and let me know if you want to be listed on our [team page](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Contact). Generally speaking, I'd be **extremely** thankful if you could tackle any other [open Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues) (especially bugs) so that our app gets more stable with cleaner code.
