### ISSUE TITLE
False Positive: Changing LAC 

### ISSUE THREAD

**Issue by Ste4thOverride** [SecUpwN/Android-IMSI-Catcher-Detector#416]
I noticed recently while driving from one area to another area the app throws a false positive Yellow attack. One solution would be to detect when the new cell tower is showing Neighbour cell tower list not to throw yellow warning and only show the warning when changed location hides neighbouring cell towers and is missing a cell identifier.

**Comment by SecUpwN** [comment]
>...the app throws a false positive Yellow attack...

Sorry having to say that, but this also seems like a dupe related to completion of #91.
Please follow up there, I'm hoping for @He3556 to give us an update there.
