### ISSUE TITLE
Positioning data is sent to google locationhistory

### ISSUE THREAD

**Issue by xranby** [SecUpwN/Android-IMSI-Catcher-Detector#419]
Prevent leakage of sensitive GPS data

When I use positioning and Android-IMSI-Catcher-Detector, the positioning data is uploaded to google with timestamps. https://maps.google.com/locationhistory/b/0. The user should be warned that their location is tracked if possible make it easy for the user to disable googles tracker. A different API should be used to display the map that do not share the users position and timestamps with a third party.

**Comment by SecUpwN** [comment]
Thank you for notifying us of the Issue, @xranby for further discussion.

>A different API should be used to display the map..

@E3V3A I thought we had removed everything Google from the code?

**Comment by E3V3A** [comment]
Well, without more detailed info from @xranby, it's impossible to tell what he's doing, and if there is anything, we can do about it. Most likely this is a Google Android API problem, far beyond our control. Please contact Google.
