### ISSUE TITLE
Only request ROOT when using AT Command Interface

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#421]
Reported [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/412#issuecomment-98833790), apparently our app even requests root when not needed.

>I would like to add that when I use the "Export Database" function, in the newest WIP (v0.1.26-alpha-b00) release and the previous release (v0.1.25-alpha-b35), I am prompted for root access for AIMSICD. However, if I deny root access, the files are still exported. I am on CM12 (5.1.1).

Solution: Improve our ROOT request to only ask for it when using the `AT Command Interface`.

**Comment by E3V3A** [comment]
I already [told](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/412#issuecomment-98852721) you why we need root for full DB export. So why do you now want to revert and cripple the DB export? Besides we never said we're gonna support CM or ROMS, on the contrary, which means we use root when we need it.
