### ISSUE TITLE
App and DB Viewer is very slow and laggy

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#423]
**Generally**: App navigation has become excruciatingly slow and laggy in almost all aspects. 

**Specifically**: This is especially evident when side swiping and when using the `Database Viewer`. Hitting the table selector takes almost a second to show up on a modern phone with dual-core Qualcomm processor. The same goes for actually displaying of the data. 

**Possible causes**: Too much graphics intensive features in irrelevant places, like spinners and load status bars and toast messages etc. Further investigation required.

**Resolution**: Apart from stripping down the app to the bare essentials, I have very few ideas and I'm open for new suggestions.

**Comment by SecUpwN** [comment]
>**Generally:** App navigation has become excruciatingly slow and laggy in almost all aspects.

I cannot confirm this. It is working smooth as butter on my own device.

>**Resolution:** Apart from stripping down the app to the bare essentials...

What exactly would you like to see removed? Sounds like you want to see your app re-coded from scratch..

**Comment by E3V3A** [comment]
This seem to have improved somewhat on the latest builds. But I haven't had a chance to test them on any additional devices yet. If we can get a couple of smooth confirmations from other developers, we can close this.

**Comment by E3V3A** [comment]
Sometime I see AIMSICD using around 50 MB of memory, not sure how this usage is calculated, but seem rather excessive... Perhaps the DB is included in this?

**Comment by wvengen** [comment]
The database viewer loads and shows all entries, as far as I understand. I've seen the app throwing an OutOfMemoryError on loading >200k OCID rows (app compiled in debug mode). Because this is running in a background task, I suppose it may hinder UI performance when running on large tasks.

If this is the cause, it may be solved by using paging in the table (and other places).

**Comment by E3V3A** [comment]
Please re-test this issue now. (Using Buildozer build >= 211)

**Comment by SecUpwN** [comment]
>Please re-test this issue now. (Using Buildozer build >= 211)

You closed this. Does that mean our app just got faster, @E3V3A?
