### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by kelna** [SecUpwN/Android-IMSI-Catcher-Detector#427]
What are these new permissions in .27? I mean, are these really necessery? SIP calling, contacts etc.? Why?
Thanks for the answers in advance!

**Comment by SecUpwN** [comment]
Hi there, @kelna! Thank you for submitting your concerns. I guess you just updated from F-Droid? The jump you've made from the last public version on F-Droid to the current version is pretty huge, many things have been added and a lot of code changed. We know that people are always concerned when having to grant so many permissions, but in our case, we simply need so many different variables to make our app work properly. Please have a look at our explanations for [permissions](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Permissions). You are always invited to help us cutting down on the permissions by improving our code. Thank you for your trust!
