### ISSUE TITLE
GPS toggle without nag

### ISSUE THREAD

**Issue by swordsteel** [SecUpwN/Android-IMSI-Catcher-Detector#428]
Would be great to use AIMSICD without need for GPS to save life on battery. I run it almost all the time but battery life is really short. When I keep my GPS off, I get a constant nag to turn GPS on. Is there a way to work it so the nag goes away?

**Comment by E3V3A** [comment]
I agree, I'd also like to see this nag screen removed. However, if this is implemented we will not get GPS data to any newly detected BTS. Thus user should not be able to upload BTS data either.

**Comment by SecUpwN** [comment]
This has essentially been filed by myself a while ago already in #251, please continue there.
