### ISSUE TITLE
Tech issue question

### ISSUE THREAD

**Issue by kbjuan** [SecUpwN/Android-IMSI-Catcher-Detector#438]
Hi, is there a manual on how to use the android-IMSI-Catcher? It is a way cool application but I am not that up on tech. When I get text messages it always says my text messages are intercepted.

**Comment by SecUpwN** [comment]
>Hi, is there a manual on how to use the android-IMSI-Catcher?

Good evening @kbjuan! First of all, our app is **NO** IMSI-Catcher, but is rather meant to detect those. Please have a look at our [WIKI](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki) and see if it helps. Are there any specific questions you have on how to use our app?

>When I get text messages it always says my text messages are intercepted.

This shouldn't be happening. Which version of our app are you using?

**Comment by kbjuan** [comment]
RIL version 0

**Comment by SecUpwN** [comment]
>RIL version 0

Version of our **APP**?

**Comment by kbjuan** [comment]
Sorry about that Version o.1.25-alpha-b6 I really  appreciate your patience and support

**Comment by SecUpwN** [comment]
>Sorry about that Version o.1.25-alpha-b6

Dude, you are using the **OLDEST** release from one of our stores, do you even care updating? Where did you get it from and why do you complain about a bug (likely related to #366 and #382) that's already been fixed a long time ago? Please use the [latest version](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases) and read the very first rule on [this page](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues)!

@kbjuan, I hope you can feel with me when I say that it's ticking me off that people complain about outdated apps, do not read our WIKI and also do not care adding pull requests to fix stuff. **CLOSED**.
