### ISSUE TITLE
LAC changing detected

### ISSUE THREAD

**Issue by MatejKovacic** [SecUpwN/Android-IMSI-Catcher-Detector#439]
I have installed AIMSICD (WIP TEST RELEASE v0.1.28-alpha-b00) to a mobile phone with Android 4.4.2. I am customer of slovenian mobile operator Si.mobil (operator's code is 29340).

Today I was at some location, where AIMSICD noted me, that I am in hostile service area - changing LAC is detected: 
![aimsicd_lac_changing_2015-05-26-20-31-41](https://cloud.githubusercontent.com/assets/3339198/7822901/e102bdf8-03f8-11e5-8478-026bb2337252.png)

So I checked out Antenna Map Viewer and it seems I am connected to two different cells: 
![aimsicd_map_2015-05-26-20-44-24](https://cloud.githubusercontent.com/assets/3339198/7822915/f3b06a7c-03f8-11e5-9dc9-b010a326aa2c.png)

However, detail view has shown, that two cells are in fact different:
![aimsicd_lac1_2015-05-26-20-41-18](https://cloud.githubusercontent.com/assets/3339198/7822920/03ec8754-03f9-11e5-8a7d-400cc162a3cb.png)
![aimsicd_lac2_2015-05-26-20-41-28](https://cloud.githubusercontent.com/assets/3339198/7822921/03ee3e6e-03f9-11e5-99cd-2ced4ef40585.png)

My question is: what does it means, how to explain this behavior. Because the area where this happened is quite isolated (there are some hills around) and there is only one base station of Si.mobil service provider.

Any idea?

**Comment by SecUpwN** [comment]
@E3V3A, would you please chime in? Thank you.

**Comment by scento** [comment]
I experienced something similar while testing *AIMSICD 0.1.28-alpha-b00* on *hammerhead* with *Android 5.1* - it seems as if all base stations around my location in Germany are using different LAC's (`40326`, `5827`, `31506`, `40326`). My map view shows even more "active" BTS, which are far away from my current location.

---
![screenshot](https://cloud.githubusercontent.com/assets/2129596/7835639/d1765912-047a-11e5-9eb0-d99978a9e435.png)

**Comment by SecUpwN** [comment]
@MatejKovacic and @scento have you made sure that you've downloaded the current OCID data?

**Comment by E3V3A** [comment]
This is a side effect of having a broken database. Fix the db and we can filter out bad data.  Furthermore the PC shown above must be wrong since it's showing 6 digits, instead of 5.

**Comment by E3V3A** [comment]
Actually, I just noticed you're using 4G (LTE ) which we currently don't have support for...

**Comment by E3V3A** [comment]
This is also a side effect of having as broken DB. Fix the DB so that we can properly filter bad BTS. The PC is also wrong since it should be 5 digits and not 6.

**Comment by SecUpwN** [comment]
>Actually, I just noticed you're using 4G (LTE ) which we currently don't have support for...

Is this an (invalid) bug on our side now, or how to classify this? Let it stay open?

**Comment by MatejKovacic** [comment]
OK, any hint how to fix broken database?

**Comment by SecUpwN** [comment]
>OK, any hint how to fix broken database?

The right thing to do would be to craft a pull request for the compete overhaul described in #215.

**Comment by E3V3A** [comment]
@SecUpwN 

> Is this an (invalid) bug on our side now, or how to classify this? Let it stay open?

I don't have a working LTE device right now, so I can't test this at all. We need to file a separate issue for LTE support.

@MatejKovacic 

> OK, any hint how to fix broken database?

All the hints required are in that #215 issue thread.

**Comment by E3V3A** [comment]
Many of the programming details and required LTE info can be found in [AIMSICDDbAdapter.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java).

**Comment by johnrandolph** [comment]
// mobile

**Comment by E3V3A** [comment]
This may also be related to #525...

**Comment by SecUpwN** [comment]
@MatejKovacic, please accept that I am closing this as `INVALID` since our app does not yet support LTE until #442 has been solved. Furthermore, you did not respond via E-Mail since more than a month. You may test the latest version of our app without using an LTE connection and re-open this if it reappears.

**Comment by SecUpwN** [comment]
@smarek, this Issue is `INVALID` since we do not support LTE yet (see #442) and it will likely not happen until the `v0.1.37-alpha` release. Hence no need to assign you, me, or a specific milestone. ;-)
