### ISSUE TITLE
Memory leak detection? (pros and cons)

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#443]
**Q:** What are the pros and cons of including a memory leak detection library? 

**Background:** Some developers have suggested we should add the [leakcanary](https://github.com/square/leakcanary) memory leak detection library to our debug builds. This sound great, but do we really need it? How will it affect our builds? To what extent will its inclusion make our code even more complex and thus even less maintainable? 

Here's a [blog](https://corner.squareup.com/2015/05/leak-canary.html) about it.

**Comment by SecUpwN** [comment]
Does not make much sense to me. Counter-question: What is the difference to our already existing [CoverityScan](https://scan.coverity.com/projects/3346)? It already analyzes every single line of code, we simply need someone specifically for fixing the discovered defects, which I already listed in our `CONTRIBUTING.md` in section [SEEKING](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md#seeking).

**Comment by E3V3A** [comment]
I think the issue is that you need to understand the issue before you can fix it. The coverity scan results are very cryptic, even for a seasoned programmer. In addition, any automated scans will undoubtedly also produce many false positives. I.e. alright code marked as bugs. Memory leaks are harder to detect, and more serious problems as they're not easily detected and can cause random crashes...

**Comment by SecUpwN** [comment]
>The coverity scan results are very cryptic, even for a seasoned programmer.

I would have no problem at all changing to a system that more developers would use to help us fixing these things. But given the current "participation" from outside users, it will make no difference at all. Added to that: *If* we use `leakanary`, shall we ditch `CoverityScan`? I would vote for an all-around solution.

**Comment by E3V3A** [comment]
CoverityScan is just analyzing the code we have, while leakanary is implementing some new code for the detection library to work.

**Comment by SecUpwN** [comment]
>CoverityScan is just analyzing the code we have, while leakanary is implementing some new code for the detection library to work.

Thanks for clarifying. @banjaxbanjo and @tobykurien, what is your opinion on adding `leakanary`?

**Comment by tobykurien** [comment]
I have no experience with it, but worth giving a try.

On 4 June 2015 09:48:06 GMT+05:30, "Security: Pwned." <notifications@github.com> wrote:
>>CoverityScan is just analyzing the code we have, while leakanary is
>implementing some new code for the detection library to work.
>
>Thanks for clarifying. @banjaxbanjo and @tobykurien, what is your
>opinion on adding `leakanary`?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/443#issuecomment-108714860

-- 
http://tobykurien.com | @tobykurien

**Comment by SecUpwN** [comment]
>I have no experience with it, but worth giving a try.

Thanks for the feedback, I have **prepared and am about to push** integration of `leakanary`. Just one more question: During my research, I also stumbled across [Fabric](https://get.fabric.io/). Would it be better switching to this full-blown solution, or do you think we'd just need to add `leakanary` to improve our app?

**Comment by SecUpwN** [comment]
@E3V3A and @tobykurien, our builds currently fail after the implementation. Did I do something wrong?

**Comment by E3V3A** [comment]
If you're asking me, you're barking up the wrong tree,as I have no idea how this works and have no time to looking it up or dealing with it.

**Comment by SecUpwN** [comment]
>If you're asking me, you're barking up the wrong tree, as I have no idea how this works and have no time to looking it up or dealing with it.

Barking up the wrong tree? @E3V3A, it is exactly this type of thing, the mentality of "here-i-have-something-but-do-it-yourself-because-nobody-has-time-for-this-shit", that is ticking me off at times when I actually try to figure something out and implement something instead of collecting new Issues. I'd appreciate some help at times, some pull requests, some code review, anything. I know we're having a rough ride on GitHub at times (like always), but if everyone just keeps "suggesting" stuff without actually doing the research and coding, then we're on a lost trail. I simply asked if this is right:

* [How to implement it](https://github.com/square/leakcanary#getting-started) vs. [how I implemented it](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/6b93245b5ad30a4c36b83d67c067a6859c4f2642). Why are builds failing? Used the wrong `build.gradle`?

**Comment by ziem** [comment]
Can you post error message?

**Comment by SecUpwN** [comment]
>Can you post error message?

@ziem, this is where [Travis CI complains](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/65388561):
>...
>Where: Build file '/home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/build.gradle' line: 8

>What: Could not find method debugCompile() for arguments [com.squareup.leakcanary:leakcanary-android:1.3.1]
>...

So it complains about the `build.gradle`. The question is: Which `build.gradle` did @square mean when they described the implementation of `leakcanary` [here](https://github.com/square/leakcanary#getting-started)? We have two: [This one](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/build.gradle) and [that one](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/build.gradle).

**Comment by ziem** [comment]
You added LeakCanary dependencies in wrong build.gradle file. Move them form `build.gradle` to `app/build.gradle`.

**Comment by SecUpwN** [comment]
>You have added LeakCanary dependencies in wrong build.gradle file.

Thanks for heping, @ziem! :+1: If you have time, can you have a look at our `URGENT` Issues now?

**Comment by ziem** [comment]
If you receive another error:
> Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material'.
You need to set `compileSdkVersion` and `targetSdkVersion` to 21.

**Comment by SecUpwN** [comment]
>You need to set `compileSdkVersion` and `targetSdkVersion` to `21`.

I did. Now I'm getting the following [complaint](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/65468235):

>:app:compileReleaseJava/home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/app/src/main/java/com/SecUpwN/AIMSICD/AppAIMSICD.java:37: error: cannot find symbol
>LeakCanary.install(this);
>^
>symbol: variable LeakCanary

**Comment by ziem** [comment]
Alt + Enter ;).

**Comment by E3V3A** [comment]
Doesn't setting target to 21 remove all downward compatibility ?

**Comment by ziem** [comment]
No, `minSdkVersion` is stll set to 16.

**Comment by SecUpwN** [comment]
>Alt + Enter ;).

I don't get it. Why is this thing not working properly? Can you digg into this, please?

**Comment by ziem** [comment]
You are probably missing:
    
    import com.squareup.leakcanary.LeakCanary;
