### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by breversa** [SecUpwN/Android-IMSI-Catcher-Detector#449]
Hi, while the green/yellow/orange/red color scheme for both the notification and antenna map icons is perfectly fine for most of the population, a significant percentage is however colorblind, and may not be able to tell between "You're safe, no worries"-green and "Run for your life !"-red.

May I suggest switching green to blue, which is much less likely to be confused by most colorblind users?

**Comment by SecUpwN** [comment]
>May I suggest switching green to blue, which is much less likely to be confused by most colorblind users?

Thank you for thinking ahead, @breversa. Are you color blind? I am not quite sure if the approach of changing our green status icon to blue would be "the solution" for this - what about the other icons? Just to note it here, if we ever add this, we should make this a **SETTING** in `Preferences/Status Icons`.

**Comment by breversa** [comment]
Hi !
Yes, I'm colorblind (deuteranomaly-type) myself.

The "flat" style icon is a bit better than the two icon styles, because it
makes the icon a single larger patch of color which is easier to recognize
(colorblind people like large patches of color ! It's easier to tell :-) ).

However, the antenna map uses both green and red dots, which I can only
hardly tell apart, especially in a city with a high antenna density (I need
to compare *each* dot with one I'm sure of its color. It's as tedious and
slow as you can imagine).

That's why I suggest another color for either the green or red icons/dots.
Le 4 juin 2015 06:24, "Security: Pwned." <notifications@github.com> a
écrit :

**Comment by SecUpwN** [comment]
@breversa, thanks for your honesty to tell us that you're actually one of the people who'd profit from such an improvement. I guess we would need to change all icons then? Here is an approach:

1. Add a **checkbox** called `Colorblind Mode`to `Preferences/INTERFACE SETTINGS`
2. Once the checkbox has been activated, all icons shall change to some preferred color

It might be a good idea to make our app use some colors that **every** colorblind person can clearly see and identify. Since you're one of them, do you know of any good resources which colors we should use? I would like to avoid having to re-craft all status icons, changing the color should be good enough, right?

**Comment by breversa** [comment]
Well, while the icons are the most oustanding problem, AIMSCID is actually color-heavy (and you might not even realize it if you're not colorblind yourself. :-) )

For instance, the database viewer uses red and green (or is that yellow ?), and I guess the Current Threat Level screen too. So it's more about good "global" UI design than simply icons… but changing the icons' color would be a pretty good start anyway. My intention was not to provoke an all-out redesign of the app ! ;-)

Anyway, I did a bit of research and found the following material regarding UI design for colorblind users :
- http://www.particletree.com/features/interfaces-and-color-blindness/ : this rather lengthy article seems to be a kind of reference in the field. It deals more with visual cues rather than color schemes, but I believe it's a very good starting point for a designer wanting to take into account colorblindness in general.
- http://critiquewall.com/2007/12/10/blindness : an example of how colorblind people may see color. Personnaly, I see NO difference between each picture (except one of the Christmas tree that looks a bit darker than the other). But other colorblind people may, so it's not universal.
- http://paletton.com/#uid=51T0u0klllleScZi6h9o-pxrOtH : this might be the most useful tool. It's a palette chooser with a "vision simulation" option (on the bottom right-hand corner) that takes into account many (if not all) colorblindness… and gives info about their rate among population. :-)

Would that be enough for you for the moment ? Even if it is not, let me thank you fondly for at least taking your time to think about the issue. ;-)

**Comment by breversa** [comment]
And come to think of it, if you're a gamer, you may know of FTL: Faster Than Light, and Borderlands 2. Both game have a colorblind setting, either simple… or the most thourough I've ever seen !

FTL switches their green/orange/red color scheme (or is it light/medium/dark green ? Again, I can't tell) for a white/green/blue one.

And the "Most colorblind-friendly game EVER" award goes to Borderlands 2, where there is one colorblind mode PER colorblindness TYPE !!! o_O It actually made ME check the scientific name of my colorblindness in order to choose the right setting. ^^

**Comment by E3V3A** [comment]
I'm sorry, but we're simply not in a position to develop support such specialized requirements at this time. I wrote about this issue in one of the first issues when we opened our GitHub, and then decided that color-blindness support could be provided by using geometrical shapes instead of colors, since there are many types of color-blindness. **We're not changing the current color coding scheme.**, Any color-blindness support would have to be provided by a separate setting. (Please send us a PR.) You may also contact Google to ask them to implement automatic color-blindness settings into their API.

**Comment by SecUpwN** [comment]
>My intention was not to provoke an all-out redesign of the app ! ;-)

Thank you for your research, @breversa. You see that your Issue here has been closed now, but maybe we can respect some of your wishes in #258. Please help us developing with pull requests!

**Comment by E3V3A** [comment]
Android Lollipop has the [11. Colour Inversion And Colour Correction](http://www.theguardian.com/technology/2015/jan/12/23-tips-tricks-android) Mode for this. Use that.

> If you’re colour blind or your vision is impaired then these features could improve your experience with Android’s new OS. Go to Settings > Accessibility and scroll to the Display sub-heading at the bottom. Turning Colour Inversion on will dramatically change the look of your device and may be more soothing on the eye for some people. Selecting Colour Correction will allow you to choose from three different colour modes - Deuteranomaly (red-green), Protanomaly (red-green), Tritanomaly (blue-yellow) - which may be beneficial to some colour blind users. As with the high contrast text, this is an experimental feature and may slow down your system.

**Comment by SecUpwN** [comment]
Thanks for adding this hint, @E3V3A. It is now [available in our FAQ](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-what-to-do-if-im-colorblind).
