### ISSUE TITLE
Translations: Proper wording for "tracking" and "monitoring"

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#450]
We currently have some rather confusing wording on the menu entries on our sidebar. These include:

* `Toggle AIMSICD monitoring`
* `Toggle 2g-only network lock`

This appears rather confusing as mentioned in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/447#issuecomment-107914666.

---

In German, I have already corrected these things somewhat:

* `Mobilfunkschutz ein/ausschalten` - means: `Toggle Cellular Protection`
* `2G-Netzwerk für Aufzeichnung nutzen` - means: `Toggle 2G-network for recording`

@E3V3A and especially @He3556 would that be a proper translation? We should make it very clear what these buttons actually do, our app is confusing enough at this very moment. Thanks for helping!

**Once this is clarified here, I will correct the meaning across all translation files.**

**Comment by ph0t0n** [comment]
do you want a native German or English speaker (I'm this) to comment? "Toggle 2G-network for recording" is very ambiguous. It sounds like you are going to change my phone mode with regards to 2G in some respect (like enable/disable 2G radio), or make AIMSICD follow the GSM mode and only be active when on 2G. (is it this?)

I looked at the source and I am still not sure. It seems to immediately set the service setCellTracking if the setting is enabled but I can't find where 2G radio notification occurs to see what the behavior is.

I have actually always wondered what this is...
(thanks for the app!)

**Comment by SecUpwN** [comment]
>do you want a native German or English speaker (I'm this) to comment?

Yes, please. Welcome to our project, @ph0t0n! ;-)

>It sounds like you are going to change my phone mode with regards to 2G in some respect (like enable/disable 2G radio), or make AIMSICD follow the GSM mode and only be active when on 2G. (is it this?)

We actually force the phone into 2G network mode and track the path where the user walks via GPS while at the same time recording the connected cells for a possbile later upload to OpenCellID.

>I looked at the source and I am still not sure. It seems to immediately set the service setCellTracking if the setting is enabled but I can't find where 2G radio notification occurs to see what the behavior is.

@E3V3A and possibly @banjaxbanjo would you please see if I explained the right thing above? If so, I wonder why people cannot see what is actually happening behind the scenes looking at the code.

>(thanks for the app!)

Thanks, makes us feel warm and fuzzy! We're always happy to receive **pull requests**, you know.. ;-)

**Comment by ph0t0n** [comment]
ok, but Tracking Cell Information is enabled by default, yes?  

right now my phone is TelephonyManager.PHONE_TYPE_GSM and TelephonyManager.NETWORK_TYPE_HSPA and the message R.message.tracking_cell_information is displayed as soon as I start the app.

I think it is from this code block:

https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/d7a9f64e3f4c1e288b0288299d32313273744d22/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L264

When I press "Toggle 2G-network for recording" I do not see my phone change to mode 2G GSM or not 2G GSM, it enables/disables Tracking Cell feature of the service. 

I tried looking closer at your German words with a dictionary and also the code and can't find 2G force code. I didn't even think Android api allowed that? I looked at your utils.SystemPropertiesReflection class to see if you were using reflection to private api but didn't see any mode change there either.

it is funny this is so obscure a feature =)

thanks!

**Comment by banjaxbanjo** [comment]
Yes this is confusing about the 2g mode to me also I haven't really focused on the difference between the 2 monitoring modes but from what I see
Toggle AIMSICD monitoring = monitor and log all cells
Toggle 2G-only network lock = gps logging (basically activates gps and when a new cell is spotted will provide up to date gps coors for celltracker) Dont know why this is named 2G network lock.

all this LocationTracker class does is gives last known location and sets up to date lat lon on location change

        public void onLocationChanged(Location loc) {
            //Log.d("location", "Got location " + loc);
            if (lastLocation != null &&
                    lastLocation.getLongitude() == loc.getLongitude() &&
                    lastLocation.getLatitude() == loc.getLatitude()) {
                // same location as before, so ignore
                return;
            }

**Comment by He3556** [comment]
sorry for my delay and all the confussion. banjaxbanjo is quite close to the right answer.

monitoring = log all info (CellID, LAC)
tracking = log own location + signal strength of the connected cell

the idea is that one parameter a catcher can't fake is the higher signal strength than the real cell. but this is more complicated...

We are mainly focused on 2G networks because that's where the catchers are working. (in the meanwhile there are catchers that can manipulate the phone in this way, that you see a 3G icon on the screen while you are actually connected with 2G) Our APP can't force the phone to connect to a special network only. 
So we should delete all the 2G stuff on the menue and in the description. 

i hope i could help a little bit.

**Comment by E3V3A** [comment]
Actually we **can** lock phone to 2G operation, but it's modem specific. We should be able to hijack the google API settings to enable this.

**Comment by E3V3A** [comment]
However as hehe3556 said , this option is probably if less importance today where 3G catchers are readily available while A5/3 are rarely implemented.

**Comment by SecUpwN** [comment]
@E3V3A, so what to do now? What would be the correct meaning that we shall print for both buttons?

**Comment by SecUpwN** [comment]
I have just received an answer from @He3556 regarding the naming the buttons and will change a few small things before publishing today's release. We need to clear up the forcing into 2G mode, since our code does not do that and it is not clear if we can do that for all devices. Thus, a renaming within our code and another renaming of the buttons (my part) will be necessary in the upcoming week.

**Comment by E3V3A** [comment]
Actually that is a good idea, but using the word "protection" is a bit of false advertising, since we're not *protecting*, but only *detecting* so far...

**Comment by SecUpwN** [comment]
>Actually that is a good idea, but using the word "protection" is a bit of false advertising, since we're not protecting, but only detecting so far...

Ok, we should find a proper naming of the button that applies to all translations and enables us to improve the underlying code without changing the naming over and over again.

I would use the term *monitoring*, but I feel this could be associated negatively, just like *tracking* - both of these things are popping up in my head when thinking about *surveillance*. Other suggestions?

**Comment by ph0t0n** [comment]
just one opinion here, but given the context that this app is running under, "tracking" is totally fine for native english. we know we are tracking things: location, cell towers, etc. the user has opted into this activity by gaining knowledge of, compiling and running this app. they are aware it is going to track metrics from their phone. it is open source too, they can read the services to make sure they agree with its activity.

"monitoring" sounds more passive and is not as applicable to this app since users are choosing to run it.

hope this helps...

**Comment by SecUpwN** [comment]
>"monitoring" sounds more passive and is not as applicable to this app since users are choosing to run it.

Yes, it does help. Thank you for throwing in your thoughts, @ph0t0n. Please vote for the better:

**Option 1**

```JAVA
    <string name="toggle_analysis">Toggle Cell Analysis</string>
    <string name="toggle_recording">Toggle Cell Recording</string>
```

**Option 2**

```JAVA
    <string name="toggle_detection">Toggle Attack Detection</string>
    <string name="toggle_recording">Toggle Cell Recording</string>
```

**Option 3**

```JAVA
    <Let me know your own preferences>
```

@E3V3A and @banjaxbanjo, again, what is the following used for? Can we remove this?

```JAVA
    <string name="toggle_femtocell">Toggle Femtocell</string>
```

**Comment by ph0t0n** [comment]
Hi @SecUpwN , 

I would suggest these choices (if you are comfortable with the derived R.string.* constants)

    <string name="toggle_attack_detection">Toggle Attack Detection</string>
    <string name="toggle_cell_tracking">Toggle Cell Tracking</string>

again this is just one person's opinion, but in english "Cell Recording" sounds like you might be recording the entire cell data stream somehow. i would not be concerned for my privacy since I am choosing to run your app, however this activity sounds like a storage hog that will fill up my phone. :) 

if you say "Cell Tracking" it sounds more like cell METADATA not DATA that you are interested in, which sounds lightweight.

if you intend to keep femtocell detection  you can change it to use consistent wording   toggle_femtocell_detection    Toggle Femtocell Detection

there are also picocell repeaters but I think they are only RF-level repeaters not protocol-level and thus have the same cell ID as the tower. it is a radio extender of sorts. http://de.wikipedia.org/wiki/Repeater  look at Repeater in Handi/Mobile Funknetzen

hope this helps. thanks

**Comment by SecUpwN** [comment]
Hi there @ph0t0n, I really like what you just proposed and will change the strings to that. Maybe you can be of further help maintaining our [strings](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/values/translatable_strings.xml)? I am German, so don't expect me to translate everything to a perfect synchronization between code and meaning - that is where I'd like you to pop in from now on. ;-)

>if you intend to keep femtocell detection you can change it to use consistent wording

Again, I am not yet sure where this string comes into play as I have never seen a "toggle button" for the Femtocell detection. To my knowledge we're using the settings for it in `Preferences`.

>there are also picocell repeaters..

If those are detectable somehow, please file a new Issue for them to discuss an implementation.

**Comment by E3V3A** [comment]
I really like @ph0t0n's [suggestion](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/450#issuecomment-110123021), so I'd vote for that.

**Comment by ph0t0n** [comment]
Hi, @E3V3A @SecUpwN I'd be happy to keep an eye on the english strings file and making sure it has a nice match with the functionality the app provides.

**Comment by SecUpwN** [comment]
Done. Before I close this Issue, can someone tell me where the "toggle button" for this is to be found?
```JAVA
    <string name="toggle_femtocell">Toggle Femtocell</string>
```
Maybe @He3556 or @tobykurien can be of help here? I thought we use a *checkbox* in `Preferences`?

**Comment by SecUpwN** [comment]
@E3V3A, would you please respond on my previous answer? This Issue is already fixed, yet I'd like to receive an answer why we have that code for a "toggle button" in there, which is clearly not there...

**Comment by E3V3A** [comment]
It's for turning on and off femtocell detection on Verizon CDMA networks... But we don't have much support for CDMA AFAIK.

**Comment by SecUpwN** [comment]
>It's for turning on and off femtocell detection on Verizon CDMA networks...

Ok, but I thought this is being done via the *checkbox* in `Preferences`?

**Comment by banjaxbanjo** [comment]
Femtocell tracking is enabled/disabled via the pref menu and the code is in the celltracker class that listens for preferences changes for this checkbox.


I dont think this is used for anything 
<string name="toggle_femtocell">Toggle Femtocell</string>


public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String key) { final String KEY_UI_ICONS = context.getString(R.string.pref_ui_icons_key); final String FEMTO_DETECTION = context.getString(R.string.pref_femto_detection_key); final String REFRESH = context.getString(R.string.pref_refresh_key); // Manual Refresh final String DB_VERSION = context.getString(R.string.pref_last_database_backup_version); final String OCID_KEY = context.getString(R.string.pref_ocid_key); if (key.equals(KEY_UI_ICONS)) { //Update Notification to display selected icon type setNotification(); } else if (key.equals(FEMTO_DETECTION)) { boolean trackFemtoPref = sharedPreferences.getBoolean(FEMTO_DETECTION, false); if (trackFemtoPref) { startTrackingFemto(); } else { stopTrackingFemto(); } } else if (key.equals(REFRESH)) { String refreshRate = sharedPreferences.getString(REFRESH, "1"); if (refreshRate.isEmpty()) { refreshRate = "1"; // Set default refresh rate to automatic "1", manual is "0". } int rate = Integer.parseInt(refreshRate); long t; switch (rate) { case 1: t = 15L; // Automatic refresh rate is 15 seconds break; default: t = (long) rate; break; } REFRESH_RATE = TimeUnit.SECONDS.toMillis(t); } else if (key.equals(DB_VERSION)) { LAST_DB_BACKUP_VERSION = sharedPreferences.getInt(DB_VERSION, 1); } else if (key.equals(OCID_KEY)) { getOcidKey(); } } public void getOcidKey() { final String OCID_KEY = context.getString(R.string.pref_ocid_key); OCID_API_KEY = prefs.getString(OCID_KEY, BuildConfig.OPEN_CELLID_API_KEY); if (OCID_API_KEY == null) { OCID_API_KEY = "NA"; // avoid null api key } }

**Comment by SecUpwN** [comment]
>I dont think this is used for anything.

Thanks for clarifying. I will remove this code then and close this Issue with the changes.

**Comment by SecUpwN** [comment]
>I dont think this is used for anything.

Thanks, @banjaxbanjo. So that means I can remove [this line](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/drawer/DrawerMenuActivityConfiguration.java#L143) and corresponding translations?

**Comment by banjaxbanjo** [comment]
@SecUpwN all that line does is add a cdma toggle button if the phone supports cdma. But the pref menu already controls cdma toggle option.
