### ISSUE TITLE
French legitim access points list

### ISSUE THREAD

**Issue by zguig52** [SecUpwN/Android-IMSI-Catcher-Detector#452]
Please find hereafter a datasource with french legitim access points (antennas/opertors/frequency plan):
http://www.cartoradio.fr/

It might be nice to integrate it in your datasources.

**Comment by E3V3A** [comment]
Thanks @zguig52 for tryingto help. But I think these should already be included into the OCID or MLS DBs. So what make you say this resource is better than those? Are you affiliated to that site?

**Comment by gusfl** [comment]
well,

>cartoradio.fr is a website managed by ANFR. (1)

I did a small comparison, and the results are really differents between OpenCellID and CartoRadio... For example, here are street in the center of Paris : 

![on CartoRadio](http://www.pixenli.com/images/1433/1433699388023172300.jpg)

![on OCID](http://www.pixenli.com/images/1433/1433697987011250200.jpg)

(yes, i promise you it's the same location ^^ )

Both of theses two map are, i think, wrong : 

- on cartoradio it's not BTS who are printed on the screen, but "location of transmition" (pylons/tower/etc.....). But you can click on a location to see what BTS is inside it.
- BTS who emit under 5W are not displayed on cartoradio

- However, OpenCellID map look wrong too...a BTS in the center of the Seine Sea, really? 

@zguig52 , i agree with you that we shoud really improve french BTS location, but i don't think it's a good idea to use cartoradio database (because it's directly linked to french governement).

>Also, another technical problem would be that cartoradio doesn't allow the export of the french >mobile operator behind a BTS. The purpose of it is to "avoid deployement strategy of operators at >national level"
> -- ANFR, Frequently asked questions

(1) ANFR : mean in french something like "National Frequency Agency". it's the government organisation who allow (or not) any radio transmitters (like BTS) to be online. In france, mobile operators must have an agreement of ANFR for each "location of transmission" they have.

**Comment by zguig52** [comment]
Hi guys,

I am not affiliated at all with this website or to the french government.

I use it for telecom engineering projects (bts coverage optim for example). All that i tried were right and properly referenced here.

I came with this suggestion because where I live (Fretin/59/north), I could not find any bts referenced on the map from imsi catcher. When you look at cartoradio, they are all there...

I don't see why being linked to government make this datasource bad as this is managed by french ITU (ANFR) who made this project to make sure all frech citizens have access to the list of activ EM sources (mainly due to health issues concerns first). As it is linked to emission permissions, this make it a good datasource for legal bts.

The export restriction might make it less usefull but it could be a way to have an error free datasource that can be combined with opencell data to make the operator name. If no operator is found then it might be a kind of added value to your soft to propose kind of open street map edition tool for opencellid, don't you think so? They might be unsure until validated by a human.

Guillaume

**Comment by E3V3A** [comment]
@gusfl Thanks for you detailed clarification! Yes, OCID data is unfortunately based on a mix of average signal measurements and exact BTS antenna locations. (Yes, you've understood this perfectly well. Antennas are not the same as a BTS, but for the purposes and simplicity of our project we refer to the exact antenna GPS points as `BTS`s. 

I also agree with @zguig52 that there is no reason not to include gov provided data. If *they* say there's an antenna there, it most likely is, contrary to what third party apps tell you. In either case this data should be part of MLS. Maybe the MLS [ichnaea](https://github.com/mozilla/ichnaea) developers can answer this:

@hannosch or @Gitschubser : 
> Does MLS contain the data from [cartoradio](http://www.cartoradio.fr/) ?

**Comment by SecUpwN** [comment]
@E3V3A, should the new external data sources look like this then?


```
( ) OCID only
( ) MLS only
( ) ANFR only
(o) OCID, MLS and ANFR
```

**Comment by hannosch** [comment]
@E3V3A I wasn't aware of cartoradio but had a look. Based on what I can tell, this site has the same problem as all the other similar sites from different countries. The underlying data does tell you about cell tower locations, and in this case even what operators are present at the cell site. But the data doesn't contain the unique logical cell ids we can observe from the phones, especially the location area / tracking area and cell id / cell identity codes. So there's no way to match this data to what can be observed from the phone.

The existing databases I could find are either about electronic frequency management (e.g. can an operator buy spectrum in the 800MHz band in an area), placement of towers from a "does this look good / fit into the neighborhoods building code" / radiation and health point of view or there are maps about internet speed or general broadband coverage, especially if there are subsidies available. None of them contain data about logical cell ids used for our purposes.

Similar sites I know about:
- Czech Republic: https://www.netmetr.cz/open-data.html
- Germany: http://emf3.bundesnetzagentur.de/karte/Default.aspx
- Austria: http://www.senderkataster.at/karte
- US: http://wireless.fcc.gov/uls/index.htm?job=transaction&page=weekly

**Comment by SecUpwN** [comment]
>But the data doesn't contain the unique logical cell ids we can observe from the phones, especially the location area / tracking area and cell id / cell identity codes. So there's no way to match this data to what can be observed from the phone.

Thanks for your thorough look at these, @hannosch. Does that mean that CartoRadio as well as all the other listed in your post above cannot be used for our purposes to verify if a malicious BTS has been planted or not (please correct me if I'm wrong here)? OCID and MLS will be the way to go, I guess.

**Comment by hannosch** [comment]
@SecUpwN yep, these sites only tell you that there is a cell tower at lat/lon. If you are near it, you cannot tell from the phone if you indeed see that specific tower, as you don't have any unique id shared between those databases and what you can observe from the phone.

**Comment by SecUpwN** [comment]
>If you are near it, you cannot tell from the phone if you indeed see that specific tower, as you don't have any unique id shared between those databases and what you can observe from the phone.

That makes sense and is indeed not what we need. Any other databases we should be looking at?

**Comment by hannosch** [comment]
None of the others have any significant size. I have a listing over at https://wiki.mozilla.org/CloudServices/Location/DataSources which points to the relevant wikipedia pages as well. I think openbmap now known as http://radiocells.org/ is the only other actually active project.

**Comment by gusfl** [comment]
>But the data doesn't contain the unique logical cell ids we can observe from the phones, especially >the location area / tracking area and cell id / cell identity codes. So there's no way to match this data >to what can be observed from the phone.

Uuh ?....A french website called www.antennesmobiles.fr show Cell ID, and this website is based on cartoradio database....Are you sure of what you say?

**Comment by hannosch** [comment]
@gusfl I don't see the cell ids we need there either? Can you be more specific and give me an example of what you mean by cell id?

**Comment by SecUpwN** [comment]
>I think openbmap now known as http://radiocells.org/ is the only other actually active project.

@hannosch, I guess those have already been added in MLS, or am I mistaken?

**Comment by hannosch** [comment]
@SecUpwN The data is not integrated into MLS, we track that over at mozilla/ichnaea#401 - so far they have data from primarily Europe, where both OCID and our own data is also really strong, so there's very little unique new data there. Wasn't worth the effort so far, but I'm keeping an eye on them.

**Comment by ph0t0n** [comment]
this is unfortunately also the case with the FCC data that governs US cell towers, as far as I know. even if you could get fast search access to the data, you would only find spectrum allocation information, not cell operating parameters like cell ID. maybe you could potentially confirm a site is running, say, USA Band 850MHz GSM, USA UMTS, etc. 

also, i dont know if this is common in other areas, but in US there are many sub-lease sub-owner etc portions of tower locations so you can't always have an easy match between the SIM company name and the cell site information.

**Comment by SecUpwN** [comment]
>Wasn't worth the effort so far, but I'm keeping an eye on them.

@hannosch, thanks for clarifying. Let us know once this project comes to a point where adding their data (or you pull it in) makes a difference. Issue solved for now, feel free to re-open if you disagree.
