### ISSUE TITLE
Make Buildozer versions concide with app info display

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#453]
It's an annoying fact the the automatic development builds made by our [Buildozer](https://buildozer.io/) engine, doesn't coincide with the version that is shown in the app under `About AIMSICD`. I would very much like to see these version number coincide. That should also be true for the non-debug GitHub releases.

This issue is closely related to #147, but that info is outdated in light of this one. Once resolved, we can close both. I've labelled this as a "bug" to prioritize it over other general enhancements.

**Comment by SecUpwN** [comment]
>It's an annoying fact the the automatic development builds made by our Buildozer engine, doesn't coincide with the version that is shown in the app under `About AIMSICD`.

Why is that "annoying" to you, @E3V3A? Those builds are just for us, just install the latest one? As far as I know there is also no way of making @Buildozer rename the app version when building it. As well, I simply don't see the huge enhancement neither from this Issue, nor from solving #147. Convince me?

If you ask me, we can remove all code for both, I prefer changing these things by hand and releasing manually. It simply makes more trouble for me than take away pressure. @He3556 what do you think?

**Comment by E3V3A** [comment]
Well, so if I tell you that the *latest* Buildozer build, not only crashes, but also locks up phone, when leakanary fails, then you will know exactly what build version and related PR's was causing this crash, right? Anyway, I see the issue, if Buildozer hasn't integrated their version in the gradle API or whatever they use.

**Comment by SecUpwN** [comment]
>Once resolved, we can close both. I've labelled this as a "bug" to prioritize it over other general enhancements.

I have just had a nice talk via E-Mail with the folks at @Buildozer and here is what they mentioned:

>There is an environment variable called BUILDOZER_BUILDNUMBER. you can use it in your scripts to put the number in a place of your choosing. If at just to be able to see what build someone has installed you could also imprint the build number on the app icon. That's a matter of checking a box in the build settings session.

Here is what I also asked them about my prefered display:

>Please have a look at the [About-screen](https://spideroak.com/share/IFEU2U2JINCA/GitHub/home/SecUpwN/SpiderOak/SCREENSHOTS/About.png). How can we add automatically add the line BUILDOZER BUILD xxx (automatic number) below the usual (red) version information and ONLY add it, when the builds have been crafted by Buildozer? When compiled via normal Android Studio, that line should not be printed and just get ignored.

They explictly said that this is in fact possible by:

The starting points would be:

* using an environment variable inside a gradle build phase
* using gradle to adjust one of your Java files pre-build

Will update this Issue when I receive mire hints. Maybe our awesome @DJaeger can also monitor this Issue (please don't overwork yourself on our repo)? Hope we can clean up our messy [build.gradle](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/build.gradle) soon.

**Comment by E3V3A** [comment]
Great! If they could only provide some example scripts, that would help even more...

**Comment by SecUpwN** [comment]
>Great! If they could only provide some example scripts, that would help even more...

I just found [this interesting GitHub Gist](https://gist.github.com/ijansch/187845faf6aea780fb99). Maybe @ijansch can guide us a bit?

**Comment by ijansch** [comment]
The gist is the equivalent for iOS. I'll see if I can create one for android as well.

**Comment by SecUpwN** [comment]
Thanks! The question is, how to change our [AndroidManifest.xml](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/AndroidManifest.xml)? Would the following work?

```JAVA
 android:versionCode="30"
android:versionName="0.1.30-alpha-b06">
android:BUILDOZER="BUILDOZER_BUILDNUMBER"
```

The `BUOLDOZER_BUILDNUMBER` shall not get added when compiliung with Android Studio or else.

**Comment by SecUpwN** [comment]
Thanks for your hard work on this, @DJaeger! It now looks like it should, but will the Buildozer Buildnumber also *not* be shown when compiling with Android Studio or other ways?

@E3V3A, I suggest that we remove [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/build.gradle#L95-L125) from our [build.gradle](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/build.gradle). Do you agree?

**Comment by DJaeger** [comment]
If not build from Buildozer the environment variable should be null, then the build variable is set to NA.
If the build variable is NA the text view is gone.

**Comment by SecUpwN** [comment]
>If not build from Buildozer the environment variable should be null, then the build variable is set to NA.
If the build variable is NA the text view is gone.

You truly rock. Issue solved, thanks for hacking like a hardcore freak! :smile_cat:

**Comment by E3V3A** [comment]
Sure sound good...
