### ISSUE TITLE
Debug build: Leak analysis failed

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#455]
For some reason I get the device message "`Leak analysis failed`" coming from the [leakcanary](https://github.com/square/leakcanary) debug APK (as included in our Buildozer debug builds). I have no idea what causes this...and have filed an issue at their repo in [176](https://github.com/square/leakcanary/issues/176).

Perhaps @square from *leakcanary* developers can help?

This is the error message I get:
```
In com.SecUpwN.AIMSICD:0.1.29-alpha-b01:29.
* FAILURE:
org.eclipse.mat.SnapshotException: SnapshotImpl_Error_ObjectNotFound
at org.eclipse.mat.parser.internal.SnapshotImpl.mapAddressToId(SnapshotImpl.java:1194)
at org.eclipse.mat.snapshot.model.ObjectReference.getObjectId(ObjectReference.java:38)
at org.eclipse.mat.snapshot.model.ObjectReference.getObject(ObjectReference.java:42)
at org.eclipse.mat.parser.model.AbstractObjectImpl.resolveValue(AbstractObjectImpl.java:149)
at com.squareup.leakcanary.HeapAnalyzer.findLeakingReference(HeapAnalyzer.java:161)
at com.squareup.leakcanary.HeapAnalyzer.checkForLeak(HeapAnalyzer.java:95)
at com.squareup.leakcanary.internal.HeapAnalyzerService.onHandleIntent(HeapAnalyzerService.java:57)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.os.HandlerThread.run(HandlerThread.java:60)

* Reference Key: d86f9d6c-XXXX-XXXX-XXXX-dbf6903b908f
* Device: samsung samsung GT-I9195 serranoltexx
* Android Version: 4.2.2 API: 17 LeakCanary: 1.3.1
* Durations: watch=5519ms, gc=277ms, heap dump=1667ms, analysis=65386ms

```

**Comment by SecUpwN** [comment]
> I have no idea what causes this...and have filed an issue at their repo in ...

@E3V3A, if you have done so, please link the Issue you filed in your OP so that we can track it here.

**Comment by E3V3A** [comment]
I wonder if it has something to do with [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/443#issuecomment-109033182) comment?

**Comment by SecUpwN** [comment]
I have digged through their Issue list and it seems the part with `SnapshotImpl_Error_ObjectNotFound` has been filed numerous times. Digging further, I found https://github.com/square/leakcanary/issues/157 referenced as to be the "solution" to this sort of Issue. Does that apply to us as well?

**Comment by E3V3A** [comment]
@SecUpwN  Please try ask a specific since (in my experience) generally addressed questions are even less likely to be answered,

**Comment by SecUpwN** [comment]
>Please try to ask a specific person since (in my experience) generally addressed questions are even less likely to be answered

Thanks for the hint, but actually I already follow that very "rule". Waiting for answer of https://github.com/square/leakcanary/issues/157#issuecomment-110961642.

**Comment by E3V3A** [comment]
Consider removing leakcanary, since nobody is using it and it creates huge 11 MB coredumps...

**Comment by SecUpwN** [comment]
>Consider removing leakcanary, since nobody is using it, bugs are ignored, and it creates huge 11 MB core-dumps...

The ore problem goes a little deeper: We need to rethink the way we handle errors and preferrably use some service that makes it easy to track and eliminate these. We currently have too many services:

* CoverityScan
* LeakCanary
* Logfile via E-Mail

None of these actually help our developers. If anybody of our more experienced developers thinking of @tobykurien, @DimaKoz and @banjaxbanjo for example) know of a service that covers all that and would enhance development drastically by automatically collecting and analyzing *valuable* data and bug reports, I'd be more than open to rethink and reprogram all the stuff that we currently use.

**Comment by agilob** [comment]
>We need to rethink the way we handle errors and preferrably use some service that makes it easy to track and eliminate these.

I used ACRA and it was pretty good for my needs, you can find example report from [my project here](http://agilob.net/projects/ss/2015-05-04_19-36-34.txt). It's not full report, some data were removed. It's disadvantage: it's considered as anti-feature by f-droid and (afaik) fdroid team tends to remove acra from projects. Advantage: it's very small, gives detailed report, it's easy to extend its features, has big communities.

**Comment by SecUpwN** [comment]
>It's disadvantage: it's considered as anti-feature by f-droid and (afaik) fdroid team tends to remove acra from projects.

Thanks for actually recommending *something*, @agilob. I really do get tired of receiving bug reports via E-Mail from people who do not actually care reading our WIKI or how to correctly report bugs. We **need** to make this bug report stuff **idiot-proof** aka "push this button and done". Regarding ACRA: I guess it might not be a great solution to implement something that F-Droid will complain about. People using F-Droid are *very* privacy-aware and we'll be run over again by questions why we did this and that. I'd prefer some other open source, privacy-aware and F-Droid friendly solution.

**Comment by agilob** [comment]
ACRA is opensource, so it can be included in a build. It's an antifeature, so it's no always removed, but the application gets new red label 'it might be tracking you'. ACRA is 100% idiot proof. It sends crash reports to online server or via email. User doesn't even know about it.

**Comment by SecUpwN** [comment]
>ACRA is 100% idiot proof. It sends crash reports to online server or via email. User doesn't even know about it.

Would like to hear @E3V3A and possibly @DJaeger on this. On one hand we had decided to make our app communicate as less as possible with other servers, on the other hand though, I'd like developers to actually *use* our bug reports to be able to *fix* stuff, not just to give emotional advice (that's what I'm currently doing with all the bug reports travelling in). Also, if we're going to implement a new solution, we should make damn sure that at least 4 to 5 people can actually care about bug logs traveling in - what's currently going on with our CoverityScan is a real bad example. Stuff is piling. :(

**Comment by DJaeger** [comment]
I think a lib which will cause an anti-feature prompted on F-Droid, especially that it could spy you, is a nogo.
Someone who wants to use this app to detect spying won't use a app that has this anti-feature.
I like the solution used for example by Firefox and OsmAnd, where a promt is shown after a crash (at least on next start) that asks to send a bug report.
This could be done like Firefox without using your one mail address or by opening a new mail with prefilled content.

**Comment by SecUpwN** [comment]
>I think a lib which will cause an anti-feature prompted on F-Droid, especially that it could spy you, is a nogo. Someone who wants to use this app to detect spying won't use a app that has this anti-feature.

Fully agree on that, I'd avoid any apps with such a warning as well.

>I like the solution used for example by Firefox and OsmAnd, where a promt is shown after a crash (at least on next start) that asks to send a bug report.

Makes perfect sense to me, but let#s hear what the others have to say about that.

>This could be done like Firefox without using your one mail address or by opening a new mail with prefilled content.

How can this be done without using our email adresses? A unfied bug collection system (which preferrably integrates with GitHub logins) would be nice. And of course we'd need people look at it.

**Comment by DJaeger** [comment]
>>This could be done like Firefox without using your one mail address or
>by opening a new mail with prefilled content.
>
>How can this be done without using our email adresses? A unfied bug
>collection system (which preferrably integrates with GitHub logins)
>would be nice. And of course we'd need people look at it.

I mean any solution, that doesn't require the user to populate anything about him/her.
Either send a mail by the app internaly or upload it so somewhere.
The problem for uploading is, it should be a solution without credentials or API keys, as we should prevent to write them into souce codes (which is required for a F-Droid build) and for mail we have to write the mail adresse to souces.

**Comment by SecUpwN** [comment]
>Either send a mail by the app internaly or upload it so somewhere.

Our app is already able to submit debugging logs to *me*, but I might be the wrong person looking at them. Currently, my email is hard-coded into our source code, not sure if that is the best solution. Want to take my part? ;-) Back to **this Issue**: Is this a problem with *our* code or the one from @square?

**Comment by E3V3A** [comment]
Too much work without any ROI. 

> It sends crash reports to online server or via email. User doesn't even know about it.

That's a **no go**, IMHO.

**Comment by SecUpwN** [comment]
@E3V3A, I have just written a personal message to @pyricau to clear up the core solution to this Issue since if you look at the [leakcanary Issue tracker](https://github.com/square/leakcanary/issues), we're not the only people reporting this.

**Comment by DJaeger** [comment]
For now we should comment out leakcanary, to not create more noise in logs than created by this app itself.
See https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/506

**Comment by E3V3A** [comment]
Yes, no code removal ,just comment out for now.  Can you make a PR for that?

**Comment by DJaeger** [comment]
Already done.
See linked PR in last comment.

**Comment by SecUpwN** [comment]
>Already done.

Thanks for your superquick work on our repo, @DJaeger! I am continuing to monitor what will be happen to https://github.com/square/leakcanary/issues/157#issuecomment-115072058 and if that actually solves this Issue as well.

**Comment by E3V3A** [comment]
closing until further notice or re-implementing leakcanary.

**Comment by SecUpwN** [comment]
Monitoring https://github.com/square/leakcanary/issues/110 and aiming to re-implement `leakcanary` after their fix.

**Comment by SecUpwN** [comment]
@E3V3A, this Issue and related errors around `SnapshotException: SnapshotImpl_Error_ObjectNotFound` should have been fixed with https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/455. Shall I re-add `leakcanary` now?

**Comment by E3V3A** [comment]
I hate leakcanary and really don't wanna see it back in here, confusing all the users and new developers, who would still remain clueless what to do about it.

**Comment by DJaeger** [comment]
I would leave it out too.
I see no adventage of it over the already available debugging 
possibillities.

-- 

Mit freundlichen Güßen

Daniel Jäger

**Comment by pyricau** [comment]
Not sure how I ended up following this conversation. Unsubscribe.
