### ISSUE TITLE
Repository history was force modified?

### ISSUE THREAD

**Issue by smarek** [SecUpwN/Android-IMSI-Catcher-Detector#456]
Hello,

I've after quite a time wanted to get my local AIMSICD repository to sync, and I've got this strange information:

```
On branch master
Your branch and 'origin/master' have diverged,
and have 890 and 1262 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working directory clean
```

Which probably means, you've force pushed into repository since I've downloaded it last time.
My last local commit in master is
```
commit a70e6d77992bab1afdec749cbd1c6a411d43d5cd
Author: SecUpwN <perfect-privacy@secure-mail.biz>
Date:   Thu Jan 29 20:17:54 2015 +0100

    Added GERMAN public notice - display it everywhere!
```

Also I've found #371 ticket, is this the cause?
I'm a bit worried about what happened to the repository, since the difference is so big.
Thank you

**Comment by SecUpwN** [comment]
Welcome back, @smarek! Please don't worry. You are absolutely right, I have cleaned our repository twice: The first time with #213 and then again with #371. We now have a much smaller repo size and only data needed to work on our app will be downloaded, which is much more developer friendly. Please **delete** your old fork and re-fork our project. Sorry for the inconvenience, we have learned from all this.
