### ISSUE TITLE
Translations: Service to track updates on GitHub?

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#460]
While working on #450 I noticed that we'll likely run into more complaints when not making sure that all translations get updated regularly. Users in other countries with outdated translations will likely have a hard time with our app, especially when string and code changes like in #450 took place.

**Solution:** Unless we have found some hardcore maintainers checking each day if changes have been made to our [main strings file](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/values/translatable_strings.xml) (which is very unlikely), we should find a service that can:

* Monitor if any strings have been changed on our [main strings file](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/values/translatable_strings.xml)
* Highlight on their website which strings on the other translation files need to be updated on GitHub

**NOTE:** I want to *avoid* managing our translations externally. Means, all translation files shall *stay in our repository*, yet an external service should show differences and possibly notify translators. Maybe having another look at #190 helps us finding such thing? Other suggestions how to handle this are welcome.

@DimaKoz, @agilob and @ph0t0n, please add your opinion here. You may have seen that our main strings file has received a huge number of changes and now you're in the heavy mess I described. Would proposed service make your life easier, or do you have a smarter way of tracking the changes?

**Comment by ph0t0n** [comment]
that is an interesting question. i don't have an answer off the top of my head but i will look at some other android projects/devs to see how they handle this. even if we had professional translators keeping the code and meanings in sync is an issue.

**Comment by agilob** [comment]
F-Droid client uses this https://translatewiki.net/wiki/Special:MainPage but I've never tried it

**Comment by SecUpwN** [comment]
>even if we had professional translators keeping the code and meanings in sync is an issue.

@ph0t0n, you are perfectly right. With https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/190#issuecomment-93831199 we found that our app shall start up in the system default language the user has set and we also saw the potential that everyone can add their translations on GitHub. However, since our app is getting more complex and translation files currently differ heavily from each other both in style and translations, I guess it would be better to switch to one of the services mentioned in #190, preferably one where only the GitHub account is needed to log in.

**Comment by ph0t0n** [comment]
@SecUpwN sorry, i had forgotten about this but just asked a pool of android developers i know to see what their best practices are. 

also if we have any strings files that are burning for updates right now pls point them out, i know quite a few coworkers with en<->{language} fluency and in the technical domain. i can probably get help if i bribe them with cerveza/cerveja/Bier/пиво/etc.

**Comment by SecUpwN** [comment]
>sorry, i had forgotten about this but just asked a pool of android developers i know to see what their best practices are.

Thanks for doing so, I've done the same, let's see what the best solution will be. Ideal service case:

* Free for open source projects (preferably with support for Android developers in case of Issues)
* Easy way to login with GitHub (no additional signups required, people hate having 1000 accounts)
* Easy way to translate [main file](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/raw/development/app/src/main/res/values/translatable_strings.xml) - when it changes, translators should be notified (via GitHub)
* Automatic pull request to `development` branch when translation for a language has been confirmed

>also if we have any strings files that are burning for updates right now pls point them out

This is a moving project, everything is burning, always. ;-) Let's find such a funky service for this first.

**Comment by E3V3A** [comment]
If you use **Weblate** make sure to hit the `SAVE` button after translating **each word**, otherwise it's not saved.

**Comment by SecUpwN** [comment]
Thanks @E3V3A, I realized that. ;-) Takes a while to get used to their system, but I like it.
