### ISSUE TITLE
DB viewer: Measured Signal Strengths broken

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#462]
Problem: The `Measured Signal Strengths` table is not updated in the DB viewer, and showing an RSS of 268435455 (**0xFFF FFFF**). This used to work very good... Please confirm this is a non-network (roaming) related bug.

**Comment by He3556** [comment]
It looks ok on my side. 

![screenshot_sign-strength copy](https://cloud.githubusercontent.com/assets/2507905/8140450/e14032e4-115b-11e5-8841-c8baca143472.jpg)

**Comment by He3556** [comment]
this measurement shows the same Cell with 11dBm, 5dBm and 8dBm. 
it's a high variability, somehow 

![screenshot_sign-strength copy2](https://cloud.githubusercontent.com/assets/2507905/8140675/139f3e72-115e-11e5-975b-17422e7a2e5c.jpg)

**Comment by SecUpwN** [comment]
@E3V3A, please test again with the latest APK. It always works on my device.

**Comment by E3V3A** [comment]
Hmm, indeed it does seem to work now... However, it seem to require a GPS lock to work...which is OK.
