### ISSUE TITLE
SMS Detection: Endless detection of same SMS

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#463]
@E3V3A already [explained](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/69#issuecomment-110620021) that in its current behavior, our silent SMS detection implemented via #69 does not clear the logcat buffer before application exit to avoid a possible side-effect on other detections.

Nevertheless, this bug is really annoying since a user will think that he is being tracked every few seconds: The same detected SMS will reappear in the `Database Viewer` and pile up there, generating a new event (and new timestamp) each time. I have described the steps to reproduce this Issue [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/69#issuecomment-110363051).

**To reproduce bug:**
1. Send a silent SMS via `HushSMS` or alike
2. Wait until `AIMSICD` alerts the receival
3. Exit `AIMSICD` and then open it again
4. Silent SMS Detection starts again.. and piles the detected silent SMS again in the Database Viewer

**Comment by E3V3A** [comment]
@banjaxbanjo 

> This will also help with other detection methods like if we recieve an sms acknowledged in buffer and didn't receive in the sms broadcast receiver then it would indicate some sort of silent sms.  If the logcat timestamp remains the same for each line everytime we access buffer then this method would be possible. At the moment I programmatically create one when sms spotted in logcat.

Yes, programatically is effective, but not working, and the alternative is a little more process intensive as it requires running another reg-ex on the logcat to get the timestamp. No problem there, as I have already done this [here](https://github.com/E3V3A/CounterCat/blob/master/catch0sms.sh#L106-L109):

```bash
# When using 'logcat -d -v time -b radio'
# Grab the logcat timestamp and convert to normalized SQL timestamp:
# '07-15 05:57:02.075 D/RILJ ...' ==>
# '2015-01-13 21:42:45'
alias grabts='sed -E "s/^(.+)/2015\-\1/" |sed -E "s/([0-9]{2})\.[0-9]{3}/\1/" | sed -E "s/(^.+[0-9]{2}:[0-9]{2}) .+/\1/"'
```

However, this may not look the same on all devices.

**Comment by banjaxbanjo** [comment]
The -v time should be enough @E3V3A  would it be better to do the refactoring by java code so not to cause any issue if sed is not installed?

If I split the string to an array using (SPACE) as the spilt character then the timestamp can be easily created.

original = '07-15 05:57:02.075 D/RILJ ...' ==>
dummyarray[] {07-15,                 <---- index 0
            05:57:02.075,                 <---- index 1
            D/RILJ,
            etc,etc}
String timestamp = "2015"+dummyarray[0]+dummyarray[1];

we can remove chars that we don't need from timestamp then with replace.

This wont be process intensive because its only called when we need to create a timestamp.

**Comment by E3V3A** [comment]
Perfect!
