### ISSUE TITLE
Dev b137 crashes upon start

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#469]
Accept pop-up screen shows twice, then FC. 

It also fails on Travis-CI with:
```
com.SecUpwN.AIMSICD.test.Detection1 > testAndroidTestCaseSetupProperly[test(AVD) - 4.2.2] FAILED 
	android.database.sqlite.SQLiteException: table opencellid has no column named latitude (code 1): , 
while compiling: CREATE INDEX OpenCellID_spatial ON opencellid (latitude, longitude);
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
```

**Comment by SecUpwN** [comment]
@E3V3A, I cannot confirm this, works perfectly for me. @wvengen can you have a look at this, please?

**Comment by E3V3A** [comment]
Please fix or revert PR. perhaps an API version problem?

**Comment by SecUpwN** [comment]
>Please fix or revert PR. Perhaps an API version problem?

@E3V3A, I will have a closer look later tonight. Hoping that @wvengen and @banjaxbanjo help us.

**Comment by SecUpwN** [comment]
>Please fix or revert PR. Perhaps an API version problem?

@E3V3A, I have had a closer look. The error log you posted in your OP and especially [these lines](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector#L1799-L1805) tell us that `table opencellid has no column named latitude (code 1)` in [Detection1.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/androidTest/java/com/SecUpwN/AIMSICD/test/Detection1.java). I expect this to be caused by the latest additions of @wvengen. The question is now: Where exactly do we need to add the missing column?

**Comment by marvinmarnold** [comment]
Is it just a matter of changing [this] (https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/16f04466d383c437909f9aa701b0316f0ca10000/app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java#L1410) & [this] (https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/16f04466d383c437909f9aa701b0316f0ca10000/app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java#L1619) (latitude, longitude) => (Lat, Lng)? That seems to fix it on my end.

**Comment by E3V3A** [comment]
@marvinmarnold Can you make PR for that?

**Comment by SecUpwN** [comment]
>That seems to fix it on my end.

Thanks for your helpful anlysis, @marvinmarnold!

>Then let's see what Travis says...

Travis CI seems happy again. Fixed for you, @E3V3A?

**Comment by agilob** [comment]
@secupwn you can close issues with [commit message](https://github.com/blog/1386-closing-issues-via-commit-messages)

**Comment by E3V3A** [comment]
@agilob we already do this, but we try to verify fixes before closing. Thanks for info.

**Comment by E3V3A** [comment]
@agilob we already do this, but we try to verify fixes before closing. Thanks for info.
