### ISSUE TITLE
Notification: Always display colored Status Icons

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#479]
I am currently testing Android 5.1.1 and my first impression is: Google, I *don't* like what you've done. But if you are like me and love to tinker with bleeding edge software and apps, you might love it. Issue: Our app displays the important Status Icons in a **tiny** and **whitish style**, likely automatically introduced by Material Design of the ROM (also related to #161). Thus, the core function of these Status Icons is gone.

![we](https://cloud.githubusercontent.com/assets/6000299/8225141/6e8a5422-1580-11e5-836f-6ab5d7f02b8a.png)

Since we have decided to not ride the wave of recoding everything for kindergarten Material Design, the best way to solve this Issue is to change our code in a way that enables the **color** of the Status Icons to be shown at all time. Other apps, such as [Trust](https://github.com/d4rken/trust) by @d4rken already accomplish that beautifully.

![trust](https://cloud.githubusercontent.com/assets/6000299/8225145/7ee057fe-1580-11e5-99e2-6f726169a822.png)

Maybe @d4rken can give us a hint on what needs to be changed so that our Status Icons will be displayed consistently in **color** even when Google should decide to craft another crazy OS design?

Even @Avast is doing it the way I'd prefer our app to display its beauty.

![avast](https://cloud.githubusercontent.com/assets/6000299/8225152/9b9664ba-1580-11e5-90a1-842b36e3836a.png)

**Comment by DJaeger** [comment]
I had written a long comment, which got because of device shutdown.
So again:
You can set two diffent icons for notifications.
A small icon (`setSmallIcon`) and a large icon (`setLargeIcon`).
The small icon is used for the statusbar, where you also find battery state and signal strenght.
The large icon is used for the notifications in opened (pulled down) list.
If only `setSmallIcon` is used this icon is shown on both places.
The documentation says that the icon in statusbar has to be white, which is ignored by the system except it is themed.
Lollipop (Android 5) takes care of this and makes it white by itself.
If one icon is defined for both, it seems it is white at both places.
So by defining different icons with `setSmallIcon` and also `setLargeIcon` you can set a full colored icon for notification list and a white icon for statusbar.

You should add "real" white icons out of the "white_" icons by making the transparent parts inside white and removing all other outsite.
Name them ic_stat_ as the naming convention says.
You could rename your Icon util method from `getIcon` to `getSmallIcon` and create a new method named `getLargeIcon` which only switches on `Status.getStatus()`.
With that you can use for example flat_ok for setLargeIcon and ic_stat_ok for setSmallIcon.

**Comment by ph0t0n** [comment]
i am running android 5.1.1 on nexus 

if AIMSICD status == yellow,  (flat_medium.png ?)
then...

if my phone is unlocked, in the top screen status bar I DO see yellow icon

if my phone is UNLOCKED and I pull down the notification list, in notification list I DO see yellow icon

if my phone is LOCKED, and I pull down notification list (set to private details) I DO NOT see the yellow icon.  I see the white icon (flat_idle.png?)

my configuration has AIMSICD running, but service set to off.

I can tell that android OS has not killed the AIMSICD activity because AIMSICD's GPS usage is causing GPS Status to produce its own notification.

hope this helps to confirm

**Comment by ph0t0n** [comment]
actually, correction. sometimes my phone, when AIMSICD status==yellow, and phone was just woken from screen sleep, the locked notification list shows the green icon.

it varies

**Comment by DJaeger** [comment]
Before looking why it differs from time to time the icon should be set as the doku says, that we don't search for an issue caused by bad behavier of Lillipop to make the icons white.

**Comment by DJaeger** [comment]
On making icons white they have to be changed, that the state could be determined without color

**Comment by SecUpwN** [comment]
Thank you for your extensive explanations here, @DJaeger.

>Lollipop (Android 5) takes care of this and makes it white by itself.

How to effectively override the automatic whiteness and make our Icon full color in all places?

**Comment by DJaeger** [comment]
>Not since Lollipop. Starting with Android 5.0, the guidelines say:
>
>>    Notification icons must be entirely white.
>
>Even if they're not, the system will only consider the alpha channel of your icon, rendering them white
>**Workaround**
>
>The only way to have a coloured icon on Lollipop is to lower your targetSdkVersion to values <21, but I think you would do better to follow the guidelines and use white icons only.
>
>If you still however decide you want colored icons, you could use the DrawableCompat.setTint >method from the new v4 support library.

Source:
http://stackoverflow.com/questions/30075827/android-statusbar-icons-color

**Comment by SecUpwN** [comment]
Thanks, that help a lot, @DJaeger.

>If you still however decide you want colored icons, you could use the DrawableCompat.setTint method from the new v4 support library.

Question at @He3556 and @E3V3A, shall we use the [DrawableCompat.setTint](https://developer.android.com/reference/android/support/v4/graphics/drawable/DrawableCompat.html) method?

**Comment by E3V3A** [comment]
I have no idea what that means, or if it resolves the issue.

**Comment by SecUpwN** [comment]
>I have no idea what that means, or if it resolves the issue.

With the [DrawableCompat.setTint](https://developer.android.com/reference/android/support/v4/graphics/drawable/DrawableCompat.html) method we can override the automatic whitening in Android  5+.

>If you still however decide you want colored icons, you could use the DrawableCompat.setTint method from the new v4 support library.

**Comment by Ph1b** [comment]
The drawable.setTint tints the whole icon in a different color. It is supposed to be white as it is the small icon. 

For a colorous icon, one has to set the icon as a large icon.

**Comment by SecUpwN** [comment]
Thanks to the work of @Ph1b, Android 5+ does now display our Status-Icons like this:

![largestatus](https://cloud.githubusercontent.com/assets/6000299/8511683/0afdfaf8-2313-11e5-8415-34ef2a9305e6.png)

The only thing left for closing this Issue would be to colorize the small Icon on the very left well.

![notificationbar](https://cloud.githubusercontent.com/assets/6000299/8511684/139ae0c2-2313-11e5-975e-831e4cacd170.png)

**Comment by E3V3A** [comment]
Yeah, I wonder how those other apps do it...

**Comment by E3V3A** [comment]
Maybe @d4rken can help us make this colored?

**Comment by SecUpwN** [comment]
>Yeah, I wonder how those other apps do it...

@E3V3A, did you really implement all necessary changes from #527? I suspect that `setSmallIcon` might need an update. As for finding out what we further need to change, we should search the source of a real "materialized" app with a colorized small icon.

**Comment by DJaeger** [comment]
It's what I telled you...
The page @Ph1b referenced to in his mail says exactly the same as I said:
>Do
>
>Use the proper notification icon style for small icons, and the Material Light action bar icon style for your action icons.
>
>Do
>
>Keep your icons visually simple, avoiding excessive detail that is hard to discern.
>
>Don't
>
>Place any additional alpha (dimming or fading) into your small icons and action icons; they can have anti-aliased edges, but because Android uses these icons as masks (that is, only the alpha channel is used), the image should generally be drawn at full opacity.
>
>Don't
>
>Use color to distinguish your app from others. Notification icons should only be a white-on-transparent background image.

The way of setting a small and a large icon to keep the large icon colored and only let the small one be whitened by L is also what I have said.

**Comment by SecUpwN** [comment]
>The way of setting a small and a large icon to keep the large icon colored and only let the small one be whitened by L is also what I have said.

Thanks for chiming in again @DJaeger. Would you *please* help us fixing the small Icon to be colored as well? If you say that we can't use [our regular app icon](https://raw.githubusercontent.com/SecUpwN/Android-IMSI-Catcher-Detector/HEAD/app/src/main/res/drawable-xxxhdpi/sense_danger.png) for this (if it has dimming as you said), maybe we can use the [flat version](https://raw.githubusercontent.com/SecUpwN/Android-IMSI-Catcher-Detector/HEAD/app/src/main/res/drawable-xxxhdpi/flat_danger.png)?

**Comment by d4rken** [comment]
I would guess "Trust" still has the colored icon because it uses the now deprecated "Notification" object directly instead of the "Notification.Builder" object. Possibly look into the sourcecode of the original and the builder notification object to see how they differ.

**Comment by E3V3A** [comment]
Hello @d4rken! Thanks for getting back to us. Could you please send a link in which file of your repo, we should look at?

**Comment by d4rken** [comment]
@E3V3A https://github.com/d4rken/trust/blob/master/app/src/main/java/eu/thedarken/trust/TrustService.java#L73
The difference i see is Notification vs Notification.Builder, so would say look at the AOSP sourcecode for what the builder object does differently.
But I'm not sure this is the correct approach, in the future Google may break this too and completely enforce icons that fit the ROM style. So the icons should be replaced with recognizeable shapes and if an important change happens, an overlayed notification could shortly appear to make the user aware of the change.

**Comment by SecUpwN** [comment]
>But I'm not sure this is the correct approach, in the future Google may break this too and completely enforce icons that fit the ROM style.

It's not like Google is enforcing users to sniff its ass, right? Because, that's how I feel like...

> So the icons should be replaced with recognizeable shapes and if an important change happens, an overlayed notification could shortly appear to make the user aware of the change.

@E3V3A, our designer @SgtObst is already designing the Icons for #512. I really love our current Icons, but if you say that we'd need to completely replace them with some shaped ones, let me know.

**Comment by E3V3A** [comment]
@SecUpwN  Something inside me just want to refuse. Why should we yield for the tastless Google design mafia? I say no, we keep the colors! If someone wanna add shapes (what fucking shapes?), go ahead and put it in the UI settings as an option.

**Comment by SecUpwN** [comment]
>Something inside me just want to refuse. Why should we yield for the tastless Google design mafia?

It's times like these where I really enjoy your hardcore stand. **Thank you so much for this!**

> I say no, **we keep the colors!**

Perfectly fine with me! Ok, so let's work on implementing the last thing to solve this:

![NotificationBar](https://cloud.githubusercontent.com/assets/6000299/8511684/139ae0c2-2313-11e5-975e-831e4cacd170.png)

In this screenshot of the notification bar, the Trust app is clearly shown in color. This might very well be due to to the differences explained in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/479#issuecomment-118668412. Can we change to the deprecated `notification` object instead of the `Notification.Builder` object or make our app detect if is being used on Android 5+ and *then* use it?

**Comment by E3V3A** [comment]
> Can we change to the deprecated Notification object instead of the Notification.Builder object or would that introduce more hassle in the future?

**It will work fine until** the next developer come around and try to outwit what we've created and making a huge PR saying "Hey, guys I've refactored your code and cleaned it up from lots of unused stuff!" and you going "Thanks dude! I'll merge ASAP!". (Sound familiar?) 

Being slightly ironic here, but that's exactly what happened to the apparently broken Neighboring cell detection, the introduction LACELLS DB and the old galaxy neighboring cells info...

**Comment by SecUpwN** [comment]
>Being slightly ironic here, but that's exactly what happened...

@E3V3A, I don't feel like laughing about this, since 'm trying to keep everyone motivated here and am actually happy that pull requests travel in. I'm not saying that it is *me* being the one who rocks the code, but I see myself as the one dude bringing in new developers, functioning as emotional glue by **thanking instead of ranting**, sound familar? Being slightly ironic here as well. ;-) I really want your inventionto rock. Of course I understood what you actually meant: Wait until @E3V3A checked every single PR. ^^

>So let's do it. :D

Let me know how to change it, please. Any guide would be appreciated.

**Comment by E3V3A** [comment]
You're absolutely right. If someone can post the code snippet to add/change, I can add it.

**Comment by SecUpwN** [comment]
@He3556 just sent me [these suggestions](https://stackoverflow.com/questions/28387602/notification-bar-icon-turns-white-in-android-5-lollipop), not sure if they're helpful though.

**Comment by d4rken** [comment]
I tested it and it's not related to Notification or Builder object. It's solely dependent on the *targetSdkVersion*. If i set it to 21, the icon in the Trust app becomes white too.
![2015-07-06 22 36 56](https://cloud.githubusercontent.com/assets/1439229/8534843/a6c27e90-2440-11e5-9c78-e44a142c7d20.png)

**Comment by SecUpwN** [comment]
>It's solely dependent on the *targetSdkVersion*.

Thanks for testing @d4rken. Can we override this somehow? If so, this might be the solution.

**Comment by SecUpwN** [comment]
Seems as if we're back to this this again since https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/22c0ca07599b0d62ec7816f3fcce27bfe33da9d6. *-sigh-*

![we](https://cloud.githubusercontent.com/assets/6000299/8225141/6e8a5422-1580-11e5-836f-6ab5d7f02b8a.png)

**Comment by SecUpwN** [comment]
>I tested it and it's not related to Notification or Builder object. It's solely dependent on the *targetSdkVersion*. If i set it to 21, the icon in the Trust app becomes white too.

Ok, thanks for finding that out, looks like we found the last bit to solve! @d4rken, your app [Trust](https://github.com/d4rken/trust) is currently using targetSdkVersion `19` and thus gets displayed like we want. My question: Would you recommend me to set our targetSdkVersion from `21` to `19` to solve this?

**Comment by banjaxbanjo** [comment]
@SecUpwN set it to 19 and test app if it looks and functions as its supposed to then there should be no issue but more opinions from others devs would be good idea. God knows what might change from changing 21>19

**Comment by SecUpwN** [comment]
>but more opinions from others devs would be good idea

@E3V3A, may I change [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/build.gradle#L46) back to `19` to test if this fixes this Issue?

**Comment by E3V3A** [comment]
I suggest you change nothing unless you're going to compile it and see if it works.

**Comment by SecUpwN** [comment]
I just asked @He3556 to craft a test version with this change for me to test on Lollipop. ;-)

**Comment by sc4ryb3ar** [comment]
i'm kinda necro-posting here, but i'm hopeful for some information on what you guys have learned.... I am in the process of creating a custom rom, from source, which means i get the advantage of changing that source :) I am wanting to locate the code in Marshmallow that controls the "white-ification" of the statusbar notifications and turn it off?  in your guys' research, did anyone find what handles that?

**Comment by j4s0nmchr1st0s** [comment]
Not dead

**Comment by j4s0nmchr1st0s** [comment]
Call or text

**Comment by j4s0nmchr1st0s** [comment]
Let the baals kiss let's go

**Comment by sc4ryb3ar** [comment]
@j4s0nmchr1st0s Hangouts sent

**Comment by j4s0nmchr1st0s** [comment]
Paul two for kola let's go call or text
