### ISSUE TITLE
Remove references to non-supporting organizations

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#490]
This project has been well known to the privacy community for years now. As we have continuously tried to reach out to those organizations that are supposed represent and promote privacy matter to the people. However, none of these organizations have responded to our repeated requests for support. And with *"support"* we never asked for much more than a mention or notice of recognition. In fact we've even stated we'd be happy to pay **them** support if we received any donation of significance. This has not happened, so I suggest we detach and remove any free-be links to those organizations. **Instead we should focus on promoting those newspapers, websites, people and organizations, that have mentioned us.**

The ones we will no longer freely promote are: 

* [EFF](https://www.eff.org/)
* [Guardian Project](https://guardianproject.info/) 
* [Privacy International](https://www.privacyinternational.org/). 

Bye guys and thanks for nothing.

**Comment by SecUpwN** [comment]
Thanks for opening this Issue after our private conversation, @E3V3A. The *only* one of the three organizations mentioned above, was @efforg who told me that they'd be forwarding our request to the "technical lead", still waiting for feedback on that. So here is my plan on how to deal with this Issue:

I will:

* Remove all organizations listed in [support](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector#support)
* Only add organizations if they *really* showed support (e.g. see https://github.com/EFForg/ssd/issues/6)

Anything else you would like me to do (maybe in our WIKI)? Let me know.
