### ISSUE TITLE
"Parse error"

### ISSUE THREAD

**Issue by duanester** [SecUpwN/Android-IMSI-Catcher-Detector#499]
when i try to install the latest version i get this pop up:

"Parse error
There is a problem parsing the package" 

i tried different versions from different sources and checked the md5. maybe this has more to do with my phone, i don't know. I just started with android, and just know enough to get myself into allot of trouble.

phone: kyrocera event
android version: 4 0 4
Rooted phone, with allot of disabled system apps, all app with google in the title and half of all the rest of the system apps,

mayabe i just need to enable a system app since i disabled so many. Do you have any idea which? Do you want a list of my disabled system apps?

**Comment by SecUpwN** [comment]
Welcome to our little project, @duanester. Here are a few core questions:

* Which system apps did you disable and which app are you using for that? Also see: [Permissions](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Permissions).
* Where did you grab the APK from? Official sources (Our Aptoide, F-Droid or GitHub Releases)?

**Comment by duanester** [comment]
Ill get the other things you requested, maybe tomorrow. ocr from screen capture below may have errors.

Disabled apps:
BackupRestoreConfirmation.apk com android backupconfirm
BooksTablet.apk com google android apps.books
Calculator.apk com android.calculator
Calendar.apk com android.calendar
CalendarProvider.apk com.android providers.calendar
Camera.apk com.android.camera
Certlnstaller.apk com.android.certinstaller
Chrome.apk com.android.chrome
ChromeBookmarksSyncAdapter.apk com.google.android.syncadapters
Connection.Optimizer.apk com birdstep.android.cm
DeskClock.apk com android.deskclock
DrmProvider.apk com.android.providers.drm
EcoMode.apk com kyocera ecomode
Email.apk com.android.email
Exchange.apk com.android.exchange
GalleryGoogle.apk com google.android gallery3d
GenieWidget.apk com.google android.apps.genie.geniev
Gmail.apk com.google.android gm
GMS.Maps.apk com.google.android.apps.maps
GmsCore.apk com.google.android.gms
GoogleBackupT ransport.apk com google android backup
GoogleCalendarSyncAdapter.apk com.google.android.syncadapters.ee
GoogleContactsSyncAdapter.apk com google android.syncadapters.ci
GoogleFeedback.apk com google android feedback
GoogleLoginService.apk com.google.android.gsf.login
GooglePartnerSetup.apk com google android.partnersetup
GoogleQuickSearchBox.apk com google android googlequickseai
GoogleServicesFramework.apk com.google.android.gsf
GoogleTTS.apk com google android tts
Hangouts.apk com google android talk
LatinlmeDictionaryPack.apk com.google.android.inputmethod.lat
LatinlmeGoogle.apk com google.android inputmethod.latin
LiveWallpapers.apk com. android, wallpaper
LiveWallpapersPicker.apk com android.wallpaper.livepicker
Magazines.apk com google.android.apps magazines
Mediallploader.apk com.google.android apps.uploader
Music2.apk com.google android.music
MusicFX.apk com android musiefx
NetworkLocation.apk com.google.android.location
OneTimelnitializer.apk com.google android onetimeinitializer
Phonesky.apk com.android.vending
PlusOne.apk com google android apps plus
Protips.apk com.android.protips
SetupWizard.apk com google.android setupwizard
SharedStorageBackup.apk com.android.sharedstoragebackup
SoundRecorder.apk com android.soundrecorder
Street.apk com.google.android.street
talkback.apk com.google.android.marvin.talkback
UserDictionaryProvider.apk com.android.providers.userdictionary
Videos.apk com.google android.videos
VisualizationWallpapers.apk com android.musievis
VisualVoiceWidget.apk com kyocera.voicemailwidget
VoiceDialer.apk com.android.voicedialer
VoiceSearch.apk com google android voicesearch
VpnDialogs.apk com.android.vpndialogs
vvm.apk com.coremobility.app.vnotes
VvmMessageCount.apk com kyocera . sect ion 7 . wmcoun ter
WAPPushManager.apk com.android.smspush
xtra_t_app.apk com qualcomm location.XT
YouTube.apk com.google.android youtube

**Comment by SecUpwN** [comment]
>Ill get the other things you requested, maybe tomorrow. ocr from screen capture below may have errors.

Doesn't help much. But I wonder why you keep disabling half of your ROM if you could just [ROOT](Ill get the other things you requested, maybe tomorrow. ocr from screen capture below may have errors.) your phone and install a custom ROM like [AOKP](http://aokp.co/)?

>NetworkLocation.apk com.google.android.location

This should be important for our app, I guess.

**Comment by duanester** [comment]
i enabled Networklocation.apk but still have the same problem

this is a single processor phone so i don't think it would do firefox very well without everything disabled. 
Ill buy a better phone just to use your app, What is the cheapest phone, you know of that runs you app. since i am liable to brick it need the cheapest.

**Comment by SecUpwN** [comment]
>i enabled Networklocation.apk but still have the same problem

As already said, this won't be the root cause to this problem.

>Ill buy a better phone just to use your app, What is the cheapest phone, you know of that runs you app.

Don't do that just because of our app. It is **bleeding ALPHA**. Just wait a little for the next release.

>i am liable to brick it need the cheapest.

Liable? Check the links I provided and see what can be done.

**Comment by E3V3A** [comment]
@duanester 

> android version: 4 0 4

AFAIK, we're only supporting AOS 4.1 (API 19) and above. Update your phone. 
(Since we're not using Google Play, there are no automatic API compatibility checks.)
