### ISSUE TITLE
Error Logs: Idiot proof warning and analysis

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#511]
Good evening everyone, I have just received another 3 error logs **without descriptions** and am now moving the discussion from https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/455#issuecomment-113900052 into this separate Issue because I am very **SICK** of all the obvious an-alphabets using our app! When pressing `Debugging` it clearly says in bold letters:

>ATTENTION! Please describe the problem you had, before sending us these logs. NO HELP WITHOUT DESCRIPTIONS!

But people are too lazy and/or cannot read this at all. So my suggestion is to either:

* Make sending without a detailed description of the problem impossible (likely not possible)
* Make a dumbass-proof popup warning that *needs* to be filled with info before sending is possible

And generally speaking, we need someone who is able to actually **analyze** the logfiles. I would like to get my email address removed from the code and also implement a way that is open source and **not** an anti-feature like `ACRA`, which had been previously suggested by @agilob. Something dead simple that helps us and developers but does not bloat or destroy our app and is actually idiot proof. Suggestions?

**Comment by agilob** [comment]
[ACRA] can be used for this purpose and [does not fully conflict with F-Droid](https://f-droid.org/wiki/page/FAQ_-_App_Developers#Which_free_library_should_I_use_.28instead_of_XXX.jar.29_to_implement_YYY)

**Comment by SecUpwN** [comment]
>ACRA can be used for this purpose and does not fully conflict with F-Droid

@agilob, I'm now confused. Please link an example app on F-Droid. In https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/455#issuecomment-113902488 you've stated:

>ACRA is opensource, so it can be included in a build. It's an antifeature, so it's no always removed, but the application gets new red label 'it might be tracking you'.

@DJaeger also said why ACRA will likely not be the solution to the whole thing:

>I think a lib which will cause an anti-feature prompted on F-Droid, especially that it could spy you, is a nogo.

I now would like to hear some official statement of the @Acra developers about this, if possible.

**Comment by william-ferguson-au** [comment]
I have never used F-Droid and an unaware of why it would list ACRA as an antifeature. This is the first time that anyone has even mentioned it to me.

ACRA can be configured in a myriad of ways from sending email (not a great bug tracking solution IMHO), to sending to a bugreport server in the background.

The way that I tend to use it is the latter and I only worry about handling crashes that rack up any sizeable number of faults. More efficient and doesn't let me get bogged down solving one person's hacked device.

If someone could point out why F-Droid thinks ACRA is an antifeature it would enhance this discussion.

**Comment by agilob** [comment]
I could be wrong https://f-droid.org/wiki/page/FAQ_-_App_Developers#Which_free_library_should_I_use_.28instead_of_XXX.jar.29_to_implement_YYY

**Comment by SecUpwN** [comment]
@william-ferguson-au and @agilob, would ACRA essentially remove the need of [Coverity Scan](https://scan.coverity.com/)?

**Comment by william-ferguson-au** [comment]
ACRA and Coverty do two different things.

ACRA captures and reports issues from a live environment.

Coverty performs static analysis of code prior to release looking for
potential issues.

Whether to ditch Coverty is a business decision. But ACRA doesn't replace
the functionality that Coverty brings.


William

On Wed, 8 Jul 2015 9:03 am Security: Pwned. <notifications@github.com>
wrote:

> @william-ferguson-au <https://github.com/william-ferguson-au> and @agilob
> <https://github.com/agilob>, would ACRA essentially remove the need of Coverity
> Scan <https://scan.coverity.com/>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/511#issuecomment-119369857>
> .
>
ᐧ

**Comment by SecUpwN** [comment]
Thanks for your statement, @william-ferguson-au, I hope asking you these many things does not get on your nerves. Before implementing ACRA, I would like to know two further things for consideration:

1. Are there any alternatives to ACRA? Some sort of comparison between these would be great.
2. Since I know that @krt16s works for @F-Droid, can you please link any apps that do use ACRA?

**Comment by william-ferguson-au** [comment]
All of my apps use ACRA
https://play.google.com/store/apps/developer?id=Xandar+Mob
As do approx 5% of all apps on Google Play.

There are plenty of commercial alternatives to ACRA. Eg BugSense
Pros for alternatives: none that I can think of of
Cons for alternatives: locked into a particular report server, have to pay
fees.

NB with ACRA you can choose which backend to forward your reports too.
A commercial one or your own.

ᐧ

**Comment by SecUpwN** [comment]
>Pros for alternatives: none that I can think of of

If I'd be its developer, I'd say that, too. ;-) **Thank you** for this positive discussion, ACRA sounds good, Iand especially your customer support. All that's left is to see some F/OSS apps with it on @F-Droid.

**Comment by krt16s** [comment]
Acra is available from central, so we should be able to build it (read: we have apps using it and they build fine, but I don't know anything about acra in details, so there might be some incompatible corner cases).

Regarding anti-features: Well, we don't have a clear policy there. Some people consider it tracking, some don't. The majority of apps using acra don't have it set by now...

**Comment by agilob** [comment]
@krt16s I saw some threads on fdroid when you discussed it as a tracking antifeature, that's why I raised that topic here. Thanks for clarifying.

**Comment by SecUpwN** [comment]
Thanks for the clarification in here, @krt16s.  Given these changes, whould we use it now @E3V3A?

**Comment by E3V3A** [comment]
We have several much more urgent issues.

**Comment by SecUpwN** [comment]
>We have several much more urgent issues.

Not the answer to my question, @E3V3A. We need to have some way to support developers work find and fix bugs ahead of time, this will ease up our lives in the llong run. @DJaeger, what do you think?

**Comment by DJaeger** [comment]
If ACRA is configured to don't send something automatically in the background it's ok for me.

**Comment by DJaeger** [comment]
But to prevent, that someone sets the F-Droid anti-feature we should make clear, that it never automaticly sends data!

**Comment by SecUpwN** [comment]
I am clsoing this Issue in favor of #659, which is in a better shape. Please continue discussion there! :+1:
