### ISSUE TITLE
Question about /dev/diag

### ISSUE THREAD

**Issue by benutzer74** [SecUpwN/Android-IMSI-Catcher-Detector#515]
A question, not an issue, about /dev/diag
What permissions does /dev/diag have on your systems?
Is it safe to make /dev/diag world writable and world readable? I guess not....!?

**Comment by DJaeger** [comment]
How is this related to this app?

**Comment by E3V3A** [comment]
It doesn't matter at all what permissions you have on any particular device, especially without knowing anything about the hardware, the exact AOS, SELinux etc. About safety? Safety from what?

Please post Q/A stuff on our XDA page.
