### ISSUE TITLE
Use libraries for clean generated code

### ISSUE THREAD

**Issue by ziem** [SecUpwN/Android-IMSI-Catcher-Detector#517]
It is just another suggestion from me. 

Developers should consider using following libraries for cleaner code:
- [Retrofit](http://square.github.io/retrofit/) - A type-safe REST client for Android and Java
- [RxJava](https://github.com/ReactiveX/RxJava) - Reactive Extensions for the JVM
- [FragmentArgs](https://github.com/sockeqwe/fragmentargs) - Annotation Processor for setting arguments in android fragments 
- [Parceler](https://github.com/johncarl81/parceler) - Android Parcelables made easy through code generation
- [ButterKnife](http://jakewharton.github.io/butterknife/) - View "injection" library for Android
- [Timber](https://github.com/JakeWharton/timber) -  logger with a small, extensible API which provides utility on top of Android's normal Log class. 
- [StorIO](https://github.com/pushtorefresh/storio)/[cupboard](https://bitbucket.org/qbusict/cupboard) - ORM/persistence
- [Nucleus](https://github.com/konmik/nucleus)/[Mosby](https://github.com/sockeqwe/mosby) - MVP

Instead of writing N lines of code we can simply use annotations and let annotation processors do the rest for us.

**Comment by E3V3A** [comment]
I love it when people recommend to use various enhancement libraries that have build errors (e.g. Ollie) in their GitHub repos... :+1:

**Comment by agilob** [comment]
It's not like AIMSICD is broken since 22.06 on FDroid and it's impossible to use it after update to 0.30

**Comment by ziem** [comment]
@E3V3A - replaced Ollie with StorIO for you...

**Comment by SecUpwN** [comment]
Thanks for opening this Issue as discussed via private E-mail, @ziem. Do I sense something like sarcasm in here, @E3V3A and @agilob? It would be *very* neat if you could skip that kindergarten. Thank you. @ziem made a valid point: In places where we could rely on libraries making our code lighter, cleaner and keep it more up to date, we should indeed use such libraries. @ziem, if you see any code that can be enhanced by one of these libraries (preferably without any build errors), then feel invited to craft a pull request. Furthermore, I am sure @DJaeger might be able to comment on this.

**Comment by E3V3A** [comment]
The problem with adding libraries, is the introduction of new language and thus obscuring the real code behind. It's like having all developers learning 10 more Java like languages.  Total waste of time. 

@ziem Could you give some specific examples, where this would serve us simplicity?

 Should we really bloat or code base with obscure and possibly poorly maintained and documented external libraries, just so that we can save a few lines of code elsewhere?

**Comment by ziem** [comment]
Most popular libraries created by best Android developers obscure and poorly maintained? :suspect:

**Few examples:**

*ButterKnife (4,3k stars):*
https://github.com/ziem/Android-IMSI-Catcher-Detector/commit/edeb740fabe0210e45b99a9cf94d128946c46039

 - instead of writing `findViewById` and then casting views, you just type `@Bind(R.id.your_id)` and voilà
 - one method annotation `@OnClick` and you have on click listener
 - more: http://jakewharton.github.io/butterknife/ (poorly documented :satisfied:)

---

*Parceler (1,1k stars):*
https://github.com/ziem/Android-IMSI-Catcher-Detector/commit/f2ab23f881540b1c9a94ec726a343cc59c3f7404
 - `@Parcel` and you have `Parcelable`, no more `CREATOR`, `writeToParcel`, etc.

---

*Timber (1k stars):*
Instead of creating and using tags everywhere:

    private static String TAG = "BaseActivity";
    ...
    Log.d(TAG, "StatusWatcher starting watching");

you just type:

    Timber.d("StatusWatcher starting watching");

---

*Retrofit (5,9k stars):*

    public interface OpenCellIdService {
        @GET("/gsmCell/user/generateApiKey")
        void generateKey(Callback<Response> responseCallback);
    }

    Retrofit retrofit = new Retrofit.Builder()
        .setEndpoint("http://opencellid.org")
        .build();

    OpenCellIdService service = retrofit.create(OpenCellIdService.class);
    service.generateKey(new Callback() {
        //todo
    });

---

*[Hugo](https://github.com/JakeWharton/hugo) (1,7k stars):*

    @DebugLog
    public List<Cell> parse(InputStream in) throws XmlPullParserException, IOException {
        try {
            XmlPullParser parser = Xml.newPullParser();
            parser.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, false);
            parser.setInput(in, null);
            parser.nextTag();
            return readCells(parser);
        } finally {
            in.close();
        }
    }

`@DebugLog` and you know how long did it take to parse XML.

---

In general:
 - less boilerplate
 - you don't have to reinvent the wheel
 - if we can make our life easier then why not?
 - more time to focus on features instead of writing another `Parcelable`, REST client, etc.

More:
 - https://www.reddit.com/r/androiddev/comments/2hv33k/my_experiences_developing_on_android/
 - https://www.reddit.com/r/androiddev/comments/1xfhnu/whats_the_most_useful_frameworklibrary_you_are/
 - https://www.reddit.com/r/androiddev/comments/2wj7i7/so_uh_what_are_nice_libraries_to_have_in_apps/

**Comment by E3V3A** [comment]
@ziem  Fantastic! Thanks you for taking the time to clearly illustrate the need. I love it when someone prove me wrong. That's when you learn...

**Comment by SecUpwN** [comment]
@ziem and @DJaeger, would you please be so kind and sift through our code to see if we can improve it using libraries from the OP? I have added them [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Resources#clean-libraries) on our resources page. BTW, when shall I close this?

**Comment by ziem** [comment]
@E3V3A :+1: 
@SecUpwN Are there any code style guidelines for developers (I only found https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Style-Guide)? If not, we can use Android [Code Style Guidelines for Contributors](https://source.android.com/source/code-style.html) or if you don't like `s`/`m` prefixes we can use [Google Java Style](http://google.github.io/styleguide/javaguide.html)/[Oracle Code conventiosn](http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html). It is even possible to enforce code style: [Enforcing coding style and being warning and lint-free across teams in Android Studio or git/github](http://stackoverflow.com/questions/28375943/enforcing-coding-style-and-being-warning-and-lint-free-across-teams-in-android-s). What do you think about it?

I can implement ButterKnife.

**Comment by SecUpwN** [comment]
@ziem, thanks for asking this. We currently only have the [Style Guide](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Style-Guide) and code has been added by developers using pretty much the style in coding and code comments based upon the already existing code of our app. I would like @E3V3A and especially @DJaeger to chime in here and tell me which way we should travel, I will add that to our guide as well. If [ButterKnife](http://jakewharton.github.io/butterknife/) is enhancing our code for the future,please craft a PR for implementing it.

**Comment by E3V3A** [comment]
@ziem  
Yes, I think a modified version of the Google Java Style seem appropriate, with the reservation of the following point I don't agree with:

* column limit to 100 char. (As we all know, our screens are 1 kilometer wide and about 2 centimeters high, so why the fuck should I read code 2 cm wide and have to scroll downwards paging through 1 kilometer?)
* line wrapping... Shut the f*** up! Nobody like line-wrapping.
* `4.6.3 Horizontal alignment` bad idea. I love horizontal alignment, and as long as we use spaces and not tabs, its perfectly great for readability.


Another good thing to tape to your screen:
> Class and member modifiers, when present, appear in the order recommended by the Java Language Specification:

```
public protected private abstract static final transient volatile synchronized native strictfp
```

**Comment by SecUpwN** [comment]
@E3V3A, since you're having specific coding requirements, please correctly add them [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Style-Guide#coding).

**Comment by He3556** [comment]
@all is this still alive? or can i close it?

**Comment by DJaeger** [comment]
This is still WIP

**Comment by SecUpwN** [comment]
@He3556, this is still alive. Someone experienced (preferrably some hacker from outside) should have a close look at our code and tell us which things to implement. Ideas for whom I may contact to do so?

**Comment by SecUpwN** [comment]
Any update on this, @larsgrefer? Please just quickly review this Issue and decide which things we should implement to make life of developers easier so that we can finally close this. Thank you very much.

**Comment by larsgrefer** [comment]
I think we should use one issue per suggestion and not one issue for all suggestions

**Comment by SecUpwN** [comment]
>I think we should use one issue per suggestion and not one issue for all suggestions

@larsgrefer, fine, I will respect that in the future. But tearing apart this Issue into multiple smaller ones is not really helpful right now, as we then pile even more stuff than we already have. Please take a minute to re-read this and open an Issue for the libraries you think should be implemented in the long run. Thanks!

**Comment by larsgrefer** [comment]
- Injection of View and Loggers is already implemented
- Retrofit can be discussed here: #752 
- My favorite persistence library is discussed here: #655
