### ISSUE TITLE
No BTS shown in the cell map function

### ISSUE THREAD

**Issue by lop1** [SecUpwN/Android-IMSI-Catcher-Detector#520]
in this AIMSICD 0.1.30 alpha b08, most of the time there are no BTS shown, sometime there is the connected BTS but that's all , I never saw the 4 BTS around my house.

**Comment by SecUpwN** [comment]
Is this a zombie of #407, @E3V3A?

**Comment by lop1** [comment]
it is only for the map view, no problem with the database view.

**Comment by E3V3A** [comment]
@lop1  What do you expect to see? Did you ever see it before?

**Comment by lop1** [comment]
I expect to see my position, my connected BTS in blue dans the 4 BTS around
my Home , i have seen it in précédent releases ( i think it was working in
0.1.25, after this release it was not working , but it was normal because
the cells DB was not populated )

**Comment by lop1** [comment]
it is only for the map view, no problem with the database view.
On 02 Jul 2015, at 21:08, Security: Pwned. <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

Is this a zombie of #407
<https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/407>,
@E3V3A <https://github.com/E3V3A>?

—
Reply to this email directly or view it on GitHub
<https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/520#issuecomment-118133848>
.

**Comment by E3V3A** [comment]
Please re-test this issue now. (Using Buildozer build >= 211)
