### ISSUE TITLE
CreditsRollView.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by DJaeger** [SecUpwN/Android-IMSI-Catcher-Detector#523]
Above mentioned line is viewed at building the app.
I think we should remove the RollView and make it a normal scrollable view or popup as the rest.
I also think the RollView is really bad to read...

**Comment by E3V3A** [comment]
I agree on this, but some dev's still think this Starwars thingy is very cool... We discussed this in issue #273.

**Comment by SecUpwN** [comment]
Too bad. I always liked it, but do also agree that we should clean our code as best as possible. Are you able to suggest a better to read solution, @DJaeger? I'd like to have something neat for our `CREDITS`, maybe something from one of my favorite repos, the [List of awesome Android UI/UX Libraries](https://github.com/wasabeef/awesome-android-ui)?

**Comment by DJaeger** [comment]
I would prefer a much simpler about view.
I think a mix of the about screen of Twidere, Amaze and GithubContributorsLib would be great.
The main about view like the one of Twidere, but with the contributors/special thanks also seperated like the developers.
When clicking on translaters open a list like the one of Amaze, when clicking on Special thanks open a list like GithubContributorsLib but extended with comments like in Twidere.
Or much better for translators would be a ExpandableListview for each language with items inside like the GithubContributorsLib.

**Comment by E3V3A** [comment]
Thanks, that sound great Daniel! But can you please link your references, so not all of us have to google every single one of those....

**Comment by DJaeger** [comment]
Will add some references.
Have only searched for ideas on my phone until now.

**Comment by SecUpwN** [comment]
@DJaeger, are you still on finding a solution? Maybe @larsgrefer can add his thoughts?

**Comment by SecUpwN** [comment]
@larsgrefer, the current build is crashing when pressing `CREDITS`. Any good suggestions for https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/523#issuecomment-126679514?

**Comment by SecUpwN** [comment]
@larsgrefer, the current build is crashing when pressing `CREDITS`. Any good suggestions for https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/523#issuecomment-126679514?

**Comment by larsgrefer** [comment]
I agree with @DJaeger. We should remove the RollView and use something more simple

**Comment by SecUpwN** [comment]
@larsgrefer, what do you think about [GithubContributorsLib](https://github.com/alorma/GithubContributorsLib)? Any better suggestions?
