### ISSUE TITLE
OCID download not respecting MNC filter

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#525]
The OCID download request is using optional filters for selecting MCC,MNC,LAC etc. We have [set it to use same MNC](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/a777e92792cf2eeb5c2a068a4b34524c98479490/app/src/main/java/com/SecUpwN/AIMSICD/utils/Helpers.java#L273-L275), as your SIM/provider, but the download is not respecting this. 

Populating (spamming) the downloaded DB with BTS cells from other service providers. 

To see this, open the Database Viewer and the `Imported OCID Data` table and look for entries with a different MNC than shown on the `Phone/SIM Details` page.

**Comment by E3V3A** [comment]
I've tracked down the issue to that the `cell.getMNC()` returns either **`0`** or **`-1`** [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/a777e92792cf2eeb5c2a068a4b34524c98479490/app/src/main/java/com/SecUpwN/AIMSICD/utils/Helpers.java#L273-L275):

```java
if (cell.getMNC() != Integer.MAX_VALUE) {
     sb.append("&mnc=").append(cell.getMNC());
}
```

The different results can be seen by sending different arguments for `&mnc=`...

**Comment by E3V3A** [comment]
@DJaeger Any ideas how to check what this actually returns? 

We should add: 
```java
Log.i(TAG, mTAG + ":OCID MNC is set to: " + cell.getMNC());
```
before those lines above.

**Comment by E3V3A** [comment]
Hmm logcat just told me that both **MCC** and **MNC** is set to: **2147473647**. I.e. to MAX_INT of `0x7FF FFFFF`.

**Comment by E3V3A** [comment]
This is a new bug from some fairly recent PR, as it was not present before. If you're a developer, please think about what you've changed in the OCID or DB related items lately...

**Comment by banjaxbanjo** [comment]
@E3V3A I've also seen this 2147473647 value somewhere but it wasnt mcc I think it was signal or something like that.

**Comment by E3V3A** [comment]
I guess it's a default value when something is empty, a kind of `null`...

**Comment by He3556** [comment]
I was also looking for this problem today. And 2147473647 in Hex is 0x7FFF D8EF 
0x7FF FFFFF is 34344009727 decimal. So maybe it's not a default value?

We get the right values from cell.getLon() & cell.getLat() but not from cell.getMNC() 
But anyway - just an idea - why are we using the Cell and not the SIM to get MCC+MNC? 

public String getSimOperator ()

**Comment by E3V3A** [comment]
No, that is not correct, check your hex/dec conversions again! 

**why are we using the Cell and not the SIM to get MCC+MNC?**
We might be roaming on another network.

**Comment by E3V3A** [comment]
This is still an issue after new DB overhaul. Still issue in Buildozer b**211**.

**Comment by banjaxbanjo** [comment]
Yea wasn't looking into that till db PR made EVA

**Comment by E3V3A** [comment]
@banjaxbanjo I know, I'm just going through everything and checking what's relevant. I know you're exhausted, so please take a holiday, unless you find it impossible to leave this project alone (as we often do).

**Comment by banjaxbanjo** [comment]
@E3V3A haha will do for sure cheers😉

**Comment by E3V3A** [comment]
This need to be fixed naaaooow!

**Comment by E3V3A** [comment]
Awesome!!! :tada:

**Comment by DJaeger** [comment]
Thanks
