### ISSUE TITLE
Remove LACELLS from app

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#529]
Because of: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/467#issuecomment-118640504

**Comment by SecUpwN** [comment]
Why fully remove it and not try to correct its implementation? @wvengen, please chime in.

**Comment by wvengen** [comment]
It's causing problems for quite some users, and can be implemented much better after the new database design. I think it's worth it to wait for that.

**Comment by E3V3A** [comment]
yes, lets wait... I think we've got this covered in new structure
