### ISSUE TITLE
WIKI: List phones with Type-0 SMS detection results

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#532]
Looking at the [SmsDetector.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/smsdetection/SmsDetector.java) we need to make a list of phones where the logcat type of *type-0* SMS detection works.

Something like:

| Phone         | Model      | AOS_VER | Type-0 | MWI  |
|:------------- |:---------- |:------- |:------ |:--- |
Samsung S5	| SM-G900F   | 4.4.2   | YES    | YES 
Samsung S4-mini	| GT-I9195   | 4.2.2   | YES    | YES 
Sony Xperia J	| ST260i     | 4.1.2   | NO     | YES 

MWI = "Message Waiting Indicator" ( @banjaxbanjo What was this again? )

**Comment by SecUpwN** [comment]
Added the proposed schemata to our [Special SMS](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Special-SMS/) page and elevated the status of @banjaxbanjo to `COLLABORATOR` so that he can update that list with his own test results. Thank you for working on this!

**Comment by banjaxbanjo** [comment]
mwi = message waiting indicator

**Comment by banjaxbanjo** [comment]
Cheers😉

Sent from Yahoo Mail on Android

**Comment by SecUpwN** [comment]
@E3V3A, I have updated the list with an MWI explanation. Please add your results of the OP if real.

**Comment by E3V3A** [comment]
IDK on top of my head. Perhaps banja knows better...

**Comment by banjaxbanjo** [comment]
I would go with 
(MWI) Message Waiting Indicator detected! But still good without  (MWI)

**Comment by SecUpwN** [comment]
The core string has been corrected with https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/ffb3c246b29959d33c7389b679a381c96a13c449, translations will follow. Is this Issue fixed now, @E3V3A?

**Comment by E3V3A** [comment]
I think we should remove this:
```
If you want this data to be analysed by our developers, send the logfiles through the Debugging menu.
```
IMHO, I'm certainly not going to analyze anybody else's logs for them...

**Comment by SecUpwN** [comment]
@E3V3A, dude, that's *exactly* why we never **finish** certain Issues! I understand that one thought might lead to another, but **please** keep it **CLEAN**! Is **THIS** Issue *fixed* now? If yes, please close it and carry your thoughts above into a new Issue so that it can be discussed and closed properly.
