### ISSUE TITLE
Remove analysis invitation from SMS warning pop-up

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#533]
I think we should remove this:
```
If you want this data to be analysed by our developers, send the logfiles through the Debugging menu.
```
IMHO, I'm certainly not going to analyze anybody else's logs for them...

Also **1**: By them time the user have navigated to the debug logger, the relevant logcat events will most likely already be gone. Especially on new bloat loaded devices. 

Also **2**: The logcat in debug logger is not showing the radio logs...and shouldn't.

Also **3**:  What we really should have, is the export of the `EventLog` table (which is currently malfunctioning or not implemented yet, AFAIK.)

**Comment by SecUpwN** [comment]
Thank you for thinking about it. Thought that comes to my mind: We still have the `Debugging` button, which @He3556 and I consider important. But should we actually remove the possibility to *send* the logs to our email address as well? If we just remove our email address, we might be a step closer to fix #511.

**Comment by banjaxbanjo** [comment]
@E3V3A lol true would be nice to get some useful data from users tho. 

Currently I have event log logging 
changing Lac
Cell not in OCID

What other events need to be added to this?

**Comment by SecUpwN** [comment]
>What other events need to be added to this?

I don't get what you mean, is this *another* Issue? I am about to push the changes to fix this one.

**Comment by banjaxbanjo** [comment]
No issue @SecUpwN just looking for info on what other events should the event log be logging.

So far its
1. Changing lac
2. Cell not in OCID
3. Maybe a detected sms no?

**Comment by SecUpwN** [comment]
>just looking for info on what other events should the event log be logging.

So you're dong it *again* and are "spamming" your own Issue to tick me off, right? ;-)
Please see if we already have a proper place for these thoughts, #201 would be perfect.

**Comment by banjaxbanjo** [comment]
@SecUpwN I need to be spoon feed data sometimes because there is so many places to search on AIMSICD. Just looking for the fast route;)
