### ISSUE TITLE
No notification icon when background service is running

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#535]
Perhaps I missed something, but nowadays I like running this app in a kind of passive mode (without GPS enabled) only looking for mystery SMS. So when running app with SMS detection on, and putting app into the background, there is no longer any app icon shown in the status bar. I'm not sure if this should be considered a feature (app is hidden) or a bug (not telling user that it's running). i think it's a bug...

**Developers:** What do you think?

**Comment by SecUpwN** [comment]
@E3V3A, I cannot confirm this, works perfectly for me. Did you enable the `Persistent Service`?

**Comment by E3V3A** [comment]
No, but it seem persistent anyway!

**Comment by SecUpwN** [comment]
>No, but it seem persistent anyway!

It "seems" like so, because we cannot quit it yet. Please turn on `Perdsistent Service` and try again.

**Comment by SecUpwN** [comment]
>No, but it seem persistent anyway! 

@E3V3A, please re-check. https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/deb50bfc7125f601707162a2b4c3f206e52af5bb might have solved this.

**Comment by DJaeger** [comment]
I can't reproduce

**Comment by E3V3A** [comment]
Neither can I. :)
