### ISSUE TITLE
Fix gradle translation warnings

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#536]
There are 4 gradle warnings about not having a default translation:
```
warning: string 'alert_silent_voice_sms_detected' has no default translation.
warning: string 'typevoice_data' has no default translation.
warning: string 'typevoice_header' has no default translation.
warning: string 'typevoice_title' has no default translation.
```

**Comment by SecUpwN** [comment]
>There are 4 gradle warnings about not having a default translation

Are you sure you've imported the current code? Those strings have been changed shortly.

**Comment by E3V3A** [comment]
yes

**Comment by SecUpwN** [comment]
>yes

Then please ignore these warnings until our app has been translated to 100%. Currently: [![Translations](https://hosted.weblate.org/widgets/aimsicd/-/shields-badge.svg)](https://hosted.weblate.org/projects/aimsicd/strings/)

**Comment by E3V3A** [comment]
No, these seem to be strings with no references to them...or I'm just confused.

**Comment by SecUpwN** [comment]
>I think you changed the id reference names and then forgot to remove the old ones?

Might be. As far as I know, weblate always compares all strings with the original `values/translatable_strings.xml` and once we change it on GitHub it notices. Thus, I thought the strings would also changes with syncing the branches. But hey, no biggie. Please re-check it in a minute.

**Comment by SecUpwN** [comment]
Awesome. Seems like builds now brake due to strings being listed more than once. Let me digg into this, give me 30 minutes. I think I'll soon need a break from all this since noone donates to our efforts. :(
