### ISSUE TITLE
Sorry I don't know alot on internet but I know its not right they took my kids information 

### ISSUE THREAD

**Issue by standalone9** [SecUpwN/Android-IMSI-Catcher-Detector#540]
I don't like  we're  people are going  people don't talk face to. Face even standing by each other people can  take  you self  worth and money children life,these people are on my children's face book adding stuff to laptops full of  gross films we had kids kill them self's last thing they did Facebook the time line not right

**Comment by standalone9** [comment]
I guessed it no one helps no one any more I'll figure it out thank you enjoy and please try to make internet safe some one has to care good by

**Comment by standalone9** [comment]
Thank you I'll leave please make the internet safe I c as nt be the only one who cares god be with you

**Comment by standalone9** [comment]
God be with you l can't be the only one who sees the dangers make safe please

**Comment by E3V3A** [comment]
reported and blocked!
