### ISSUE TITLE
Working with 802.11 projects

### ISSUE THREAD

**Issue by ehem** [SecUpwN/Android-IMSI-Catcher-Detector#545]
I'd like to suggest the AIMSICD project may want to look at working with some of the projects centered around 802.11 privacy.  They have a similar target, identifying fake 802.11 access points.

I'm somewhat hopeful there might be room for sharing code due to the similar goal, though I suspect most of the code in these projects will be in drivers not the core and thus not so good for reuse.  On the flip side making AIMSICD's core flexible enough to be reused may provide benefits.

**Comment by SecUpwN** [comment]
>I'd like to suggest the AIMSICD project may want to look at working with some of the projects centered around 802.11 privacy. They have a similar target, identifying fake 802.11 access points.

Interesting, but I'm not quite sure what you mean. Would you please link these projects here?

**Comment by ehem** [comment]
The two that I've found so far are [WiFi Privacy Police](https://github.com/BramBonne/privacypolice) and [WiGLE Wifi Wardriving](https://github.com/wiglenet/wigle-wifi-wardriving).  I'm quite unsure of how much potential value there is here.  These are similar in that given a location, some set of 802.11 access points *should* or should *not* be found, unexpected access points can be suspicious.  With overall similar data patterns this might be readily combined with AIMSICD to some value (perhaps not enough).

**Comment by SecUpwN** [comment]
@ehem, thanks for clarifying, but this Issue is closed already. Our app has *nothing* to do with WIFI, but with your cellular connection base stations. Please make sure to read our [README](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/README.md) and [WIKI](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki). Thanks!
