### ISSUE TITLE
English String consistency (OpenCellID vs OpenCellId vs OCID)

### ISSUE THREAD

**Issue by ehem** [SecUpwN/Android-IMSI-Catcher-Detector#546]
Looking at app/src/main/res/values/translatable_strings.xml

I see the Open Cell ID project referred to as "OpenCellID", "OpenCellId" and "OCID".  Of these it looks like "OpenCellID" is most common, looking at their site I suspect this is the spelling varient they would prefer.

Of note "invalid_key_try_later" and "getting_ocid_key" use "OpenCellId".  While "pref_request_ocid_key", "cell_id_doesnt_exist_in_db", "uploaded_bts_data_successfully", "error_uploading_bts_data", "help_main_acd", "help_tracking_toggle_cell_tracking", "help_app_download_local_bst", "help_app_upload_local_bst", and "imported_ocid_data" use "OCID".

This is an issue for later in development, but it is out there.

**Comment by SecUpwN** [comment]
Thanks for digging so deep into our strings and attempting to make our app use consistent translations! If `OpenCellID` is what they actually prefer, I'd vote for using this in our app and across all language files, but would like to hear @E3V3A on this first since we use `OCID` in places where `OpenCellID` is too long.

**Comment by DJaeger** [comment]
I have thought about that too.
I think changing ```OpenCellId``` to ```OpenCellID``` shouldn't be a problem.
If we want to use ```OCID``` we should at least declare this term to the user.

**Comment by E3V3A** [comment]
We'll continue to use `OCID`, thank you. It's *declared* all over this site.

**Comment by SecUpwN** [comment]
>We'll continue to use `OCID`, thank you. It's *declared* all over this site.

@E3V3A, I begin to get mad about you closing Issues that are **not fixed**! The whole purpose of having them open is to **track** what **needs to be solved**! @DJaeger, can you check that our whole app as well as all translations change to `OCID` to make our app and code consistent? That would be great.

**Comment by agilob** [comment]
lol

**Comment by He3556** [comment]
oh sorry Sec - didn't see you comment
:)

**Comment by agilob** [comment]
did you close the issues without reading last comments?

**Comment by He3556** [comment]
yes - and reopened it :)

**Comment by SecUpwN** [comment]
No problem, @He3556, it happens to the best of us. ;-) To finally close this Issue: Shall we rename all publicly displayed strings in our app to the shortened version `OCID` now? If so, tell me and I will take care of this next week. I am voting on not changing the code comments though.  Feedback appreciated.

**Comment by DJaeger** [comment]
That whould be ok for me, but we should at least descripe one time what this means to the users.
For example in the first start tutorial.

**Comment by He3556** [comment]
I would just leave it like it is and use "OpenCellID" in the future. 

We have so many shortened names and it is easy to get confused with CID and OCID for people who doesn't know about all this.

**Comment by SecUpwN** [comment]
>I would just leave it like it is and use "OpenCellID" in the future.

Fair. So should I change all shortened terms in our app displays to `OpenCellID`?

**Comment by He3556** [comment]
yes, and than close this issue? ;)

**Comment by SecUpwN** [comment]
>yes, and than close this issue? ;)

Agreed. I'll claim this Issue, but it will not happen before I'll get back to my own computer. Patience.
