### ISSUE TITLE
Remove DBTableColumnIds.java and re-insert constants in Db adapter

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#550]
Transparency has been totally lost in latest DB update (overhaul) PR. We need to re-insert all the DB constants in clear-text into the AIMSICDDbAdapter.java file and remove DBTableColumnIds.java.

**Comment by SecUpwN** [comment]
>Transparency has been totally lost in latest DB update (overhaul) PR.

I don't want to blame anyone here, but why did you merge it when you did not check the whole thing? Let me know if you need mee to revert the whole database overhaul, we can press the `Revert` button.

**Comment by E3V3A** [comment]
There are over 3000 lines and hundreds of comments and several dozens old and new "TODO"s. Feel free to check! Given code freeze, we assumed that everything was synched. But we're only human and some assumptions and copy pastes later, we were out of sync... 

I don't think its necessary to revert, but we need to check and compare to previous days code. This is the drawback with making huge PR's, we can't revert individual files, using standard Github files. For a real GIT, you proably could. Please remember that. 

As for this issue. 
We can probably keep: DBTableColumnIds.java for use where we're indexing and loading the tables. But for the queries, I'd like to see raw SQL constants, and using String.parse() thing for readability.
