### ISSUE TITLE
dalvikvm: Could not find class

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#555]
Get the following error:

```
E/dalvikvm(...): Could not find class `android.telephony.CellInfoWcdma`, refreneced from method com.SecUpwN.AIMSICD.utils.DeviceApi17.loadCellInfo
W/dalvikvm(...): VFY: unable to resolve instanceof 704 (Landroid/telephony/CellInfo/Wcdma;) in Lcom/SecUpwN/AIMSICD/utils/DeviceApi17;
W/dalvikvm(...): VFY: replacing opcode 0x20 at 0x0128
```

Did we forget to update [DeviceApi17.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/utils/DeviceApi17.java) for DB overhaul?

**Comment by SecUpwN** [comment]
>Did we forget to update `DeviceApi17.java` for DB overhaul?

Seems like it. Can't find any modifications in #547. What's missing?

**Comment by DJaeger** [comment]
Maybe this helps?
http://stackoverflow.com/questions/19071702/could-not-find-class-android-telephony-cellinfolte

**Comment by SecUpwN** [comment]
@DJaeger, would you suggest adding this to `DeviceApi17.java`?

```JAVA
import android.telephony.CellInfoLte;
```

**Comment by E3V3A** [comment]
Apparently I had [already posted](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/143#issuecomment-58651468) in #143, about this exact problem one year ago!!

[CellInfoWcdma](https://developer.android.com/reference/android/telephony/CellInfoWcdma.html) belongs to API 18 (AOS 4.3). Thus **DeviceApi17.java** should probably be called ** DeviceApi18.java** and using `...SDK > 17` instead of `16`...

The lines in CellTracker.java make it unclear what is really supposed to be executed. As my understanding was that the DeviceApi17.java class should only be executed if you use API17, since we only start support from 17 and up? Instead the lines read as follows.

First [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L397-L400), then [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L948-L950): 

```java
 public List<Cell> updateNeighbouringCells() {
...
            //LISTEN_CELL_INFO added in API 17
            if (Build.VERSION.SDK_INT > 16) {
                DeviceApi17.startListening(tm, phoneStatelistener);
            } else {
...
    public void onLocationChanged(Location loc) {
        //Log.i(mTAG, "in onLocationChanged(Location loc)");
        if (Build.VERSION.SDK_INT > 16) {
            DeviceApi17.loadCellInfo(tm, mDevice);
        }
...
```

What to do?

**Comment by DJaeger** [comment]
As of our build.gradle the app supports API 16 and up.
So this class should not be used in API 16-17.
So you are correct, @E3V3A.

**Comment by E3V3A** [comment]
Ok, so who's changing it?  
* Should I rename the DeviceApi class? 
* Should I increase the **if**s? (Will that break anything?)
