### ISSUE TITLE
cell not in database

### ISSUE THREAD

**Issue by lop1** [SecUpwN/Android-IMSI-Catcher-Detector#564]
when my phone is connected to a rather distant BTS ( around 7 km from my house ), and this BTS is in the opencellid database, AIMSICD show a yellow icon (cell not in database).
It seems that the BTS should be within 5 km to be recognised by the app.

ps : It was retested several times, with several clean installs of the last build

**Comment by banjaxbanjo** [comment]
@lop1 have you gone to this area with your gps on and then downloaded cells for this area with app?

Even tho its in ocid it doesn't mean you have it downloaded.

**Comment by lop1** [comment]
hi,

it is clear that this BTS was not downloaded in the app. I drove to this BTS ( I know all of them by their first names ;-) ) and make a new download and this was fixed.

the problem is that after a new clean install, the app does not load the BTS that are a bit far away ( more than 5 km ?? ).

I understand that there must be a limit to the size of the download from opencellid , but in a low density place ( not in cities ) this limit is really a bit short as somebody launching the app will see a yellow icon sometime.

**Comment by banjaxbanjo** [comment]
The trouble is at the moment this app is very alpha and we change db design continously till we have it the way we want so if we change a column from text to int this will stop db from copying over your old saved tables. Bit like your installing app for first time with  no data

**Comment by DJaeger** [comment]
The app is downloading a maximum of 1000 cells in a radius of 2km arount you if you trigger the download.
This will be extended and is already filed in #303.

After downloading the state displayed in notification is not updated, so it will change not before restart app or cell change.
This will also be fixed and is filed in #558.

If your issue is another one, please clarify, what's your issue.

**Comment by DJaeger** [comment]
If your issue is one of the mentioned, please move there and close this.

**Comment by lop1** [comment]
My issue is that the app download 23 BTS , in these BTS there is not the one I am connected to which is 7 km from my phone. I am in a low BTS density place , and the BTS I am connected to is on a hill.
So when I launch the app the icon is yellow and stays yellow even after several re launch..

To clarify this , I drove to the BTS and  make a download near the BTS and then after re launch, the icon is green.

If you only download with a radius of 2km this behaviour is normal , but for the user it is a bit worrying.

May be a switch between high density places (cities) with the 2km radius and low density places (rural)  with a 20km radius will be a good way to solve this.

**Comment by E3V3A** [comment]
What @DJaeger said. AND...OCID DB doesn't contain all BTS, rather very far from all. You need to upload the BTS's you know are ok by using the OpenCellID's own app, or others... Go to their website and look for the [inViu OpenCellID](http://wiki.opencellid.org/wiki/Data_sources) app.

**Comment by SecUpwN** [comment]
Thanks for managing this, @E3V3A. I'll label this as `BUG` and `INVALID`.
