### ISSUE TITLE
Toggles are fantastic!

### ISSUE THREAD

**Issue by swordsteel** [SecUpwN/Android-IMSI-Catcher-Detector#567]
Hi Guys

Thanks for the new toggle features. This really helps to keep battery life going.
Would like to ask if you could impement a toggle for GPS, so cell monitoring can take place with or without GPS. This would really save on battery life.
Add to this, could you guys implement toggle on stingray detection?
This app is really starting to mature. Thanks for the hard work.

**Comment by E3V3A** [comment]
Thank you @swordsteel. But the toggles aren't that new. For additional features and request, please go through our current github issues, and feel free to make some Pull Requests to implement what you want. In your case, probably #309 among others.

**Comment by TPS** [comment]
FWIW, #898 contains docs with some Stingray details.

**Comment by webcoderz** [comment]
See if you can add it to the wiki or readme.txt

**Comment by TPS** [comment]
I think I _may_ have access to do so, @akrolla, but I'm not sure where/how to do so correctly, so I'm hoping @SecUpwN will comment @ #898 with some guidance.

**Comment by webcoderz** [comment]
Id lime to help with that can u send me a message with tour email so we can
correspond without dirtying up the hub?

**Comment by TPS** [comment]
Just communicate via #898.

**Comment by webcoderz** [comment]
Fair enough
lemme star that issue.

**Comment by webcoderz** [comment]
You know though this is a public forum and by discussing something like
this could lead to your door getting kicked in.
