### ISSUE TITLE
Fix and make DBV xml style sheet template

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#568]
We need to make a template for the xml stylesheets used in the Database Viewer (DBV). 
As a start I tried to fix the [dbe_import_items.xml]() style sheet that is used to display the `Imported OCID Data`. However, it seem that I didn't get it right. This is how it looks right now, and I don't seem able to get rid of the huge vertical space between the `tLast` (time_last) and `Source` (DBsource) items. 

![2015-07-21](https://cloud.githubusercontent.com/assets/194392/8808282/4bf84a02-2fea-11e5-9eeb-6e68bb16f85a.png)
 
In addition I'd like the *item counter* (here shown as `1/645`) to be 
1. shown on the right side and 
2. be right justified and
3. shown in blue.

**Comment by inderjeetuiet** [comment]
You can assign me this bug

**Comment by SecUpwN** [comment]
>You can assign me this bug

Woof, woof! :dog: You're "allowed" to take it, feel invited to craft a pull request.

**Comment by E3V3A** [comment]
It's already been fixed by @banjaxbanjo . However, the source and item counter should be separate entities.

**Comment by inderjeetuiet** [comment]
Ok I will do this minor change

**Comment by inderjeetuiet** [comment]
I have changed the color of item counter to blue and set item counter position to right i.e below tLast string value. ()
If you think it is fine I can create the pull request

**Comment by E3V3A** [comment]
Yes thank you,  please do. Could you please also have a look at the card inflater of the measurement table. I think i messed something up as it FCs when you try to open it.

**Comment by inderjeetuiet** [comment]
@E3V3A , I tried to reproduced the issue of FC on card inflater of measurement table, but could not. So any pointers toward this issue..

**Comment by E3V3A** [comment]
Most DBV issues are fixed.
