### ISSUE TITLE
Update Wiki Development Status

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#569]
We need to update the [Development Status](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status) as shown on our Wiki, to reflect new functionality and fixed items etc. Especially in the WIP section.

**Comment by SecUpwN** [comment]
I had advised @He3556 to do so last week and he told me this should be current. What is missing?

**Comment by E3V3A** [comment]
Hmm, ok
