### ISSUE TITLE
Fix spelling error DOWNLOAD_LOCAL_BST_DATA

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#570]
Fix the wrong spelling of `DOWNLOAD_LOCAL_BST_DATA` which should read `DOWNLOAD_LOCAL_BTS_DATA`. This is present [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/search?utf8=%E2%9C%93&q=DOWNLOAD_LOCAL_BST_DATA).

This problem also occurs in `help_app_download_local_bst` which are present [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/search?utf8=%E2%9C%93&q=help_app_download_local_bst).

**Comment by inderjeetuiet** [comment]
I would take this issue, would be good start to understand the code. Thanks

**Comment by E3V3A** [comment]
Thanks a lot @inderjeetuiet for helping us out wit this. And BTW Welcome to AIMISCD development!
