### ISSUE TITLE
FC when viewing BTS Measurements in DBV

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#573]
My current changes in cb7eb9a0973fe9f54ab7e62c51a93155ed49a2ed  trying to fix the layout XML of the complicated `BTS Measurements` table in the Database Viewer, causes a force close. I have no clue what went wrong, since everything else works. @banjaxbanjo or @DJaeger  Can you please have a look?

**Comment by E3V3A** [comment]
@banjaxbanjo I noticed you used *bb_power*, but I'm not sure where you got that data from since it showed a different value than in for *rx_signal*, and is not yet available from API. So I commented it out as it wouldn't compile my PR above. Perhaps that's the reason for broken measurements table in the DBV?

**Comment by banjaxbanjo** [comment]
@E3V3A I think I used rssi or dbm as I didn't know what bb_power was but that shouldn't cause any crash because them functions usually return a value. But better to comment out as these are not correct value for it as you said.

**Comment by E3V3A** [comment]
It was an index number problem.  Now fixed.

**Comment by SecUpwN** [comment]
>It was an index number problem. Now fixed.

@E3V3A, please link the commit here so that we can track it. Thanks.
