### ISSUE TITLE
Completely remove leakcanary code

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#574]
Evolved from the discussion in #455 we found that [leakcanary](https://github.com/square/leakcanary) does not improve our code development.

@E3V3A said:
>I hate leakcanary and really don't wanna see it back in here, confusing all the users and new developers, who would still remain clueless what to do about it.

@DJaeger said:
>I would leave it out too. I see no advantage of it over the already available debugging possibilities.

Is there any "alternative" you'd suggest using? Otherwise please **fully** remove leakcanary.

**Comment by E3V3A** [comment]
Well for now, the way to enable or disable it, is just a matter of a small edit of the gradle file (correct me if I'm wrong). So we can just leave it off, until further notice. If by the time we go beta, we still don't need it, then we can remove it permanently.

**Comment by DJaeger** [comment]
I agree with @E3V3A.

**Comment by SecUpwN** [comment]
Thanks guys. Shall I close this, or let this open until decided in `BETA`?

**Comment by DJaeger** [comment]
Close it.
It will be a new decision when it reachs beta state.
We should try to close as far as possible all issues before reaching beta state.

**Comment by SecUpwN** [comment]
>We should try to close as far as possible all issues before reaching beta state.

Fully agree on this. But in order to do so, we also need to move `#230` into our WIKI (or some place else) and make sure that Issues nearly solved (such as `#215`) finally get the requested response!

**Comment by DJaeger** [comment]
That's correct
