### ISSUE TITLE
Clearing logcat in "Debugging" drawer, causes reset of app

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#580]
If you go to the drawer menus and select `Debugging` and then choose `Clear`, the App resets and asks again about enabling GPS etc. Actually this is true whenever the location manager is not on. Very annoying. This is possibly related to #428.

**Comment by SecUpwN** [comment]
This Issue seems to be not present any longer. Case closed, feel invited to re-open if it appears again.
