### ISSUE TITLE
Re-implement deleting and resetting DB

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#581]
For some still unknown reason the possibility to clear and reset the AIMSICD DB was removed. The only comments present are these found in [AIMSICD.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/2626fa36168f4024fdc2e39955fabb58b51dd3ac/app/src/main/java/com/SecUpwN/AIMSICD/AIMSICD.java#L305-L309)
```java
        } else if (selectedItem.getId() == DrawerMenu.ID.SETTINGS.RESET_DB) {
            //Helpers.askAndDeleteDb(this); Todo this isnt a good method for deleting database
            // @banjaxbanjo  If it isn't good, that it not a good enough reason to remove it.
            // or what did you mean?
            // "If it ain't broke, don't fix."
```

Following this lead we get the following code segment in [Helpers.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/c48a65fc53fc634d7974c12d26f2065dae85c2f6/app/src/main/java/com/SecUpwN/AIMSICD/utils/Helpers.java#L583-L610):

```java
    /**
     * Very cool method. Completely erases the entire database.
     * Apply on medical prescription.
     * Also asks the user, whether he wants to erase its database ...
     *
     * @param pContext Context of Activity
     */
    public static void askAndDeleteDb(final Context pContext) {
        AlertDialog lAlertDialog = new AlertDialog.Builder(pContext)
                .setNegativeButton(R.string.open_cell_id_button_cancel, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        //Do nothing
                    }
                })
                .setPositiveButton(R.string.open_cell_id_button_ok, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        //FIXME need to remove hardcoded string into constants
                        pContext.deleteDatabase("aimsicd.db");
                    }
                })
                .setMessage(pContext.getString(R.string.clear_database_question))
                .setTitle(R.string.clear_database)
                .setCancelable(false)
                .setIcon(R.drawable.ic_action_delete_database).create();
        lAlertDialog.show();
    }
```

It's hard to tell if these comments is an attempt to be ironic, so it would be much more appreciated to rather describe the problem or present a method of solution. @banjaxbanjo  Can you please explain?

**Comment by banjaxbanjo** [comment]
@E3V3A this would cause app to crash if you delete the .db and a function tries to insert a value to a db that is not there. Maybe a dialog stating that the apps needs to be restarted once db is deleted or run the AIMSICDDbAdapter as soon as db deleted and this will create a freah db. 

It was broke eva that's the thing and as I said eva ye wanted db PR asap so didn't get around to doing it.

**Comment by E3V3A** [comment]
@banjaxbanjo 

> ...or run the AIMSICDDbAdapter as soon as db deleted and this will create a fresh db. 

That is a good solution. How to do that?

**Comment by banjaxbanjo** [comment]
Simple @E3V3A just do 
```Java
new AIMSICDDbAdapter(getApplicationContext());
```
Do this call soon as db deleted.

**Comment by E3V3A** [comment]
ok I did this, in: 1e017ef25e62a1b2bc1504d1433c1ba15a03777f
But app still FC... But reloads ok... 
Maybe more graceful way of doing this, or quitting? (Whatever works without FC.)

**Comment by banjaxbanjo** [comment]
Put it in Helpers.java eva because if the user selects no its still going to delete it where you have it now. Put it in the positive button after the delete db.

**Comment by banjaxbanjo** [comment]
Also might be a good idea to stop AIMSICD service before deleting db then start it after db is recreated this should stop any errors of classes accessing db.

**Comment by E3V3A** [comment]
Excellent! 

Also, after thinking about what you said before, I recalled: 

>  app needs to be restarted to not show already stored data in the DBV

That's right. Because the SQLite is in memory (and journaled) as long as app is alive.
