### ISSUE TITLE
PSC incorrect in DBV:EventLog

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#582]
The PSC shown in the EventLog in DBV is giving 2147483647 = 0x7FFF FFFF (MAXINT?) value...

**Comment by E3V3A** [comment]
> 9-bit UMTS Primary Scrambling Code described in TS 25.331, 0..511, Integer.MAX_VALUE if unknown

**Comment by banjaxbanjo** [comment]
Yep getting that value myself 2147483647, Funny thing is I seen this value 2147483647 in the (4636 Menu) screen on my Sony Xperia M in the neighbouring cells list.

**Comment by E3V3A** [comment]
> Funny thing is I seen this...

Nope, the funny thing is that PSC is working everywhere else! ;)

**Comment by SecUpwN** [comment]
Adding another strange thing: `CID`, `LAC` and `PSC` have been logged with MAXINT on my phone.

**Comment by E3V3A** [comment]
23 days and nobody else bothered hunting for this bug? May I proclaim this project development as dead now?

**Comment by SecUpwN** [comment]
>May I proclaim this project development as dead now?

No, you may not! It is simply the same old story happening here: We lack developers, because they get discouraged quickly due to us chasing them around. That is what it boils down to. And then, great developers like @marvinmarnold branch off our work and will likely face troubles merging back into our repo - which in effect means that he'll be doing his own thing (I'm just being realistic here and would love to be convinced of the opposite). @He3556 have you had this bug already?

**Comment by He3556** [comment]
Sorry i saw the 2147483647 = 0x7FFF FFFF and thought we already fixed it. But this was in another issue^^ where the object was instantiated to early in the code, so it got the wrong value. 
It might take a while to find this issue again. 

I see PSC = 0 on the db viewer (unique BTS) and on the main view
Sorry my EventLog has no entries.

**Comment by E3V3A** [comment]
@He3556 
> I see PSC = 0 on the db viewer (unique BTS) and on the main view

That is weird. It should never be 0 unless not available, are you sure you're on 3G (UMTS) and not LTE (which doesn't have PSC)?

**Comment by banjaxbanjo** [comment]
I've set psc in db viewer to 0 if that max value shows up, that weird value we keep seeing for psc 0xffffffff. Is this a problem?

**Comment by E3V3A** [comment]
Probably better to show max values, but since PSC can never be higher that 511, we can set bad PSCs to `666`!! :)

**Comment by SecUpwN** [comment]
>It should never be 0 unless not available, are you sure you're on 3G (UMTS) and not LTE (which doesn't have PSC)?

Instead of showing `**666**`, we should add some indicator that the value is not going to be displayed unless switching the network to 3G. But that could be solved with configuring the phone with #181 first.

**Comment by SecUpwN** [comment]
@banjaxbanjo, has https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/40098a0bd2ea8b3fa8da64e92ebfa7101f02f677 been merged already or is this one of the commits you deleted?

**Comment by smarek** [comment]
@SecUpwN afaik was not merged, should I provide it again as PR?

**Comment by SecUpwN** [comment]
@smarek, yes that would be lovely and hopefully eliminates this bug. :+1:

**Comment by banjaxbanjo** [comment]
@SecUpwN didn't merge sec nothing special just fixes the invalid psc values. If @smarek wants to bring it up to date that would be good.

**Comment by smarek** [comment]
Provided in #648
