### ISSUE TITLE
Possible helpful app & code: RoamingInfo

### ISSUE THREAD

**Issue by TPS** [SecUpwN/Android-IMSI-Catcher-Detector#584]
https://github.com/jbardera/RoamingInfo has just popped up in F-droid.  I would like to propose to have any developer evaluate its core idea ("Displays a notification with current operator's name and in case of roaming it also shows the original SIM's operator name" — i.e.: notify when the network operator changes, for good or ill) & code may be helpful in AICD's stated purpose re: IMSI catchers.

Thanks!

**Comment by E3V3A** [comment]
We already show this info...

**Comment by TPS** [comment]
Show, yes, but also keep track of when SIM/network operator changes, & then (perhaps) further determine if that's not good?  This is the question I have.

For instance, in an area (e.g., home) that I always have my native cell carrier's signal, suddenly, I only have access to a roaming provider, should I be flagged, further especially if it (somehow) can be determined this should not be so? Also, is this within AICD's scope?  These questions I'd like to propose to be answered.

N.B.: I'm not even requesting this even be implemented soon (*iff* the above comes out in the affirmative), but just to keep track of a possible enhancement for down the road, especially as there seems to mature public domain code available. AICD just now has already so many larger current issues to close!

**Comment by E3V3A** [comment]
> For instance, ...

That's what this app is all about.

**Comment by TPS** [comment]
Not sure I follow:

A normal IMSI-catcher, if I understand, will try to basically clone or pretend to be a native cell-tower (so, as femtocell) in a certain area.  If I'm understanding you, even if it is pretending to be a non-native (i.e., roaming) tower for my device, it'll still be caught?  Or, if I'm suddenly unexpectedly roaming where I shouldn't, AICD already catches that?

Reason I'm pursuing this is that, several weeks ago, I mentioned in #457 that I was going to travel to known femtocells in my area, but my tests were inconclusive.  I visited both native (Sprint) & roaming (Verizon) CDMA femtocell areas, & got no warnings. Now I'm wondering if the imported code is designed solely for native Verizon phones to catch Verizon femtocells.  Then this app popped up in the recent F-droid database update & seemed to fill that gap.  Any thoughts, anyone?

**Comment by E3V3A** [comment]
I don't have an CDMA device, please feel free to send me one... But there are other apps that detect femtocells and our femtocell code is 2 years old and not maintained. Feel free to post a PR to implement what you want, because I have no idea what you're looking for, that we're not already trying to do.
