### ISSUE TITLE
Wifi calling possibly causing false positives

### ISSUE THREAD

**Issue by cybrangl** [SecUpwN/Android-IMSI-Catcher-Detector#589]
I have a Tmobile phone, Nexus 6.  After installing the application everything was fine until I turned on wifi calling.  Once I turned on Wifi calling it showed a tower directly on top of me that was not in the database.  The "tower" would follow me as long as I have wifi calling on, even if I'm not connected.

**Comment by SecUpwN** [comment]
Welcome to our project, @cybrangl. Please make this a valid Issue by adding a proper [logcat](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues).

**Comment by E3V3A** [comment]
What is Wi-Fi calling? Link please.

**Comment by SecUpwN** [comment]
>What is Wi-Fi calling? Link please. 

I guess he is talking about calling via an app like [RedPhone](https://github.com/WhisperSystems/RedPhone).

**Comment by E3V3A** [comment]
What service are subscribed to? Wi-Max,  LTE ?
Screen shot of SIM info page?

**Comment by E3V3A** [comment]
[Wi-FI Calling](https://support.t-mobile.com/docs/DOC-22442) is essentially a T-mobile provided [ROM](http://phandroid.com/2015/05/26/tmobile-nexus-6-android-511-update-factory-image-download/) based on WiFi. We do not support ROMs, nor do we support tracking of WiFi as there are millions of apps already doing that. Case closed.

**Comment by cybrangl** [comment]
Well, that makes your app useless for anyone with Tmobile.

**Comment by E3V3A** [comment]
Eh,  no, it only prevents ignorant users from tracking things they're not connected to or even using.

**Comment by cybrangl** [comment]
Wow.  If your code is as bad as your attitude this things is going to end up bricking phone. I guess this is one project I won't support and definitely will not recommend.  I suggest a potential bug and all you give is an excuse and attitude as to why you can't be bothered to look at it.  If you hand out false positives the app i useless.  It can't be trusted to do what it was intended to do.  If you cannot trust the app, why use it?

**Comment by E3V3A** [comment]
Please keep your ignorant rants to yourself.  

What you're essentially asking here, is the equivalent of having an FM radio, then bitching about it to the manufacturer about not being able to watch satellite tv! :D

**Comment by SecUpwN** [comment]
@cybrangl, please excuse the harsh tone in this Issue. We're still working very hard to implement the basic functions we've planned to add - and all of that happens for free and with the few developers that we have. You may encourage our developers [dropping a coin](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Donations) though. Regarding your filed Issue here: Please stay patient until the upcoming release this sunday, our developers are coding core changes right now. Let me know in this Issue if the cupcoming version `0.1.34-alpha-build-00` will fix this. Thank you!

**Comment by TPS** [comment]
@E3V3A Wi-Fi calling is not "just" a ROM; it is now integrated into Android 5.1+ by Google itself, & is being extensively being used in its https://fi.google.com/ service on Nexus 6 & (rumors abound) more devices soon.  I think you may owe @cybrangl an apology.…

**Comment by E3V3A** [comment]
@TPS Thanks for clarifying, but I don't owe anyone anything, and in particular not to someone who's being rude! And as I've said, this app is not about WiFi, and if you need to locate WiFi AP's there are a million other apps to do that.

**Comment by DJaeger** [comment]
This app is not about WiFi, but it seems to get wrong information, if that feature is used.
So that feature seems to interfere with the radio data our app requests.
I think we should at least try to exclude these wrong BTS data by WiFi Calling.
I think the WiFi Calling presents a virtaal cell it is calling over to the rest of the AOS.

**Comment by SecUpwN** [comment]
>This app is not about WiFi, but it seems to get wrong information, if that feature is used.

Thanks for the clarification, this makes sense.

>So that feature seems to interfere with the radio data our app requests.
>I think we should at least try to exclude these wrong BTS data by WiFi Calling.
>I think the WiFi Calling presents a virtual cell it is calling over to the rest of the AOS.

Indeed. Would you please tackle this? I am re-opening this Issue until this has been implemented.

**Comment by TPS** [comment]
@SecUpwN Could the __Invalid__ tag also be removed until that is formally verified?

**Comment by E3V3A** [comment]
I love how clueless people insist in continuing in speculating on how this works.. Keep going folks! Love to see just how far you can go with `much ado about nothing`!

**Comment by SecUpwN** [comment]
>I love how clueless people insist on continuing speculations on how this works..

@E3V3A, were these words meant for me? I don't hope so.

>@SecUpwN Could the Invalid tag also be removed until that is formally verified?

@TPS, no I won't. It currently stays an `INVALID` Issue until @DJaeger kindly responds with a way how exclude wrong BTS data generated by WiFi calling. Furthermore, why the fuck is nobody respecting [THIS](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues)?

**Comment by E3V3A** [comment]
> So this man walk into the doctors office, and says; "My arm hurt when I do this" and he show the doctor what he does. Then the doctor answers; "well, stop doing that!".

So if our app is incompatible when using WiFi Calling, then bloody stop using it, or make a PR for fixing it.
