### ISSUE TITLE
Log should not show identifying information or location

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#599]
like CID, GPS LAT/LON...

**Comment by E3V3A** [comment]
Good idea for the internal Debug logger used for sending, but very bad idea for the general logcat! We're using it all the time to debug everything from cells db to map and ocid download etc. 

In addition, if your phone is rooted, ROM'd or you're using Google Play, Facebook or Whats App, all your data is everyone anyway! So what's the issue again? 

We can try to filter this...but it would require some work. Feel free with some code suggestions .

**Comment by SecUpwN** [comment]
There's this other app (not saying it's name here, you know which one), which already enables the user to craft a logcat without private data (at least that's what I think) - please have a look into it's source.

**Comment by agilob** [comment]
The problem is not to hide that data from facebook or google, but from other users and developers. Then people submit issues on github with logs they very often manually remove location from logs.

>We can try to filter this...but it would require some work. Feel free with some code suggestions .

Set system variable in Gradle, use this variable on compilation stage to hardcode boolean value. If value is true then you have location logs enabled, false means app is in production mode and location is not printed. Several lines of code.

**Comment by E3V3A** [comment]
@agilob That sound like nice solution. How would that code look like?

**Comment by DJaeger** [comment]
@agilob: Great idea.
If buildType is release location should never be logged.
Would you do a PR for this?

**Comment by E3V3A** [comment]
It's not a bug, and there's no response and no PRs on the horizon. So we close.

**Comment by SecUpwN** [comment]
>It's not a bug, and there's no response and no PRs on the horizon. So we close.

I basically agree with you, @E3V3A. But please do not close important Issues like this one too fast until we've send out another reminder to the person who published the solution. @agilob, would you please respond to https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/599#issuecomment-128270950? I will then re-open this Issue and it would be lovely to receive your PR then.

**Comment by agilob** [comment]
@E3V3A take a look at com.fitchfamiliy.android.wifi_backend, it offers different debug levels to be set in preferences.

**Comment by agilob** [comment]
Please reopen.
