### ISSUE TITLE
Silent SMS notification should be silent

### ISSUE THREAD

**Issue by solsticedhiver** [SecUpwN/Android-IMSI-Catcher-Detector#600]
If I understand correctly, AIMSICD detects silent SMS and vibrate in that case.

I found in my particular case that feature not diserable.

Would it be possible to turn off the vibration and instead use a configurable sound like the default SMS notification sound. Or better no sound even if in that case, you can't be warned at all about a silent SMS.

**Comment by solsticedhiver** [comment]
As a sidenote, I became aware I was being sent silent SMS with pushbullet. It showed me for a fraction of a second empty notifications on the screen of my PC.

**Comment by E3V3A** [comment]
Hi @solsticedhiver, thanks for joining us. We're currently working on the notification features in #15, but feel free to make some PR for faster progress.

**Comment by SecUpwN** [comment]
@E3V3A, should I rename `#15` to `Alarm Notification on Attacks` and close this as `DUPLICATE`?

**Comment by DJaeger** [comment]
@SecUpwN: I would say yes.

**Comment by E3V3A** [comment]
sure
