### ISSUE TITLE
Unique BTS Data stays empty

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#601]
I am unsure if we have already filed this in an existing Issue, but it appears that I do not get any "Unique BTS Data" at all - the table stays empty all the time. Appears since long before our database overhaul.

**Comment by E3V3A** [comment]
Funny, Works for me...

**Comment by DJaeger** [comment]
It's empty for me too.

**Comment by E3V3A** [comment]
Really??
What do you mean *empty*? Like not showing anything at all, or showing the column names but without data?

**Comment by DJaeger** [comment]
Mhm, now it works for me.
I'm not sure if I have done a update in the meantime.

**Comment by DJaeger** [comment]
I have still only that single unique entry I have seen on my last comment 2 days ago.
In addition, if I open the map it shown my current lication and than moves to the location I was at, when I have first seen this entry and says I'm connected to a cell tower there.
But it is far away and I wasn't there since two days.

**Comment by SecUpwN** [comment]
>What do you mean *empty*?

I mean that the page `Unique BTS Data` on our app stays empty. Not sure how to check if data even really gets collected since my AIMSICD folder only appears to contain the downloaded OCID .csv file.

**Comment by E3V3A** [comment]
Does somebody else have this problem?

**Comment by SecUpwN** [comment]
>Does somebody else have this problem?

@banjaxbanjo and @He3556 what is your test result?

**Comment by banjaxbanjo** [comment]
@SecUpwN I don't have this problem I get multiple entries.

**Comment by E3V3A** [comment]
@SecUpwN  Can you please send us a logcat + screen shot when enetring this DBV, because it seem to be a problem only you have... Otherwise please close the issue.

**Comment by SecUpwN** [comment]
>Can you please send us a logcat + screen shot when entering this DBV

Not sure how to take this logcat. Just letting catlog run and entering `Unique BTS Data` via the `Database Viewer`? In fact, `BTS Measurements` and `Measured Signal Strengths` also stay empty.

**Comment by DJaeger** [comment]
Have you done a clean installation, activated GPS and waited?
That is was what I have done to get it to work.

**Comment by SecUpwN** [comment]
>Have you done a clean installation, activated GPS and waited?

Thanks for the hint @DJaeger, but it stays the same. How long did you wait? Maybe we should prompt for the GPS activation again when opening tabs requiring GPS data in the `Database Viewer`?

**Comment by E3V3A** [comment]
You need a GPS lock

**Comment by SecUpwN** [comment]
>You need a GPS lock

If I turn on GPS and then also turn on the GPS monitoring within our app it still doesn't work. If that is not what you actually meant, please be so kind to clarify. Thank you!

**Comment by hellyberry** [comment]
I experience this also on SGS4, Android 4.4.4 and aimsicd Version 0.1.3.4.-alpha-b00.
Is the newest aimsicd Version code changes reviewed? Log appended.

**Comment by He3556** [comment]
sorry we have to close a few issues - i this still needs clarification pls let me know.
