### ISSUE TITLE
Please add Dutch translation

### ISSUE THREAD

**Issue by johanw666** [SecUpwN/Android-IMSI-Catcher-Detector#602]
I want to contribute to this project, but I don't see any immediate programming points I can quickly pick up. However, I can work on a Dutch translation if it can be added.

**Comment by DJaeger** [comment]
You can add a new language in Weblate under the existing languages

**Comment by johanw666** [comment]
Ah, I had to login first to see that option. Sorry, I was unfamiliar with the system.
