### ISSUE TITLE
0.1.33-alpha-b00 crashes consistently

### ISSUE THREAD

**Issue by pysiak** [SecUpwN/Android-IMSI-Catcher-Detector#604]
I just installed 0.1.33-alpha-b00 from f-droid on my old Android 2.3.6 Samsung Galaxy S Advance.
No error messages. Previous (0.1.32-alpha-b00) didn't crash.

Sorry for a vague report, but there's something in there crashing it.

**Comment by TPS** [comment]
@pysiak Please see #596 & #597.  TLDR: In-place update isn't yet officially supported, & wiping the data from Android app settings & rerunning AICD should get you back on your way

**Comment by E3V3A** [comment]
We don't support lower API than 16 which is Jelly Bean 4.1.

**Comment by TPS** [comment]
@E3V3A I didn't know that API requirement.  @pysiak did claim that 0.1.32-alpha-b00 did function, @ least somewhat on 2.3.6.…  What shouldn't have worked, or is the 4.1 requirement new as of 0.1.33-alpha-b00?

**Comment by E3V3A** [comment]
So send a logcat.

**Comment by pysiak** [comment]
1) uninstalled from f-droid, installed again and it works, thanks
2) sorry for confusing you with 2.3.6; I mixed up my phones. I'm running 5.0 and 2.3.6 is an old crap phone I was reporting an issue with for a completely different app that day.

Thanks!

**Comment by elfevenfairy** [comment]
What do you run when your on a computer? Thank you for helping me I'm
trying to learn all of this.

**Comment by SecUpwN** [comment]
>What do you run when your on a computer? Thank you for helping me I'm trying to learn all of this.

@elfevenfairy, please don't get me wrong, but you're spamming across our Issues list and seem to be another bot. I reported you to be checked by the GitHub security team. Don't take it personal. Thanks.
