### ISSUE TITLE
Localization: How to translate style type "Sense"?

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#609]
In `Preferences` our users are able to select a style for the [Status Icons](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Status-Icons):

**English**
* Flat
* Sense
* White

**German**
* Flach
* Sense
* Weiß

The word "Sense" has not been translated across all languages. Just recently I have received the suggested German translation "Gefühl", but is this really matching the case? Professional help?

**Comment by E3V3A** [comment]
These are names ,not to be translated..

**Comment by agilob** [comment]
Personally, I would see them removed and keep one flat theme included.

**Comment by TPS** [comment]
@agilob That defeats the purpose of _options_, no? ;)

@SecUpwN As @E3V3A said, Sense is a theme name (HTC's, I think) that isn't translated in any language, but simply kept as-is, AFAIKT

**Comment by E3V3A** [comment]
@SecUpwN  Please close this issue as it's not an issue.

**Comment by SecUpwN** [comment]
>Sense is a theme name (HTC's, I think) that isn't translated in any language, but simply kept as-is

Ok, this answers this Issue. I just filed it because Weblate keeps complaining. Thanks for helping guys!

**Comment by agilob** [comment]
>@agilob That defeats the purpose of options, no? ;)

do you know any other application that offers different icons? tray icon is like ID of an application and it should be consistent across platforms, devices and versions.

**Comment by SecUpwN** [comment]
>do you know any other application that offers different icons?

No, I don't. But our app is neither like "any other app", nor do we *have to* offer only one style. When we created the Icons, we discussed that at length and decided that all three styles had their own right to exist. So in my yes, having the choice is better and really is no Issue at all. Thanks for helping, @agilob!
