### ISSUE TITLE
I'm permanenltly leaving this project, thank you and goodbye!

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#621]
To all of you who have been a great inspiration and driving force behind this project, I just want to say:

**THANK YOU!**

I've now after many difficult tours and turns decided to finally exit this project permanently. So please respect my decision for doing so, by **not** tagging me, emailing me, or in other ways trying to contact me regarding this project.

I hope you understand. 

Good Luck.

**Comment by He3556** [comment]
I am respecting your decision - but there is a big part missing now. 
Thank you, for your time and energy you have put into this project. 
We will keep it going...
