### ISSUE TITLE
Six to Nine BSTs sitting in my back yard

### ISSUE THREAD

**Issue by Gnashspike** [SecUpwN/Android-IMSI-Catcher-Detector#624]
ATTENTION! Please describe the problem you had, before sending us these logs. NO HELP WITHOUT DESCRIPTIONS!

I've read the GitHub discussions regarding all the "holy shit I'm attacked!" emails, as well as the "lively" discussions between developers and SecUPwn, I'm sorry to see E3V3A left the project and I hope you've found a suitable replacement for one so adamant and stalwart. That said, please forgive my ignorance if this is submitted to the wrong category; I did attempt to set it in "BUG" but not sure I did it correctly, so I'm submitting this for... posterity, if you will, with apologies up front.

I don't "need" an answer, nor help really, as I've been harassed and eavesdropped (even repeatedly burglarized: the kind of trespass designed to mind-fuck the target; called "black bag jobs", multiple times to my apartment and both vehicles, plus tons-o-fun nightly property damage and vandalism; cops notified numerous occasions, blah, blah, blah...) going on five years now. I'm fortunate (or blessed, idk) to be intelligent enough to observe and discern. Every time I've uncovered/discovered another "protocol" and announced to them via my baritone voice box from my back yard, the perp(etrator) implementing that failed scheme gets moved out and another renter takes his/her/their place. Moving van (the EXACT same U-Haul truck) has been to every surrounding house at least 2 times this year, and has appeared EVERY month, sometimes twice a month, once, three times. It takes these renters no less than 72 hours to fill the overcab van's storage, done mostly at night. If that all sounds odd, well, you don't know much about gang stalking! No worries, nothing you can do about it.

I also understand and have read about the button remaining yellow, or could someone from dev team, or tester, etc. give a thumbs up, or whitelist unidentified towers. Please, DO NOT ALLOW TESTERS TO WHITELIST ANYTHING, nor give a green light, etc. That should be done only by someone from OCID or by you devs personally, at worst, via a valid, unspoofed vid-link from known testers. If I didn't already know what kind of neighbors live around me I'd have dumped your app due to 'false positives' or 'broken gps'. BUT, because I've had TWO phones (a 3G and 4G android) in the last YEAR "air-bricked", one number purchased from Straight Talk wireless by the FCC to pursue the cloner(s), I know better. I'm going to beat the shit out of this app uploading info to OCID. I won't stuff your inbox with any more of these unless it's specifically requested. These techie punks aren't anything me and my laser-guided blow gun can't handle... JK.

However, I think 6-8 towers sitting on top of me is a bit much. After my first info upload to OCID, the number of towers went from 6 to 8, then to 3, then none (zero) then shot up to 9, back down to 7, then 5, now at 6... ALL WITHIN THE 80 FOOT RADIUS OF ERROR OF MY PHONE.

Over the last 3 hours I've watched these "towers" move around (so has the app) and converge then disperse. Only one has moved outside my phone's 'radius of error' and it only move a block and a half away. Incidetally, when using any of my "find my phone" features it's location has always been EXACTLY one of these (very) local towers' locations. Is it really possible to have more than one BTS on my almost exact lat/lon location? ATM, I've got NINE. >.<

Please help with any info I can use to nail these fuckers to the wall, or tower as the case may be. Send hints as to best times/intervals to upload.

The only other 'problem' is AIMSICD will simply freeze and shit all over itself; buttons become unresponsive and quite often the "upload BTS info" never happens (is jammed? Yeah, I also looked at the PKI Electronics site...).

Thanks heaps for this (alpha) app. I'll be plastering your app all over Googl+ in a few minutes. Your endeavors, and service to this country, are greatly appreciated and duly noted. Deserving of a Nobel Prize this is. =)

**Comment by agilob** [comment]
>However, I think 6-8 towers sitting on top of me is a bit much. After my first info upload to OCID, the number of towers went from 6 to 8, then to 3, then none (zero) then shot up to 9, back down to 7, then 5, now at 6... ALL WITHIN THE 80 FOOT RADIUS OF ERROR OF MY PHONE.

AIMSICD sends fake and temporary BTSs to online services. Most probably you were a victim of
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/411
There might have been a network reconfiguration around you, there were not many reports about the "new" BTS and you send it, online services verify your uploads and remove those with fake data.

**Comment by andr3jx** [comment]
@SecUpwN  **Somebody with EDIT rights please remove immediately this log from here. It contains private location info.**

**Comment by agilob** [comment]
@andr3jx https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/599 apparently it's not a problem in AIMSICD... Thanks EVA.

**Comment by andr3jx** [comment]
@He3556 @agilob this is totally unacceptable in my opinion. This needs to be fixed.

I'm also of the opinion that @Gnashspike doesn't have convincing data for the existence of fake BTS. Actually his phone is in 3G mode and 3G fake BTS can not be detected. Only if his phone is downgraded to 2G it might be a fake BTS.
In this state the app is close to snake oil (therefore it is alpha).

**Comment by He3556** [comment]
Sorry for delay.
I am not sure whose data this is - so i backed it up on my local machine but deleted it on the post. 
Thanks @andr3jx for taking a deeper look into this.

**Comment by darkerego** [comment]
I notice this all of time. The blue 'currently connected BTS's' follow me everywhere. I assumed it was a glitch, because this is how it's been since I started using this app. Sometimes there will be like 10 of them around me, and than over time that number will drop. 

What is strange though is that when using RFSignalTracker (or maybe its called rfsignaldetector) it says Im always connected to a cell that is 5000 miles away in the middle of the atlantic ocean. I attributed that to a glitch as well.

Also every single time I listen to a voice message, after the voice mail is deleted, I get a "MWI" warning.

**Comment by agilob** [comment]
@darkerego it's another bug I reported that eva thinks it's not a bug:
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/471

**Comment by darkerego** [comment]
@agilob I believe that this is what happens:

If I am tracking cells with the app, while say, walking down the street, the app will not take measurements because I am moving around, as I can see in the debug logs. But, if I stop and stand still for a second, it starts taking measurements. This is when it leaves one of those 'blue circles'. I think it's actually a measurement of a BTS, shown where the measurement was taken. Does that make sense?

**Comment by felixhcat** [comment]
If that is the case (which I had assumed it was-- that the map shows the measurement locations, not the towers themselves) why don't they use some kind of crowdsourced triangulation where known variables are used to solve for the towers more accurate location? (signal strength and error & measurementPos and error) 

Is that a crazy idea and impossible for some reason? Or is the OCSI database inherently flawed?

**Comment by SecUpwN** [comment]
@agilob, thanks for taking care of this Issue filed by @Gnashspike, even though not proven. I am re-opening #471 since this seems to be the core of this experience, please continue discussion there.
