### ISSUE TITLE
Add to AIMSICD info about used A5X cipher.

### ISSUE THREAD

**Issue by billionaire** [SecUpwN/Android-IMSI-Catcher-Detector#625]
Hello.
I liked the app AIMSICD. You are doing a great job.
But, unfortunately, on my device, it does not show the current level of encryption of data between my phone and BTS (a5x is always n/a).
But I found an application that displays which the cipher is used: https://opensource.srlabs.de/projects/snoopsnitch
Can you add to AIMSICD display information about a cipher?
Thank you.
Sincerely.

**AIMSICD version:** 0.1.34-alpha-b00
**Phone:** Sony Xperia Z3 compact (D5803)
**Processor:** Qualcomm MSM8974PRO-AC
**Android version:** 5.1.1
**Kernel Version:** 3.4.0-perf-g5c87ba0-02008-gbe52486 BuildUser@BuildHost #1 Tue Sep 17 15:00:01 2015
**Build Number:** 23.4.A.1.232
**RIL version:** 53
Xprivacy not installed.
![aimsicd](https://cloud.githubusercontent.com/assets/6255854/10459064/82344070-71d6-11e5-8c44-0dc69ee59002.png)
![snoopsnitch](https://cloud.githubusercontent.com/assets/6255854/10459065/8237d410-71d6-11e5-8ce7-754888dcfffe.png)

**Comment by andr3jx** [comment]
We are aware that the app can't show the ciphering algorithm. Thanks for the suggestion but I don't see it being implemented any time soon. 
Snoopsnitch has great features and works stable but unfortunately only runs on some rooted Qualcomm phones. I advice you to keep using it if you have the luck that it supports your phone. AIMSICD doesn't come close to Snoopsnitch at the moment.

**Comment by He3556** [comment]
thanks @andr3jx - i can close this i guess...

**Comment by SecUpwN** [comment]
Thanks for responding here, guys. Am I right when guessing that their app can only detect the Cipher because they have access to the necessary baseband variables or would we be able to extract this another way?
