### ISSUE TITLE
Issue/Question??

### ISSUE THREAD

**Issue by playalistic** [SecUpwN/Android-IMSI-Catcher-Detector#626]
Ok....so in "Antenna Map Viewer," while I'm at my house or surrounding areas with my phone's gps on, indicator shows that I am constantly connected to a "new or recently added BTS" that appears as a orange circle with a "2" in the middle and is directly on top of my, or my neighbor's house; as if I'm connected to two new or recently added towers that are always directly over my, or my neighbor's house. Now I know there is no BTS tower in this immediate vicinity, though i get no alert to being in an insecure area, engaged in active tracking, being tracked down, or to RUN! Handset Manipulated! This not only concerns me as far as a potential "issue" goes, but for other obvious reasons too. Could someone please guide me on what is happening?

**Comment by agilob** [comment]
Antenna map viewer is broken, shows cells in wrong locations, shows duplicates of cells (in wrong locations), also if you get yellow and have a blue cell just where you stand, it's another bug.

**Comment by playalistic** [comment]
Well i certainly do appreciate the prompt response. So theoretically, I can assume that the app's alert will still sound and notify me to an actual "IMSI-Catcher" threat and it's threat level to the best of it's current capabilities regardless of what the antenna map view indicates? Furthermore, any eta on when the broken map viewer function will be fixed, as it would be a very beneficial and informative tool?

**Comment by agilob** [comment]
>it's threat level to the best of it's current capabilities regardless of what the antenna map view indicates

the detector works correct on friends Samsung A3, but for me (S3 with CM) it **has 100% false positives** since February (since then I never had green, icon is always yellow) so I guess this might be something device dependent and bug in the code which I'm investigating.

**Comment by playalistic** [comment]
Thank you very much for your discernment & troubleshooting efforts since Feb until now. I'm not clear as to whether you're writing that the false positives regard ''Antenna Map View" specifically or also the app's "IMSI-Catcher" alert features (or lack there of) overall, regardless of device, though based on your observations, maybe it's better that I run a build dating before 2/15? Again, antenna view is not my main concern but accurate alert of man in midd is. Thank you again and any further explanation, instruction, or clarification to my immediate concern would be much appreciated! No matter it's status now, this app has the potential to be a huge asset to the mass's fight for freedom and our right to privacy and I certainly appreciate the dev's efforts and hope you all will continue to refine/perfect this valuable tool.

**Comment by DJaeger** [comment]
He means both.
Under specific conditions the mapviewer doesn't work and under specific conditions the generel alerts doesn't work.
In a build of before 2/15 are much more other bugs and are not garanteed to work in anyway.
So please be patient until we fixed the issues.
