### ISSUE TITLE
Optimize system permissions 

### ISSUE THREAD

**Issue by He3556** [SecUpwN/Android-IMSI-Catcher-Detector#636]
Delete unnecessary access, for example to the phonebook and other recourses we don't need. 
**EDIT by SecUpwN:** Also see [Stackoverflow: Clean up unused Android permissions]( http://stackoverflow.com/questions/18362305/clean-up-unused-android-permissions).

**Comment by SecUpwN** [comment]
Thanks fr filing this, I've been receiving multiple requests from concerned users. Just to clarify for the people reading this: We started using all permissions possible since we did not know which permissions may be necessary in the future to collect necessary variables needed for our App to work properly. But since it is currently pretty useless doe to its bloated code and few functions, we really need to clean up unnecessary things - and granted permissions are on the top of that list. Which permissions shall I remove, @He3556?

**Comment by He3556** [comment]
Error:Execution failed for task ':app:proguardRelease'.
> java.io.IOException: Please correct the above warnings first.


was ist proguardrelease? das ist der Fehler den ich seit 2 Monaten bekomme wenn
ich die Release mache.

**Comment by smarek** [comment]
Also if we're going to support Marshmallow (API 23) and compile the project against it, we'll be able to request permissions on runtime, not having to request all of them as mandatory in manifest.

@He3556 proguardRelease is task to trim down the APK size and resources, that are not used (ie. included and not used libraries code, etc...)  

For me current master fails with `MissingTranslation` errors in `:app:lintVitalRelease` task
About Proguard, this is output that can shoot down the release build for you
```
Note: there were 157 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: com.kaichunlin.transition.DefaultTransitionManager$1: can't find referenced method 'float getStart()' in program class com.kaichunlin.transition.Transition
Warning: com.kaichunlin.transition.adapter.AdapterState: can't find referenced class com.kaichunlin.transition.adapter.AdapterState$State
Warning: there were 1 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 1 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
```

We need to track them down and fix the `app/proguard-rules.txt` definition

**Comment by He3556** [comment]
Thanks @smarek - i tried to add  '-dontwarn' like (here http://stackoverflow.com/questions/29954434/gradle-issue-you-may-need-to-add-missing-library-jars-or-update-their-versions) but it didn't worked.

**Comment by smarek** [comment]
@He3556 from my experience, you have to obtain verbose log of the Proguard and go library by library to configure it right. We already have default SDK provided `proguard-android.txt` included so that should solve majority of issues.

**Comment by SecUpwN** [comment]
>For me current master fails with `MissingTranslation` errors in `:app:lintVitalRelease` task
>About Proguard, this is output that can shoot down the release build for you
```
Note: there were 157 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: com.kaichunlin.transition.DefaultTransitionManager$1: can't find referenced method 'float getStart()' in program class com.kaichunlin.transition.Transition
Warning: com.kaichunlin.transition.adapter.AdapterState: can't find referenced class com.kaichunlin.transition.adapter.AdapterState$State
Warning: there were 1 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 1 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
```

>We need to track them down and fix the `app/proguard-rules.txt` definition

Thanks for informing us, @smarek. Not siure if you can fix what you've detected, but I've been thinking to let [Buildozer](https://buildozer.io/) autoamtically build our releases as well, but I've been a bit reluctant about that until now since I'd have to add our release key to our account there. They previously told me that the key is being stored securely and ONLY being used during the signing process, but should we do this?

**Comment by smarek** [comment]
Well I'm still against uploading your key into any cloud-based service, so I'll try to fix the build first

**Comment by He3556** [comment]
Thank you @smarek, 
sorry that i can't really help here. But good to know it's not my IDE that is causing the trouble.

**Comment by smarek** [comment]
Good, we solved the OT discussion about Gradle with #643 so now for permissions optimalization :+1:

**Comment by SecUpwN** [comment]
Thanks again @smarek for your improvement on git versioning! Let's continue with this very important Issue. Question is, how can we use as few permissions as possible, but still make our app work for as many devices as possible? And is there a way of checking which permissions are permantently needed?

We should probably also throw out deprecated permissions:

```JAVA
    <!-- possibly deprecated -->
    <uses-permission android:name="android.permission.RECEIVE_EMERGENCY_BROADCAST"/>
    <uses-permission android:name="android.permission.READ_NETWORK_USAGE_HISTORY"/>
```

**Comment by SecUpwN** [comment]
I've been in touch with @tobykurien and he just sent me these important hints:

>Unfortunately that's not simple, as far as I know. I did have a look after I received your e-mail from a few days ago. See here: http://stackoverflow.com/questions/18362305/clean-up-unused-android-permissions

>Basically:
>- try the apkinspector tool (https://github.com/honeynet/apkinspector/) which might tell you where permissions are used. I've never used that tool before.
>- remove permissions one-by-one and test THE WHOLE APP (including code paths that are triggered by network events, GPS, movement, etc.) and look for SecurityException being thrown. Obviously this is not practical for your app.

>Note that the permissions model changed in Android 6, so a lot of additional code will need to be added to support it.

**Comment by He3556** [comment]
Thanks for your research @SecUpwN 
No.1 Summary from the developer: "So, well, it doesn't really work but at least it was interesting. "
No.2 seems outdated (2012, Android 4.1.1.)

Since we have the repository [permission-cleanup] (https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/tree/permissions-cleanup) i would just kick out Camera, Microphone and Contacts and test it. 
Maybe not bad to use this plugin from the first link. You can install it on Android Studio and see if there are any problems. Only if we want to tighten permission to a maximum we can run in trouble and the plugin can't help us with that.

**Comment by SecUpwN** [comment]
@He3556, thanks for your kind words. Below are the permissions I kicked so far. Anything else to kick?
```JAVA
-    <uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED"/>
-    <uses-permission android:name="android.permission.NFC"/>
-    <uses-permission android:name="android.permission.READ_CONTACTS"/>
-    <uses-permission android:name="android.permission.USE_SIP"/>
-    <uses-permission android:name="android.permission.RECEIVE_EMERGENCY_BROADCAST"/>
-    <uses-permission android:name="android.permission.READ_NETWORK_USAGE_HISTORY"/>
```

**Comment by smarek** [comment]
Closing because #649 was merged

**Comment by larsgrefer** [comment]
reopen because of https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/649#issuecomment-162476210

**Comment by SecUpwN** [comment]
@larsgrefer, did you run an analysis with [APU](https://github.com/RomainPiel/AndroidPermissionsUsage) yet? Anything else needed to solve before until closing?

**Comment by larsgrefer** [comment]
No, I have not tested yet

**Comment by SecUpwN** [comment]
>No, I have not tested yet

Please do and let me know if I shall change anything else before clsoing this Issue as solved.
