### ISSUE TITLE
Coding guidelines: Comments usage

### ISSUE THREAD

**Issue by smarek** [SecUpwN/Android-IMSI-Catcher-Detector#642]
Let us demonstrate the problem on current (or proposed update) of `AIMSICDDbAdapter` class

Current: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/25616a0fc0d185aa9e07c92ee5abddb0094ff4fd/app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java
Proposed: https://github.com/smarek/Android-IMSI-Catcher-Detector/blob/class-cleanup-3/app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java

What are the questions:
  - Can we simply remove comments which are just *discussions* ? (ie. `banjaxbanjo: What do you mean?`, `EVA do I need to update an already known cell?`)
  - Can we slim down the comments (class, function, field) to effective javadocs for developing, with additional explanation on how the function works (using javadoc `@see` to refer to other methods, classes, ...) ?
  - Should we keep TODOs in comments to classes? 

This class is not a rarity, all the classes have the problems, apart from deviating from coding standards, however the comments make the refactoring implementation much more painful, because it's hard to make changes, when there is not centralised issue management (issues / ideas / ...) are duplicated between source and issue tracker here on github, and from comments it seems like that there is currently somebody else working on the same particular part of code.

Can you provide your opinions please @E3V3A @SecUpwN @He3556 ?

**Comment by He3556** [comment]
Basically i like the additional information about every line of code and i know that EVA put a lot of work into it. But on the other hand i understand that it is a pain to update all the information, when changing the code. So we have to change it to a standard level. 

Maybe we first set up some scheme of an external documentation, where we can copy and paste the information from the source code (not all 1:1) at a later time. 

We already have a [Technical Overview] (https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Technical-Overview) where i would start with structuring. 
Just an first idea...

**Index:** 
* Database (like the diagram we have, explantation of the tables and where the inserts and deletes happen)
* Main Classes (where are the Objects instantiated and what attributes and methods do they have) 
* Classes and methods of detection (see above)
* Setting and configuration values 
* Import/Export (DB) and external data (OpenCellID), where is this processed 
* Important details (like the fallback, for neighbouring cells on Samsung Devices, or detection of Silent-SMS, false changing LAC alarm...)

We can link to the issues and the files that belong to each point. 
i am sure there is more to put on the list.

**Comment by DJaeger** [comment]
* I think discussions should be minified to a NOTE.
* Using javadoc style would be great a can prevent documenting multiple times (code & wiki).
* We should create issues for the TODOs, label them in an declarative way and remove the TODOS in the comments, to have them all in one place.

**Comment by agilob** [comment]
Just one thing:

documents what's not obvious and what's important.

Documentation of setters like:
```
/** 
 * sets LAC
 *
 * @param lac lat to set
**/
```
is so goddamn pointless, avoid it.

AIMSICD is not a library so there is no point in documenting everything extensively like Java/Android is documented. Keep it simple, use javadoc, don't develop new standards or formatting or schemes, use githab for chatting.

**Comment by smarek** [comment]
Also I'm missing some documentation on database columns, ie. what's meaning of `DF_id` and `DF_description` ? Could anybody with deeper understanding of current DB model document on `app/src/main/assets/aimsicd.sql` file please?

**Comment by He3556** [comment]
it's already there:  
Line 29 * DetectionFlags.csv	# Detection flag descriptions and parameter settings,
Thats why i like something like [Technical-Overview] (https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Technical-Overview)

I also don't want to invent a new scheme but if we use javadoc we just have a few hundert lines of documentation taken out of the comments in the code. I was thinking about an top down approach of the things that are really important. 
But right now, when i take a look at the "technical overview " i think we can delete it. 
This (old) information doesn't really help anymore.

**Comment by SecUpwN** [comment]
>But right now, when i take a look at the "technical overview " i think we can delete it.

Delete `Technical Overview`? Why not update it accordingly?

**Comment by larsgrefer** [comment]
Thoughts about some parts of the (javadoc-) comments:
- `Description:`
  - Don't prefix the description with `Description:` in order to be more javadoc-like
- `Issues:` and `Todos:`
  - Don't track this in comments
  - Better track them here at github (or another bugtracker)
- `Changelog:`
  - Don't track this in comments
  - We have `git log -- <file>` and `git blame <file>` for that
- In general the javadoc comments should be more javadoc like:
  - Use HTML tags like `<p>` and `<a>`
  - Use things like:
    - `@see`
    - `@author`
    - `{@link <method|class|field>}`

About discussions:
- Don't keep discussion in source code comments
- Use line comments at github for that

About source code comments vs wiki:
- Use source code comments for (technical) information/documentation about a particular class/method/field
- Use the wiki for overviews, manuals and so on 

I think this project has too much and too detailed documentation which is bad in two steps:

1. Its too much work to keep code and documentation in sync
2. Someone won`t do the work to keep them in sync, so they get out of sync which will make the complete documentation useless

In my opinion its better to have less documentation which is up-do-date than having too much documentation which needs to much work and becomes out-of-date

**Comment by SecUpwN** [comment]
>In my opinion its better to have less documentation which is up-do-date than having too much documentation which needs too much work and becomes out-of-date

Fully agree on this. @larsgrefer, have a look at [General Overview](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/General-Overview) and [Technical Overview](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Technical-Overview). As well, we have a page called [Development Status](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status). Generally speaking, someone needs to review our whole WIKI and see where stuff can be slimmed down. It seems that our app code still needs heavy lifting to eliminate the bloating comments and conversationsmentioned by @smarek in the OP, I guess.

**Comment by larsgrefer** [comment]
About the wiki-pages:
- General Overview
  - looks good to me
  - low risk to become out-of-date
- Technical Overview
  - looks good too
  - maybe needs some work to be kept up to date
- Development Status
  - **Already accomplished**-Section
    - Aren't these just resolved issues and merged pull requests?
    - Much work to keep up-to-date
  - **Working on right now**-Section
    - Better track this as open issues?
  - development stages
    - Better use milestones and issues for this?

**Comment by smarek** [comment]
@larsgrefer "Already accomplished" and "Working on right now" is imho duplicate to issues and changelog. If anything, I'd keep "Already accomplished" only for achieved long-term (big) goals, not for everything we touched on the way.

**Comment by DJaeger** [comment]
I fully agree with @larsgrefer

**Comment by SecUpwN** [comment]
@larsgrefer, shall I place https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/642#issuecomment-162463128 into our [Style Guide](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Style-Guide)?

**Comment by larsgrefer** [comment]
@SecUpwN good idea

**Comment by SecUpwN** [comment]
@larsgrefer, done. You also have editing rights in the WIKI, so feel invited add your improvements. ;-)
