### ISSUE TITLE
Crashes when pressing Status-Icons and Debugging

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#661]
Hi @larsgrefer, I've just played a bit with our fresher app after you polished our design a bit with #654.
Looks and feels great so far, but our app now crashes on the following events (which it didn't do before):

* Pressing the Status Icons in the `About` menu
* Pressing `Debugging` in the Navigation Drawer

I've crafted a [logcat](https://defuse.ca/b/ByxKkHqk) for you, hopefully it contains enough information to fix what is wrong. Thank you!

**Comment by larsgrefer** [comment]
I'll have a look at it later
