### ISSUE TITLE
Enable Attack Detection after quitting and restarting

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#662]
When pressing `Quit` from the Navigation Drawer, our app quits as supposed to. But when restarting it, the button `Toggle Attack Detection` is OFF. It shall automatically be enabled when starting our app.

**Comment by DJaeger** [comment]
The startup behavior of the attack detection and monitoring is configured in settings.
We have discussed this already.

**Comment by SecUpwN** [comment]
>The startup behavior of the attack detection and monitoring is configured in settings.

Yes, I know. But is it normal behavior that when checking `Persisten Service` and all protection mechanisms our app still does not start with detections enabled when restarting after pressing `Quit`?

**Comment by agilob** [comment]
`Toggle attack detection` works only if GPS is enabled and it's awaiting GPS-fix, isn't it?

**Comment by SecUpwN** [comment]
>`Toggle attack detection` works only if GPS is enabled and it's awaiting GPS-fix, isn't it?

No, this button is supposed to be the On/Off-Switch for the detections enabled in `Preferences`, for example detection of silent SMS. What you are talking about, is when wanting to collect connected BTS (correct me if I'm wrong here), then we need the GPS-fix. Issue #578 is about the fact that our app does not remember if attack detections are enabled or disabled when quitting our app and restarting it.

**Comment by agilob** [comment]
1. Turn off **all** location services
2. Turn off AIMSICD completely (and remove from recent)
3. Start AIMSICD with **no location service whatsoever
4. Toggle attack detection
5. You can't without GPS on
?

**Comment by SecUpwN** [comment]
@agilob, this Issue is **closed** in favor of #578. I am not sure you understood what my Issue is about:

1. Press `Toggle Attack Detection` to run it ON
2. Press `Quit`
3. Re-enter App and notice how `Toggle Attack Detection` it turned OFF.
