### ISSUE TITLE
Remove default rules from our proguard file

### ISSUE THREAD

**Issue by larsgrefer** [SecUpwN/Android-IMSI-Catcher-Detector#666]
We are importing two proguard files:
1. `getDefaultProguardFile('proguard-android.txt')`
2. `'proguard-rules.txt'`

Our file (the second one) contains many rules which are already defined in the first one.
We should remove those rules from our file

**Comment by smarek** [comment]
I dont agree, first file contains default rules given by Android SDK and libraries, see docs: https://developer.android.com/tools/help/proguard.html#enabling-gradle

**Comment by larsgrefer** [comment]
@smarek and our file contains most of those default rules too, which is redundant

**Comment by larsgrefer** [comment]
I've never seen a project before which needed to (re)declare things like this:

```java
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
```

**Comment by smarek** [comment]
@larsgrefer I agree, however important is **most of those default rules**, not all of them, and they can change depending on SDK changes, I'd be more for removing rules from our proguard file (to not duplicate the rules)

**Comment by larsgrefer** [comment]
I think you missunderstood me.
All I want to do is to clean up our file

**Comment by smarek** [comment]
Oh sorry, I've read it as "we should remove the import of default proguard file", my fault, I agree with your idea :-)

**Comment by larsgrefer** [comment]
the worst rule in our file is
```java
-keep public class * {
public protected *;
}
```
which nearly disables proguard

**Comment by SecUpwN** [comment]
Since this is an open project where everyone can contribute, it is no wonder you'll be discovering creepy stuff as well. Thanks for your really giving our project this very much needed lifting, @larsgrefer! :+1:
