### ISSUE TITLE
Use checkstyle to enforce coding guidelines

### ISSUE THREAD

**Issue by larsgrefer** [SecUpwN/Android-IMSI-Catcher-Detector#671]
http://checkstyle.sourceforge.net/checks.html

Just an idea. Which checks to enable has to be discussed separately

**Comment by larsgrefer** [comment]
@SecUpwN Your Opinion?

**Comment by SecUpwN** [comment]
>@SecUpwN Your Opinion?

I am fire and flame for it! Developers having a first glance at the code will be happy to know that guidelines exist and the everyone contributing must follow those. Any drawbacks we would face?

**Comment by larsgrefer** [comment]
Some possible drawbacks:
- Some developers might be annoyed by some rules
- Whenever we want to activate a new rule, we might have some work to do in order to fix the old code in order to pass the new checks

**Comment by SecUpwN** [comment]
@larsgrefer, I'd like to wait for some devs like @DJaeger, @banjaxbanjo and @smarek to answer here.

**Comment by banjaxbanjo** [comment]
@SecUpwN @larsgrefer if it helps new coders like me to program better I'm all for it, if it turns out to a pain and slows dev I'd be against.

This could open a can of worms if it's used to check all the current code.

**Comment by larsgrefer** [comment]
I think we just have to try which of these checks will suit our needs: http://checkstyle.sourceforge.net/checks.html

**Comment by agilob** [comment]
@banjaxbanjo it will be only pain if you don't have external education (source) and other projects.

**Comment by banjaxbanjo** [comment]
I'm good so😉

**Comment by SecUpwN** [comment]
>I'm good so

Means? You're not for using checkstyle?

**Comment by banjaxbanjo** [comment]
I'm good either way Sec checks will improve code.

**Comment by SecUpwN** [comment]
>I'm good either way Sec checks will improve code.

Ok, fair words. @larsgrefer, which particular checks do you have in mind to enable?
