### ISSUE TITLE
Update Javadoc comments

### ISSUE THREAD

**Issue by larsgrefer** [SecUpwN/Android-IMSI-Catcher-Detector#672]
according to #642

* remove `Changelog:`-Section
* remove `Issues:`- and `Todos:`-Section
* remove `Description:`-Prefix

---

**EDIT by SecUpwN.** I have crawled through our *whole* code and below files need *heavy* cleanup.
Please add a checkmark when a file is cleaned up so that we know what still needs to be worked on:

- [ ] AIMSICDDbAdapter.java
- [ ] BtsMeasureCardInflater.java
- [ ] BtsMeasureItemData.java
- [ ] CardItemData.java
- [x] CellCardInflater.java
- [ ] EventLogItemData.java
- [ ] UniqueBtsCardInflater.java
- [ ] UniqueBtsItemData.java
- [ ] DebugLogs.java
- [ ] MapViewerOsmDroid.java
- [ ] AtCommandFragment.java
- [ ] CellInfoFragment.java
- [ ] DbViewerFragment.java
- [ ] AccelerometerMonitor.java
- [ ] AimsicdService.java
- [ ] CellTracker.java
- [ ] SignalStrengthTracker.java
- [ ] SmsDetector.java
- [ ] AtCommandTerminal.java
- [ ] TtyStream.java
- [x] Device.java
- [ ] Helpers.java
- [ ] RequestTask.java
- [ ] StackOverflowXmlParser.java
- [x] SystemPropertiesReflection.java
- [x] AIMSICD.java

**Comment by SecUpwN** [comment]
@larsgrefer, is it one specific file you're referrring to, or do you mean the whole code?

**Comment by larsgrefer** [comment]
The whole code

**Comment by SecUpwN** [comment]
>The whole code

@larsgrefer, is there a convenient way with Android Studio or some other tool to clean up our code and create Issues for To-Do's taken from comments - or do we really have to manually review the codebase?

**Comment by larsgrefer** [comment]
@SecUpwN I'm afraid that it must be done manually
