### ISSUE TITLE
Aptoide cancelled our store again - should we ban Aptoide?

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#675]
Good morning security enthusiasts! I am filing this Issue here for public discussion because I am **sick** of @Aptoide doing no effort to explain why our Aptoide store located at http://aimsicd.store.aptoide.com/ has been cancelled the second time without any warning. I've been writing multiple emails to their support since November 19 and even to publishers support (which is supposed to resolve matters as quickly as possible), but noone replied at all. It was only a public tweet that made them reply on Twitter via PM with:

>Hello, I've seen your tweet regarding the cancelation of the store. Can you give the name of the store so that i can check out why? Thanks!

So I did send them a Twitter PM with the link to our store, after sevaral days and asking if they ignore us:

>**Aptoide:** Hello, have you reached our support team at support@aptoide.com?

>**Me:** They're ignoring us, I've sent multiple requests to the poublishers team as well as regular support team. Noone seems to care at all!

>**Aptoide:** The will answer back to you, your question is probably in the que. What email did you use'?

I replied with my email address and never received an answer since. Even though I like @Aptoide, I do not understand why our store gets cancelled without prior notification that there exists some "problem" (none at all, to my knowledge). @Aptoide, did you receive an [NSL](https://www.eff.org/issues/national-security-letters/) or why the heck are you treating us like this?

I have now notified @Aptoide via Twitter, both E-Mail support adresses and GitHub to reply ASAP  **HERE.**

**Comment by agilob** [comment]
>OWN your android market

XDD

**Comment by agilob** [comment]
Ehh try to make it loud on reddit, /r/privacy, /r/netsec, /r/androiddev

**Comment by SecUpwN** [comment]
And suddenly our store works again. No excuse, no clarification, no nothing. How come, @Aptoide?
