### ISSUE TITLE
Get RootShell from Maven

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#684]
Thanks to the already merged https://github.com/Stericson/RootShell/pull/9, we should now be able to replace `third_party/rootshell` with the latest and greatest `RootShell` from Maven.

**Comment by larsgrefer** [comment]
I'll implement this later

**Comment by SecUpwN** [comment]
>I'll implement this later

Thanks. If you won't be able to do it in time, I'll get my hands dirty myself.

**Comment by larsgrefer** [comment]
we should wait for Stericson/RootShell#10

**Comment by SecUpwN** [comment]
>we should wait for Stericson/RootShell#10

Will do. Guess you're assigned anyhow. ;-)

**Comment by larsgrefer** [comment]
Stericson/RootShell#11
