### ISSUE TITLE
App is directly closed when trying to open it

### ISSUE THREAD

**Issue by Cellino** [SecUpwN/Android-IMSI-Catcher-Detector#688]
Just installed AIMSICD latest release on a Samsung SM-N9002 Dual SIM. When trying to start the app, it tries to open dialog (some short black window), but then it directly shuts down with message box "Android IMSI-Catcher Detector stopped". But the notification message of that mobile cells are registered. So it seems process is started and the part in background is working, but dialog part seems not to work.
Installed version is 0.1.37-alpha-release - Android version is 5.0 - Phone is rooted - I tried after reboot of phone, same effect - I stopped app, deleted cache and data, then restarted app, it shows license agreement to be accepted, after acceptance first dialog shortly appears but app then immediately stops with effect described above.
How could I provide you further information?

**Comment by larsgrefer** [comment]
Sorry to hear about this.
It would be great for us to see what `/system/bin/logcat -D` outputs while you try to open the app

**Comment by Cellino** [comment]
How to get into an Android shell to set debug mode for logcat? Can you propose a certain shell to get the needed information?

**Comment by larsgrefer** [comment]
If you are familliar with adb, use the `adb shell` command on your PC to get a shell of your device
If you are using a Terminal Emulator on your phone, the `logcat` command must run as root

**Comment by larsgrefer** [comment]
btw: I'm not able to reproduce this

**Comment by Cellino** [comment]
Yes, I suppose so. Seems to be something special. Perhaps usage of Google Handschrifteingabe instead of a keyboard? Anyway, attached you'll find the log with option D, I tried to start up AIMSICD 3 times. Hope you'll find something.
[Log_AIMSICD_20151215.txt](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/files/62450/Log_AIMSICD_20151215.txt)

**Comment by larsgrefer** [comment]
@Cellino Thank you, but the logcat command did not run as root, so logcat only outputs logs from the Terminal Emulator you used, but not from AIMSICD

**Comment by Cellino** [comment]
Don't know how to run logcat as root... any ideas?

**Comment by larsgrefer** [comment]
@Cellino first run `su` in order to become root and then run `logcat`

**Comment by SecUpwN** [comment]
@larsgrefer, this is likely the bug I've already reported to you with my logcat right after our release.

**Comment by Cellino** [comment]
Already yesterday I managed to create the log file in Terminal Emulator, but nearly got crazy to copy it from TE to somewhere where it was able to write and is accessible from outside... finally I managed it. Hope you find enough information. I tried 3 times to start AIMSICD, you should find the same sequence 3 times. If I didn't delete enough information please remove log file from thread. Thank you for your help!
[logAIMSICD_20151215.zip](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/files/64522/logAIMSICD_20151215.zip)

**Comment by larsgrefer** [comment]
@Cellino According to the log you tried it 4 times :wink: 
@SecUpwN Yes, it's the same bug you found

**Comment by Cellino** [comment]
No, I tried really only 3 times. I wondered about the effect that although I started it only 3 times the stopping error message appeared once more (so 4 times). I don't know why that happens, perhaps due to dialog in background that scans the cells?
Can you tell something about what happens and why the app crashes? Something special with screen resolution?

**Comment by larsgrefer** [comment]
This is the important part of your log(s):
```
D/AndroidRuntime( 9466): Shutting down VM
E/AndroidRuntime( 9466): FATAL EXCEPTION: main
E/AndroidRuntime( 9466): Process: com.SecUpwN.AIMSICD, PID: 9466
E/AndroidRuntime( 9466): android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@28d06a6 -- permission denied for this window type
E/AndroidRuntime( 9466): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:711)
E/AndroidRuntime( 9466): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:288)
E/AndroidRuntime( 9466): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/AndroidRuntime( 9466): 	at android.app.Dialog.show(Dialog.java:312)
E/AndroidRuntime( 9466): 	at com.SecUpwN.AIMSICD.service.AimsicdService.m(AimsicdService.java:270)
E/AndroidRuntime( 9466): 	at com.SecUpwN.AIMSICD.service.AimsicdService.k(AimsicdService.java:242)
E/AndroidRuntime( 9466): 	at com.SecUpwN.AIMSICD.f.onServiceConnected(AIMSICD.java:489)
E/AndroidRuntime( 9466): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1265)
E/AndroidRuntime( 9466): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1282)
E/AndroidRuntime( 9466): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 9466): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 9466): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 9466): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
E/AndroidRuntime( 9466): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9466): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9466): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime( 9466): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
W/ActivityManager( 1074):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD
```

**Comment by larsgrefer** [comment]
@Cellino @SecUpwN Could you please try to start the app once with Location Services (GPS) off and once with GPS on

**Comment by SecUpwN** [comment]
@larsgrefer, when turning GPS on, `v0.1.37-alpha` [does not crash](https://defuse.ca/b/Ud27gwzC), but when turning it off, [it does](https://defuse.ca/b/fE3gY0hJ). Another strange thing: I can't install the latest version from Buildozer (currently `377`). See [this logfile](https://defuse.ca/b/tjQPvWPA). Seems like permissions we already removed (like NFC and contacts) are being requested. How come?

**Comment by Cellino** [comment]
@larsgrefer: Same with me. Starting up with GPS on --> start screen appears, starting up with GPS off --> crashes. I think it shouldn't crash with GPS off?! I'm awaiting next official alpha release.

**Comment by 1slickvdc** [comment]
@larsgrefer I also verify the experience shared here on an LG V10 on Android 5.1.1. I've got root access, so if needed I could grab logs as described above if they're still needed.

**Comment by agilob** [comment]
As @Cellino is not a technical user, you should immediately remove the log file, it contains a lot of sensitive information!

**Comment by SecUpwN** [comment]
>As @Cellino is not a technical user, you should immediately remove the log file, it contains a lot of sensitive information!

Thanks for the warning, @agilob. Log has been removed.

**Comment by Cellino** [comment]
@agilob: I am a technical user and I am very much aware of data protection in general, but don't know in detail the log items that have to be eliminated. Due to SecUpwN I removed CID und LAC (latter was not present) - are there really still sensitive informations inside the log?

**Comment by SecUpwN** [comment]
>are there really still sensitive informations inside the log?

@Cellino, I've alreayd removed the log. Let's wait for @larsgrefer to see if he still needs anything else.

**Comment by larsgrefer** [comment]
@SecUpwN @Cellino @1slickvdc 
The following happens:
- The background service detects that GPS is off and tries to show a dialog about that.
- Services are not allowed to show dialogs (because dialogs wich come out of nowhere might be confusing), the only way for them to show dialogs is using `TYPE_SYSTEM_ALERT`
- The service tries to show an `TYPE_SYSTEM_ALERT` dialog, but fails there, because we removed the needed permission `android.permission.SYSTEM_ALERT_WINDOW` earlier

Two possible solutions:
- re-add the `android.permission.SYSTEM_ALERT_WINDOW` permission
- don't use a dialog here but a notification

I'd prefer the second solution because background services are not intended to show dialogs for a reason. Displaying information or warnings from a background service is exactly the use case notifications were made for.

**Comment by SecUpwN** [comment]
>I'd prefer the second solution because background services are not intended to show dialogs for a reason. Displaying information or warnings from a background service is exactly the use case notifications were made for.

@larsgrefer, if that means a fix for both Issues I report with https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/688#issuecomment-165340489, please add a notification.

**Comment by Cellino** [comment]
Why does the background service detect the turned off GPS only when app is trying to be started? Why doesn't it create notifications of GPS turned off already when scanning cells regularly in neighbourhood in background?
What's the behaviour with notifications? Are they shown in foreground of all windows when coming up, or will they be added to the list of notifications in background? It seems important to me that the notification may be related to the startup of the app, because the cell analyzer always works in background, even if GPS is set off, and notification might be misunderstood because the notification is created without any dialog window shown behind. Couldn't the dialog that is coming up, when GPS is turned on, being shown grayed out in background and a message box to be confirmed by user is shown in foreground? With this option, the dialog message could be related to the not coming up app AINSICD.

**Comment by larsgrefer** [comment]
@SecUpwN The SMS alerts currenly have the same problem (dialogs from background services are not allowed)

@Cellino The service can work without GPS too, but with GPS on it can work better, so it tries to suggest you to enable GPS.
If we set the Priority of the notification high enough you will get an overlay in the foreground like here: http://www.google.com/design/spec/patterns/notifications.html#notifications-peeking-notifications

**Comment by licaon-kter** [comment]
Had the crash ot start too, turnitg GPS on fixed it, although the whole error on file creation seems different.

Logcat here: https://gist.github.com/licaon-kter/e95adbcd83992c5e200a

**Comment by SecUpwN** [comment]
@licaon-kter, thanks for addinh your log. This bug is fixed now, please wait for the next release.

**Comment by larsgrefer** [comment]
The GPS related crash is fixed but the file error mentioned by @licaon-kter is still present

**Comment by SecUpwN** [comment]
>The GPS related crash is fixed but the file error mentioned by @licaon-kter is still present

@larsgrefer, please open a fresh Issue for this and add the logfile tpo it. Thank you.

**Comment by licaon-kter** [comment]
Done https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/698
