### ISSUE TITLE
Buildozer Builds not installable

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#690]
Separated this bug from https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/688#issuecomment-165340489. @larsgrefer, how come we get [this logfile](https://defuse.ca/b/tjQPvWPA)?

**Comment by larsgrefer** [comment]
@SecUpwN Because we declare many non-standard permissions in our AndroidManifest.xml (e.g. everything with `com.sec.**`)

**Comment by SecUpwN** [comment]
Thanks for having a look @larsgrefer. I wonder why our app now refuses to be installed when it worked as it should before? Is that a result of cleaning up the unused permissions? Do we need another cleanup?

**Comment by larsgrefer** [comment]
@SecUpwN It seems like buildozer builds the `system` flavor instead of the `normal`flavor

**Comment by SecUpwN** [comment]
@larsgrefer, I am about to clean up and sort our `AndroidManifest.xml`. Do we need [these](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/AIMSICD/src/main/AndroidManifest.xml#L32-L49)?

**Comment by larsgrefer** [comment]
I don't know. My phone doesn't even know all the `com.sec.**` permissions
Maybe they are samsung-specific

**Comment by SecUpwN** [comment]
>I don't know.

How come? Who has introduced those? :P

**Comment by larsgrefer** [comment]
@SecUpwN @E3V3A has introduced them: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blame/development/AIMSICD/src/main/AndroidManifest.xml#L32-L49

**Comment by SecUpwN** [comment]
@larsgrefer, would you agree if I remove those and re-add them once we see the need for them?

**Comment by larsgrefer** [comment]
yes, good idea :+1:

**Comment by SecUpwN** [comment]
@larsgrefer, please review above changes and let me know if you'd add any other changes. Thank you!

**Comment by larsgrefer** [comment]
@SecUpwN This is the reason why you cannot install the app:
```
com.android.server.pm.PackageManagerException: Package com.SecUpwN.AIMSICD has no signatures that match those in shared user android.uid.system; ignoring!
```
