### ISSUE TITLE
Inconsistency of status names

### ISSUE THREAD

**Issue by larsgrefer** [SecUpwN/Android-IMSI-Catcher-Detector#701]
Some status have different names at different places in code:

- OK vs NORMAL
  - The drawables are named `ok`
  - The strings are named `normal`
- SKULL vs RUN
  - The drawables are named `skull`
  - The strings are named `run`

**Comment by SecUpwN** [comment]
Yes, this could be conffusing to some devs. What do you suggest? Shall I name stringls like drawables?

**Comment by larsgrefer** [comment]
> Shall I name strings like drawables?

this, or vice versa.

Im not sure which names are better, but one status should only have one name across the whole code (java + resources)

**Comment by SecUpwN** [comment]
>...but one status should only have one name across the whole code (java + resources)

I am aware of that. What makes most sense to you personally when using our app?
