### ISSUE TITLE
detection SMS type zero

### ISSUE THREAD

**Issue by lop1** [SecUpwN/Android-IMSI-Catcher-Detector#705]
On my S4 mini stock firmware rooted AIMSICD does not detect a SMS class zero ( but the phone detect it and show the SMS on the screen )

![screenshot_2015-12-25-15-35-23](https://cloud.githubusercontent.com/assets/13037127/12003418/2e4db0d2-ab1e-11e5-830e-33a2a93a375d.png)
![screenshot_2015-12-25-15-35-47](https://cloud.githubusercontent.com/assets/13037127/12003421/344870f8-ab1e-11e5-9b9d-1835caa563b9.png)

the detection is set in preferences and the phone is rooted.

**Comment by SecUpwN** [comment]
tanks for filing. We need to improve #537 - please continue discussion there. Thank you.
