### ISSUE TITLE
Services still running after closing AIMSICD

### ISSUE THREAD

**Issue by lop1** [SecUpwN/Android-IMSI-Catcher-Detector#706]
After exit of AIMSICD and clearing AIMSICD from memory there are still some services running (may be the SMS detection )

![screenshot_2015-12-25-15-59-03](https://cloud.githubusercontent.com/assets/13037127/12003473/fd5d9232-ab20-11e5-9891-1316edf937f7.png)

**Comment by SecUpwN** [comment]
@lop1, please [improve this bug report](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md#debugging), otherwise our developers cannot digg depper to fix this. Thanks!

**Comment by agilob** [comment]
@lop1 what application is that? I remember having it long time ago...

**Comment by lop1** [comment]
Here are the full details about this problem.

samsung galaxy S4 mini
stock rom ( I9195XXUCOJ1 ) last chitchat release for this model
rooted towelroot

If you run AIMSICD without stealth SMS detection , no problem, when you exit from it there are no more process running in the device.

if you run AIMSICD WITH stealth SMS detection and you exit  from it a process keep running in background. If you rerun the software and exit it you will have two process still running in the device. If you run it once more you will get three process running in background. etc .... 
And there is no way to get rid of these process , the only solution ( for me , but there may be some way ) is to reboot the device as killing them from OS monitor does not work.

It seems that if you exit from AIMSICD with stealth SMS , the software forget to shut down the SMS process.

I can't get the log as the AIMSICD is closed when this process are still running.

hope this helps.

**Comment by SecUpwN** [comment]
@jensstein or maybe @NezSpencer, can you find the cause of these Issues?

**Comment by NezSpencer** [comment]
@lop1 @SecUpwN  by __stealth sms detection__ do you mean __enable sms detection__ checkbox preference in the settings screen?

**Comment by NezSpencer** [comment]
and how should it behave normally?: shut down all processes or only allow one process to exist?

**Comment by lop1** [comment]
Yes, this is in my understanding the Way  to activate the detection .

Envoyé de mon iPad

**Comment by NezSpencer** [comment]
@lop1 I havent been able to reproduce this issue. Have you been able to reproduce it again lately?

**Comment by NezSpencer** [comment]
This is what I get: 
As long as the app is opened, a process appears on the OS monitor process screen but when I close the app, the process clears as in __No AIMSICD process__ runs. I think earlier bug fixes might have fixed this as well but please indicate if you still get this issue

**Comment by lop1** [comment]
Yes today, I just run it twice and have 4 process running after quiting.



Envoyé de mon mobile 

<div>-------- Message d'origine --------</div><div>De : Nnabueze Uhiara <notifications@github.com> </div><div>Date :13/01/2016  12:26  (GMT+01:00) </div><div>À : SecUpwN/Android-IMSI-Catcher-Detector <Android-IMSI-Catcher-Detector@noreply.github.com> </div><div>Cc : lop1 <65c02@orange.fr> </div><div>Objet : Re: [Android-IMSI-Catcher-Detector] Services still running after
  closing AIMSICD (#706) </div><div>
</div>@lop1 I havent been able to reproduce this issue. Have you been able to reproduce it again lately?

**Comment by NezSpencer** [comment]
@lop1 on what phone?

**Comment by NezSpencer** [comment]
and can you state clearly what you did with the AIMSICD app when you ran it?

**Comment by lop1** [comment]
Samsung galaxy s4 mini , stock Tom rooted with towel root. 
I9195 XXUCOJ1


Envoyé de mon mobile 

<div>-------- Message d'origine --------</div><div>De : Nnabueze Uhiara <notifications@github.com> </div><div>Date :13/01/2016  12:43  (GMT+01:00) </div><div>À : SecUpwN/Android-IMSI-Catcher-Detector <Android-IMSI-Catcher-Detector@noreply.github.com> </div><div>Cc : lop1 <65c02@orange.fr> </div><div>Objet : Re: [Android-IMSI-Catcher-Detector] Services still running after
  closing AIMSICD (#706) </div><div>
</div>@lop1 on what phone?

**Comment by lop1** [comment]
Just run it, Check the "sms détection", let it run for 30 seconds, quit aimsicd, then run os monitor to see what is remaining.

Envoyé de mon iPad

**Comment by lop1** [comment]
And after 10 minutes :



Envoyé de mon mobile 

<div>-------- Message d'origine --------</div><div>De : Nnabueze Uhiara <notifications@github.com> </div><div>Date :13/01/2016  12:45  (GMT+01:00) </div><div>À : SecUpwN/Android-IMSI-Catcher-Detector <Android-IMSI-Catcher-Detector@noreply.github.com> </div><div>Cc : lop1 <65c02@orange.fr> </div><div>Objet : Re: [Android-IMSI-Catcher-Detector] Services still running after
  closing AIMSICD (#706) </div><div>
</div>and can you state clearly what you did with the AIMSICD app when you ran it?

**Comment by lop1** [comment]
I try to run it, uncheck the sms detection and quit after 30 seconds. 



Envoyé de mon mobile 

<div>-------- Message d'origine --------</div><div>De : Nnabueze Uhiara <notifications@github.com> </div><div>Date :13/01/2016  12:45  (GMT+01:00) </div><div>À : SecUpwN/Android-IMSI-Catcher-Detector <Android-IMSI-Catcher-Detector@noreply.github.com> </div><div>Cc : lop1 <65c02@orange.fr> </div><div>Objet : Re: [Android-IMSI-Catcher-Detector] Services still running after
  closing AIMSICD (#706) </div><div>
</div>and can you state clearly what you did with the AIMSICD app when you ran it?

**Comment by SecUpwN** [comment]
>I think earlier bug fixes might have fixed this as well but please indicate if you still get this issue

@NezSpencer, that's interesting. Thansk for digging into it.

>Yes today, I just run it twice and have 4 process running after quiting.

@lop1, which version of our app you run? Did you compile a fresh build from `development` branch?

**Comment by NezSpencer** [comment]
@SecUpwN thanks I forgot to ask that

**Comment by SecUpwN** [comment]
@NezSpencer, not your fault. It's just too bad that most people ignore our [CONTRIBUTING.md](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md).

**Comment by lop1** [comment]
The 1.38 bêta official 

Envoyé de mon mobile

**Comment by SecUpwN** [comment]
>The 1.38 bêta official

@lop1, please use [these instructions](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Building) and verify that this Issue persists. Thank you.

**Comment by Walkman100** [comment]
how up-to-date is the F-Droid repo?

**Comment by Walkman100** [comment]
or out of date, for that matter

**Comment by SecUpwN** [comment]
>how up to date is the F-Droid repo? or out of date, for that matter

@Walkman100, the F-Droid repo gets updated with every release. Of course, our `development` branch is always ahead. So if you want to check if an Issue still persists, a manual build is recommended.

**Comment by SecUpwN** [comment]
@lop1, please properly maintain your Issue here. Is this bug still present?

**Comment by lop1** [comment]
just tested on the build T 1643 , and it is working OK, no more ghost process after exit with the sms detection on.
