### ISSUE TITLE
App doesn't start on boot on CM13

### ISSUE THREAD

**Issue by mimi89999** [SecUpwN/Android-IMSI-Catcher-Detector#713]

**Comment by SecUpwN** [comment]
Hi there @mimi89999, thank for checking our our app! Did you activate the startup in `Preferences`?

**Comment by mimi89999** [comment]
Yes

**Comment by SecUpwN** [comment]
>Yes

If you're sure you did so, please make this a *valid* Issue by adding [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md#debugging) to your OP. CM13 is running Android 6 Marshmallow, our app is likely not optimized for that yet. Oh and hey: We love pull requests! ;-)

**Comment by mimi89999** [comment]
AIMSICD version: v0.1.37-alpha-release
ROM: CM13 nightly
HW: Samsung Galaxy S4 mini GT-I9195 (serranoltexx)
