### ISSUE TITLE
ExampleException in home#example

### ISSUE THREAD

**Issue by larsgrefer** [SecUpwN/Android-IMSI-Catcher-Detector#715]
## New exception in Example.com

**ExampleException** in **home#example**
Something really bad happened

[View on Bugsnag](http://bugsnag.com/errors/example/events/example)

## Stacktrace

    app/controllers/home_controller.rb:123 - example
    app/controllers/other_controller.rb:12 - broken
    lib/important/magic.rb:4 - load_something

[View full stacktrace](http://bugsnag.com/errors/example/events/example)

**Comment by SecUpwN** [comment]
@larsgrefer, I would like to avoid filing Issues with the label `WILL_NOT_FIX` as they pile and essentially cannot be solved. Please explain what this "Issue" is about and what its purpose is.

**Comment by larsgrefer** [comment]
@SecUpwN This is an example issue created by bugsnag (on my behalf).
I have added the `WILL_NOT_FIX` label by hand, because this isn't something we can fix.

**Comment by SecUpwN** [comment]
>I have added the `WILL_NOT_FIX` label by hand, because this isn't something we can fix.

I'm afraid I don't really understand. You tested the Issue creation, but we can't close this Issue afterwards?

**Comment by larsgrefer** [comment]
Yes, i've tested the issue creation.
No, we can close this whenever we like

**Comment by SecUpwN** [comment]
>No, we can close this whenever we like

Ok, that is taking the shock away. ;-) Please only use the `WILL_NOT_FIX` label when we *really* encounter an Issue that is not fixable (hopefully that won't happen). Please close this when done. Thanks.
