### ISSUE TITLE
Main Screen: Empty SIM Serial Number

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#717]
@larsgrefer, I've just noticed that my SIM serial number is empty in the main screen. Is that normal due to our code maybe not reading the SIM serial number any more? Or is something wrong with my SIM?

**Comment by SecUpwN** [comment]
Can anyone confirm this, please? @He3556 or @jensstein maybe?

**Comment by jensstein** [comment]
i don't really know your project, so maybe i'm missing something, but you seem to put the serial information into the imsi textview and leave out the imsi / subscriberid information.
here is a patch which fixes it (for me at least and ).

```
From 0eaaa9f740a473e0bc576c01c3cdd2a8db55a881 Mon Sep 17 00:00:00 2001
From: jens stein <jens.s.stein@gmail.com>
Date: Sat, 9 Jan 2016 22:05:40 +0100
Subject: [PATCH] Correct SIM serial and IMSI information

---
 .../src/main/java/com/SecUpwN/AIMSICD/fragments/DeviceFragment.java    | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/AIMSICD/src/main/java/com/SecUpwN/AIMSICD/fragments/DeviceFragment.java b/AIMSICD/src/main/java/com/SecUpwN/AIMSICD/fragments/DeviceFragment.java
index 67c3a3e..5f69302 100644
--- a/AIMSICD/src/main/java/com/SecUpwN/AIMSICD/fragments/DeviceFragment.java
+++ b/AIMSICD/src/main/java/com/SecUpwN/AIMSICD/fragments/DeviceFragment.java
@@ -172,7 +172,8 @@ public class DeviceFragment extends InjectionFragment {
             content = (HighlightTextView) getView().findViewById(R.id.sim_operator_name);
             content.updateText(mDevice.getSimOperatorName(), ani);
             content = (HighlightTextView)  getView().findViewById(R.id.sim_imsi);
-//            content.updateText(mDevice.getSimSubs(), ani);
+            content.updateText(mDevice.getSimSubs(), ani);
+            content = (HighlightTextView)  getView().findViewById(R.id.sim_serial);
             content.updateText(mDevice.getSimSerial(), ani);
 
             content = (HighlightTextView)  getView().findViewById(R.id.device_type);
-- 
2.7.0

```

**Comment by SecUpwN** [comment]
Awesome, thanks for checking this, @jensstein! Would you please be so kind to craft a pull request for it?

**Comment by jensstein** [comment]
well, you can just apply my patch directly. save it as e.g. sim-serial.patch and run ```git apply sim-serial.patch``` (or use ```patch```) and check that the fix is okay (nothing is commited at this stage). then you can run ```git am sim-serial.patch``` which will commit the patch with my commit message and everything.

**Comment by SecUpwN** [comment]
>well, you can just apply my patch directly

Thanks for telling me, but I am not on my private computer right now, that is why I was asking politely. :)

**Comment by jensstein** [comment]
it's cool, i guess it can wait, right? :)

**Comment by SecUpwN** [comment]
>it's cool, i guess it can wait, right? :)

@jensstein, I'd prefer a quick pull request so that I can directly test that via the automated build created.

**Comment by SecUpwN** [comment]
Sorry @jensstein, seems like your pull request still did not fix this one. Need to re-open it. :P

**Comment by jensstein** [comment]
eh, how didn't it fix it? is the serial number still completely missing? is imsi displayed? are the fields blank or do they have "N/A"?
both imsi and serial is displayed correctly on my device now with a fresh compile of the development branch.

**Comment by SecUpwN** [comment]
>eh, how didn't it fix it? is the serial number still completely missing? is imsi displayed?

@jensstein, obvioussly Buildozer did not do a fsuperfresh build - it now did and everything is fine. But let me ask you one last question: When `Operator:` shows `N/A`, that means that this Info is not on the SIM, right?

**Comment by jensstein** [comment]
great :)
also, relating to "N/A" you have a bug where the strings for the various sim attributes are not initialised if TelephonyManager.getSimState() returns anything other than SIM_STATE_READY. so in all other cases nothing is displayed.
this also means that checking sim state in e.g. Device.getSimSerial in effect is redundant. is this by design? without having any knowledge of the code i would probably think it would be wise to lose the switch in Device.java:L123. or initialising the strings to "N/A" when declaring. or both.
