### ISSUE TITLE
CREDITS: Convert into string resource

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#726]
Taken from https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/709#issuecomment-167266552, our `CREDITS` file is currently an asset instead of a string resource. It also contains manual line-breaks with `\n`. Since we've changed how our `CREDITS` are being displayed, we should make sure that this file is following the best practice for developers for easier editing and view.

@larsgrefer, would you please have a look at this Issue? Should we center all text as well?

**Comment by SimonMarquis** [comment]
Every button on the *About* page already redirects the user to a specific web page.
It would make more sense to use the same mechanism for the *credits* button.
For instance, there could be a CREDITS.md file at the root of the project.
What do you think about this?

**Comment by SecUpwN** [comment]
>For instance, there could be a CREDITS.md file at the root of the project.

Interesting point, @SimonMarquis. To be honest, our main goal always was to make our app get away from using internet access at all. Personally, I enjoy that the list of contributors can be seen within our app and we plan to make all other buttons be In-App buttons as well. Unfortunately, we really lack developers.

**Comment by SimonMarquis** [comment]
Well I can do a PR for this issue (refactoring the asset into a string)

**Comment by SecUpwN** [comment]
>Well I can do a PR for this issue (refactoring the asset into a string)

That would be wonderful, @SimonMarquis! Are you able to craft a PR until tomorrow? :)
