### ISSUE TITLE
About-Screen: Git SHA-Hash is always null

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#731]
The Git SHA-Hash in our `About` screen always says `null`.
This should be fixed, otherwise displaying it is senseless.

**Comment by larsgrefer** [comment]
@SecUpwN The git-sha is only null on Buildozer builds because of the already known git issue

On travis and local builds the git-sha is present

**Comment by SecUpwN** [comment]
>The git-sha is only null on Buildozer builds because of the already known git issue

Oh, that makes sense. I guess when #730 works and has been merged, this Issue solves itself.

**Comment by SecUpwN** [comment]
Seems like @Buildozer has finally solved this Issue. GIT-Sha is now shown. Thank you very much!
