### ISSUE TITLE
Infinite(?) loop on denied position

### ISSUE THREAD

**Issue by liar666** [SecUpwN/Android-IMSI-Catcher-Detector#739]
Hi,

My phone is almost always in airplane mode, or at least without Wifi/GPS. Also, I often set as limited permissions as possible to newly installed applications.

When I start AIMSICD in such conditions, it shows a popup with "Denied Position" and whatever I do (OK/Cancel), it just loops (infinitely?) showing this message...

**Comment by NezSpencer** [comment]
Hi
I would like to work on this issue

**Comment by SecUpwN** [comment]
Welcome back, @NezSpencer! Am I right that you're the one from [our OpenHatch page](https://openhatch.org/projects/Android%20IMSI-Catcher%20Detector) who wanted to contribute? If so, feel invited to craft a pull request for fixing this Issue. Thanks for improving our code!

**Comment by NezSpencer** [comment]
Yes I am.
forked and cloned the repo yesterday but. I am having some difficulty migrating the project to gradle in android studio. Any help as to how to do this please?

**Comment by larsgrefer** [comment]
@NezSpencer Just use `File -> Open` and select the build.gradle file in the repository root

**Comment by NezSpencer** [comment]
@larsgrefer  Thanks it worked!

**Comment by larsgrefer** [comment]
I think we should add a preference to ignore disabled gps

**Comment by NezSpencer** [comment]
@liar666 I tested it now on my phone with airplane mode enabled but it dint reproduce the error

**Comment by NezSpencer** [comment]
although it asked me at first to enable GPS

**Comment by NezSpencer** [comment]
@larsgrefer  Were you able to reproduce the bug?

**Comment by SecUpwN** [comment]
>I think we should add a preference to ignore disabled gps

@larsgrefer, I guess this solution would essentially solve #251. Is this Issue a `DUPLICATE` of it?
