### ISSUE TITLE
Reconsider DarkCoin as a donation option

### ISSUE THREAD

**Issue by andr3jx** [SecUpwN/Android-IMSI-Catcher-Detector#74]
Hi, I want you to reconsider accepting DarkCoin donations because DarkCoins are more or less like Bitcoins only much less known, less widespread and harder to get. I know you choose DarkCoins because they are marketed with an "Encrypted transaction network" and "Anonymous blockchain using coinjoin technology" but both features are as far as I understood not really ready.

I suggest that @SecUpwN creates a bitcoin wallet which he manages for bitcoin donations. If you want to send an anonymous bitcoin donation you can fire up TOR Browser and create a wallet on sharedcoin.com or bitcoinchain.info. You send the amount you want to donate to your sharedcoin / bitcoinchain -wallet and once the bitcoins are available you do a transaction to the donation-wallet. You need to use the option "Shared Coin" and choose how many "repetitions" you want to make the transaction hard to trace. Shared Coin is based on CoinJoin which is used in DarkCoin.

**Comment by SecUpwN** [comment]
@ukanth, I just noticed you're using [Gratipay](https://gratipay.com/), where it says you're [give and receive anonymously](https://gratipay.com/ukanth/). Would you please be so nice and give some feedback here? I am still evaluating the best option for our own developers and contributors to collect and send some small funding. Thanks!

**Comment by ukanth** [comment]
@SecUpwN , I registered to see the service when it was called gittip. I never received/donated any amount as it doesn't support NON-US accounts/cards. It may be suitable for US only account holders.

**Comment by SecUpwN** [comment]
>I registered to see the service when it was called gittip. I never received/donated any amount as it doesn't support NON-US accounts/cards. It may be suitable for US only account holders.

@ukanth, thanks for stating this. It's a no-brainer that we won't be using it then. Any other services that are as open as possible and support anonymous receiving/sending to numerous other services?

**Comment by alanthehat** [comment]
Whilst I understand an absolute requirement for *developers* to maintain anonymity I am comfortable with the idea of using my money to register a **public vote** against governments & other criminals attempting to spy on me or subvert my equipment. 

Some way of accepting open donations is very much wanted. Is there a crowd-funding service that will pass on monies anonymously?

**Comment by SecUpwN** [comment]
> Is there a crowd-funding service that will pass on monies anonymously?

Hi there, @alanthehat! Thank you for chiming in. Personally, I consider this Issue to be one of the most important, but sadly have not yet found a service that supports open donations from numerous sources while passing on the money anonymously. Of course we could always register at some service that is not fully anonymous, but I intend to support privacy-minded organizations like [EFF](https://www.eff.org/), [The Guardian Project](https://guardianproject.info/), [Privacy International](https://www.privacyinternational.org/), possible whistleblowers and similar organizations. Also, I would like to add some sort of banner to our `README` that would always show much money is currently in the cup. All of that is a pretty tough challenge to solve - feel invited to digg the web to find it, we would very much appreciate it!

**Comment by alanthehat** [comment]
Hmm, I would expect that the organizations that you link have (at least access to) anonymous funding channels.

**Comment by SecUpwN** [comment]
@alanthehat, unfortunately not. They're either using PayPal, BitCoin or Credit Cards. None of these are really an option for us. We'd like to find a service (preferrably open source) through which users can decide on how to donate (PayPal, Credit Card, BitCpin, direct payments, anonymous payments) and the money collected should be (preferrably) untraceable afterwards. We do not want to risk anyone donating to our cause to get difficulties in their country or at work.

**Comment by SecUpwN** [comment]
A few days ago, when cleaning our repository with the awesome [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) by @rtyley, I have discovered that he uses [Bountysource](https://www.bountysource.com/). It looks great, but I would like to have some feedback of you guys (especially @He3556, @tobykurien, @banjaxbanjo and @DimaKoz) if it does meet the needs we have been talking about so extensively in this Issue. I am open for further suggestions to finally find a service that works well, supports anonymous donations and does enable our project t fund developers fair.

**Comment by rappo** [comment]
Hi all, I'm from Bountysource.com and was sent here to publicly respond to a few questions from @SecUpwN. As a note, I did *not* read the thread (yet) as there's a lot to it and I wanted to get a reply right away. Here are the questions sent to support@bountysource.com with my answers:

> Is there a way to donate anonymously?

All payments require a Bountysource account. Paypal transactions are also tied to your Paypal account for obvious reasons. BTC payments are processed by Coinbase and may also be tied to your Coinbase account (if you have/use one). We have discussed possible BTC donations that don't require a Bountysource account, but this is not a high priority and may never happen.

> Is Bountysource good for whistleblowers?

I'm not sure exactly how to answer this. The members of the Bountysource team are supporters of open-source, advocates for privacy, and love crypto-currency. That said, we do everything within the confines of the law and have built a legitimate business. If there are laws in place that allow us to help protect whistleblowers, we will take advantage of that. If a situation came up, my first reaction would be to reach out to an organization like the EFF for guidance. Maybe if you had a more specific question I could better answer.

> Can people also donate money via PayPal?

Yes, definitely! Paypal and BTC are accepted for bounties and team contributions. Paypal and Credit Card are accepted for our new sustained-funding feature, Salt (see https://salt.bountysource.com/teams/neovim for an example)

> Would you please add Dark Coin to your options?

Honestly, this is unlikely. We've only had a couple requests for Darkcoin and the implementation cost of adding it would not be something we can handle at the moment. Add to it the fact that BTC makes up a small portion of our revenue compared to Paypal, and there's little incentive for us to do it. We do use Coinbase as our BTC payment processor -- if they were to add features that allowed us to accept altcoins easily, I would certainly consider it.

**Comment by DimaKoz** [comment]
via PayPal
https://developer.paypal.com/docs/classic/mobile/ht_mpl-itemPayment-Android/

I can try to add a Pay with PayPal button in our app.
It is interesting to implement.
What are your decisions?

**Comment by banjaxbanjo** [comment]
Donations would definitely bring more devs and give people mire incentive to code on project more.

**Comment by SecUpwN** [comment]
Thank you so much for replying on my questions, @rappo! I see that Bountysource is a great platform, but do I have to open up a PayPal account for it? PayPal requires a bank verification and since I all about staying anonymous (since we're coding a tool to detect heavy technology of the state), I am not sure I can sign up for your service without giving up my anonymity. Which other possibilities do I have?

>Donations would definitely bring more devs and give people more incentive to code on project.

That is one of the main reasons I consider this Issue so important. I feel guilty when people add code, invest time and get pissed when not getting anything back other than more coding requests.

>I can try to add a Pay with PayPal button in our app.

Please don't do so. We have to agree on a service here first, then we can discuss the right button.

**Comment by DimaKoz** [comment]
Just as an idea, I can offer to implement a simple application for donations through Google Play. For most users, android payment through it will not cause difficulties.
For example, you can see here:
https://play.google.com/store/apps/details?id=eu.chainfire.supersu.про

**Comment by SecUpwN** [comment]
>Just as an idea, I can offer to implement a simple application for donations through Google Play.

Thanks for the neat idea, maybe something we can also consider for #202. But donating should not be only possible via one service. Furthermore, I am really still not sure if I want our app to be on GooglePlay since we are [standing strong against it](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-why-wont-you-upload-your-app-to-the-google-play-store).

**Comment by DimaKoz** [comment]
Google does not make a lot of things, very long time, including a fix their bugs, unfortunately.
Do not use Google market, we are losing a lot of users.
On the other side the application on Google Play should not have other methods of payment other than only through Google Play.
Therefore, if you decide to get a huge market for our application, we will have the following problem. We will need to maintain two versions of the actual build of the application:
- For donations through Google;
- For donations through a pool of other possible systems of payment (PayPal, etc.);

As [SecUpwN](https://github.com/SecUpwN) said:
> PayPal requires a bank verification and since I all about staying anonymous

Authorize necessary in most systems to obtain money (except maybe Bitcoin)

**Comment by E3V3A** [comment]
I thonk what Sec said, is that we've been thinking to provide an AIMSICD wrapper/downloader on GP. That way were present, and people can still download our app (using the downloader standalone) and donate, all without actually having our latest built apps messed up by Google spyware bloat etc.

**Comment by SecUpwN** [comment]
@DimaKoz, have you had a look at [Bountysource]([![CallYa Toppings](http://toppings.vodafone.de/img/topping-fb.jpg)](http://toppings.vodafone.de/)) yet? I am specifically looking for something like that, a service that is able to make people vote and donate on Issues. They also offer a browser extension, that way people can support developers during their usual GitHub use.

The only thing I am currently having a problem with, is that it seems that I have to reveal my real identity. How can I protect my identity after I have signed up with your service, @rappo? Anonymous donations?

**Comment by SecUpwN** [comment]
@andr3jx, @He3556, @DimaKoz and @E3V3A, check this out: [![Bountysource](https://www.bountysource.com/badge/team?team_id=40338&style=bounties_received)](https://www.bountysource.com/teams/android-imsi-catcher-detector/issues?utm_source=Android%20IMSI-Catcher%20Detector&utm_medium=shield&utm_campaign=bounties_received)

I am currently testing it and am playing with the idea of replacing one of those buttons from our `About` page with the link to our donation page. Please have a look at Bountysource, everyone. I want this important Issue to be solved properly, thus encouraging high-quality coders to continue adding their code to our app. Let me know when I shall craft a public announcement on Twitter that we use it. Or, if you really don't like Bountysource, tell me the reasons here and lets continue finding another service.

**Comment by E3V3A** [comment]
Great initiative! We need this.

**Comment by SecUpwN** [comment]
>Great initiative! We need this.

Thanks. May I consider this Issue as solved now? I will publicly announce this via Twitter then.
