### ISSUE TITLE
Main Screen: Operator shows N/A

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#749]
Discovered by @jensstein in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/717#issuecomment-170907747, `Operator:` is currently showing `N/A`. Reason:

>also, relating to "N/A" you have a bug where the strings for the various sim attributes are not initialised if TelephonyManager.getSimState() returns anything other than SIM_STATE_READY. so in all other cases nothing is displayed.
>this also means that checking sim state in e.g. Device.getSimSerial in effect is redundant. is this by design? without having any knowledge of the code i would probably think it would be wise to lose the switch in Device.java:L123. or initialising the strings to "N/A" when declaring. or both.

Since you've digged that part of the code, would it be possible for you creating a fixing pull request?

**Comment by jensstein** [comment]
yes, the problem isn't that it is showing N/A but that none of the fields are showing anything if the system doesn't report the sim card as being ready.
if i were to make a patch i would like to pull out the switch statement and maybe also the other checks for the return of getSimState because they don't really seem to do anything.
would that be okay?
there is also a great deal of code duplication there so maybe that could be cleaned up as well.

**Comment by SecUpwN** [comment]
>yes, the problem isn't that it is showing N/A but that none of the fields are showing anything if the system doesn't report the sim card as being ready.

Thanks for analyzing our code, @jensstein! We're happy getting any improving help we can get.

>if i were to make a patch i would like to pull out the switch statement and maybe also the other checks for the return of getSimState because they don't really seem to do anything.
would that be okay?

I'm not sure wether these are needed for solving #96 (hopefully some day), but don't worry, the pull request you'll create will likely be checked by @larsgrefer before we merge it. We'll make sure it fits.

>there is also a great deal of code duplication there so maybe that could be cleaned up as well.

If that is the case, of course we'd be happy to see these things melt down. Thanks ahead!

**Comment by jensstein** [comment]
pull requested: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/753 :)

**Comment by SecUpwN** [comment]
Thanks for still working on this, @jensstein. This will be solved when https://github.com/jensstein/Android-IMSI-Catcher-Detector/pull/1 has been added.

**Comment by SecUpwN** [comment]
@jensstein, it seems as if your pull request solved our Issues with missing `IMSI` and `Serial Number`, but now `Operator` always stays empty. Are you still working on https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/753#discussion-diff-49934850 and removing duplicate code?

**Comment by SecUpwN** [comment]
@VladThodo, since you currently seem online, would you please confirm that this is actually a bug and not just my SIM card mocking around? If it really *is* a bug in our code, feel invited to see if you can fix it. Thanks!

**Comment by VladThodo** [comment]
@SecUpwN  On my phone it's all good,both `Operator name` and `Operator ID` are showing ;)

**Comment by SecUpwN** [comment]
Thanks for checking, @VladThodo. If @f3ndot cannot confirm this bug as well, I'll close it.

**Comment by f3ndot** [comment]
@SecUpwN unable to reproduce. Both `Operator name` and `Operator ID` are, well, operating :wink:

**Comment by SecUpwN** [comment]
Thanks for checking, @f3ndot. Is it normal that my SIM card does not provide the `Operator Name`?

**Comment by f3ndot** [comment]
Not a clue @SecUpwN! That info appears to be driven by `TelephonyManager` which is part of the Android framework.

Not sure what your wireless environment is like in Germany, but could it be your cellular provider?

**Comment by SecUpwN** [comment]
>Not sure what your wireless environment is like in Germany, but could it be your cellular provider?

Could be. We need a check of another German. @He3556 or @larsgrefer do you see `Operator Name`?

**Comment by Nordlenning** [comment]
@SecUpwN Unable to reproduce bug in Norway. Both Operator name and Operator ID are, well, operating.

**Comment by SecUpwN** [comment]
Thanks for checking, folks! I guess it's either my provider or my SIM card not providing that information.
