### ISSUE TITLE
F-Droid: Automatic updates disabled

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#750]
Taken from https://gitlab.com/fdroid/fdroiddata/issues/377#note_3099166, I am filing this Issue to find out what we need to change in order to be able to provide the next version of our app on F-Droid as well. The solution to this Issue should ultimately be in line with the upcoming #730. Maybe @mvdan can help us?

**Comment by mvdan** [comment]
We parse the build.gradle file (or android manifest) to gather the version name. All we get is this:

```
versionName "$project.version-system"
```

And no, we cannot execute gradle to evaluate that. It would make the whole process a lot more insecure, complicated and slow.

You can fix this by just using a number here.

**Comment by SecUpwN** [comment]
>And no, we cannot execute gradle to evaluate that. It would make the whole process a lot more insecure, complicated and slow. You can fix this by just using a number here.

@mvdan, does that mean that F-Droid won't detect version changes when we merge #730?

**Comment by mvdan** [comment]
The same will apply, yes.

Note that this only affects automatic updates. Updates can still happen, but they'll have to be manual.

**Comment by SecUpwN** [comment]
>The same will apply, yes.

@mvdan, what do you mean by "the same"? We are aiming to automatically publish our app on the stores that we support with merging #682, will that also not be possible then?

>Note that this only affects automatic updates. Updates can still happen, but they'll have to be manual.

Means, I'd have to manually edit the metadata file via merge request on GitLab?
@larsgrefer, I'd like you to chime in and tell us if we can improve #730 somehow?

**Comment by mvdan** [comment]
Come on, this is not that hard. I am saying that you should use a literal instead of a variable in that line. Like:

```
versionName "v1.0"
```

Instead of:

```
versionName "$some-variable"
```

**Comment by larsgrefer** [comment]
@SecUpwN It seems like we can't use automatic updates on f-Droid and #730 at the same time because F-Droid wants to have a literal here but we are using an expression

**Comment by SecUpwN** [comment]
>It seems like we can't use automatic updates on f-Droid and #730 at the same time because F-Droid wants to have an literal here but we are using an expression.

@larsgrefer, that's uncool. That would mean I'd have to log in to Gitlab each time we publish a new release, then manually go through all the hassle of creating and cleaning the metadata file and ask for a merge. @mvdan, isn't there a slight possibility that F-Droid could improve the version detection, please?

**Comment by larsgrefer** [comment]
@mvdan using a literal at this point would hurt the DRY principle on our side because we want to use different versionNames for different productFlavors and we want to use git for tracking our versions.

How can we use the manual updates you mentioned earlier?
Or is it possible for us to give you only the apk?

**Comment by mvdan** [comment]
> How can we use the manual updates you mentioned earlier?

Something like https://gitlab.com/fdroid/fdroiddata/merge_requests/1139

> manually go through all the hassle of creating and cleaning the metadata file

False.

> isn't there a slight possibility that F-Droid could improve the version detection, please?

As already said, no.

**Comment by SecUpwN** [comment]
>Something like https://gitlab.com/fdroid/fdroiddata/merge_requests/1139

I don't really see the process there. Do you have a step-by-step guide for this, @mvdan?

**Comment by mvdan** [comment]
No, there is no step-by-step guide for such a simple thing. You only need to add another build entry like this one:

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.SecUpwN.AIMSICD.txt#L131

**Comment by SecUpwN** [comment]
Thanks for the clarification and your patience with my nagging questions, @mvdan.
