### ISSUE TITLE
Consider adapting CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by TPS** [SecUpwN/Android-IMSI-Catcher-Detector#757]
Full document @ https://github.com/ContributorCovenant/contributor_covenant/blob/master/CODE_OF_CONDUCT.md, & details @ https://github.com/ContributorCovenant/contributor_covenant/.

What do you all think?

**Comment by SecUpwN** [comment]
Thanks foryour suggestion, @TPS. All these things, like treating each other with respect and filing proper Issues as well as bringing patience to the table, are standard principles everyone should know. We already have our [CONTRIBUTING.md](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md) and [DISCLAIMER](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/DISCLAIMER), don't you think that's enough explanation already?

**Comment by TPS** [comment]
[CODE_OF_CONDUCT.md](https://github.com/ContributorCovenant/contributor_covenant/blob/master/CODE_OF_CONDUCT.md) is more of a meta-dev doc — i.e., how we treat _each other_, not so much the code proper, while we contribute to AIMSICD.  Nothing I see in any of those docs addresses that, & many projects _don't_ use such as working principles.  As we continue to get devs from many backgrounds, I think we should make it obvious from the beginning.

Also, if adapted correctly, it'd put you, @SecUpwN, as final arbiter of said behavior, & perhaps would've helped keep some of the drama _less_ last year.

**Comment by SecUpwN** [comment]
>...how we treat each other, not so much the code proper, while we contribute to AIMSICD

Ok, I see your point. I would like to avoid adding yet another file to our source tree and add a modified version of  the `Code of Conduct` into our [CONTRIBUTING.md](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md), similar to [how GitLab did it](https://github.com/gitlabhq/gitlabhq/blob/master/CONTRIBUTING.md#code-of-conduct). Fair?

>Also, if adapted correctly, it'd put you, @SecUpwN, as final arbiter of said behavior

That is usually what I do anyways, but it does not always work, even when we implement this. Everything depends on

**Comment by TPS** [comment]
Perfectly fair (just perhaps as long we keep an eye on any beneficial changes to [the source doc](https://github.com/ContributorCovenant/contributor_covenant/blob/master/CODE_OF_CONDUCT.md)).

&, of course, I agree (& :clap:) with all the rest of the above!
