### ISSUE TITLE
Incompatible update from 0.1.38-alpha to 0.1.39-alpha

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#769]
Just to let everyone know: It seems as if the APKs automatically attached to [released 0.1.39-alpha](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases/tag/v0.1.39-alpha) are not compatible to the previous version `0.1.38-alpha`, something may be wrong with our automated buillds. 

Also, we moved the tag for `0.1.39-alpha` after we released it and then realized that it pointed to no new changes. Therefore, [F-Droid cannot build the current version](https://gitlab.com/fdroid/fdroiddata/issues/401). @larsgrefer and @He3556 are currently investigating this and will hopefully fix it soon. Meanwhile, please update via [Aptoide](http://aimsicd.store.aptoide.com/) or [XDALabs](http://forum.xda-developers.com/android/apps-games/labs-t3241866). Thanks.

---

@larsgrefer, I thought @He3556 did already find the error? Are you sure that https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/be335f0159fd6e93e94103f42912057667e376b7 fixes this Issue?

**Comment by larsgrefer** [comment]
fixed in v0.1.39.1-alpha (be335f0159fd6e93e94103f42912057667e376b7)
