### ISSUE TITLE
Usage of Issue and Pull Request templates

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#774]
Should I add [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates), or do you think our [CONTRIBUTING.md](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md) is fine?
An in-depth explanation of the various possibilities with these improvements can be found [here](https://help.github.com/articles/helping-people-contribute-to-your-project/).

[![IssueTemplates](https://cloud.githubusercontent.com/assets/25792/13120859/733479fe-d564-11e5-8a1f-a03f95072f7a.png)](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by agilob** [comment]
This is another file in repo in top level directory that locks code on github.

**Comment by SecUpwN** [comment]
>If you're worried about the added clutter in the root directory of your project, we also added support for a `.github/` folder. You can put `CONTRIBUTING.md`, `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md` files in `.github/` and everything will work as expected.

**Comment by larsgrefer** [comment]
@SecUpwN Yes, you should.

**Comment by SecUpwN** [comment]
>Yes, you should.

@larsgrefer, I'll digg into these changes in the upcoming week. Have to set up my new laptop first. :)

**Comment by SecUpwN** [comment]
>@SecUpwN Yes, you should.

@larsgrefer, my ThinkPad is configuared now and I'm ready to rumble. Do you have a proposal on how you'd like our templates to look like? As an inspiration, just have a look at [Awesome GitHub Issues/PRs Templates](https://github.com/devspace/awesome-github-templates).
