### ISSUE TITLE
OpenCellID requests end up as 403

### ISSUE THREAD

**Issue by licaon-kter** [SecUpwN/Android-IMSI-Catcher-Detector#777]
Until https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/721 is solved the error message is strange, `check your network`, it the mean time reading the log, as of v0.1.39-alpha my OCID key yields error 403: `Your API key must be white listed in order to run this operation...`.

Is this something to be fixed in AIMSICD? OCID? My key?

**Comment by SecUpwN** [comment]
>Is this something to be fixed in AIMSICD? OCID? My key?

Please try deleting and requesting a fresh key from within our app.

**Comment by licaon-kter** [comment]
I though that any key, like requested on their site, would be ok.

I'll do.

**Comment by SecUpwN** [comment]
>I though that any key, like requested on their site, would be ok.

@licaon-kter, let us know here if requesting a key via our app resolved this.

**Comment by licaon-kter** [comment]
It's ok.
Is the key request in place, say if I forget to submit some data it will get rejected too, so I'll have to request another one and I'll just get it?

**Comment by SecUpwN** [comment]
>Is the key request in place, say if I forget to submit some data it will get rejected too, so I'll have to request another one and I'll just get it?

I don't know what you mean. If you fetched a key, you should upload data at least every 20 days.

**Comment by licaon-kter** [comment]
What if I don't? Will it be rejected? Will I need to press "get key" in AIMSCD? Will I get one?

I guess it happened with my previous one, I did bother to upload but maybe did not use the app that often.

**Comment by SecUpwN** [comment]
>What if I don't? Will it be rejected? Will I need to press "get key" in AIMSICD? Will I get one?

Please read the note that appears when pressing the button to fetch a fresh key. It clearly states that if not data is being uploaded to OCID within 20 days, the key will get invalid. These are their rules, not ours.

**Comment by licaon-kter** [comment]
I've seen them, what about my last 2 questions?

**Comment by SecUpwN** [comment]
>Will I need to press "get key" in AIMSICD?

Of course.

>Will I get one?

Of course. Please be aware that a new key can only be fetched every 24 hours.

**Comment by licaon-kter** [comment]
Ok, thanks.

**Comment by SecUpwN** [comment]
>Ok, thanks.

You're welcome. You can always see and edit your key in the `Preferences` within our app.

**Comment by licaon-kter** [comment]
Already had one there. :)
