### ISSUE TITLE
All current Cell Details

### ISSUE THREAD

**Issue by Nordlenning** [SecUpwN/Android-IMSI-Catcher-Detector#783]
Sony Xperia V lt25i,Unlocked,Rooted CyanogenMod 12.1 NEO-tsubasa  Lollipop 5.1.1 
AIMSICD Version unspecified-normal, Version Nummer T-1643.(WIP TEST RELEASE v0.1.41-alpha)

If I download OCID Data from MAP view the downloading marker (circle) keeps turning after
the downloading has finished. It stops if I leave the page & return back.

If I try to go to "All current Cell Details" in the menu nothing happens, seems like it's not
possible to return to "All current Cell Details" from any place..

**Comment by SecUpwN** [comment]
@Nordlenning, thanks for filing this and also thanks for all your translation contributions so far! Would you please do us the favor to attach a logcat after removing your provate data (like `CID` and `LAC`) here?

**Comment by Nordlenning** [comment]
@SecUpwN , My pleasure!  > Adding getprop -  AIMSICD internal Log & Logcat. 
Hope it can be of any help. Need more ? let me know...

[tsubasa  logcat.txt](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/files/143037/tsubasa.logcat.txt)
[AIMSICD mainLOG.txt](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/files/143038/AIMSICD.mainLOG.txt)
[tsubasa getprop.txt](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/files/143039/tsubasa.getprop.txt)

**Comment by tt3mm** [comment]
It seems, that it fails at parsing the response XML.
I made a quick fix, it seems working, at least it is refreshing the fields in DeviceFragment.

Of course this action only has effect if the DeviceFragment is open, not other, so I am thinking in moving this NavDrawer item to there. 
This name 'All Current Cell Details' doesn't say much I think, so a refresh button in DeviceFragment would do instead. This refresh button could be on the action bar, or as an action button.

@SecUpwN @larsgrefer pls confirm, and I make a refactor around this and the BUG/UI fix too.

**Comment by larsgrefer** [comment]
Refresh/loading animations and actions should be done with a SwipeRefreshLayout
