### ISSUE TITLE
AIMSICD not using downloaded OCID and always at MEDIUM alert

### ISSUE THREAD

**Issue by f3ndot** [SecUpwN/Android-IMSI-Catcher-Detector#790]
#### Versions

HW: Nexus 6P 
FW: Android 6.0.1 (stock)
Build Number: MMB29Q
AIMSICD Ver 0.1.39-alpha-normal via f-droid

#### Steps to Reproduce

1. Download and install AIMSICD
2. Enter in OCID API key
3. Download the database
4. After getting the successful download toast, quit the app and reopen
5. Observe warning that "Cell ID not in OpenCellID Database!"

[Log/debug file (with sensitive bits redacted) of me downloading the OCID](https://defuse.ca/b/6ntsXYntG8gzgJ2pMDFXBq). **Password: _AIMSICD_**

I live in Toronto downtown, Canada's largest city, using Canada's most popular cell provider. I've had AIMSICD open for days moving around. I've never had anything but MEDIUM/Cell ID not in OpenCellID Database.

I'm fairly confident this is a bug vs me encountering cells absent from the DB.

Also my Database Viewer of Imported OpenCellID Data is empty, so I don't know if DB is truly imported or #434 is affecting me.

**Comment by elevenhour** [comment]
I'm having this issue too.
Samsung Galaxy Note 4 
FW 5.0.1
Aimsicd Build Number T-1643

**Comment by Nordlenning** [comment]
Hi, This was a problem on my Sony phone too until Latest test release of AIMSICD that is >> WIP TEST RELEASE v0.1.41-alpha. Now I have the Green Icon.Try it...Download the APK under Pulse on this Site..

**Comment by SecUpwN** [comment]
Good evening @f3ndot, your bugs actually boil down to one. After downloading the OpenCellID database, our app should re-check the currently connected cell, which it doesn't. Please follow #558.

**Comment by f3ndot** [comment]
Hi @secupwn, if you see my steps to reproduce you'll see I mention this persists past restarting the app. To verify it's not background services, I even have rebooted my device. 

I'm not entirely sure if it's the bug you've referenced

**Comment by f3ndot** [comment]
However I'll take a stable at #558 since the issue has been untouched since 2015. If it fixes my problem too then I'll happily eat some humble pie. 

Let's see if I can dust off my java skills...

**Comment by SecUpwN** [comment]
>Let's see if I can dust off my java skills... 

@f3ndot, that would be wonderful. We#re badly missing more enthusiastic Android developers. Let me know if your error disappears when the other Issue is fixed, otherwise we'll just re-open this one here.

**Comment by f3ndot** [comment]
@SecUpwN WOW! I debugged the application and it appears the URL generated to download the CSV from OCID *_truncated*_ the last digit of my `mnc` GET parameter in the request!

This explains why, if you look carefully in my original logfile, it claims to import just 1 row (the .csv header line)

The `Cell` object passed to `getOpenCellData` is missing the final character in its `mnc` property.

Investigating...

**Comment by f3ndot** [comment]
This is the culprit: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/1b07e3cb033d3235fdb797ae0c8567b2407c35be/AIMSICD/src/main/java/com/SecUpwN/AIMSICD/AIMSICD.java#L384

My MNC is 3 characters and it interestingly assumes all to just be two, prematurely truncating the string. the intermediate variable `mnc` just above it however correctly grabs the rest.

Fixup PR inbound. Happy I actually helped! :tada:
