### ISSUE TITLE
Toggle Cell Tracking re-enables itself

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#794]
Steps to reproduce this Issue:

1. **Disable** `Toggle Cell Tracking` in the top right corner of our app
2. Shortly open the `Navigation Drawer` and go back to `Toggle Cell Tracking`
3. Checkbox `Toggle Cell Tracking` has obviously **re-enabled** itself

**Comment by Nordlenning** [comment]
Just tested the findings on my rooted Sony.

I turned off (Cell Tracking) & (Cell Monitoring) in the top bar.

Both (Cell Tracking) & (Cell Monitoring)  re-enabled if I go down to About AIMSICD.

If I turn them off in Preferences they still  re-enabled on the top bar, also after a restart of the app,
but my Icon turns Grey. So the services are not running & they are still off in preferences. 

If I turn them on in preferences (while the app is running),the app refreshes & my Icon turns Green again. Hope it can be of any help. Let me know if logs are needed.

**Comment by tt3mm** [comment]
There was a bug in the UI, it set the checks not based on what is running.
Also there was a bug in trackCell(), because it always set it true. 
Hopefully both fixed now.
