### ISSUE TITLE
Serial interface for At Command

### ISSUE THREAD

**Issue by virux84** [SecUpwN/Android-IMSI-Catcher-Detector#795]
Hi,
I have a Nexus 5, but I don't know which is the serial interface, like ttyACMx or other, that I have to use for send AT commands.

I also have an android smartphone based on mtk processor, that has two serial interface for at command, one for sim card. Do you know if there is an at command for scan neighbour cell and retrive infos like BCCH?
Thank you

**Comment by SecUpwN** [comment]
Good evening @virux84, first of all, please note that our GitHub Issues are intendet to support our app.

>I have a Nexus 5, but I don't know which is the serial interface, like ttyACMx or other, that I have to use for send AT commands.

Out `AT Command Interface` is supposed to [detect the available serial interfaces](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/AT-Command-Interface), when it is fully coded.

>Do you know if there is an at command for scan neighbour cell and retrive infos like BCCH?

Why do you need an AT Command for scanning for neighborings cells? Our app will do that for you, too - again, when everything is ready for [BETA](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status#beta-stage) stage, but we're still in bleeding `ALPHA`. Please help us here.
