### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by obones** [SecUpwN/Android-IMSI-Catcher-Detector#800]
Hello,

I see that the last commit for the French translation comes from Weblate.
Has this translation been proofread? If not, do you want me to do it?

Regards

**Comment by SecUpwN** [comment]
Good evening @obones, thanks for offering your help! as far as I know, our french translations have been checked multiple times. But of course, if you're keen to really proofread the translations, please [click here](https://hosted.weblate.org/accounts/login/github/?next=/projects/aimsicd/strings/) to directly sign in to `weblate` via your GitHub account and make any changes you find applicable. All corrections made via `weblate` are pulled into our repository here autonmatically. Cheers!
