### ISSUE TITLE
Time display on AIMSICD lockscreen notification

### ISSUE THREAD

**Issue by Nordlenning** [SecUpwN/Android-IMSI-Catcher-Detector#802]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

This may be a stupid Question, forgive me if it is.,What is the clock on the Warning banner supposed to show? Currently it's stating the time the App started.

---

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

Start AIMSICD & wait for the Warning banner. (See picture)

---

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

Could not find other than #372 

---

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

![screenshot_2016-02-27-20-15-21](https://cloud.githubusercontent.com/assets/17292772/13375381/9dcebc22-dd95-11e5-83c0-226e9ab414a3.png)

**Comment by SecUpwN** [comment]
Good evening @Nordlenning, I' afraid I don't get your question. Do you actually mean the purpose of the [Status Icons](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Status-Icons) appearing on your lockscreen? If so, they are supposed to show you the threat level at a quick glance and without unlocking your screen while on the move. Does that solve your Issue here?

Also, please note that your referenced Issue (about the warning banner) is actually the pull request for adding the following *real* worning banner to our `README` since people always keep complaining:

[![Warning](https://spideroak.com/share/IFEU2U2JINCA/GitHub/home/SecUpwN/SpiderOak/DOCUMENTATION/Warning.png)](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status)

**Comment by Nordlenning** [comment]
Good evening @SecUpwN I'm sorry if I'm not used to Github & make mistakes, Only trying to help your Core team bughunting. I was pointing to the Small Number on the right side of the border stating 15.19, that was the time I started the APP.. If you look at the Clock in the middle of the picture it states 20:15.
Tested it Again Now. Banner(Number)?. Synchronized.. So I would normally guess it should state Current Time.. ( 22:57 -- 22:58 In this picture) or is my treat level 22.57 ?. Just asking :) 


![screenshot_2016-02-27-22-58-40](https://cloud.githubusercontent.com/assets/17292772/13375731/8a404824-dd9f-11e5-85d8-d78eabd7e5d4.png)

**Comment by SecUpwN** [comment]
>I was pointing to the Small Number on the right side of the border stating 15.19, that was the time I started the APP.. f you look at the Clock in the middle of the picture it states 20:15.
Tested it Again Now. Banner(Number)?

Oh, now I get it! Next time, please add a **red circle** around what you actually mean. No, tjis is simply your **current time** - and if you have other notifications on your lockscreen, you'll see that those automatically have that too. The time on that natification is refreshing once either the status changes, or you've accessed the app or your phone. You may change the refresh time in `Preferences`. **Issue solved?** :)

**Comment by Nordlenning** [comment]
Question answered, Now I Know. Case Closed. Have a Nice Evening :)

**Comment by SecUpwN** [comment]
>Question answered, Now I Know. Case Closed. Have a Nice Evening :)

Thanks, it was a pleasure to help you! Please close your Issue if it solved.

**Comment by Nordlenning** [comment]
Thank you for Guidense :)
