### ISSUE TITLE
MissingRegistered lint check fails

### ISSUE THREAD

**Issue by larsgrefer** [SecUpwN/Android-IMSI-Catcher-Detector#810]
The **MissingRegistered** lint check fails because our package names contain upper-case letters which is against the java naming conventions: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by larsgrefer** [comment]
Shall I rename the java packages in order to match the java naming conventions?

**Comment by SecUpwN** [comment]
>Shall I rename the java packages in order to match the java naming conventions?

Yes, that would be lovely. If there is a way to enforce this with `checkstyle`, please add it there, too.
